prometheus-operator/prometheus-operator

pkg/operator/petset.go
@fabxc see [example PVC](https://github.com/kubernetes/kubernetes/blob/3fe8db8651ea5c327568a2733c62c810d7607b47/examples/experimental/persistent-volume-provisioning/claim1.json#L7) for auto provisioning.
=> pkg/operator: fix storage-class apiVersion

pkg/operator/petset.go
This resolves https://github.com/coreos/prometheus-operator/issues/29
=> subpath creation while mounting prometheus data volume

pkg/operator/operator.go, pkg/operator/petset.go, pkg/spec/spec.go
=> Configure resources & auto-tune flags

pkg/operator/petset.go
=> Instantiate empty map if necessary

pkg/alertmanager/operator.go, pkg/alertmanager/petset.go, pkg/prometheus/operator.go
=> Cleanup Alertmanager operator

README.md
=> Add blog post and kube-prometheus reference to readme

Documentation/prometheus.md
Reading through the doc I came across a few minor improvements
=> Minor spelling fixes and readability improvements

cmd/operator/main.go
Not urgent at all, just helped me find out a configuration problem and uses the logger for consistency.
=> log unexpected error

pkg/prometheus/promcfg.go
This employs exactly the same mechanism to sanitize labels as Prometheus
does internally.
Fixes #68
If we don't do this then any selector where a key has an invalid key name will result in a misconfigured Prometheus that won't start up.
=> pkg/prometheus: sanitize labels when generating config

pkg/prometheus/promcfg.go
Cherrypicking the bugfix that was included in v0.2.0 but not in a v0.1.x release yet. Will release a v0.1.1 with this once merged.
=> backport bugfix into v0.1

CHANGELOG.md
I will open a PR to merge `master` into the `release-0.2` branch once the changelog is merged.
=> add v0.2.1 changelog

CHANGELOG.md, pkg/alertmanager/statefulset.go, pkg/prometheus/statefulset.go
@fabxc @alexsomesan @jonboulle
=> cut v0.2.1

pkg/alertmanager/petset.go, pkg/prometheus/petset.go, pkg/spec/spec.go
Backport of #80 into the 0.1 release.
=> external url backport into 0.1 release

CHANGELOG.md
=> CHANGELOG: add changelog for v0.1.2 and v0.2.2

Makefile, pkg/alertmanager/statefulset.go, pkg/prometheus/statefulset.go
@alexsomesan @fabxc 
Fixes #86
=> *: fix config reloading when using external urls

CHANGELOG.md
=> CHANGELOG: add v0.1.3 and v0.2.3 changelog

CHANGELOG.md, Makefile, pkg/alertmanager/statefulset.go, pkg/prometheus/statefulset.go, pkg/spec/spec.go
=> cut v0.2.3

Makefile, pkg/alertmanager/petset.go, pkg/prometheus/petset.go
@alexsomesan @fabxc 
This also cuts `v0.1.3`
=> [backport] *: fix config reloading when using external urls

Documentation/service-monitor.md, pkg/client/monitoring/v1alpha1/types.go, pkg/prometheus/promcfg.go
=> Add TLS configuration options to ServiceMonitor

Documentation/alertmanager.md, Documentation/exposing-metrics.md, Documentation/prometheus.md, Documentation/service-monitor.md
First of multiple PRs extending the documentation requested in #98.
@galexrt @alexsomesan @fabxc
=> Documentation: exposing metrics

pkg/prometheus/promcfg.go
Before the job label and the endpoint were concatenated into the job
label, however, this same effect of uniqueness can be achieved by having
granular labels that are separate.
@alexsomesan @fabxc
=> prometheus: put endpoint in separate label

cmd/operator/main.go
@alexsomesan @brancz 
This uses the `errgroup` package and contexts. On the first error returned by either operator's `Run()`, the context gets canceled and ensures the other one exits as well and with it the program as a whole.
I disabled closing of the server for now and just let it run. It's not graceful and just returns confusing errors.
We can do it properly once https://tip.golang.org/pkg/net/http/#Server.Shutdown lands in go1.8
=> Properly exit on error

example/prometheus.yaml, pkg/prometheus/statefulset.go
=> prometheus: update default version to v1.5.2

cmd/operator/main.go, pkg/alertmanager/operator.go, pkg/alertmanager/statefulset.go, pkg/prometheus/operator.go, pkg/prometheus/statefulset.go
this is for issue https://github.com/coreos/prometheus-operator/issues/137
=> pass in configmap reload image as an argument

CHANGELOG.md
=> cut v0.5.0

CHANGELOG.md
@fabxc 
/cc @aerokite @TamalSaha
=> cut v0.5.1

example/alertmanager-service.yaml, example/prometheus-service.yaml
See #157.
***
Should an example ServiceMonitor for Prometheus be added too?
=> Add labels to example services

Jenkinsfile, Makefile, scripts/jenkins/Dockerfile, scripts/jenkins/Makefile, scripts/jenkins/ed.sh, scripts/jenkins/manifests/kops/regular-ig.yaml, scripts/jenkins/templates/kops-prereq.tf, scripts/jenkins/templates/outputs.tf, scripts/jenkins/wait-for-cluster.sh, test/e2e/alertmanager_e2e_test.go, test/e2e/framework/ingress.go, test/e2e/prometheus_e2e_test.go
Automate prometheus-operator e2e tests via Jenkins.
=> test: Setup jenkins ci

test/e2e/framework/prometheus.go, test/e2e/prometheus_e2e_test.go
Instead of listening to logs for reload we change the prometheus.yml and
check if configuration changes.
=> test: Fix flaky TestPrometheusReloadConfig

.gitignore, README.md
Here's a starter for a removal section, discussed in #162. Modify it however you like.
=> Document removal instructions in the README

pkg/alertmanager/operator.go, pkg/alertmanager/statefulset.go, pkg/client/monitoring/v1alpha1/types.go, pkg/prometheus/operator.go, pkg/prometheus/statefulset.go, test/e2e/framework/alertmanager.go, test/e2e/framework/prometheus.go
=> *: convert replicas field to pointer

pkg/k8sutil/k8sutil.go, pkg/prometheus/operator.go, test/e2e/prometheus_e2e_test.go
=> prometheus: use pkg/errors consistently

CHANGELOG.md
=> CHANGELOG: add v0.6.0 changes

pkg/prometheus/statefulset.go
=> prometheus: use chunk encoding v2

README.md, contrib/kube-prometheus/docs/KOPSonAWS.md
As we migrated the kube-prometheus repository into this repository we now need to update the references to it.
@fabxc
=> fix kube-prometheus references

pkg/alertmanager/operator.go, pkg/alertmanager/statefulset.go, pkg/client/monitoring/v1alpha1/types.go
Closes #191 and I also made sure to use `pkg/errors` where applicable just like in the prometheus package.
@fabxc
=> Alertmanager node selector

Documentation/user-guides/cluster-monitoring.md, Documentation/user-guides/storage.md
This example is meant to help with issues like #175 
I manually ran through the example on my cluster and the pv/prometheus bound together just fine.
cc @rrix
=> storage: add nfs example

contrib/kube-prometheus/README.md
=> Fix broken link in README.md to prometheus specification

Jenkinsfile
=> test: Add "generate" target to Jenkins file

Documentation/user-guides/exposing-prometheus-and-alertmanager.md
Ingress resources was moved from kubernetes/contrib to kubernetes/ingress
=> Fix ingress repo

test/e2e/alertmanager_e2e_test.go, test/e2e/framework/alertmanager.go, test/e2e/framework/cluster_role.go, test/e2e/framework/cluster_role_binding.go, test/e2e/framework/deployment.go, test/e2e/framework/framework.go, test/e2e/framework/helpers.go, test/e2e/framework/ingress.go, test/e2e/framework/prometheus.go, test/e2e/framework/replication-controller.go, test/e2e/framework/service.go, test/e2e/framework/service_account.go, test/e2e/framework/third_party_ressource.go, test/e2e/prometheus_e2e_test.go
Instead of attaching functions to the framework struct they are independent. This enables
other projects to use this framework without initialization.
=> test: Refactor testing framework

helm/prometheus-operator/README.md, helm/prometheus-operator/templates/deployment.yaml, helm/prometheus-operator/values.yaml
=> Add --kubelet-object option to helm chart

helm/prometheus-operator/README.md
=> Added Helm RBAC instructions to README

contrib/kube-prometheus/manifests/exporters/kube-state-metrics-deployment.yaml
Related to https://github.com/kubernetes/kube-state-metrics/issues/112#issuecomment-292965833
=> Increase memory limits to avoid OOMKilled

Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/manifests/alertmanager/alertmanager-service.yaml, contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-service.yaml, contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-servicemonitors.yaml
=> Setup service monitor for prometheus and alertmanager

pkg/prometheus/statefulset.go
I'm very conservative onto failureThreshold to avoid pod restarts. After this PR the generated liveness probe will be
```
livenessProbe:
failureThreshold: 10
httpGet:
path: /status
port: web
scheme: HTTP
periodSeconds: 10
successThreshold: 1
timeoutSeconds: 10
```
Fix #303
=> add livenessprobe

contrib/kube-prometheus/assets/grafana/deployment-dashboard.json, contrib/kube-prometheus/manifests/grafana/grafana-dashboards.yaml
This fixes the currently broken and erroring grafana dashboard for deployments.
=> kube-prometheus: fix deployment dashboard multiple values error

Documentation/api.md, Documentation/user-guides/cluster-monitoring.md, Documentation/user-guides/exposing-prometheus-and-alertmanager.md, contrib/kube-prometheus/manifests/alertmanager/alertmanager.yaml, pkg/alertmanager/statefulset.go, pkg/client/monitoring/v1alpha1/types.go, test/e2e/alertmanager_test.go
=> Alertmanager default resources and liveness probe

pkg/prometheus/operator.go, pkg/prometheus/statefulset.go
=> prometheus: do not delete secret when not managed by Operator

Documentation/api.md, Documentation/user-guides/basic-auth.md, contrib/kube-prometheus/manifests/examples/basic-auth/secrets.yaml, contrib/kube-prometheus/manifests/examples/basic-auth/service-monitor.yaml, contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml, pkg/client/monitoring/v1alpha1/types.go, pkg/prometheus/operator.go, pkg/prometheus/promcfg.go
=> basic auth

Documentation/troubleshooting.md
Based on https://github.com/coreos/prometheus-operator/issues/357
Not sure how you would like this document structured.
=> add RBAC info for GKE 1.6

.gitignore, helm/prometheus-operator/Chart.yaml, helm/prometheus-operator/README.md, helm/prometheus-operator/values.yaml
=> Operator chart v0.0.3

pkg/alertmanager/collector.go, pkg/prometheus/collector.go
=> *: use min replicas in metrics when unset

pkg/prometheus/statefulset.go
=> prometheus: always add route prefix flag

pkg/client/monitoring/v1alpha1/servicemonitor.go
=> client: fix non interface return type

contrib/kube-prometheus/assets/prometheus/rules/etcd3.rules, contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml, helm/kube-prometheus/charts/exporter-kube-etcd/templates/configmap.yaml
happend to see this bug, see ref https://github.com/coreos/etcd/pull/8081
=> fix alert rule bug

contrib/kube-prometheus/assets/prometheus/rules/alertmanager.rules, contrib/kube-prometheus/assets/prometheus/rules/general.rules, contrib/kube-prometheus/assets/prometheus/rules/kube-apiserver.rules, contrib/kube-prometheus/assets/prometheus/rules/kube-controller-manager.rules, contrib/kube-prometheus/assets/prometheus/rules/kube-scheduler.rules, contrib/kube-prometheus/assets/prometheus/rules/kubelet.rules, contrib/kube-prometheus/assets/prometheus/rules/node.rules, contrib/kube-prometheus/assets/prometheus/rules/prometheus.rules
@fabxc @mxinden @Gouthamve
I intentionally did not modify the etcd rules yet as I want to get that merged upstream first.
=> alerting rules: replace severity with action

contrib/kube-prometheus/assets/prometheus/rules/alertmanager.rules, contrib/kube-prometheus/assets/prometheus/rules/general.rules, contrib/kube-prometheus/assets/prometheus/rules/kube-apiserver.rules, contrib/kube-prometheus/assets/prometheus/rules/kube-controller-manager.rules, contrib/kube-prometheus/assets/prometheus/rules/kube-scheduler.rules, contrib/kube-prometheus/assets/prometheus/rules/kubelet.rules, contrib/kube-prometheus/assets/prometheus/rules/node.rules, contrib/kube-prometheus/assets/prometheus/rules/prometheus.rules
Reverts coreos/prometheus-operator#422
@fabxc @mxinden @gouthamve
=> Revert "alerting rules: replace severity with action"

pkg/alertmanager/operator.go, pkg/alertmanager/statefulset.go
This is similar to how Prometheus is updated.
@brancz @fabxc @mxinden
=> Update AM on relevant changes.

helm/prometheus-operator/Chart.yaml, helm/prometheus-operator/README.md, helm/prometheus-operator/templates/deployment.yaml, helm/prometheus-operator/values.yaml
Allow overriding all images the operator uses and adds additional "PullPolicy" flags for configmap images.
=> Allow overriding configmap images

vendor/github.com/cenkalti/backoff/LICENSE, vendor/github.com/cenkalti/backoff/README.md, vendor/github.com/cenkalti/backoff/backoff.go, vendor/github.com/cenkalti/backoff/context.go, vendor/github.com/cenkalti/backoff/exponential.go, vendor/github.com/cenkalti/backoff/retry.go, vendor/github.com/cenkalti/backoff/ticker.go, vendor/vendor.json
@mxinden @fabxc @Gouthamve 
Without this our unit tests will fail.
=> vendor: add backoff

pkg/k8sutil/k8sutil.go, test/e2e/framework/deployment.go, test/e2e/framework/framework.go, test/e2e/framework/helpers.go
=> test: Improve error feedback on e2e framework setup

pkg/prometheus/promcfg.go, pkg/prometheus/statefulset.go, test/e2e/framework/prometheus.go, test/e2e/prometheus_test.go
=> Fix targetPort relabeling

helm/alertmanager/Chart.yaml, helm/alertmanager/values.yaml, helm/prometheus-operator/Chart.yaml, helm/prometheus-operator/values.yaml, helm/prometheus/Chart.yaml, helm/prometheus/templates/clusterrole.yaml, helm/prometheus/templates/clusterrolebinding.yaml, helm/prometheus/templates/prometheus.yaml, helm/prometheus/templates/serviceaccount.yaml, helm/prometheus/values.yaml
bump alertmanager, prometheus and operator version
=> create rbac rules for prometheus + bump version

helm/alertmanager/Chart.yaml, helm/alertmanager/README.md, helm/alertmanager/templates/alertmanager.yaml, helm/alertmanager/values.yaml, helm/kube-prometheus/values.yaml, helm/prometheus/README.md, helm/prometheus/values.yaml
Fixes #446
- Removed some commented lines that appear to be typos.
- Updated docs that referred to prometheus.md
- Bump chart version
=> helm/alertmanager: Fix template causing invalid YAML

Documentation/api.md, Makefile, cmd/apidocgen/main.go, pkg/client/monitoring/v1alpha1/types.go
In the API docs, link to the PersistentVolumeClaim reference.
=> Add link to PersistentVolumeClaim reference

pkg/alertmanager/statefulset.go
Fixes https://github.com/coreos/prometheus-operator/issues/516
As we deprecated the storage fields we should have adapted the Alertmanager accordingly, so here the fix for that.
@fabxc @Gouthamve @mxinden
=> alertmanager: adapt storage mounted to prometheus changes

README.md
- Basic docs for how to run unit and e2e tests.
=> Adding Some Development Testing Documentation.

Documentation/api.md, pkg/client/monitoring/v1alpha1/types.go
=> Documentation: endpoints are required

Documentation/api.md, pkg/client/monitoring/v1alpha1/types.go, pkg/prometheus/promcfg.go
=> Adds scrape timeout property to ServiceMonitor endpoint

contrib/kube-prometheus/manifests/prometheus-operator/prometheus-operator-cluster-role.yaml
=> kube-prometheus: update the Prometheus Operator RBAC roles

contrib/kube-prometheus/hack/cluster-monitoring/deploy
Closes #581.
@fabxc 
/cc @albert0815
=> kube-prometheus: adapt deploy script to wait for CRDs

Documentation/network-policies.md
=> network-policies.md: Fix typo in broken link

pkg/prometheus/statefulset.go
=> prometheus: increase cpu/memory limit for config reloader

Documentation/api.md, pkg/alertmanager/statefulset.go, pkg/client/monitoring/v1/types.go, pkg/prometheus/statefulset.go
=> *: add tolerations and affinity

Documentation/api.md, Documentation/compatibility.md, Documentation/design.md, Documentation/exposing-metrics.md, Documentation/high-availability.md, Documentation/migration.md, Documentation/network-policies.md, Documentation/rbac.md, Documentation/troubleshooting.md, Documentation/user-guides/alerting.md, Documentation/user-guides/basic-auth.md, Documentation/user-guides/cluster-monitoring.md, Documentation/user-guides/exposing-prometheus-and-alertmanager.md, Documentation/user-guides/getting-started.md, Documentation/user-guides/running-exporters.md, Documentation/user-guides/storage.md, cmd/po-docgen/api.go, cmd/po-docgen/compatibility.go
As @athai suggested, I added the version compatibility warning header to the docs.
Closes #598 
@athai @joshix @fabxc @pgburt
=> docs: add compatibility warning

test/e2e/prometheus_test.go
Previously we had a race where we updated the Prometheus object and didn't actually wait for the deployment to finish, but rather check whether enough pods exist, which can be the case if the deployment hasn't actually started, so the value is still the old value. Now we check periodically whether the resources are already in the state that we expect and timeout after 2 minutes.
=> test: fix resource flake

helm/kube-prometheus/charts/exporter-kube-state/Chart.yaml, helm/kube-prometheus/charts/exporter-kube-state/templates/deployment.yaml, helm/kube-prometheus/requirements.yaml
Part of: https://github.com/coreos/prometheus-operator/issues/592
=> [kube-prometheus/exporter-kube-state] Use fullname template so it's consistent with other exporters

pkg/migrator/migrator.go
=> migrator: log which error causes rollback

helm/prometheus-operator/templates/get-crd-job.yaml
=> Update and rename get-tprs-job.yaml to get-crd-job.yaml

Documentation/api.md, Documentation/compatibility.md, pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, pkg/client/monitoring/v1/types.go, pkg/client/monitoring/v1alpha1/types.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
The respective PR to complete the Alertmanager part of #580, the Prometheus part was already done by @jescarri in #591.
@fabxc
=> alertmanager: add pod objectmeta

CHANGELOG.md, pkg/prometheus/operator.go
=> prometheus: make node sync periodic instead of watching

Documentation/user-guides/cluster-monitoring.md, Documentation/user-guides/getting-started.md, contrib/kube-prometheus/docs/Monitoring external etcd.md, contrib/kube-prometheus/manifests/examples/example-app/prometheus-frontend.yaml, contrib/kube-prometheus/manifests/prometheus/prometheus-k8s.yaml, example/user-guides/getting-started/prometheus.yaml
This updates prometheus to 1.7.1 where it was missing
=> Updated to prometheus 1.7.1

contrib/kube-prometheus/assets/grafana/kubernetes-capacity-planning-dashboard.json, contrib/kube-prometheus/assets/grafana/kubernetes-cluster-health-dashboard.json, contrib/kube-prometheus/assets/grafana/kubernetes-cluster-status-dashboard.json, contrib/kube-prometheus/assets/grafana/kubernetes-control-plane-status-dashboard.json, contrib/kube-prometheus/manifests/grafana/grafana-dashboards.yaml
=> grafana-dashboards: various small improvements

helm/prometheus/README.md
Helm-Prometheus: Remove extra code formating
To increase readability of the Readme.
=> Increased readability by removing code formating

pkg/prometheus/statefulset.go
Part of #491 (Prometheus only)
=> Add parallel pod management

contrib/kube-prometheus/Makefile
change manifest generate to use docker to improve probability issues seen in #631.
=> change make generate to use docker run to be more protable

Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/manifests/alertmanager/alertmanager.yaml, contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml, contrib/kube-prometheus/manifests/node-exporter/node-exporter-daemonset.yaml, contrib/kube-prometheus/manifests/prometheus/prometheus-k8s.yaml
=> kube-prometheus: various version updates

Documentation/compatibility.md, pkg/prometheus/statefulset.go
=> #669: Use /-/healthy and /-/ready for probes

Makefile, cmd/operator/main.go, pkg/alertmanager/operator.go, pkg/alertmanager/statefulset.go, pkg/k8sutil/k8sutil.go, pkg/migrator/migrator.go, pkg/prometheus/operator.go, pkg/prometheus/statefulset.go, test/migration/migration_test.go
=> Customize the Crd Group and propagate optional labels

pkg/alertmanager/operator.go, pkg/alertmanager/statefulset.go, pkg/prometheus/operator.go, pkg/prometheus/statefulset.go
=> *: add owner references to statefulsets and secrets

Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/manifests/node-exporter/node-exporter-daemonset.yaml, pkg/alertmanager/operator.go, pkg/api/api.go, pkg/client/monitoring/clientset.go, pkg/client/monitoring/v1/client.go, pkg/migrator/migrator.go, pkg/prometheus/operator.go, test/framework/cluster_role.go, test/framework/cluster_role_binding.go, test/framework/framework.go
=> *: ensure using crdgroup flag in monitoring client

helm/grafana/README.md, helm/grafana/templates/dashboards-configmap.yaml, helm/grafana/templates/grafana-deployment.yaml, helm/grafana/values.yaml
Expose grfana watcher image so it can be overrinded and pulled from another repository
=> Grafana helm Chart: Expose grafana-watcher image in values.yml

Documentation/compatibility.md, Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/manifests/prometheus/prometheus-k8s.yaml, pkg/prometheus/statefulset.go
=> *: upgrade to Prometheus 2.0

cmd/operator/main.go, pkg/client/monitoring/v1/client.go
=> Add default for crd-kinds

RELEASE.md
=> *: Add release documentation

pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
=> Change alertmanager default storage.path

helm/exporter-node/templates/deamonset.yaml
Just to be sure this worked, I created a Playground
https://play.golang.org/p/E3sjIbjRd4
=> Adding v to version image tag

contrib/kube-prometheus/assets/prometheus/rules/prometheus.rules.yaml
=> kube-prometheus: Add Prometheus 2.0 rules

pkg/alertmanager/operator_test.go, pkg/prometheus/operator_test.go
=> *: Fix ListOptions test flakes

.travis.yml
@ant31 
https://travis-ci.org/coreos/prometheus-operator/jobs/316372208#L1620
=> Fix breakline

.travis.yml, Makefile
=> fix travis s3 sync

helm/hack/sync-repo.sh
=> Do not stop the helm sync when the hash comparison fail

.travis.yml, helm/hack/helm-package.sh, helm/hack/sync-repo.sh
@ant31 this will fix the failure before the s3 sync and the hash comparison
=> Fix helm sync

Documentation/api.md, pkg/client/monitoring/v1/types.go, pkg/prometheus/statefulset.go
Supersedes #500 and closes #474 
@ant31
=> prometheus: Add ability to specify log level

Documentation/api.md, pkg/client/monitoring/v1/types.go, pkg/prometheus/statefulset.go
=> prometheus: Allow specifying custom SecurityContext

Makefile, contrib/kube-prometheus/Dockerfile, contrib/kube-prometheus/Makefile, contrib/kube-prometheus/assets/prometheus/rules/etcd3.rules.yaml, contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml, scripts/jsonnet/Dockerfile
@ant31 
@mxinden so you're aware of the kube-prometheus generation step :)
=> Update etcd rules

Makefile, helm/exporter-kube-state/Chart.yaml, helm/kube-prometheus/requirements.yaml
Remove exporter-kube-api from kube-prometheus requirement
bump chart kube-state 
@brancz
=> Helm review (again...)

helm/kube-prometheus/Chart.yaml
=> Bump kube-prometheus version

pkg/prometheus/statefulset.go
=> prometheus: Add --storage.tsdb.no-lockfile flag for Prometheus 2.0

helm/kube-prometheus/Chart.yaml
=> helm : bump kube-prometheus version following PR #829

contrib/kube-prometheus/assets/grafana/.gitignore, contrib/kube-prometheus/assets/grafana/generated/.gitignore, contrib/kube-prometheus/assets/grafana/raw-json-dashboards/etcd-dashboard.json, contrib/kube-prometheus/hack/scripts/generate-dashboards-configmap.sh, contrib/kube-prometheus/hack/scripts/generate-manifests.sh, contrib/kube-prometheus/hack/scripts/wrap-dashboard.sh, contrib/kube-prometheus/manifests/grafana/grafana-dashboards.yaml
=> kube-prometheus: Add etcd dashboard

helm/kube-prometheus/requirements.yaml
=> Bump kube-etcd version

helm/README.md
make it even easier for newcomer
=> helm: add '--namespace monitoring' in README

Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/assets/prometheus/rules/etcd3.rules.yaml, contrib/kube-prometheus/hack/grafana-dashboards-configmap-generator/templates/grafana-deployment-template.yaml, contrib/kube-prometheus/manifests/alertmanager/alertmanager.yaml, contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml, contrib/kube-prometheus/manifests/kube-state-metrics/kube-state-metrics-deployment.yaml, contrib/kube-prometheus/manifests/node-exporter/node-exporter-daemonset.yaml, contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml, pkg/alertmanager/statefulset.go, test/e2e/alertmanager_test.go, test/framework/alertmanager.go
=> kube-prometheus: bump various versions

.travis.yml
Speed up travis tests running simultaneously e2e tests 
Similar to #791
=> Run e2e tests in parallel

Documentation/api.md, Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/grafana-image/Dockerfile, contrib/kube-prometheus/grafana-image/Makefile, contrib/kube-prometheus/grafana-image/config.toml, contrib/kube-prometheus/hack/grafana-dashboards-configmap-generator/templates/grafana-deployment-template.yaml, contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml, contrib/kube-prometheus/manifests/node-exporter/node-exporter-daemonset.yaml, pkg/alertmanager/statefulset.go, pkg/client/monitoring/v1/types.go, pkg/client/monitoring/v1/zz_generated.deepcopy.go
=> *: Use non-root

helm/grafana/Chart.yaml, helm/grafana/README.md, helm/grafana/templates/grafana-deployment.yaml, helm/grafana/values.yaml, helm/kube-prometheus/requirements.yaml
=> add auth.anonymous.enabled value on Grafana

contrib/kube-prometheus/hack/scripts/generate-dashboards-configmap.sh, contrib/kube-prometheus/hack/scripts/wrap-dashboard.sh
Fixes #925 
I wish we could just enable the scripts to fail on any error, unfortunately there are some more deep problems with this and I plan to address rewriting some of these scripts anyways. So for now just fixing the errors we're seeing.
@ant31 
/cc @aosmith
=> kube-prometheus: Fix generate scripts

contrib/kube-prometheus/docs/Monitoring external etcd.md
=> Minor typo fix

helm/exporter-kube-etcd/Chart.yaml, helm/exporter-kube-etcd/values.yaml, helm/kube-prometheus/requirements.yaml
=> Rollback default etcd scheme to http

helm/grafana/Chart.yaml, helm/grafana/README.md
=> Add Helm tip for GCE

helm/grafana/Chart.yaml, helm/grafana/templates/grafana-deployment.yaml, helm/kube-prometheus/Chart.yaml, helm/kube-prometheus/requirements.yaml
=> Add readinessProbe for grafana Helm

contrib/kube-prometheus/hack/scripts/wrap-dashboard.sh
=> fixing inputname var assignment

contrib/kube-prometheus/hack/scripts/generate-dashboards-configmap.sh
Fixing invalid configmap
Also removing duplicate code
=> fixing#947

helm/README.md, helm/prometheus-operator/Chart.yaml, helm/prometheus-operator/values.yaml
* bump prometheus operator helm chart to 0.16.1 
* add developer notes
=> bump prometheus-operator chart

helm/grafana/Chart.yaml, helm/grafana/templates/ingress.yaml, helm/kube-prometheus/Chart.yaml, helm/kube-prometheus/requirements.yaml
=> remove path on helm grafan ingress

helm/kube-prometheus/Chart.yaml, helm/kube-prometheus/requirements.yaml, helm/prometheus/Chart.yaml, helm/prometheus/templates/prometheus.yaml, helm/prometheus/values.yaml
Allow to modify prometheus log level when using helm charts
=> helm: allow to modify prometheus log level

helm/grafana/Chart.yaml, helm/grafana/README.md, helm/grafana/templates/grafana-deployment.yaml, helm/grafana/values.yaml, helm/kube-prometheus/Chart.yaml, helm/kube-prometheus/requirements.yaml
=> Helm Grafana - Add extraVars

contrib/kube-prometheus/grafana-image/config.toml
As mentioned in https://github.com/coreos/prometheus-operator/issues/924#issuecomment-362859346 .
=> Fix for issue #924

contrib/kube-prometheus/grafana-image/Makefile, contrib/kube-prometheus/hack/grafana-dashboards-configmap-generator/templates/grafana-deployment-template.yaml, contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml
Updating the Grafana image with the changes from #957.
@ant31 @fabxc @gitfrederic
=> kube-prometheus: Update Grafana image

contrib/kube-prometheus/hack/scripts/wrap-dashboard.sh
=> Minor typo fixes

contrib/kube-prometheus/hack/scripts/generate-dashboards-configmap.sh
=> fixing#972

Documentation/user-guides/alerting.md, Documentation/user-guides/getting-started.md
@brancz  we would like to add alpha and beta banners to all applicable docs for Lithium, please. Thanks.
=> docs: add alpha banner

Documentation/user-guides/running-exporters.md
This looks like it may have been a WIP. I took a pass through it before I noticed. Apologies if it was premature.
=> docs: editorial pass on running-exporters.md

Documentation/api.md, example/prometheus-operator-crd/alertmanager.crd.yaml, example/prometheus-operator-crd/prometheus.crd.yaml, pkg/client/monitoring/v1/openapi_generated.go, pkg/client/monitoring/v1/types.go
=> Update validation spec

helm/alertmanager/Chart.yaml, helm/alertmanager/values.yaml, helm/exporter-kubelets/Chart.yaml, helm/grafana/Chart.yaml, helm/kube-prometheus/requirements.yaml, helm/kube-prometheus/values.yaml, helm/prometheus-operator/Chart.yaml, helm/prometheus-operator/values.yaml, helm/prometheus/Chart.yaml, helm/prometheus/values.yaml
=> Bump prometheus, prometheus-operator and alertmanager helm versions

cmd/operator/main.go, cmd/po-docgen/compatibility.go, contrib/prometheus-config-reloader/main.go, pkg/alertmanager/operator.go, pkg/alertmanager/statefulset.go, pkg/prometheus/operator.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
=> Allow disabling runAsUser

contrib/kube-prometheus/docs/kube-prometheus-on-kubeadm.md
Added information on webhook token authentication and information on how to update the manifests if Kubernetes is already deployed with kubeadm.
=> Added information on webhook token authentication

contrib/kube-prometheus/assets/prometheus/rules/kubelet.rules.yaml, contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml, helm/exporter-kubelets/Chart.yaml, helm/exporter-kubelets/templates/kubelet.rules.yaml, helm/kube-prometheus/Chart.yaml, helm/kube-prometheus/requirements.yaml
Update alert rule check kubelet down ratio from 1% to 10%.
In #774 , it is changed to 1%, so returns to 10%.
=> Update alert rule for kubelet

helm/alertmanager/Chart.yaml, helm/alertmanager/templates/alertmanager.yaml, helm/alertmanager/values.yaml, helm/exporter-kube-state/Chart.yaml, helm/exporter-kube-state/templates/deployment.yaml, helm/exporter-kube-state/values.yaml, helm/exporter-node/Chart.yaml, helm/exporter-node/templates/daemonset.yaml, helm/exporter-node/values.yaml, helm/grafana/Chart.yaml, helm/grafana/templates/grafana-deployment.yaml, helm/grafana/values.yaml, helm/hack/e2e-test.sh, helm/kube-prometheus/requirements.yaml, helm/prometheus-operator/Chart.yaml, helm/prometheus-operator/templates/deployment.yaml, helm/prometheus-operator/values.yaml, helm/prometheus/Chart.yaml, helm/prometheus/templates/prometheus.yaml, helm/prometheus/values.yaml
Added fields for tolerations throughout.
=> Added fields for tolerations where applicable

contrib/kube-prometheus/grafana-image/Makefile, contrib/kube-prometheus/hack/grafana-dashboards-configmap-generator/templates/grafana-deployment-template.yaml, contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml
Tested in my cluster, looking good in migration from 5.0.0-beta5 to 5.0.0
=> Update to grafana 5.0.0

pkg/prometheus/operator.go
This PR fixes https://github.com/coreos/prometheus-operator/issues/1028
=> BugFix: check is secret exists 

Makefile, helm/exporter-kube-controller-manager/Chart.yaml, helm/exporter-kube-state/Chart.yaml, helm/exporter-kubelets/Chart.yaml, helm/exporter-kubernetes/Chart.yaml, helm/hack/sync-repo.sh, helm/kube-prometheus/requirements.yaml
Fix the current CI that is broken
Check if the user bumped charts before merging it
=> Review helm e2e

helm/hack/helm-package.sh, helm/kube-prometheus/Chart.yaml
=> bump kube-prometheus

Documentation/api.md, example/prometheus-operator-crd/alertmanager.crd.yaml, example/prometheus-operator-crd/prometheus.crd.yaml, helm/kube-prometheus/Chart.yaml, pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, pkg/client/monitoring/v1/openapi_generated.go, pkg/client/monitoring/v1/types.go, pkg/client/monitoring/v1/zz_generated.deepcopy.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
This will allow one to specify a proxy that is actually the entry point for a Prometheus/Alertmanager Pods UI.
@ant31 @fabxc
=> *: Allow listening locally and specifying additional containers

helm/grafana/Chart.yaml, helm/kube-prometheus/requirements.yaml, helm/prometheus/Chart.yaml, helm/prometheus/values.yaml
=> Review prometheus storagespec example

helm/grafana/Chart.yaml, helm/grafana/dashboards/nodes-dashboard.json, helm/grafana/dashboards/pods-dashboard.json, helm/kube-prometheus/requirements.yaml
This PR fixes legend issue reported on #1076 issue and #1006
=> Fixed legendFormat for Grafana dashboards #1076

Documentation/compatibility.md, Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/manifests/prometheus/prometheus-k8s.yaml, helm/kube-prometheus/Chart.yaml, helm/kube-prometheus/requirements.yaml, helm/kube-prometheus/values.yaml, helm/prometheus/Chart.yaml, helm/prometheus/values.yaml, pkg/prometheus/statefulset.go
• bump prometheus to `2.2.1`
• prometheus chart set to `0.0.21`
• kube-prometheus chart set to `0.0.31`
=> Update Prometheus to stable 2.2.1

helm/exporter-kube-state/Chart.yaml, helm/exporter-kube-state/templates/deployment.yaml, helm/kube-prometheus/Chart.yaml, helm/kube-prometheus/requirements.yaml
Fixes #1090
Signed-off-by: Maximilian Gaß <m.gass@babiel.com>
=> helm: remove erroneus replica override in exporter-kube-state chart

helm/kube-prometheus/Chart.yaml, helm/kube-prometheus/requirements.yaml, helm/prometheus/Chart.yaml, helm/prometheus/templates/prometheus.yaml
allow Rules Selector to use other Selectors besides matchLabels
Fixes #914
=> helm/prometheus: prometheus template

Documentation/api.md, example/prometheus-operator-crd/prometheus.crd.yaml, pkg/client/monitoring/v1/openapi_generated.go, pkg/client/monitoring/v1/types.go, pkg/client/monitoring/v1/zz_generated.deepcopy.go, pkg/prometheus/promcfg.go
=> add ability to set TLSConfig for alertmanager connections

pkg/alertmanager/operator.go, pkg/prometheus/operator.go
We should probably create some alerts for these two counters. But I just quickly added those two.
What do you think?
Closes #1097
=> Create statefulset reconcile errors counter

contrib/kube-prometheus/assets/prometheus/rules/node.rules.yaml, contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml, helm/exporter-node/Chart.yaml, helm/exporter-node/templates/node.rules.yaml, helm/kube-prometheus/Chart.yaml, helm/kube-prometheus/requirements.yaml
Update rules with summary for better notifications.
=> Update Alert Manager rules for NodeDiskRunningFull with summary

helm/grafana/Chart.yaml, helm/grafana/templates/grafana-deployment.yaml, helm/grafana/values.yaml, helm/kube-prometheus/Chart.yaml, helm/kube-prometheus/requirements.yaml
This change enable Grafna config customization.
=> Add the possibility to mount grafana config

contrib/kube-prometheus/assets/prometheus/rules/prometheus.rules.yaml, contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml, helm/kube-prometheus/Chart.yaml, helm/kube-prometheus/requirements.yaml, helm/prometheus/Chart.yaml, helm/prometheus/templates/prometheus.rules.yaml
Add new alert for prometheus.
show issue: #1139
=> Add new alert for samples rejected due ti duplicate timestamp

Documentation/api.md, example/prometheus-operator-crd/prometheus.crd.yaml, example/prometheus-operator-crd/servicemonitor.crd.yaml, pkg/client/monitoring/v1/openapi_generated.go, pkg/client/monitoring/v1/types.go
Closes #1167 
@ant31 @fabxc @mxinden
=> prometheus: Make relabeling fields optional

pkg/prometheus/promcfg.go
=> prometheus: Make relabeling field SourceLabel optional

Makefile, helm/README.md, helm/exporter-kubernetes/Chart.yaml, helm/kube-prometheus/requirements.yaml, helm/prometheus-operator/Chart.yaml, helm/prometheus-operator/values.yaml
Fix CI adding s3 sync to exporter-coredns
=> Bump chart prometheus-operator to v0.18.0

Documentation/api.md, example/prometheus-operator-crd/servicemonitor.crd.yaml, pkg/client/monitoring/v1/openapi_generated.go, pkg/client/monitoring/v1/types.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
The generation of StaticTargets was broken.
I've fixed that.
Sadly the unit tests right now doesn't seem to compile the correct YAML.
@brancz @mxinden
=> Fix StaticTargets generation and add unit test

contrib/kube-prometheus/assets/prometheus/rules/kube-state-metrics.rules.yaml, contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml
@gianrubio Are there any steps for me to take to update the helm code?
Replaces https://github.com/coreos/prometheus-operator/pull/950
=> kube-prometheus: Fix minor typo

contrib/kube-prometheus/docs/Monitoring external etcd.md
=> Update Monitoring external etcd.md

README.md, helm/prometheus-operator/Chart.yaml, helm/prometheus-operator/templates/_helpers.tpl, helm/prometheus-operator/templates/deployment.yaml
@gianrubio per https://github.com/coreos/prometheus-operator/issues/1233
I also updated the README file to match 0.18.0's Changelog on k8s compatibility.
=> Drop compat for <prometheus-operator-0.13.0

contrib/kube-prometheus/hack/cluster-monitoring/deploy, contrib/kube-prometheus/jsonnet/prometheus/prometheus-k8s-role-binding-config.libsonnet, contrib/kube-prometheus/jsonnet/prometheus/prometheus-k8s-role-binding-default.libsonnet, contrib/kube-prometheus/jsonnet/prometheus/prometheus-k8s-role-binding-kube-system.libsonnet, contrib/kube-prometheus/jsonnet/prometheus/prometheus-k8s-role-binding-namespace.libsonnet, contrib/kube-prometheus/jsonnet/prometheus/prometheus-k8s-rules.libsonnet, contrib/kube-prometheus/jsonnet/prometheus/prometheus-namespace-role-binding.libsonnet, contrib/kube-prometheus/manifests/grafana/grafana-dashboard-definitions.yaml, contrib/kube-prometheus/manifests/prometheus-k8s/prometheus-k8s-role-binding-config.yaml, contrib/kube-prometheus/manifests/prometheus-k8s/prometheus-k8s-rules.yaml, scripts/jsonnet/Dockerfile
This PR:
* Fixes config reloader RBAC permissions (more specifically correctly binding roles)
* Adds missing labels to Prometheus rules configmap
* Updates to latest grafana dashboards
@mxinden @metalmatze
=> Various kube-prometheus fixes

pkg/prometheus/statefulset.go
statefulset: fix which probe has initial delay
The readiness probe is used for the case of a pod being initially ready, not the liveness probe.
Since this is the grace period used for recovering bad metrics data, the grace period for recovery should be applied to readiness, not liveness.
=> Move the initial delay seconds to Readiness, not Liveness.

helm/kube-prometheus/requirements.yaml, helm/prometheus/Chart.yaml, helm/prometheus/templates/servicemonitors.yaml
Adresses #1240 
Local tests with serviceMonitors worked, but I don't know the project's CI well enough to add a real test.
@gianrubio Feel free to throw this away if you already have a better solution. I just needed a quick fix.
=> Fix scope when adding serviceMonitors to prometheus

cmd/operator/main.go, pkg/alertmanager/operator.go, pkg/prometheus/operator.go
While debugging something myself I wished for some additional debug logs, so adding leveled logging (and some additional logging, but mostly adapting existing log calls).
@mxinden
=> Add leveled logging

Documentation/user-guides/getting-started.md, example/user-guides/getting-started/prometheus.yaml
=> Documentation/getting-started: Use serviceAccountName

helm/prometheus-operator/Chart.yaml, helm/prometheus-operator/templates/create-servicemonitor-job.yaml
Adds nodeSelectors & tolerations to the prometheus-operator SM jobs
=> helm/prometheus-operator: add nodeSelector & tolerations to SM job

Documentation/network-policies.md
Update documentation to valid yaml 
(my first PR so bare with me as I learn process)
=> Update deny all networkPolicy

contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml
In order to prevent this in the future we need to check in the lock file and update dependencies explicitly. I'm working on enabling this, but for now to allow other builds to work this PR.
@mxinden
=> kube-prometheus: regenerate

helm/kube-prometheus/Chart.yaml, helm/kube-prometheus/values.yaml
=> ISSUE-1320: To fix the missing kube-state scraping config in Prometheus

contrib/grafana-watcher/README.md, contrib/kube-prometheus/README.md, contrib/kube-prometheus/docs/developing-prometheus-rules-and-grafana-dashboards.md, contrib/kube-prometheus/docs/monitoring-external-etcd.md
=> fixed dashboard example path

test/e2e/prometheus_test.go
Instead of checking if a resource was updated exactly x times, check if
the amount of updates is within a range.
The test should prevent repeadet (>100) updates by the Prometheus
Operator. Kubernetes updates resources by itself, e.g. the status
fields. This amount stays within limits. Thereby checking if the
statefulset was updated between 1 and 3 times is enough.
=> e2ePrometheusOnlyUpdatedOnRelevantChanges: Check for range

contrib/kube-prometheus/experimental/custom-metrics-api/gencerts.sh
=> Mac compat

helm/grafana/Chart.yaml, helm/grafana/README.md, helm/grafana/templates/grafana-deployment.yaml, helm/grafana/values.yaml, helm/kube-prometheus/Chart.yaml, helm/kube-prometheus/requirements.yaml
This pull request removes the hardcoded resources from the grafana helm chart and makes them configurable.
=> Added grafana and grafana watcher resources to templates

Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus-operator/prometheus-operator.libsonnet, contrib/kube-prometheus/manifests/0prometheus-operator-deployment.yaml
ablity to custom configmapReloader & prometheusConfigReloader image in jsonnet template
also close #1322
=> support custom kube-prometheus configmapReloader & prometheusConfigReloader image

helm/kube-prometheus/Chart.yaml, helm/kube-prometheus/requirements.yaml, helm/prometheus/Chart.yaml, helm/prometheus/templates/prometheus.yaml, helm/prometheus/values.yaml
=> [helm] Add serviceMonitorNamespaceSelector to prometheus helm chart

pkg/alertmanager/operator.go, pkg/prometheus/operator.go
This PR changes, that CRDs (including their validations) are always updated on boot of the Prometheus Operator.
@mxinden
=> *: Update CRDs on boot

Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus-operator/prometheus-operator.libsonnet, contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet, contrib/kube-prometheus/manifests/0prometheus-operator-clusterRole.yaml, contrib/kube-prometheus/manifests/0prometheus-operator-deployment.yaml, contrib/kube-prometheus/manifests/prometheus-rules.yaml, scripts/travis-push-docker-image.sh
89fc4e306972604eba2dcb961a6d29cc27a668ad introduced the new Prometheus
rule file custom resource definition. This patch adjusts the
kube-prometheus project to use the new custom resource definition.
=> kube-prometheus: Adjust to new Prometheus rule file CRD

Documentation/user-guides/alerting.md, example/user-guides/alerting/prometheus-example-rules.yaml, example/user-guides/alerting/prometheus-example.yaml
=> doc: Update alerting documentation to rule file crd

helm/grafana/Chart.yaml, helm/grafana/README.md, helm/grafana/templates/svc.yaml, helm/grafana/values.yaml, helm/kube-prometheus/Chart.yaml, helm/kube-prometheus/requirements.yaml
See: e131164c428a4a6ed3c2b60efb6bc627f3af95dd
=> helm/grafana: Allow to set custom Service labels

pkg/prometheus/statefulset.go
Adds missing parameters to prometheus for rendering consoles visualization.
Fixes #1460
=> Fix prometheus consoles visualization

Documentation/user-guides/alerting.md, example/user-guides/alerting/prometheus-example-rules.yaml, example/user-guides/alerting/prometheus-example.yaml
With recent changes, we renamed RuleFile to PrometheusRule and ruleFileSelector
to ruleSelector.
=> docs: renamed RuleFile to PrometheusRule and ruleFileSelector to ruleSelector

contrib/kube-prometheus/manifests/grafana-dashboardDatasources.yaml
=> kube-prometheus: Update grafana jsonnet dependency

Makefile, scripts/travis-push-docker-image.sh
Sorry for the regression through the build system refactoring patch.
=> travis: Update travis-push-docker-image.sh to new build system

contrib/kube-prometheus/manifests/0prometheus-operator-0prometheusCustomResourceDefinition.yaml
=> kube-prometheus: Regenerate prometheus CRD

contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml
=> kube-prometheus: Re-generate dashboards

contrib/kube-prometheus/manifests/grafana-dashboardDatasources.yaml, contrib/kube-prometheus/manifests/grafana-deployment.yaml
Follow up to https://github.com/brancz/kubernetes-grafana/pull/32.
@mxinden @metalmatze
=> kube-prometheus: Re-generate Grafana jsonnet dependency

helm/kube-prometheus/Chart.yaml, helm/kube-prometheus/requirements.yaml, helm/prometheus/Chart.yaml, helm/prometheus/templates/prometheus.yaml, helm/prometheus/values.yaml
Missed the variable in https://github.com/coreos/prometheus-operator/pull/1540
=> Fix prometheus chart for ruleNamespaceSelector

contrib/kube-prometheus/README.md
There is a section in the Makefile to do that instead of execute manually a script.
=> Make "Compiling" section easier to execute

README.md
=> README: Update target for container image build

example/thanos/querier-deployment.yaml, pkg/prometheus/statefulset.go
This should fix the flakes we are having related to Thanos.
Closes #1555 
@mxinden
=> Update Thanos pieces to default to v0.1.0-rc.2

.travis.yml, pkg/prometheus/operator_test.go, pkg/prometheus/rules.go, pkg/prometheus/rules_test.go, test/e2e/main_test.go, test/e2e/prometheus_test.go, test/framework/event.go, test/framework/pod.go
This should help debugging flakes seen among others in https://github.com/coreos/prometheus-operator/pull/1586.
=> test/e2e: Decrease config map data limit 

scripts/create-minikube.sh
Supersedes #1389
Closes #1389
@mxinden
=> scripts: Enable subresources on CI

Makefile, contrib/kube-prometheus/Makefile, contrib/kube-prometheus/README.md, contrib/kube-prometheus/build.sh, contrib/kube-prometheus/experimental/custom-metrics-api/gencerts.sh, contrib/kube-prometheus/test.sh, hack/concat-kubernetes-manifests.sh, hack/run-external.sh, hack/show-image.sh, helm/hack/e2e-test.sh, helm/hack/helm-package.sh, helm/hack/sync-repo.sh, helm/hack/wait-pods-running-state.sh, scripts/check_license.sh, scripts/create-minikube.sh, scripts/travis-e2e-helm.sh, scripts/travis-e2e.sh
**Work in progress**
As an attempt to catch my bash script bugs early on.
[1] https://github.com/koalaman/shellcheck
=> format: Introduce shellcheck [1] for shell script analysis

Dockerfile, Documentation/user-guides/cluster-monitoring.md, Documentation/user-guides/getting-started.md, bundle.yaml, contrib/kube-prometheus/manifests/0prometheus-operator-deployment.yaml, contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml, contrib/kube-prometheus/manifests/prometheus-rules.yaml, example/non-rbac/prometheus-operator.yaml, example/rbac/prometheus-operator/prometheus-operator-deployment.yaml, jsonnet/prometheus-operator/prometheus-operator.libsonnet
* Make the Prometheus Operator Docker image run as `nobody` by default.
* Disallow privilege escalation via K8s
* Enforce read only root filesystem
//CC @squeed
=> security: Enforce nobody user and read only /

Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/README.md, contrib/kube-prometheus/jsonnet/kube-prometheus/kube-state-metrics/kube-state-metrics.libsonnet, contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml, contrib/kube-prometheus/manifests/kube-state-metrics-deployment.yaml, contrib/kube-prometheus/manifests/kube-state-metrics-serviceMonitor.yaml, contrib/kube-prometheus/manifests/prometheus-rules.yaml
As I work with kube-state-metrics in a large cluster, I found I needed to make some adjustments.
- Expose the collectors, allowing one to configure exclusions. 
- Expose resource limits, allowing large adjustments.
=> Configure kube-state-metrics

contrib/kube-prometheus/manifests/grafana-deployment.yaml
=> Update jsonnet dependencies

helm/prometheus-operator/Chart.yaml, helm/prometheus-operator/templates/deployment.yaml, helm/prometheus-operator/values.yaml, pkg/prometheus/statefulset.go
Follow-up PR of https://github.com/coreos/prometheus-operator/pull/1475
=> Enable logFormat in helm / Forward option from operator to p-c-r 

.github/ISSUE_TEMPLATE.md
We pretty much always need to ask the version of the operator to debug issues.
cc @mxinden
=> .github: request operator version in issues

contrib/kube-prometheus/jsonnet/kube-prometheus/alerts/node.libsonnet, contrib/kube-prometheus/manifests/prometheus-rules.yaml, helm/exporter-node/Chart.yaml, helm/exporter-node/templates/node.rules.yaml, helm/kube-prometheus/Chart.yaml, helm/kube-prometheus/requirements.yaml
Based on the discussion in https://github.com/coreos/prometheus-operator/issues/1180
=> Only alert for nodes that currently exist

cmd/operator/main.go, pkg/alertmanager/operator.go, pkg/alertmanager/statefulset.go, pkg/prometheus/operator.go, pkg/prometheus/statefulset.go
Add flag for fixing localhost resolve issue: https://github.com/coreos/prometheus-operator/issues/1646
=> Make localhost for local pods configurable via operator flag

.editorconfig
This will be useful for helm charts
=> .editorconfig: Add configuration for yaml files

contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet
to implement the feature from PR #1227
=> add serviceMonitorNamespaceSelector to the prometheus jsonnet library

pkg/prometheus/operator.go, test/e2e/prometheus_test.go
Fixes #1768
@mxinden @squat @s-urbaniak
=> prometheus: Fix error handling when not generating config

contrib/kube-prometheus/examples/etcd-skip-verify.jsonnet, contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-static-etcd.libsonnet, contrib/kube-prometheus/jsonnetfile.lock.json
Closes #1755 
@mxinden @squat @s-urbaniak
cc @jolson490
=> kube-prometheus: Allow skipping etcd TLS errors

contrib/kube-prometheus/experimental/custom-metrics-api/gencerts.sh, contrib/kube-prometheus/hack/example-service-monitoring/deploy, contrib/kube-prometheus/hack/example-service-monitoring/teardown, hack/concat-kubernetes-manifests.sh, hack/generate-bundle.sh, hack/generate/build-non-rbac-prometheus-operator.sh, hack/generate/build-rbac-prometheus-operator.sh, hack/run-external.sh, hack/show-image.sh, hack/show-rules.sh, scripts/check_license.sh
Adding the following accross the project:
```bash
/# exit immediately when a command fails
set -e
/# only exit with zero if all commands of the pipeline exit successfully
set -o pipefail
/# error on unset variables
+set -u
```
=> *.sh: Set sane bash options on shell scripts

pkg/listwatch/listwatch_test.go
=> pkg/listwatch: add unit tests for multiWatch

Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/jsonnet/kube-prometheus/jsonnetfile.json, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/0prometheus-operator-deployment.yaml, contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml
=> kube-prometheus: Update Prometheus Operator to v0.23.2

pkg/prometheus/statefulset.go
This changes set cluster.address and grpc-address from pod.ip.
It's disabled automatic pod ip detection which is not working, on node with multi network interfaces or non standart private network
issue details: #1835 
Signed-off-by: Calu <lucas.boisserie@gmail.com>
=> Set thanos cluster and grpc ip from pod.ip

Documentation/user-guides/cluster-monitoring.md
File: `Documentation/user-guides/cluster-monitoring.md`
=> Add missing angular bracket

Documentation/api.md, Documentation/user-guides/storage.md, contrib/kube-prometheus/README.md, contrib/kube-prometheus/examples/minikube.jsonnet, contrib/kube-prometheus/examples/prometheus-pvc.jsonnet
=> kube-prometheus: PVC (using persistent storage for the prom tsdb) example/documentation

contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml, contrib/kube-prometheus/manifests/prometheus-rules.yaml
This bumps the kubernetes-mixin dependency to add
https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/76.
=> kube-prometheus: bump kubernetes-mixins

contrib/kube-prometheus/jsonnet/kube-prometheus/alerts/alertmanager.libsonnet, contrib/kube-prometheus/jsonnet/kube-prometheus/alerts/general.libsonnet, contrib/kube-prometheus/jsonnet/kube-prometheus/alerts/node.libsonnet
small commit to fix alert messages. more fixes coming in kubernetes-monitoring/kubernetes-mixin
cc @brancz @metalmatze @s-urbaniak
=> contrib/.../alerts: improve alert messages

Documentation/design.md
It was missing. Any comments/suggestions welcome
=> Add PrometheusRule in design doc

pkg/k8sutil/k8sutil_test.go
cc @mxinden @metalmatze 
addresses: https://github.com/coreos/prometheus-operator/pull/1907#pullrequestreview-157673507
=> pkg/k8sutil: add test case for secret name sanitization

pkg/alertmanager/operator.go, pkg/prometheus/operator.go, scripts/create-minikube.sh, test/e2e/alertmanager_test.go, test/e2e/main_test.go, test/e2e/prometheus_test.go
Fixes #1926
@mxinden @s-urbaniak @squat @metalmatze
=> *: Add illegal update reconciliation

Documentation/compatibility.md, Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/prometheus-prometheus.yaml, pkg/prometheus/statefulset.go, test/e2e/alertmanager_test.go, test/e2e/prometheus_test.go, test/framework/alertmanager.go
Supersedes https://github.com/coreos/prometheus-operator/pull/1894.
=> *: Update to Prometheus 2.4.0

pkg/prometheus/promcfg.go
Fixed generateRemoteReadConfig function to generate bearer_token
Fixes #1955
=> Remote read config generator

README.md, RELEASE.md
@metalmatze this should give a good first start. Let's improve this as you are cutting the new Prometheus Operator release.
@brancz Any major concerns?
=>  RELEASE.md: Update documentation 

contrib/kube-prometheus/README.md
=> Add some commands to ensure kube-prometheus is fully successfully deployed

contrib/kube-prometheus/jsonnet/kube-prometheus/alertmanager/alertmanager.libsonnet
this way it will be possible to merge configs
=> objectify alertmanager config

contrib/kube-prometheus/jsonnet/kube-prometheus/alerts/prometheus.libsonnet, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/prometheus-rules.yaml
Change `Promehteus` to `Prometheus`
=> contrib: fix typo in contrib prometheus rules

Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/jsonnet/kube-prometheus/jsonnetfile.json, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/0prometheus-operator-0alertmanagerCustomResourceDefinition.yaml, contrib/kube-prometheus/manifests/0prometheus-operator-0prometheusCustomResourceDefinition.yaml, contrib/kube-prometheus/manifests/0prometheus-operator-0prometheusruleCustomResourceDefinition.yaml, contrib/kube-prometheus/manifests/0prometheus-operator-deployment.yaml, contrib/kube-prometheus/manifests/prometheus-rules.yaml
=> kube-prometheus: Bump Prometheus Operator to v0.25.0

contrib/kube-prometheus/docs/exposing-prometheus-alertmanager-grafana-ingress.md
See: https://github.com/coreos/prometheus-operator/pull/2026#discussion_r228917452
=> kube-prometheus: docs - fix example link

contrib/kube-prometheus/README.md
Added some instructions to update jb and update the prometheus operator. Requested here https://github.com/coreos/prometheus-operator/issues/2050
=> Adding an how to update section in kube-prometheus doc

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
=> Better handling for pod/node labels from ServiceMonitors. 

Documentation/api.md, Documentation/user-guides/storage.md, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml, contrib/kube-prometheus/manifests/prometheus-rules.yaml
Fix https://github.com/helm/charts/issues/9034, replacements list:
```
{{ $labels.job }} -> {{ $labels. job_name }}
{{ $labels.namespaces }} -> {{ $labels.namespace }}
```
=> Fix k8s labels in prometheus rules

README.md
=> README: some grammar fixes

Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/README.md, contrib/kube-prometheus/jsonnet/kube-prometheus/alertmanager/alertmanager.libsonnet, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/alertmanager-alertmanager.yaml, contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml, contrib/kube-prometheus/manifests/prometheus-rules.yaml, pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, test/e2e/alertmanager_test.go
https://github.com/prometheus/alertmanager/releases/tag/v0.15.3
=> Move to Alertmanager 0.15.3

contrib/kube-prometheus/README.md, contrib/kube-prometheus/examples/jsonnet-snippets/kube-aws.jsonnet, contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-kube-aws.libsonnet, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/grafana-deployment.yaml, contrib/kube-prometheus/manifests/prometheus-rules.yaml
simple examples for kube-aws. Just the services to monitor kube-controller-manager and kube-scheduler.
=> adding examples for kube-aws

pkg/prometheus/statefulset.go
=> sanitize thanos secret volume mount name

contrib/kube-prometheus/jsonnet/kube-prometheus/alerts/alertmanager.libsonnet, contrib/kube-prometheus/jsonnet/kube-prometheus/alerts/tests.yaml, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/prometheus-rules.yaml
=> Fix AlertmanagerMembersInconsistent rule

contrib/kube-prometheus/docs/exposing-prometheus-alertmanager-grafana-ingress.md
Explicitly reference values we are interesting in (jsonnet style)
instead of just following conventions (helm style)
=> Change examples to be more robust against customizations

Documentation/design.md, Documentation/thanos.md
Adds some Thanos documentation.
=> Thanos docs

Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/jsonnet/kube-prometheus/jsonnetfile.json, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/0prometheus-operator-0alertmanagerCustomResourceDefinition.yaml, contrib/kube-prometheus/manifests/0prometheus-operator-0prometheusCustomResourceDefinition.yaml, contrib/kube-prometheus/manifests/0prometheus-operator-deployment.yaml, contrib/kube-prometheus/manifests/prometheus-rules.yaml
=> kube-prometheus: bump prometheus-operator

contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus-adapter/prometheus-adapter.libsonnet, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/prometheus-adapter-deployment.yaml
=> contrib/kube-prometheus: bump k8s-adapter to fix bug

pkg/prometheus/operator.go
Alternative implementation for same problem as in https://github.com/coreos/prometheus-operator/pull/1997
=> Load ServiceMon secrets directly

Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/jsonnet/kube-prometheus/kube-state-metrics/kube-state-metrics.libsonnet, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/kube-state-metrics-deployment.yaml
Update to latest kube-state-metrics release
=> contrib/kube-prometheus: Update kube-state-metrics to v1.5.0

contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-thanos.libsonnet
As of now we start Thanos as sidecar and provide the store as StatefulSet as well as the querier as Deployment. However we don't collect any metrics from these components.
This PR adds a ServiceMonitor collecting metrics from Services that have `thanos-peers: true` and that then matches pods having `thanos-peers: true` too. Thus, we can scrape sidecars, stores an queriers with one ServiceMonitor. 
Tested on my minikube cluster.
/cc @brancz @squat @s-urbaniak
=> contrib/kube-prometheus: Add ServiceMonitor for thanos-peers

contrib/kube-prometheus/jsonnet/kube-prometheus/kube-state-metrics/kube-state-metrics.libsonnet, contrib/kube-prometheus/jsonnetfile.lock.json
Small follow up from #2308 
@mxinden @s-urbaniak @metalmatze @squat
=> Remove duplicate list

Documentation/thanos.md
Make it more obvious with which versions the new Thanos guide is compatible.
/cc @brancz @mxinden @squat
=> Documentation: Add version constraint to Thanos doc

contrib/kube-prometheus/jsonnet/kube-prometheus/rules/node-rules.libsonnet, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/prometheus-rules.yaml
Also, bump `node-exporter` to `0.17.0`.
=> Update remaining node-exporter rules

contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml, contrib/kube-prometheus/manifests/prometheus-rules.yaml
Hi, @brancz!
This sync allows https://github.com/helm/charts/pull/10840 to be merged.
=> Sync rules

pkg/prometheus/statefulset.go
=> pass prometheus route prefix to thanos sidecar

contrib/kube-prometheus/jsonnet/kube-prometheus/alerts/general.libsonnet, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml, contrib/kube-prometheus/manifests/prometheus-rules.yaml
@metalmatze @s-urbaniak @mxinden @squat
=> Rename DeadMansSwitch to Watchdog

test/framework/alertmanager.go, test/framework/helpers.go
port is never used in the functions get/post requests.
=> test/framework/*: Remove unused port var

Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/README.md, contrib/kube-prometheus/jsonnet/kube-prometheus/kube-state-metrics/kube-state-metrics.libsonnet, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml, contrib/kube-prometheus/manifests/kube-state-metrics-deployment.yaml, contrib/kube-prometheus/manifests/prometheus-rules.yaml, helm/exporter-kube-state/templates/deployment.yaml, helm/exporter-kube-state/values.yaml
Fix for #2366.
Corrected the parameter to reflect new version. Also I've updated the references for the images and version.
=> Update to support new version of addon-resizer

Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/jsonnet/kube-prometheus/jsonnetfile.json, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/0prometheus-operator-0alertmanagerCustomResourceDefinition.yaml, contrib/kube-prometheus/manifests/0prometheus-operator-0prometheusCustomResourceDefinition.yaml, contrib/kube-prometheus/manifests/0prometheus-operator-0prometheusruleCustomResourceDefinition.yaml, contrib/kube-prometheus/manifests/0prometheus-operator-0servicemonitorCustomResourceDefinition.yaml, contrib/kube-prometheus/manifests/0prometheus-operator-deployment.yaml
=> Update Prometheus Operator in kube-prometheus to v0.29.0

Documentation/thanos.md
after fixed the indent, it works for me
=> updated thanos.md, fixed indent of thanos spec config

pkg/prometheus/operator.go
When operator starts endpoints for kubelet creates only in 3 minutes
=> fix startup nodeSyncEndpoints

contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-thanos.libsonnet, contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus.libsonnet, contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet
Update Prometheus, Thanos and Grafana's default versions.
This PR is mostly here, so that we can update Grafana from beta to stable.
/cc @brancz
=> contrib/kube-prometheus: Update Prometheus, Thanos & Grafana

pkg/prometheus/operator.go
This commit enables the creation of a Prometheus when
additionalScrapeConfigs is defined but points to a non-existent secret
and `additionalScrapeConfigs.optional` is set to `true`.
Formerly, the creation of the Prometheus would error; this change adds
support to respect the `optional` field.
Fixes: #2457
=> pkg/prometheus: optional secret in scrapeconfig

contrib/kube-prometheus/README.md
Follow up from #2519.
@mxinden @squat @s-urbaniak @metalmatze
=> kube-prometheus: Document disabling metrics-server on minikube

Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus-adapter/prometheus-adapter.libsonnet, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/grafana-deployment.yaml, contrib/kube-prometheus/manifests/prometheus-adapter-configMap.yaml, contrib/kube-prometheus/manifests/prometheus-prometheus.yaml
This should fix https://bugzilla.redhat.com/show_bug.cgi?id=1669410
@mxinden @metalmatze @squat @s-urbaniak @paulfantom
=> Fix prometheus adapter double accounting

contrib/kube-prometheus/jsonnet/kube-prometheus/alertmanager/alertmanager.libsonnet, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/alertmanager-service.yaml, contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml, contrib/kube-prometheus/manifests/grafana-deployment.yaml, contrib/kube-prometheus/manifests/prometheus-rules.yaml
@mxinden @metalmatze @s-urbaniak @squat @paulfantom
=> Set Alertmanager session affinity to ClientIP

Documentation/user-guides/cluster-monitoring.md, contrib/kube-prometheus/jsonnet/kube-prometheus/alerts/node.libsonnet, contrib/kube-prometheus/jsonnet/kube-prometheus/node-exporter/node-exporter.libsonnet, contrib/kube-prometheus/jsonnetfile.lock.json, contrib/kube-prometheus/manifests/node-exporter-daemonset.yaml, contrib/kube-prometheus/manifests/prometheus-rules.yaml
@mxinden @metalmatze @s-urbaniak @squat @paulfantom
=> Node clock skew and node network interface alerts

pkg/alertmanager/statefulset.go, test/e2e/alertmanager_test.go, test/framework/alertmanager.go
Trying to find a solution to flaky AM test discussed in #2534 
/cc @mxinden
=> test/e2e: Check for AM pods and cluster ready & no parallel

CHANGELOG.md, Documentation/additional-scrape-config.md, Documentation/thanos.md, Documentation/user-guides/exposing-prometheus-and-alertmanager.md
=> [Fix] Corrected word spelling error

pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
=> support storage.tsdb.retention.time for prometheus >=2.7.0

pkg/alertmanager/operator.go, pkg/alertmanager/statefulset.go, pkg/prometheus/operator.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go, vendor/modules.txt
Ref. https://github.com/coreos/prometheus-operator/issues/2592
=> Switch from apps/v1beta to apps/v1

pkg/alertmanager/statefulset.go
Solves https://github.com/coreos/prometheus-operator/issues/2599
Exists in alertmanager since early 2018: https://github.com/prometheus/alertmanager/issues/991
=> Alertmanager: Use /-/healthy and /-/ready for probes .

scripts/jsonnet/Dockerfile
Related to https://github.com/openshift/cluster-monitoring-operator/pull/351
/cc: @brancz @metalmatze @s-urbaniak @squat
=> scripts/jsonnet: add gawk to jsonnet container image

scripts/jsonnet/Dockerfile
Forgot about this one in #2609
/cc: @metalmatze
=> scripts/jsonnet: add python-yaml

README.md
Should at least add an explanation here about what the differences are, I am talking with the other maintainers about options around renaming the chart.
=> Add doc re community helm chart

pkg/prometheus/statefulset.go
In thanos v0.4, gossip was deprecated and disabled by default. With thanos v0.4, prometheus-operator users could (must?) migrate to gossip-less thanos while prometheus-operator continued to provide the extra (ignored) cluster args to the sidecar.
In thanos v0.5, the gossip code is removed along with its associated flags, which is now a fatal error to continue providing. 
This removes the sidecar's gossip/cluster args and the container's cluster port starting at thanos v0.5.0-rc.0.
Fixes #2517
=> Remove gossip from thanos sidecar v0.5.0-rc.0+

cmd/operator/main.go, pkg/alertmanager/operator.go, pkg/prometheus/operator.go, vendor/modules.txt
Recently a parameter has been added to filter by label selectors prometheus objects.
I did the same for alertmanagers
=> Adding label selector for AlertManager objects discovery filtering

pkg/k8sutil/k8sutil.go
Add support for KUBECONFIG env when starting controller.
This env  enables people to run and debug this operator in their local development  environment easily.
=> support KUBECONFIG environment

OWNERS
/cc @brancz @metalmatze @squat @LiliC @paulfantom
=> OWNERS: add LiliC

Documentation/thanos.md
Since thanos move to thanos-io org several days ago, this PR here update some thanos doc.
=> update some outdated thanos doc

scripts/create-minikube.sh
=> scripts/create-minikube.sh: Bump k8s to v1.14.5

scripts/jsonnet/Dockerfile
... as it was removed https://github.com/coreos/prometheus-operator/pull/2739.
=> scripts/jsonnet/Dockerfile: re-enable python-yaml

Documentation/thanos.md, cmd/operator/main.go, example/thanos/query-deployment.yaml, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go, test/e2e/prometheus_test.go
Since the latest thanos image is in quay.io/thanos/thanos, so update it.
=> bump thanos image and version

Documentation/user-guides/alerting.md
there is not more to say here.
=> Fix a typo

OWNERS
Happy to help in Prometheus Operator Maintainance :+1: 
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>
=> Added bwplotka to owner files.

.travis.yml, scripts/travis-push-docker-image.sh
Small nit, but IMO it's a bit more verbose when you see conditional above the script.
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>
=> Cleaned up travis yaml.

scripts/jsonnet/Dockerfile
@metalmatze @s-urbaniak @LiliC @paulfantom
=> scripts/jsonnet: Bump jsonnet and golangci-lint versions

Documentation/api.md, pkg/apis/monitoring/v1/types.go
I also removed the comment, as I am not sure what it means. If its meant as a TODO lets open an issue for it instead.
cc @paulfantom @brancz
=> pkg,Documentation: Add missing json struct tag

pkg/prometheus/promcfg_test.go
Adding some tests covering prometheus global settings.
=> pkg/prometheus: add testing global settings

pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1762968
@s-urbaniak @LiliC @paulfantom @pgier @simonpasquier @krasi-georgiev
=> *: Ensure containers have "FallbackToLogsOnError" termination policy

Documentation/design.md, Documentation/user-guides/getting-started.md, README.md, example/user-guides/getting-started/example-app-pod-monitor.yaml
Fixes https://github.com/coreos/prometheus-operator/issues/2738
Signed-off-by: Arno Uhlig <arno.uhlig@sap.com>
=> basic podmonitor docs

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Only append relabelings if EnforcedNamespaceLabel value is set.
cc @s-urbaniak @brancz
=> pkg/prometheus/promcfg.go: Only append relabelings if EnforcedNamespaceLabel value is set

Documentation/thanos.md, README.md, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
... as it's not required (:
Happy Halloween! :jack_o_lantern: 
Also:
* updated Thanos docs!
* added tests
* bumped default image.
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>
=> Do not disable compaction on sidecar without object storage configuration

Documentation/thanos.md
specify latest thanos version and remove extra whitespace
Thanks for the great project!
=> docs: update thanos image version

pkg/alertmanager/operator.go, pkg/prometheus/operator.go
=> deprecate baseImage, tag, and sha fields in custom resources

pkg/alertmanager/statefulset.go, pkg/prometheus/statefulset.go
=> Allow to configure PVC access mode

OWNERS
brings the OWNERS file in sync with openshift/prometheus-operator
=> OWNERS: add krasi-georgiev and paulfantom

pkg/thanos/rules_test.go, test/e2e/main_test.go
Add basic rules test for thanos.  Fix e2e test to call thanos e2e test.
=> improve thanosruler tests

pkg/alertmanager/statefulset.go, pkg/prometheus/statefulset.go, pkg/thanos/operator.go, pkg/thanos/statefulset.go, pkg/thanos/statefulset_test.go
Add thanos rules configmap reloader. Use the same logic with the reloader for Prometheus rules.
Already tested in my local environment.
=> Add thanos-ruler rules configmap reloader

pkg/prometheus/operator.go
=> prevent prometheus sts update loop

CHANGELOG.md
I noticed immediately after releasing that the date was incorrect in the changelog :(
=> fix date in CHANGELOG for v0.35.1

go.mod, go.sum, scripts/generate/jsonnetfile.json, vendor/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/init.go, vendor/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/install.go, vendor/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/main.go, vendor/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/update.go, vendor/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/version.go, vendor/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/version111.go, vendor/github.com/jsonnet-bundler/jsonnet-bundler/pkg/git.go, vendor/github.com/jsonnet-bundler/jsonnet-bundler/pkg/jsonnetfile/jsonnetfile.go, vendor/github.com/jsonnet-bundler/jsonnet-bundler/pkg/local.go, vendor/github.com/jsonnet-bundler/jsonnet-bundler/pkg/packages.go, vendor/github.com/jsonnet-bundler/jsonnet-bundler/spec/spec.go, vendor/modules.txt
Not sure if we want to start upgrading projects yet to jb v0.2.0, but I thought I would create this PR while I was thinking about it after some testing.
=> Upgrade jsonnet bundler

pkg/thanos/operator.go, pkg/thanos/rules.go
Updated some comments in Thanos Ruler.
=> Update comments from prometheus to thanos ruler

pkg/prometheus/statefulset_test.go, pkg/thanos/statefulset_test.go
Add some unit tests for thanos ruler, including:
1. tracing
2. obj store
3. labels and alert drop labels
4. additional container
=> Add some thanos ruler unit tests

Documentation/api.md, cmd/po-docgen/api.go
=> Update api doc links

Documentation/compatibility.md, pkg/prometheus/statefulset.go
=> support Prometheus v2.16.0

cmd/operator/main.go, pkg/prometheus/operator.go
=> add cli option to set web listen address

cmd/operator/main.go, cmd/operator/main_test.go, pkg/listwatch/listwatch.go, pkg/listwatch/namespace_denylist.go, pkg/listwatch/namespace_denylist_test.go, pkg/prometheus/operator.go
minor simplification of CLI arg handling
=> Use map for namespace config

Documentation/rbac.md, Documentation/user-guides/getting-started.md, bundle.yaml, example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml, jsonnet/prometheus-operator/prometheus-operator.libsonnet
=> Release 0.34 restrict api extension rbac rules

pkg/thanos/operator.go
Spotted this typo while working on another issue...
=> pkg/thanos: fix typo in statefulset informer

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/support.md
- add notes about kube-prometheus and helm installations
- remove tectonic-installer from cluster installation examples
/cc @coreos/team-monitoring
=> .github/ISSUE_TEMPLATES: small update

Documentation/user-guides/webhook.md, README.md
=> docs: add a user-guide for the admission webhook

README.md
* Update listed features to include references to Alertmanager
and Thanos Ruler.
* Update Kubernetes version prerequisites
* Update wording in various places
=> README.md: updates and improvements

pkg/operator/defaults.go
~~Created a a draft because v0.21.0 isn't built yet.~~
=> pkg/operator: bump Alertmanager default version to v0.21.0

test/e2e/main_test.go, test/e2e/prometheus_test.go, test/framework/probe.go
This pr adds a basic E2E test for Probe with static targets.
=> Add E2E test for probe static targets

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Support jobName, honor_labels and honor_timestamps config in probe
=> Support job name in probe

bundle.yaml, example/non-rbac/prometheus-operator.yaml, example/rbac/prometheus-operator/prometheus-operator-deployment.yaml, jsonnet/prometheus-operator/prometheus-operator.libsonnet, pkg/operator/defaults.go
https://github.com/jimmidyson/configmap-reload/compare/v0.3.0...v0.4.0
Updates default configmap-reload image to more recent version
=> configmap-reload: Update to v0.4.0

RELEASE.md
=> Volunteer for prometheus-operator v0.41 release

pkg/listwatch/listwatch.go, pkg/listwatch/listwatch_test.go
This cherry-picks the https://github.com/coreos/prometheus-operator/pull/3340 into master.
cc @brancz @paulfantom
=> listwatch: do not duplicate resource versions

.travis.yml, scripts/travis-push-docker-image.sh
Allow pushing release images from `release-0.41` branch to new quay organization.
/cc @brancz @lilic
=> secondary stage to push images to quay.io/coreos

RELEASE.md
And fix link to Prometheus documentation
=> RELEASE.md: add myself (Simon Pasquier) for v0.43

pkg/alertmanager/operator.go
The Alertmanager controller deleted dependent resources manually while
prometheus and thanos rely on Kubernetes to do the work using
OwnerReferences.
=> pkg/alertmanager: cleanup resources via OwnerReferences

cmd/operator/main.go, cmd/operator/main_test.go, pkg/alertmanager/operator.go, pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, pkg/listwatch/listwatch.go, pkg/listwatch/listwatch_test.go, pkg/listwatch/namespace_denylist.go, pkg/listwatch/namespace_denylist_test.go, pkg/prometheus/operator.go, pkg/thanos/operator.go, pkg/thanos/statefulset.go, test/e2e/alertmanager_test.go, test/framework/alertmanager.go
Backport PRs #3126,#3179,#3182,#3233 and their dependencies
=> Backport PRs #3126,#3179,#3182,#3233

Documentation/user-guides/getting-started.md, bundle.yaml, example/non-rbac/prometheus-operator.yaml, example/rbac/prometheus-operator/prometheus-operator-deployment.yaml, jsonnet/prometheus-operator/prometheus-operator.libsonnet, pkg/operator/defaults.go
Rename quay.io/coreos/* images to quay.io/prometheus-operator/*.
Closes #3448
=> *: update image locations to new org

cmd/operator/main.go, pkg/alertmanager/operator.go, pkg/api/api.go, pkg/k8sutil/k8sutil.go, pkg/prometheus/asset_store.go, pkg/prometheus/asset_store_test.go, pkg/prometheus/operator.go, pkg/prometheus/rules.go, pkg/thanos/operator.go, pkg/thanos/rules.go, test/framework/prometheus.go, test/framework/thanosruler.go
Follow-up of [#3445](https://github.com/prometheus-operator/prometheus-operator/pull/3445#issuecomment-683810179).
=> *: pass context.Context to client-go functions

pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
When the Thanos spec doesn't configure object storage, there's no need to
configure the Thanos sidecar for block uploads and mount the
Prometheus data volume.
=> pkg/prometheus: enable Thanos uploads only when needed

cmd/po-docgen/api.go
When po-docgen was generating the API documentation, it was
intentionally skipping inlined fields. Thus, they were absent from the
documentation instead of being displayed inline.
The assumption to skip inlined fields was correct for foreign types as
we most likely don't want their content to be part of the API
documentation. However, we want the content of internal types to be
inlined correctly.
This PR originates from the following discussion: https://github.com/prometheus-operator/prometheus-operator/pull/3370#discussion_r486931129
=> po-docgen: fix doc generation for inlined fields

RELEASE.md
=> RELEASE.md: add instructions for tagging pkg/apis/monitoring

example/mixin/alerts.yaml, jsonnet/mixin/alerts/alerts.libsonnet
Issue was found while including mixin in kube-prometheus project https://github.com/prometheus-operator/kube-prometheus/pull/677
=> mixin: incorrect promql expression

.github/workflows/.mlc_config.json, .github/workflows/ci.yaml, CONTRIBUTING.md, Documentation/additional-scrape-config.md, Documentation/api.md, Documentation/custom-configuration.md, Documentation/thanos.md, Documentation/user-guides/monitoring-kubernetes-ingress.md, Documentation/user-guides/webhook.md, pkg/apis/monitoring/v1/types.go
=> Add broken links check in CI

CHANGELOG.md, RELEASE.md, go.mod
Towards: https://github.com/prometheus-operator/prometheus-operator/issues/3530
=> set pkg/apis/monitoring tag to v0.42.1

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Closes https://github.com/prometheus-operator/prometheus-operator/issues/3476
I have not tested this as I am waiting for examples from @nerzhul. Hence WIP until then, just opening PR in case @nerzhul wants to test it out.
=> pkg/prometheus/promcfg.go: Generate more unique probe job name

go.mod, test/e2e/alertmanager_test.go, test/framework/alertmanager.go
=> Update Alertmanager api to v2 in E2E test

pkg/prometheus/operator.go
=> pkg/prometheus: add more logs to syncNodeEndpoints()

test/framework/alertmanager.go
=> Fix flaky e2e Alertmanager test 

pkg/alertmanager/operator.go
=> pkg/alertmanager: add metrics on selected/rejected AlertmanagerConfig

Documentation/user-guides/running-exporters.md
Aligned serviceMonitor usage inline with getting-started
=> Documentation: Aligned serviceMonitor usage inline with getting-started

pkg/versionutil/cli_test.go
Not sure how this bug has slipped through the CI...
=> pkg/versionutil: fix tests

pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go
This change ensures that the operator rejects AlertmanagerConfig objects
defining:
* Routes that reference non-existing receivers.
* Duplicate receivers.
=> pkg/alertmanager: add more validations for AlertmanagerConfig objects

example/mixin/alerts.yaml, jsonnet/mixin/alerts/alerts.libsonnet
=> jsonnet/mixin: add PrometheusOperatorRejectedResources alert

pkg/alertmanager/operator.go, pkg/listwatch/listwatch.go, pkg/prometheus/operator.go, pkg/thanos/operator.go
=> Refactor to remove context.TODO

RELEASE.md
=> *: add @paulfantom as next release shepherd

test/framework/helpers.go
Signed-off-by: sheetalsingala <ssingala@redhat.com>
Fixes #3639
=> Remove framework.Poll

.github/workflows/ci.yaml
See https://github.com/engineerd/setup-kind/issues/28 for details
=> .github: update version of engineerd/setup-kind

pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, pkg/operator/image.go, pkg/operator/image_test.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go, pkg/thanos/statefulset.go, pkg/thanos/statefulset_test.go
=> #3623: Fix usage of --prometheus-default-base-image, --alertmanager-default-base-image, --thanos-default-base-image

scripts/go.mod, scripts/go.sum
=> upgrade to jsonnet v0.17.0

pkg/prometheus/operator.go, pkg/prometheus/promcfg.go
Added the TLS support for Remote Read , The support is already present for Remote Write
Fixes #3635
=> Adding TLS support for remote read

cmd/prometheus-config-reloader/main.go
log the error msg if reloader watcher failed or we don't what it faield.
```release-note:REPLACEME
```
=> log error when reloader watching file failed

MAINTAINERS.md
```release-note:none
```
@prometheus-operator/prometheus-operator-reviewers
=> MAINTAINERS.md: Update my company association

pkg/prometheus/operator.go
**Release Note**
```release-note:bug
Fix log messages when syncing node endpoints.
```
=> pkg/prometheus: fix log messages in syncNodeEndpoints()

pkg/prometheus/operator.go
```release-note:enhancement
Add `app.kubernetes.io/name` label to Kubelet Service/Endpoints object.
```
Related to https://github.com/prometheus-operator/kube-prometheus/pull/858
@prometheus-operator/prometheus-operator-reviewers
=> *: Add recommended app label to kubelet Service/Endpoints

cmd/operator/main.go
This change configures the HTTP server with the same logger we use
everywhere else.
**Release Note **
```release-note:enhancement
Improve HTTP server's logging
```
=> cmd/operator: improve HTTP server's logging

cmd/operator/main.go
```release-note:change
remove deprecated --config-reloader-image flag
```
=> cmd/operator: remove deprecated --config-reloader-image flag

test/e2e/alertmanager_instance_namespaces_test.go
**Release Note Template **
```release-note:none
```
=> test/e2e: fix compilation error

Documentation/rbac.md, Makefile, bundle.yaml, example/non-rbac/prometheus-operator.yaml, example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml, example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml, example/rbac/prometheus-operator/prometheus-operator-deployment.yaml, example/rbac/prometheus-operator/prometheus-operator-service-account.yaml, example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml, example/rbac/prometheus-operator/prometheus-operator-service.yaml, jsonnet/prometheus-operator/prometheus-operator.libsonnet, scripts/generate/config.jsonnet, scripts/generate/prometheus-operator-non-rbac.jsonnet, scripts/generate/prometheus-operator-rbac.jsonnet
- remove ksonnet
- refactor code to be more "functional"
This is needed for https://github.com/prometheus-operator/kube-prometheus/issues/566
```release-note: change
refactored jsonnet library to remove ksonnet and align with kube-prometheus
```
=> jsonnet: refactor

Documentation/user-guides/alerting.md
Remove mention of tectonic (:cry:) and an inactive email address.
```release-note:none
```
=> Documentation: remove mention of inactive email

Makefile, scripts/generate/config.jsonnet
Follow-up to #3781. Add dependencies on a new target.
Tested on Linux by executing:
```
echo 0.99.0 > VERSION
make generate
```
The above should change version number in all files it is used.
/cc @lilic can you test this on MacOS?
```release-note:none
```
=> *: fix generator by adding dependencies on config.jsonnet

RELEASE.md
cc @s-urbaniak since we've discussed it offline.
```release-note:none
```
=> RELEASE.md: update shepherds for v0.46 and v0.47

Documentation/compatibility.md, pkg/operator/defaults.go, pkg/prometheus/promcfg.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
Closes #2813 
```release-note:change
Drop support for prometheus 1.x
```
=> Remove support for prometheus 1.x

README.md
Adds reference to the troubleshooting document in the main README.md
=> Update README.md with troubleshooting reference

ADOPTERS.md
As discussed on slack.
@prometheus-operator/prometheus-operator-reviewers
=> Add start of ADOPTERS.md

ADOPTERS.md
Add template for next adopters entries.
@prometheus-operator/prometheus-operator-reviewers
=> Add Adopters template

ADOPTERS.md
Adds Skyscanner to Adopters list.
=> Adopters: Add Skyscanner

ADOPTERS.md
Adds Giant Swarm to the Adopters list.
=> Add Giant Swarm as an adopter

ADOPTERS.md
Add [Veepee](https://www.veepee.com) as an adopter of the solution.
**Warning**, this is the stats for our biggest Kubernetes cluster at this moment. 
If you wants me to summary all our Kubernetes clusters (as they are part of a big federation) tell me.
=> Add Veepee as adopter of the solution

ADOPTERS.md
Adds Lunar to the Adopters list.
<!-- AUTOCHANGELOG for Downstream PRs.
release-note:none
=> Added Lunar as adopter

ADOPTERS.md
Fix #3870
```release-note:none
```
=> sort ADOPTERS file

cmd/po-lint/main.go
Fixes: #3147
Check prometheus rules in CRD PrometheusRules with promtool lib
=> add rulefmt check to po-lint

ADOPTERS.md
Previously we only put one Kubernetes cluster.
Now we publish stats for all our clusters
```release-note:REPLACEME
```
=> Update Veepee on ADOPTER.md

ADOPTERS.md, CONTRIBUTING.md, Documentation/api.md, Documentation/compatibility.md, Documentation/design.md, Documentation/high-availability.md, Documentation/rbac-crd.md, Documentation/rbac.md, Documentation/thanos.md, Documentation/troubleshooting.md, cmd/po-docgen/api.go, cmd/po-docgen/compatibility.go
I've started creating a website and for that we are going to be adding YAML headers to all files we want to publish on that site.
Here are a few first ones.
=> Add headers for Hugo website

.golangci.yml, cmd/operator/main.go, go.mod, go.sum, pkg/alertmanager/amcfg.go, pkg/alertmanager/statefulset.go, pkg/prometheus/operator.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/statefulset.go, test/e2e/alertmanager_test.go, test/e2e/denylist_test.go, test/e2e/prometheus_instance_namespaces_test.go, test/e2e/prometheus_test.go, test/e2e/thanosruler_test.go, test/instrumented-sample-app/main.go
Follow-up of #3924
```release-note:none
```
=> *: fix staticcheck errors

.golangci.yml, cmd/po-docgen/api.go, pkg/alertmanager/statefulset.go, pkg/prometheus/statefulset.go, pkg/thanos/statefulset.go, test/framework/admission-webhooks.go, test/framework/crd.go
=> *: fix gosimple errors

.golangci.yml, cmd/operator/main.go, example/alertmanger-webhook/main.go, pkg/alertmanager/operator.go, pkg/prometheus/operator.go, scripts/errcheck_excludes.txt, test/instrumented-sample-app/main.go
=> *: fix errcheck errors

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/support.md
Better information about providing prometheus-operator version and not helm chart or kube-prometheus.
```release-note:none
```
=> .github/ISSUE_TEMPLATE: clarifications

ADOPTERS.md
=> Add gitpod to Adopters 🎉

ADOPTERS.md
Add Nozzle to Adopters.md
<!-- AUTOCHANGELOG for Downstream PRs.
Please select one of the following "release-note:" headings:
- release-note:none
=> Add Nozzle to Adopters.md

ADOPTERS.md
For almost every PR updating ADOPTERS.md, we need to ask people to keep the list alphabetically ordered. This PR rearranges the document to make it clearer.
```release-note:none
```
=> ADOPTERS.md: update instructions

MAINTAINERS.md
=> Update metalmatze's company

RELEASE.md
=> RELEASE.md: add instruction for website

Documentation/troubleshooting.md
Reverts prometheus-operator/prometheus-operator#4008
=> Revert "Update troubleshooting.md"

ADOPTERS.md
About time we added ourselves to this list :D
```release-note:none
```
=> Add Wise to adopters list
