prometheus-operator/prometheus-operator

- pkg/operator/petset.go
When the value of the annotation is empty the cluster still tries to
auto provision the PVC/PV.
This fix allows users to specify the variables for the PVC Template
without requiring auto provisioning of PVs.
> pkg/operator: only set storage class annotation if given

- example/node-exporter-bundle.yaml
- example/node-exporter-monitor.yaml
- pkg/operator/petset.go
Added the node exporter manifests here for testing purposes and so they won't pollute the Alertmanager PR. Let me know if you think that's ok. The actual fix is in `pkg/operator/petset.go`.
@fabxc
> pkg/operator: fix flag typo

- Documentation/alertmanager.md
- cmd/prometheus-operator/main.go
- example/alertmanager-config.yaml
- example/alertmanager-service.yaml
- example/alertmanager.yaml
- example/prometheus.yaml
- pkg/alertmanager/client.go
- pkg/alertmanager/operator.go
- pkg/alertmanager/petset.go
- pkg/analytics/analytics.go
- pkg/prometheus/client.go
- pkg/prometheus/operator.go
- pkg/prometheus/petset.go
- pkg/prometheus/promcfg.go
- pkg/spec/spec.go
I would like to use this PR as a discussion about how we structure this repo. I deliberately did not change the `Makefile` yet to start the discussion un-opinionated in terms of code.
The dilemma is to either ship a single binary as a "monitoring-operator" and include all operators that _can_ be used for monitoring. It is actually a very similar approach to the official kubernetes components, where you might not actually use all controllers available, but have them at hand when you do need them. In contrast to shipping multiple binaries and having to operate/update/version each of them as an operator.
Depending on the outcome we'll need to add documentation in different ways. Either a single unified documentation or separate docs for each operator.
Wdyt @fabxc? Feel free to draw anyone …
> add Alertmanager operator

- Documentation/service-monitor.md
- pkg/prometheus/promcfg.go
- pkg/spec/spec.go
The jobLabel field allows generating safe job names based on labels.
This is necessary for services running the same application to have the
same job name even though their direct service names are different.
The default case still falls back to the plain service name.
@brancz
> Add jobLabel field

- pkg/prometheus/operator.go
- pkg/prometheus/promcfg.go
- pkg/spec/spec.go
@brancz 
This implements selection by "any" and a list of names for namespaces. By default it only includes the namespace of the specified ServiceMonitor. (As discussed in #39)
This is just based on my idea on this issue – there was not opinions stated towards either of the options.
Configuration is now generated without templates. Still not using config types but notably safer and saner nonetheless.
Also added mapping of the label selections via set operations to the appropriate relabeling configs.
> Namespace selection and service label set matching

- pkg/alertmanager/operator.go
- pkg/k8sutil/k8sutil.go
- pkg/prometheus/operator.go
- test/e2e/framework/framework.go
Making this method more easily reusable could be a first step in extracting a common set of helper functions for TPR based operators.
> Make WaitForTPRReady more reusable by passing configured RESTClient rather than raw HTTPClient

- pkg/alertmanager/operator.go
- pkg/prometheus/operator.go
This handles ^C during startup rather than waiting for server connection to timeout.
> Gracefully handle interruption when initiating API server connection

- example/prometheus.yaml
- pkg/prometheus/operator.go
- pkg/prometheus/promcfg.go
- pkg/queue/queue.go
@brancz This got a bit convoluted with other changes. Essentially, the queue used now is deduping. So if we add an item several times while it's being processed, it will only be in the queue once.
Secondly, we enqueue keys, not full objects. Instead we retrieve the object when getting the key from the queue. That avoids stale updates as in the case where we have multiple updates while the item was enqueued.
Lastly, the deadlocking if the PetSet gets stuck because a pod cannot be scheduled (that's intentional btw). We do only delete pods manually to have them be recreated if there's no ongoing work by the PetSet controller to minimize disruption. Otherwise, we just re-enqueue ourselves.
If we do delete a pod, we just delete one and don't wait for recreation and delete the next etc. but …
> prometheus: fix queue staleness and deadlock

- pkg/alertmanager/operator.go
- pkg/k8sutil/k8sutil.go
- pkg/prometheus/operator.go
Also re-adds wrongly removed graceful handling interrupts during startup (see https://github.com/coreos/prometheus-operator/pull/51#discussion_r89768659)
> Fixes error handling when waiting for TPRs

- Documentation/prometheus.md
- pkg/prometheus/operator.go
- pkg/spec/spec.go
Mostly cleaning up very noisy logs. Every handler has its own methods – a bit verbose right now, but if we add metrics, further filtering steps etc. it will be more convenient.
Some better filtering added, i.e. only enqueue Prometheus keys for ServiceMonitor changes within the same namespace.
> Cleanup and filter event handling

- Makefile
- test/e2e/framework/framework.go
Instead of testing the current image in the repository we want to test with a container image that is built from current working tree.
Fixes #48
> test: build image from current tree when running e2e tests

- README.md
@fabxc lmk if you like this wording, or whether you just want to treat everything as one Operator or split up the TPRs in two sections. (personally I think we should refer to the whole thing as the *one* Prometheus Operator aka remove the `(s)` that it currently contains)
> README: reference Alertmanager docs

- cmd/operator/main.go
- pkg/alertmanager/operator.go
- pkg/api/api.go
- pkg/k8sutil/k8sutil.go
- pkg/prometheus/client.go
- pkg/prometheus/operator.go
- pkg/spec/spec.go
So we can observe a deployment of a new version we need a current state of the Prometheus deployment. This resembles a status object similar to the some used in the `Deployment` object. Until upstream kubernetes resolves how to manage sub-resources of TPRs we will keep this independent of the actual Prometheus TPR, but depending on the upstream decisions it might go into the Prometheus TPR at some point.
> add status endpoint

- pkg/alertmanager/operator.go
The Alertmanager config to use is not generated by the operator, it is
entirely user created, therefore don't delete it when the Alertmanager
TPR is deleted.
> pkg/alertmanager: don't delete Alertmanager config

- pkg/alertmanager/statefulset.go
- pkg/prometheus/statefulset.go
There is an issue with `emptyDir` volumes that does not allow them to have a `subPath` set. This should be non-disruptive for any other volume providers (I have done some tests and confirmed that the issue does not exist with `hostPath` volumes). Nonetheless I would like to ask some people to try this change with various providers.
@Rastusik you have previously introduced the `subPath` for volumes, do you happen to still have your GlusterFS available to test with a v1.5.1 cluster?
Fixes #74 
> *: no subPath for emptyDir volumes

- README.md
It seems that people often miss to notice `kube-prometheus` in the existing paragraph, so I would like to present it more prominently as people likely just want the one-click solution.
This was initially discussed out of bound with @chancez.
@fabxc @alexsomesan @jonboulle Do you think the wording is ok like this or maybe it should be even higher up in the readme itself?
> README: point out kube-prometheus more clearly

- pkg/alertmanager/statefulset.go
- pkg/prometheus/statefulset.go
- pkg/spec/spec.go
@alexsomesan @fabxc 
Tested with minikube. And the following manifests (replacing the manifests from `kube-prometheus`).
Prometheus:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
name: prometheus-k8s
labels:
prometheus: k8s
spec:
version: v1.4.1
externalUrl: http://192.168.99.100:30900/prometheus
resources:
requests:
memory: 400Mi
```
Alertmanager:
```
apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "Alertmanager"
metadata:
name: "alertmanager-main"
labels:
alertmanager: "main"
spec:
replicas: 3
version: v0.5.1
externalUrl: http://192.168.99.100:30903/alertmanager
```
Fixes #26
> External url

- pkg/api/api.go
- pkg/client/monitoring/v1alpha1/types.go
- pkg/prometheus/operator.go
I haven't added a test as a unit test would be testing the transformation of a faked http request. I would have wanted to add an end-to-end test, but as the operator is not exposed in any way it's not really possible to issue requests against it right now. Do you think it is worth exposing?
Either way, I tested this manually and have verified that this works.
@alexsomesan @fabxc
> pkg/client/monitoring/v1alpha1: use pointer for status

- Makefile
- pkg/alertmanager/operator.go
- pkg/alertmanager/statefulset.go
- pkg/client/monitoring/v1alpha1/types.go
- pkg/prometheus/operator.go
- test/e2e/alertmanager_e2e_test.go
- test/e2e/framework/alertmanager.go
- test/e2e/framework/framework.go
- test/e2e/framework/prometheus.go
- test/e2e/main_test.go
- test/e2e/prometheus_e2e_test.go
To run these e2e tests you need `minikube` installed on your local machine. In addition to that two recently added APIs are required of upstream Prometheus (targets/alertmanager API). Therefore to run these tests your cluster needs to use an image that already has those. As there is no release out yet that does the `master` image is used here.
> make sure you set your `DOCKER_HOST` to the minikube provided one
Then run these e2e tests with (this also builds the operator from current working tree tagged with the short `HEAD` commit hash):
```
make e2e
```
Prometheus test suite now consists of:
- create/delete
- scale up/down
- version migration
- config generation, target discovery and basic query
- alertmanager discovery
Alertmanager test suite now consists of:
- create/delete
- scale …
> test: extend prometheus/alertmanager e2e test suites

- Documentation/service-monitor.md
- pkg/client/monitoring/v1alpha1/types.go
Just so we keep a habit of having all of our API objects documented, I completed it for everything we have now and whenever we add something. And this is potentially interesting for #110. Once we should revisit the docs we have in place and the current comments and take the best of both as they are sometimes more detailed in one then the other.
@alexsomesan @fabxc
> *: complete comments for types

- Documentation/prometheus.md
- pkg/client/monitoring/v1alpha1/types.go
- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
This rebases #109 for inclusion in upcoming release.
Also fills in the license header missing in a test file.
> Rebase node selector PR + fix license header in test

- Documentation/prometheus.md
@alexsomesan 
It's a `map[string]string` which is simply of an object type in sync with the Kubernetes API docs.
> Fix node selector documentation

- Documentation/alertmanager.md
- Documentation/exposing-prometheus-and-alertmanager.md
- Documentation/prometheus.md
- pkg/client/monitoring/v1alpha1/types.go
- pkg/prometheus/statefulset.go
I started writing this documentation on exposing Prometheus and Alertmanager to the outside world as mentioned in #98, and realized that for Prometheus the `routePrefix` is necessary for when a proxy (`kubectl proxy` in this case) rewrites request URLs. It removes the `/api/v1/...` part from the request, which is not a problem for the Alertmanager, which does relative requests, but Prometheus does require it, and it won't go away soon as it is part of the stability guarantee of version 1.
@alexsomesan @fabxc 
@mxinden maybe we can come up with a few test cases to cover all of these in our e2e tests.
> Exposing Prometheus and Alertmanager

- .gitignore
- Dockerfile
- Makefile
- pkg/prometheus/statefulset.go
- test/e2e/prometheus_e2e_test.go
Two small things before we finish up the `0.3.0` release.
* separate building the binary from building the container image
* use `v1.5.0` of Prometheus where we used `master` before and use it as the default image
e2e tests passing :)
@alexsomesan @fabxc @mxinden
> Fix container build

- Makefile
- test/e2e/alertmanager_e2e_test.go
- test/e2e/framework/alertmanager.go
- test/e2e/framework/framework.go
- test/e2e/framework/ingress.go
- test/e2e/framework/prometheus.go
- test/e2e/framework/replication-controller.go
- test/e2e/framework/ressources/default-http-backend-service.yml
- test/e2e/framework/ressources/default-http-backend.yml
- test/e2e/framework/ressources/nxginx-ingress-controller.yml
- test/e2e/framework/service.go
- test/e2e/prometheus_e2e_test.go
Ensuring functionality of the "Exposing prometheus and alertmanaer"
tutorial. Testing exposure of alertmanager and prometheus via Nodeport,
Kubernetes API and Ingress controller.
https://github.com/coreos/prometheus-operator/blob/master/Documentation/exposing-prometheus-and-alertmanager.md
> test: Add e2e alertmanager & prometheus exposure tests

- Documentation/high-availability.md
Multiple people have asked about a high availability scheme documentation regarding Prometheus. This is a document describing it and commenting on the role the operator has in it.
@alexsomesan @fabxc
> Documentation: add high availability scheme documetation

- cmd/operator/main.go
- pkg/prometheus/operator.go
As the kubelet will not be self-hosted for the time being, we need to be able to handle it anyways. This is an implementation of a feature synchronizing nodes into an Endpoints object for discovery by Prometheus.
@fabxc
> prometheus: syncronize nodes to enpoints object

- pkg/prometheus/statefulset.go
This is supposed to fix missing headless service problem(#149).
> Use governingServiceName as ServiceName in StatefulSet for Prometheus

- pkg/prometheus/operator.go
- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
- pkg/prometheus/statefulset_test.go
- vendor/github.com/prometheus/common/LICENSE
- vendor/github.com/prometheus/common/NOTICE
- vendor/github.com/prometheus/common/model/alert.go
- vendor/github.com/prometheus/common/model/fingerprinting.go
- vendor/github.com/prometheus/common/model/fnv.go
- vendor/github.com/prometheus/common/model/labels.go
- vendor/github.com/prometheus/common/model/labelset.go
- vendor/github.com/prometheus/common/model/metric.go
- vendor/github.com/prometheus/common/model/model.go
- vendor/github.com/prometheus/common/model/signature.go
- vendor/github.com/prometheus/common/model/silence.go
- vendor/github.com/prometheus/common/model/time.go
- vendor/github.com/prometheus/common/model/value.go
- vendor/github.com/prometheus/prometheus/LICENSE
- vendor/github.com/prometheus/prometheus/NOTICE
- vendor/github.com/prometheus/prometheus/config/config.go
- vendor/vendor.json
For components that want to expose metrics including a namespace label, like Kubernetes components do, we need to allow those components not to get the namespace label relabelled onto them when doing discovery.
Components this is required for:
* kubelets (nodes resource is not namespaced in kubernetes either)
* kube-state-metrics (only one kube-state-metrics instance per cluster should exist)
@fabxc 
Closes #154
> prometheus: allow components not to relabel namespace label

- pkg/alertmanager/operator.go
- pkg/alertmanager/statefulset.go
- pkg/k8sutil/k8sutil.go
- pkg/prometheus/operator.go
- pkg/prometheus/statefulset.go
- vendor/github.com/pkg/errors/LICENSE
- vendor/github.com/pkg/errors/README.md
- vendor/github.com/pkg/errors/appveyor.yml
- vendor/github.com/pkg/errors/errors.go
- vendor/github.com/pkg/errors/stack.go
- vendor/vendor.json
This PR adds unique labeling to the governing services of the Alertmanager and Prometheus. Additionally it instead of just trying to create the service reconciles them, in case an old `Service` exists and is thus updated, which may lead to using informers for this eventually but right now by requesting the API. Finally this PR vendors and introduces `pkg/errors`, and implements it on all occurrences that were touched.
In addition with #158 this closes #157.
@fabxc 
/cc @galexrt
> Governing service labeling

- Documentation/rbac.md
- example/rbac/prometheus-operator-cluster-role.yaml
As Service and Endpoints objects are now reconciled, the current object
needs to be retrieved from the API, therefore the get action must also
be allowed.
@fabxc
> rbac: add get action for services and endpoints

- .github/ISSUE_TEMPLATE.md
As we often ask the same questions when troubleshooting with users I thought it would be a good idea to setup an issue template so we hopefully get the data on submission of the issue.
@fabxc
> github: add issue template

- Documentation/storage.md
- example/storage/persisted-prometheus.yaml
- example/storage/storageclass.yaml
This adds documentation on how to use storage provisioning with a concrete example for AWS. This should solve some confusion around the topic.
@fabxc
> Documentation: add documentation on how to use storage

- README.md
As mentioned in #172, we want to make more clear that kube-prometheus is not a contender, but rather makes use of the Prometheus Operator.
@fabxc 
/cc @whereisaaron
> README: make the relationship with kube-prometheus clearer

- Jenkinsfile
1. The current working dir was not properly specified when building the prometheus operator binary. It is now retrieved via the `$PWD` environment variable. 
2. The sha1 of the commit to be tested was previously only specified via the *GitHub Pull Request Builder* hook. This prevents the ability to trigger the job manually in Jenkins as Jenkins doesn't know which commit to test. This commit adds the sha1 string parameter to the `Jenkinsfil` job dsl for users to specify the sha1 when triggering jobs manually.
> test: Fix working dir spec and add string param for manual build

- Jenkinsfile
This instructs the Jenkins Github pull request builder plugin to add one
test status line for each e2e and unit tests in the pull request view.
In addition it updates the status when the tests are triggered and when
they are started.
> test: Add context to test status in pull request view

- pkg/alertmanager/statefulset.go
This fixes the Alertmanager cluster mesh initialization, which was effectively broken since we renamed the governing services.
@fabxc 
@mxinden We should talk through an e2e test to make sure an Alertmanager cluster's mesh network initialized correctly.
> alertmanager: fix mesh peer connection address

- contrib/grafana-watcher/grafana/dashboard.go
- contrib/grafana-watcher/grafana/datasource.go
- contrib/grafana-watcher/grafana/grafana.go
- contrib/grafana-watcher/main.go
- contrib/grafana-watcher/updater/dashboard.go
- contrib/grafana-watcher/updater/datasource.go
- scripts/check_license.sh
Adding license headers as I noticed that the check license script failed on the grafana-watcher source files.
@fabxc
> contrib/grafana-watcher: add license headers

- test/e2e/alertmanager_e2e_test.go
- test/e2e/framework/alertmanager.go
- test/e2e/framework/framework.go
Spin up three alertmanagers via prometheus operator and check with the
/status API endpoint if they discover each other correctly.
❗️ ❗️ ❗️  Depends on alertmanager [PR 644](https://github.com/prometheus/alertmanager/pull/644)
> test: Check whether alertmanager mesh network initializes correctly

- test/e2e/framework/alertmanager.go
- test/e2e/framework/framework.go
- test/e2e/framework/prometheus.go
- test/e2e/prometheus_e2e_test.go
* Use framework internal Poll function instead of reimplementing it.
* Don't return pods list - only needed by one function call.
* Have one specification of how long to wait for a pod.
Instead of checking for pods running correct image in WaitForPodsReady
this functionallity is extracted into WaitForPodsRunImage function.  By
not requiring an image name when calling WaitForPodsReady we can remove
the image specification in MakeBasicPrometheus and
MakeBasicAlertmanager. Thereby basic tests are not fixed to specific am
and prom versions.
> Default prom am version

- Documentation/api.md
Docs can be automatically build with `make docs`. This PR keeps the current api doc in sync with current master code.
❗️  Please wait for [206](https://github.com/coreos/prometheus-operator/pull/206) to fail.
> Rebuild api documentation with nodeSelector

- Jenkinsfile
The prometheus operator api docs are generated automatically. To ensure
the docs are not out of sync with the code we generate the docs on every
pr and check if they changed.
> test: Add jenkins job building the docs to check if they changed

- contrib/kube-prometheus/assets/grafana/deployment-dashboard.json
- contrib/kube-prometheus/manifests/exporters/kube-state-metrics-deployment.yaml
- contrib/kube-prometheus/manifests/grafana/grafana-dashboards.yaml
This can happen if you run multiple replicas, or if you redeploy kube-state-metrics.
In either case, prometheus records multiple metrics with the instance ip in, and the dashboard fails.
This uses aggregation functions to get sensible output in either case
I've switched between max and min to try and be pessimistic where appropriate (e.g. max for generations and total replicas, min for available replicas etc.)
Shouldn't really matter given multiple copies should report the same data anyway
> Allow for multiple kube-state-metrics series

- contrib/kube-prometheus/README.md
We've just hit an issue where:
- if you have multiple grafana pods
- then you update the configmap to change dashboards
- then some of the grafana pods get restarted (but not all)
then the prometheus datasource ID is 0 on the new ones and N on the others, so URLs generated by one grafana instance don't work on the others.
We've fixed this by adding this to our Ingress:
```
annotations:
ingress.kubernetes.io/affinity: cookie
```
> Add warning about Grafana HA

- contrib/kube-prometheus/assets/grafana/resource-requests-dashboard.json
- contrib/kube-prometheus/manifests/grafana/grafana-dashboards.yaml
This presents the resource requests vs the allocatable capacity in the cluster.
> Add resource requests dashboard

- test/e2e/alertmanager_e2e_test.go
- test/e2e/framework/alertmanager.go
This test first creates a config inside a kubernetes secret, checks if
alertmanager picks the config up correctly. Then it changes the config
and checks again if it is loaded by alertmanager correctly.
This is related to PR #201
> test: Check whether alertmanager reloads its config

- Documentation/rbac.md
- cmd/apidocgen/main.go
- example/rbac/prometheus-cluster-role.yaml
Due to the recently developed Prometheus side-car the RBAC requirements
for Prometheus Pods has changed slightly.
> RBAC: update RBAC requirements for Prometheus

- test/e2e/framework/framework.go
If the ingress controller is not yet, polling will result in a global
error. Before this would end the polling. Instead now we still keep on
polling to give the ingress controller more time to start.
Issue noticed in PR #219
> test: Fix flaky ingress tests

- Documentation/user-guides/running-exporters.md
This adds:
* ~~`kube-state-metrics` deployment, service and servicemonitor as an example~~
* ~~ServiceMonitor for the `default/kubernetes kube-apiserver` service~~
* ~~ServiceMonitor for the `kubelet` service (created by the prometheu-operator)~~
* Documentation for running exporters on the cluster
> Documentation for running exporters on the cluster

- example/networkpolicies/grafana.yaml
Previous version had a dash on the first line which prevent the script from being imported into k8s
> Removed the erroneous dash beside apiVersion

- contrib/grafana-watcher/Makefile
- contrib/grafana-watcher/examples/grafana-bundle.yaml
- contrib/grafana-watcher/grafana/dashboard.go
- contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml
Fixes #224 
Will push the new version (`v0.0.1`) to quay once this we merge this change.
> grafana-watcher: use official documented API

- Documentation/network-policies.md
- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/hack/cluster-monitoring/deploy
- contrib/kube-prometheus/hack/cluster-monitoring/teardown
- contrib/kube-prometheus/manifests/exporters/kube-state-metrics-cluster-role-binding.yaml
- contrib/kube-prometheus/manifests/exporters/kube-state-metrics-cluster-role.yaml
- contrib/kube-prometheus/manifests/exporters/kube-state-metrics-deployment.yaml
- contrib/kube-prometheus/manifests/exporters/kube-state-metrics-service-account.yaml
- contrib/kube-prometheus/manifests/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
- contrib/kube-prometheus/manifests/prometheus-operator/prometheus-operator-cluster-role.yaml
- contrib/kube-prometheus/manifests/prometheus-operator/prometheus-operator-service-account.yaml
- contrib/kube-prometheus/manifests/prometheus-operator/prometheus-operator.yaml
- contrib/kube-prometheus/manifests/prometheus/prometheus-cluster-role-binding.yaml
- contrib/kube-prometheus/manifests/prometheus/prometheus-cluster-role.yaml
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-service-account.yaml
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s.yaml
With Kubernetes 1.6 RBAC is becoming a default. Therefore we should make sure that everything necessary to run end to end monitoring is RBAC aware.
Should be good to merge if you can successfully deploy this on a 1.6.x cluster.
> kube-prometheus: add RBAC resources

- contrib/kube-prometheus/manifests/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
This entire thing is built in the monitoring namespace but the
rolebinding was on default. This caused the operator to never launch.
> kube-prometheus: fix rolebinding

- .helmignore
- helm/Chart.yaml
- helm/README.md
- helm/templates/NOTES.txt
- helm/templates/_helpers.tpl
- helm/templates/cleanup-job.yaml
- helm/templates/deployment.yaml
- helm/templates/get-tprs-job.yaml
- helm/values.yaml
@mgoodness as discussed on Slack, we'd like to maintain Helm charts along with the repo itself to make it easier to keep versions in sync.
Later on also moving the kube-prometheus packaging stuff would be great.
This just moves the prometheus-operator charts including their commit history. RBAC files should be added.
@brancz
> Add Helm chart by mgoodness

- contrib/grafana-watcher/Makefile
- contrib/grafana-watcher/examples/grafana-bundle.yaml
- contrib/grafana-watcher/grafana/dashboard.go
- contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml
The dashboard create endpoint behaves slightly different when templating
is used. The import API works exactly the same as the front-end import
functionality.
/cc @nirdothan
> grafana-watcher: revert to import endpoint

- test/e2e/alertmanager_e2e_test.go
- test/e2e/framework/alertmanager.go
- test/e2e/framework/framework.go
- test/e2e/framework/ingress.go
- test/e2e/framework/prometheus.go
- test/e2e/framework/service.go
- test/e2e/prometheus_e2e_test.go
Adding context before passing down an error message with the library
pkg/errors is hopefully going to help us with debugging failing tests on
the Jenkins CI. This is supposed to happen with all prometheus-operator
tests in the long run.
Related to PR #234
> Introduce pkg/errors to ingress tests

- test/e2e/framework/alertmanager.go
- test/e2e/framework/framework.go
- test/e2e/framework/ingress.go
- test/e2e/framework/prometheus.go
- test/e2e/framework/replication-controller.go
- test/e2e/framework/service.go
- test/e2e/prometheus_e2e_test.go
@brancz As discussed replacing our *Poll* implementation with the client-go implementation.
> test: Replace own framework.Poll with client-go wait.Poll

- helm/prometheus-operator/Chart.yaml
- helm/prometheus-operator/templates/clusterrole.yaml
- helm/prometheus-operator/templates/clusterrolebinding.yaml
Use `rbac.authorization.k8s.io/v1beta1` if the cluster supports it, otherwise fall back to `rbac.authorization.k8s.io/v1alpha1`.
Published as v0.7.1 and confirmed still working in K8s v1.5, but I don't yet have a K8s v1.6 cluster to test against. Recommend we wait for @peterrosell (or other) to deploy & confirm before merging.
> Support both alpha & beta RBAC API

- Documentation/rbac.md
- contrib/kube-prometheus/manifests/prometheus/prometheus-cluster-role.yaml
- example/rbac/prometheus/prometheus-cluster-role.yaml
When RBAC is enabled the Prometheus instance requires an RBAC role to be able to scrape the `/metrics` endpoint of the Kubernetes apiserver.
> Documentation: Prometheus requires RBAC role for apiserver metrics

- contrib/grafana-watcher/Makefile
- contrib/grafana-watcher/examples/grafana-bundle.yaml
- contrib/grafana-watcher/grafana/dashboard.go
- contrib/grafana-watcher/grafana/datasource.go
- contrib/grafana-watcher/grafana/grafana.go
- contrib/grafana-watcher/main.go
- contrib/kube-prometheus/hack/scripts/generate-grafana-credentials-secret.sh
- contrib/kube-prometheus/hack/scripts/generate-manifests.sh
- contrib/kube-prometheus/manifests/grafana/grafana-credentials.yaml
- contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml
This adds the ability to specify grafana credentials through environment variables. The default in kube-prometheus is still admin:admin, but now specified via a `Secret` instead of plaintext.
Closes #258
> grafana-watcher: allow credentials from env variable

- pkg/prometheus/promcfg.go
If available relabel the pod and service name onto pods. Using these labels can be joined onto them from metrics exposed by kube-state-metrics.
Closes #242
> prometheus: add pod and service label

- contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml
This was previously used for debugging locally, but I forgot to remove it, and no error occurred because the image was present.
> kube-prometheus: remove grafana never pull policy

- Documentation/user-guides/exposing-prometheus-and-alertmanager.md
This PR add grafana as ingress service. It also add some advice on how to protect this resources over internet.
> Add security recommendations for ingress

- Documentation/user-guides/cluster-monitoring.md
- pkg/prometheus/operator.go
As the insecure port is going to be necessary for the time being regarding metrics, we should have it on the Endpoints object we synchronize the kubelets into.
> prometheus: add insecure port to kubelet endpoints object

- contrib/grafana-watcher/grafana/datasource.go
- contrib/kube-prometheus/hack/cluster-monitoring/deploy
There is a potential race condition when the grafana manifests are applied where the credentials may not be applied prior to the deployment, which depends on them. I believe this was the cause of some issues I had with `grafana-watcher`.
There is now a helpful error message when `grafana-watcher` cannot log in, and `grafana-credentials.yaml` are applied prior to other grafana manifests to prevent weird login conditions like the one I experienced.
> grafana-watcher login fixes

- test/e2e/framework/alertmanager.go
- test/e2e/framework/framework.go
- test/e2e/framework/helpers.go
- test/e2e/framework/prometheus.go
This should be set via a flag in the long run. Adjust waitForPodsReady
function to take a timeout as third argument. Passing in the default
framework time out for now.
> Add default timeout to test framework

- Jenkinsfile
External PRs should not run on our testing infrastructure automatically.
They can be verified by an admin with the 'Test this please.' phrase.
Related to #307
> test: Fix external PR trigger

- Documentation/rbac.md
- Documentation/user-guides/getting-started.md
- bundle.yaml
- example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
- example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
- example/rbac/prometheus/prometheus-cluster-role-binding.yaml
- example/rbac/prometheus/prometheus-cluster-role.yaml
- example/rbac/prometheus/prometheus.yaml
- example/user-guides/getting-started/prometheus-service.yaml
- example/user-guides/getting-started/prometheus.yaml
Currently the getting started guide only creates a `ClusterRole` and a `ClusterRoleBinding` for the Prometheus operator but not for the Prometheus pods. This PR adds the steps to do so for the Prometheus pods as well.
Tested with tectonic-installer and minikube cluster.
Related to #290
> docs: Make getting-started guide RBAC aware

- Documentation/user-guides/alerting.md
~'ConfigMap's -> 'ConfigMap'~
Remove the 'a' in front of `ConfigMap`s
> Fixing typo

- pkg/prometheus/operator.go
Why:
* Some clusters (e.g. openstack) may only have externalIP addresses
> prometheus: Fall back to externalIP addresses

- contrib/kube-prometheus/hack/example-service-monitoring/deploy
https://github.com/kubernetes/kubernetes/issues/29542 has been fixed,
use apply instead of create to create third party resources in custom service
monitoring example.
> Use kubectl apply in custom service example deploy

- Documentation/user-guides/storage.md
I didn't use automatic provisioning, but this guide shows how to do GCE provisioning manually. Without this storageclass, PVC and PVs may not bind, depending on certain kuberenetes versions + certain cloud providers.
As per https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#volumes
> Disabling Automatic StorageClasses

- pkg/client/monitoring/v1alpha1/alertmanager.go
Wrapping the errors the way we did before this does not allow us to
check the errors for equality, and did not add any valuable semantics.
> client: return errors directly from Kubernetes dynamic client

- pkg/prometheus/statefulset.go
We want to react quickly to readiness changes, so other replicas get used.
We want to give 5 minutes grace on startup for crash recovery to complete, before we start killing the pod
Fixes #319
> prometheus: Adjust probe timers

- Jenkinsfile
The trigger phrase is case insensitiv by default. The GitHub comment
only has to contain the phrase, it can be more than that.
E.g.: "test this please", "please test this", "Please test this dear
CoreOS Bot", ...
> test: Adjust trigger phrase

- pkg/prometheus/promcfg.go
This may relabel unwanted labels onto the targets and if any labels are
necessary for further querying they can be joined onto the results using
the label metrics available in kube-state-metrics. If it turns out we
need explicit support in the Prometheus Operator then we can reintroduce
it with an explicit whitelisting approach.
> prometheus: remove automatically relabelling kubernetes labels

- Jenkinsfile
- scripts/jenkins/post-e2e-tests.sh
- scripts/jenkins/run-e2e-tests.sh
This moves the e2e execution logic to shell scripts. 
In the long run these scripts will be reused to run tests on master.
> test: Move e2e run logic into scripts

- Documentation/user-guides/cluster-monitoring.md
- cmd/operator/main.go
- contrib/kube-prometheus/manifests/prometheus-operator/prometheus-operator.yaml
As @mgoodness in #354 `kubelet-service` describes much better what the flag is supposed to represent than `kubelet-object`, therefore the renaming here.
@mgoodness @fabxc @mxinden
> cmd/operator: rename kubelet-object flag to kubelet-service

- contrib/kube-prometheus/assets/grafana/kubernetes-pods-dashboard.json
- contrib/kube-prometheus/manifests/grafana/grafana-dashboards.yaml
Rename kube_pod_container_requested_memory_bytes -> kube_pod_container_resource_requests_memory_bytes in grafana dashboard
Based on https://github.com/coreos/prometheus-operator/issues/356#issuecomment-300090929
> Correct metric for container requested memory in grafana dashboard

- Makefile
- scripts/jenkins/Dockerfile
- test/e2e/alertmanager_test.go
- test/e2e/framework/alertmanager.go
- test/e2e/framework/context.go
- test/e2e/framework/framework.go
- test/e2e/framework/helpers.go
- test/e2e/framework/ingress.go
- test/e2e/framework/namespace.go
- test/e2e/framework/prometheus.go
- test/e2e/framework/service.go
- test/e2e/main_test.go
- test/e2e/prometheus_test.go
test: Introduce test context per test
test: Clean up e2e test code
* Remove unneeded delete steps
* Improve error feedback
* Cleanup main namespace properly after tests
* Wait for NodePort services to be deleted
test: Run save tests in parallel
> test: Introduce a context and a namespace per test and run save tests in parallel

- .gitignore
- helm/prometheus-operator/Chart.yaml
- helm/prometheus-operator/README.md
- helm/prometheus-operator/templates/NOTES.txt
- helm/prometheus-operator/templates/deployment.yaml
- helm/prometheus-operator/values.yaml
Fixes #353 
* Renamed `kubeletObject` -> `kubeletService` to make the effect clearer (IMHO)
* Renamed `kubeletObject.object` -> `kubeletService.name` for same reason
* Updated default prometheus-operator image to `v0.8.2`
I'll publish v0.0.2 to my `opsgoodness` repo once this is merged.
> Chart v0.0.2

- Jenkinsfile
- README.md
* Moves e2e, unit and generation tests into one job.
* GitHub triggers Jenkins on every push event.
* Jenkins triggers the po-tests-master job on master pushes. 
* It runs the unit, generation and e2e tests and updates the :master image on quay.
* It runs daily to ensure PO operates with external dependencies.
* Adds build status to README.md.
> test: Add master job to Jenkins

- Documentation/api.md
- pkg/client/monitoring/v1alpha1/types.go
- pkg/prometheus/promcfg.go
This allows the prometheus config `external_labels` to be configured via the PrometheusSpec TPR.  This is useful for adding unique identifiers for any federation or alerting.
> prometheus: add externalLabels to PrometheusSpec API

- pkg/prometheus/statefulset.go
Tested this again current state of the Prometheus `dev-2.0` branch and it works nicely.
Let me know if you want to wait to merge this until we actually release `v2.0.0-alpha.1`, but this code is functional against current state of 2.0.
> prometheus: add experimental 2.0 support

- Jenkinsfile
From now on, if a job on master fails, it will be reported in our #team-monitoring slack channel.
> test: Add slack integration to master job

- pkg/prometheus/operator.go
- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
Because maps have a non-deterministic order when newly instantiated, we need to use means to make sure that the prometheus yaml configuration we generate is deterministic.
This changes any use of a map in the config to use the `yaml.MapSlice`, which ensures deterministic map behavior, because the `yaml.MapItem`s are sorted by their keys before marshaling to yaml.
Note that this does rely on Kubernetes not changing the order or arrays in objects, as the `Alertmanagers` and `Endpoints` lists are reflected 1 to 1 in the generated config. If this does turn out to be a problem we'll have to find a way to sort those items as well, but that will likely require individual sorting for each of the lists.
Let me know if you want to keep the test that I wrote to make sure that it is deterministic or …
> prometheus: generate config deterministically

- contrib/grafana-watcher/grafana/datasource.go
- pkg/prometheus/operator.go
- pkg/prometheus/promcfg_test.go
- test/e2e/framework/cluster_role.go
- test/e2e/framework/cluster_role_binding.go
- test/e2e/framework/context.go
- test/e2e/framework/deployment.go
- test/e2e/framework/helpers.go
- test/e2e/framework/namespace.go
- test/e2e/framework/service_account.go
- test/e2e/framework/third_party_ressource.go
Changes of the requested resources will be reflected in pods and still trigger an update. But it can no longer cause flaps by resource overwrites by admission control.
@brancz
> Don't actively delete pods on resource changes

- Documentation/user-guides/alerting.md
This PR tries to clarify (or at least explain the magic behind the operator) the setup of the configuration on the alertmanager along with alertmanager's templating files.
Closes #389
> Clarify Alertmanager configuration setup on the user guide

- contrib/kube-prometheus/manifests/examples/example-app/prometheus-frontend-svc.yaml
- contrib/kube-prometheus/manifests/k8s/minikube/kube-controller-manager.yaml
- contrib/kube-prometheus/manifests/k8s/minikube/kube-scheduler.yaml
I found some minor issues that I have fixed. Please review and let me know if you agree:
1) in example-app, the selector of prometheus-frontend-svc was incorrect.
2) in kube-scheduler and kube-controller discovery services for minikube, the namespace has to be kube-system to be compatible with the current deployment of k8s-app ServiceMonitor, otherwise the service won't be selected by the ServiceMonitor.
(note: the self-hosted resources are okay)
> small changes in k8s/minikube and example-app

- Jenkinsfile
- scripts/jenkins/check-make-generate.sh
- scripts/jenkins/make-test.sh
- scripts/jenkins/push-to-quay.sh
* Move `make generate` test to separate script
* Move push to quay step to separate script
* Move unit test step to separate script
* Remove helper docker images after usage on every step
* Remove prometheus-operator image after tests
> test: Clean up Jenkins test execution

- Documentation/user-guides/cluster-monitoring.md
- Documentation/user-guides/exposing-prometheus-and-alertmanager.md
- contrib/kube-prometheus/manifests/alertmanager/alertmanager.yaml
- pkg/alertmanager/statefulset.go
- test/e2e/alertmanager_test.go
This updates the Prometheus and Alertmanager versions we default to and is used in example manifests to the latest releases.
> *: update default versions and example usages

- Documentation/user-guides/basic-auth.md
- contrib/kube-prometheus/manifests/examples/basic-auth/service-monitor.yaml
- pkg/prometheus/operator.go
**Warning: This is a breaking change!!!**
The `key` and `name` were in a inverse (wrong) order.  Before applying this patch edit your `ServiceMonitor` and swap your `key` and `name` values of `basicAuth`.
fix #402
> Fix basicAuth, swapping key and name

- Documentation/api.md
- pkg/client/monitoring/v1alpha1/types.go
- pkg/prometheus/promcfg.go
Fixes #378 
While we don't recommend configuring the Alertmanager like this, it is not a completely unreasonable thing to support, for example if the Alertmanager is running outside or in another Kubernetes cluster.
/cc @galexrt
> prometheus: allow specifying alertmanager url path prefix

- Documentation/api.md
- Documentation/user-guides/storage.md
- pkg/client/monitoring/v1alpha1/types.go
- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
All test passes, and tested in a cluster.
Prometheus manifest:
````
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
name: persisted
spec:
replicas: 1
resources:
pvc:
metadata:
name: myclaim
annotations:
volume.beta.kubernetes.io/storage-class: gp2
aws-ebs-additional-resource-tags: 'Test1=foo, Test2=bar'
spec:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 1Gi
#storageClassName: gp2
````
````
kubectl get statefulsets prometheus-persisted -o yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
creationTimestamp: 2017-06-13T00:03:10Z
generation: 1
labels:
app: prometheus
prometheus: persisted
name: prometheus-persisted
namespace: default
resourceVersion: "4307003"
selfLink: /apis/apps/v1beta1/namespaces/default/statefulsets/prometheus-persisted
uid: …
```
> Adding Field to Storage Spec to use a PVC Spec instead of v1alpha1.Storage

- contrib/kube-prometheus/README.md
This fixes two relative links, probably made invalid by the repo move.
> Fix relative links in kube-prometheus readme

- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s.yaml
In commit 9cd05a8c39c6ed03688859de92372d93af5cc6e2 the labels on the ServiceMonitors were changed from k8s-apps to k8s-app. This commit makes the Prometheus serviceMonitorSelector match that change.
> kube-prometheus: update serviceMonitorSelector

- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
- pkg/prometheus/statefulset.go
- test/e2e/prometheus_test.go
Through the ServiceMonitors we're able to infer the namespaces the Prometheus instance will need.
This allows us to run Prometheus instances with the RBAC roles set for the namespaces the instance will actually need.
@fabxc @mxinden @Gouthamve
Closes #39
> prometheus: configure namespaces to actually necessary namespaces

- CHANGELOG.md
- pkg/prometheus/statefulset.go
@fabxc @mxinden @Gouthamve 
I'll release a new patch release as soon as this is merged.
> prometheus: use computed route prefix instead of the spec

- helm/alertmanager/README.md
- helm/prometheus/README.md
Because the `thirdypartyresource` is not yet installed, you got an error when you are trying to install  prometheus/alermanager.
```
$ helm install alertmanager --name alertmanager --debug
[debug] Created tunnel using local port: '57662'
[debug] SERVER: "localhost:57662"
[debug] CHART PATH: /Users/grubio/work/src/github.com/coreos/prometheus-operator/helm/alertmanager
Error: apiVersion "monitoring.coreos.com/v1alpha1" in alertmanager/templates/alertmanager.yaml is not available
```
> Add recomendation to install operator before alertmanager/prometheus

- cmd/operator/main.go
- contrib/prometheus-config-reloader/Makefile
- contrib/prometheus-config-reloader/examples/prometheus-config-reloader.yaml
- contrib/prometheus-config-reloader/main.go
- helm/prometheus-operator/README.md
- helm/prometheus-operator/values.yaml
On startup, prometheus may not be ready to be reloaded.
Or, during operation, something may go wrong with prometheus temporarily.
In either case, reloading would fail. This situation would not be fixed until
another change was detected.
Here we fix this by retrying until success.
Fixes #436
> Use exponential backoff for prometheus reloading.

- contrib/grafana-watcher/examples/grafana-bundle.yaml
Maybe I miss a reason for that being there but probably just cruft?
> grafana watcher example: Remove imagePullPolicy

- contrib/kube-prometheus/assets/prometheus/rules/general.rules
- contrib/kube-prometheus/assets/prometheus/rules/kube-apiserver.rules
- contrib/kube-prometheus/assets/prometheus/rules/kube-controller-manager.rules
- contrib/kube-prometheus/assets/prometheus/rules/kube-scheduler.rules
- contrib/kube-prometheus/assets/prometheus/rules/kubelet.rules
- contrib/kube-prometheus/assets/prometheus/rules/node.rules
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml
Previously we did not trigger when there is no cluster label and a target is discovered, but not down.
@fabxc @mxinden @Gouthamve
> kube-prometheus: ensure triggering alerts on down targets

- contrib/grafana-watcher/examples/grafana-bundle.yaml
This is probably cruft, grafana has no /metrics endpoint.
> Remove scrape: true annotation

- contrib/kube-prometheus/manifests/kube-state-metrics/kube-state-metrics-cluster-role.yaml
After installing kube-prometheus from hack/cluster-monitoring/self-hosted-deploy I noticed that the API server logs were getting flooded with RBAC DENY messages for kube-state-metrics:
```
I0629 16:36:49.945856       5 rbac.go:87] RBAC DENY: user "system:serviceaccount:monitoring:kube-state-metrics" groups [system:serviceaccounts system:serviceaccounts:monitoring system:authenticated] cannot "list" resource "replicationcontrollers" cluster-wide
```
Looks like kube-state-metrics needs additional permissions for replicationcontrollers, limitranges, and services. Once I added those permissions the messages went away and kube-state-metrics seems to be happy.
> kube-prometheus: Update RBAC for kube-state-metrics

- contrib/grafana-watcher/Makefile
- contrib/grafana-watcher/examples/grafana-bundle.yaml
- contrib/grafana-watcher/updater/datasource.go
- contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml
Previously the error result of createDatasourceFromFile in the loop in createDatasourcesFromFile was dropped.  This meant any errors from datasource creation would be ignored.  This change makes the loop check and propagate any errors.
> Check createDatasourceFromFile error

- pkg/prometheus/statefulset.go
While setting the pvc template in the statefulset `Spec.Resources` and `Spec.Selector` where not being properly propagated.
This commit fixes this issue.
````
✔ ~/workspace/go-workspace/src/github.com/coreos/prometheus-operator [master|●1]
13:08 $ kubectl create -f ~/workspace/kubernetes-pvtest/prom.yaml
prometheus "persisted" created
✔ ~/workspace/go-workspace/src/github.com/coreos/prometheus-operator [master|●1]
13:09 $ kubectl get pvc
NAME                                             STATUS    VOLUME                                     CAPACITY   ACCESSMODES   AGE
prometheus-persisted-db-prometheus-persisted-0   Bound     pvc-7d61f054-5b74-11e7-bd6d-0e70723885a2   1Gi        RWO           45s
✔ ~/workspace/go-workspace/src/github.com/coreos/prometheus-operator [master|●1]
13:09 $ …
```
> Fixing storage for persisted prometheus

- helm/prometheus/Chart.yaml
- helm/prometheus/README.md
- helm/prometheus/templates/prometheus.yaml
- helm/prometheus/values.yaml
Adds the externalLabel spec option from #365 to the Prometheus helm chart.
> helm/prometheus: add externalLabels spec to be configured

- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-service-monitor-kubelet.yaml
- pkg/prometheus/operator.go
Kubernetes 1.7 [inadvertently stopped reporting cAdvisor metrics on the main /metrics endpoint](https://github.com/kubernetes/kubernetes/issues/48483). They are now only reported on the cAdvisor /metrics endpoint. As a temporary solution, I've added the cAdvisor port to the kubelet endpoint and servicemonitor so they get scraped as well.
I'm not totally sure it's a good idea to merge this, since [the original behavior might be restored soon](https://github.com/kubernetes/kubernetes/issues/48483#issuecomment-314828142), but I did want to bring it up in this repository in an attempt to save other folks some headdesking trying to figure out why pod-level metrics are not being reported in Kubernetes 1.7.
As a stopgap for my use case, I've built my own container with this fix and pushed it to …
> Scrapes cAdvisor port for metrics in Kubernetes 1.7

- scripts/jenkins/run-e2e-tests.sh
@Gouthamve Noticed, that we are not actually spinning up a k8s 1.7 cluster, even though current tectonic-installer:master has it.
My guess is, that the tectonic-installer image on our Jenkins workers is not up to date.
> [WIP] tests: Make sure tectonic-builder image is up to date

- cmd/operator/main.go
#483 suggests there might be a memory leak in the Prometheus Operator. To be able to investigate properly, we'll need to perform some profiling.
@Gouthamve @fabxc @mxinden
> *: add profiling endpoints

- Documentation/api.md
- example/alertmanger-webhook/Dockerfile
- example/alertmanger-webhook/Makefile
- example/alertmanger-webhook/main.go
- pkg/client/monitoring/v1alpha1/types.go
- pkg/prometheus/promcfg.go
- test/e2e/alertmanager_test.go
- test/e2e/framework/alertmanager.go
The way we perform rolling updates of the Alertmanager right now can't 100% ensure that there is no data loss, so we rely on the Alertmanager mesh to synchronize correctly on deploy. While this mechanism can and should be improved further, it shows that our rolling update does usually work without data loss.
This test ensures that there are no duplicate notifications are sent, while 3 Prometheus instances are firing the same alert every 100ms. The count is retrieved from the number of calls the webhook server the Alertmanagers fire against.
Before having written this test I felt like we may be in a worse position than we are, but having written this and having run it a lot of times I'm a lot more confident.
The example webhook image is currently under …
> test/e2e: add test for zero downtime alertmanager deploys

- contrib/grafana-watcher/Makefile
- contrib/grafana-watcher/examples/grafana-bundle.yaml
- contrib/grafana-watcher/grafana/dashboard.go
- contrib/grafana-watcher/grafana/datasource.go
- contrib/grafana-watcher/grafana/grafana.go
- helm/grafana/Chart.yaml
- helm/grafana/README.md
- helm/grafana/templates/NOTES.txt
- helm/grafana/templates/_helpers.tpl
- helm/grafana/templates/dashboards-configmap.yaml
- helm/grafana/templates/grafana-deployment.yaml
- helm/grafana/templates/ingress.yaml
- helm/grafana/templates/pvc.yaml
- helm/grafana/templates/secret.yaml
- helm/grafana/templates/svc.yaml
- helm/grafana/values.yaml
Add a grafana chart for kube-prometheus, mainly from stable/grafana & prometheus-oprator/contrib/kube-prometheus/grafana, made some adjustment to fit into kube-prometheus.
This pr only adds the grafana chart, to included into kube-prometheus(add this to requrements.yaml), I must publish this chart into a helm repo (which I don't have), but I have test it use manual manage dependency.
> grafana chart for kube-prometheus

- Documentation/user-guides/storage.md
spec.storage.volumeClaimTemplate.spec was missing from Manual storage provisioning documentation
Fixes #466
> documentation: fix storage doc

- contrib/kube-prometheus/assets/prometheus/rules/node.rules
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml
Alerts for a node out of disk, and a node under either memory or disk pressure were not configured by default.  We added them into our implementation, and figured these would be nice to have by default.
> Added a few extra node rules

- helm/alertmanager/Chart.yaml
- helm/alertmanager/values.yaml
- helm/grafana/Chart.yaml
- helm/grafana/values.yaml
- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/values.yaml
- helm/prometheus/Chart.yaml
- helm/prometheus/values.yaml
This sets valid default values for service `nodePort`, avoiding errors
when using service of type NodePort.
Fixes #496
> helm/kube-prometheus: Use valid defaults for service nodePort values.

- helm/kube-prometheus/requirements.yaml
This bumps the version of `alertmanager` and `prometheus` dependencies, resolving some errors.
Not sure if there are other implications to these bumps...
Fixes #498
> helm/kube-prometheus: Bump alertmanager and prometheus dependency versions

- pkg/alertmanager/operator.go
- pkg/alertmanager/statefulset.go
- pkg/prometheus/operator.go
- pkg/prometheus/statefulset.go
With Kubernetes 1.7 we now have the ability to perform real rolling updates and more importantly the whole StatefulSet and PodTemplate can be mutated.
I made sure to keep compatibility with Kubernetes versions before 1.7, in which case we fallback to the previous strategy.
Fixes #510 
Closes #49 
@fabxc @Gouthamve @mxinden
> Implement StatefulSet updates (+ full PodTemplate updates)

- scripts/jenkins/jsonnet/Dockerfile
According to the docker file reference [1] `ADD` will unpack recognized
compression formats as a directory. There is no need for us anymore to
unpack jsonnet.
[1] https://docs.docker.com/engine/reference/builder/#add
//CC @bison
> tests: Fix jsonnet docker build

- Jenkinsfile
There were a bunch of old builds laying around on the worker machine. This should fix the problem for the future.
> tests: Set thresholds how long to keep past builds

- helm/grafana/templates/grafana-deployment.yaml
Currently the `nodeSelector` value is ignored.
> Use nodeSelector value in grafana helm chart

- helm/kube-prometheus/charts/exporter-kubelets/templates/servicemonitor.yaml
#477 didn't applied the same rules for the kube-prometheus chart
> Scrapes cadvisor port metrics

- helm/kube-prometheus/charts/exporter-node/values.yaml
When bootstraping node-exporter with the kube-prometheus helm chart I got an error 
```
time="2017-08-14T13:05:51Z" level=error msg="ERROR: hwmon collector failed after 0.000024s: open /host/sys/class/hwmon: no such file or directory" source="node_exporter.go:91" 
```
Node-exporter already fixed this [issue](https://github.com/prometheus/node_exporter/issues/430) on v0.14
> Bump node-exporter to a stable version

- helm/prometheus/README.md
- helm/prometheus/templates/prometheus.yaml
- helm/prometheus/values.yaml
Adds `secrets` configuration to the prometheus chart
> helm/prometheus: allow for configuration of PrometheusSpec secrets

- pkg/alertmanager/operator.go
- pkg/prometheus/operator.go
When vendoring different versions of client-go the `Apps` function can behave differently here as the version is not fixed to a specific version.
@fabxc
> *: ensure using the apps v1beta1 api

- contrib/kube-prometheus/assets/prometheus/rules/kubelet.rules
- contrib/kube-prometheus/assets/prometheus/rules/node.rules
- contrib/kube-prometheus/manifests/kube-state-metrics/kube-state-metrics-cluster-role.yaml
- contrib/kube-prometheus/manifests/kube-state-metrics/kube-state-metrics-deployment.yaml
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml
- helm/kube-prometheus/charts/exporter-kube-state/Chart.yaml
- helm/kube-prometheus/charts/exporter-kube-state/templates/configmap.yaml
- helm/kube-prometheus/charts/exporter-kube-state/values.yaml
I updated to this release on our QA cluster.  I visually checked the kube-prometheus grafana dashboards and prometheus alerts and didn't see anything broken.  So I think it is safe to default to v1.0.0.
> Update to latest kube-state-metrics

- contrib/grafana-watcher/examples/grafana-bundle.yaml
- contrib/grafana-watcher/main.go
- contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml
- helm/grafana/templates/grafana-deployment.yaml
Currently, an update will only be partially applied if an
error occurs in one of the handler routines. The grafana
system will be left in a dirty intermediate state until
the ConfigMap is updated again. This change will retry failed updates
until all scheduled updates have succeeded OR until the ConfigMap
is changed again.
This log file from the `grafana-watcher` container in the `grafanaXXX` pod from a `kube-prometheus` deployment shows the retry loop working correctly (I have no idea why I get so many timouts T_T):
```
2017/08/04 20:45:25 Waiting for Grafana to be available.
2017/08/04 20:45:41 Initializing datasources.
2017/08/04 20:45:41 Retrieving existing datasources
2017/08/04 20:45:41 Deleting 0 datasources
2017/08/04 20:45:41 Creating datasource from: …
```
> grafana-watcher: retry failed updates from ConfigMap changes

- contrib/prometheus-config-reloader/main.go
- pkg/prometheus/statefulset.go
The Lifecycle API is disabled by default starting with Prometheus v2.0.0-beta.0, causing the config reloader to error out:
```
ts=2017-08-15T19:12:35Z caller=main.go:214 component=volume-watcher msg="Reloading Prometheus temporarily failed." err="Received response code %!s(int=403), expected 200" next-retry=25.169469033s
```
This PR adds a flag to Prometheus to enable the Lifecycle API on v2.0.0-beta.0 and higher, allowing the config reloader to work correctly:
```
ts=2017-08-16T15:59:20Z caller=main.go:219 component=volume-watcher msg="Prometheus successfully reloaded."
```
> Enable Lifecycle API on Prometheus 2.0.0-beta.0 and up

- pkg/prometheus/statefulset.go
Currently, when the Prometheus Operator is configured to use persistent storage on a cluster configured to use dynamic volume provisioning, pods on the Prometheus StatefulSet fail to launch due to a permissions error when accessing the storage mount point.
```
time="2017-08-04T16:56:37Z" level=info msg="Starting prometheus (version=2.0.0-beta.0, branch=master, revision=2b5d9159537cbd123219296121e05244e26c0940)" source="main.go:202" 
time="2017-08-04T16:56:37Z" level=info msg="Build context (go=go1.8.3, user=root@fc24486243df, date=20170712-12:21:13)" source="main.go:203" 
time="2017-08-04T16:56:37Z" level=info msg="Host details (Linux 4.11.11-coreos #1 SMP Tue Jul 18 23:06:59 UTC 2017 x86_64 prometheus-k8s-0 (none))" source="main.go:204" 
time="2017-08-04T16:56:37Z" level=info …
```
> Set SecurityContext on Prometheus StatefulSet

- Documentation/user-guides/cluster-monitoring.md
The `ServiceMonitor` must have a label with key `k8s-app` (and not `k8s-apps`)
> Fix typo for service monitoring

- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/manifests/kube-state-metrics/kube-state-metrics-deployment.yaml
- contrib/kube-prometheus/manifests/kube-state-metrics/kube-state-metrics-role-binding.yaml
- contrib/kube-prometheus/manifests/kube-state-metrics/kube-state-metrics-role.yaml
This bumps kube-state-metrics to the latest release as well as introduced the addon-resizer for it.
@fabxc
> kube-prometheus: bump kube-state-metrics to v1.0.1 release

- scripts/jenkins/push-to-quay.sh
We are quite often running into net/http: TLS handshake timeout errors (e.g. build # [240](https://jenkins-monitoring.prod.coreos.systems/job/po-tests-master/240/console)).
To prevent this, we are now trying 5 times to push the docker image.
> tests: Retry pushing docker image

- contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml
- contrib/kube-prometheus/manifests/grafana/grafana-service.yaml
Remove the port name for the Grafana service so that you can access Kibana via `kubectl proxy` at http://localhost:8001/api/v1/proxy/namespaces/monitoring/services/grafana, without the `:web` suffix as is required if the port is named.
> Remove port name of Grafana service for compatibility with kubectl proxy

- Documentation/api.md
- pkg/client/monitoring/v1/types.go
- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
On [the prometheus configuration page](https://prometheus.io/docs/operating/configuration/), there is a config for setting HTTP GET params. This is required if one wants to federate prometheuses _(promethei?)_. I had tried just making the ServiceMonitor's path like `/federate?match[]={__name__=~".+"}`, but it looked as if it was getting URL encoded, unless I'm doing this wrong somehow.
With this PR, then it'd be just setting up a `ServiceMonitor` to federate another prometheus and grab all metrics like so
```yaml
kind: ServiceMonitor
metadata:
name: k8s-prometheus
labels:
team: infra
spec:
selector:
matchLabels:
prometheus: k8s
namespaceSelector:
matchNames:
- kube-public
endpoints:
- port: web
interval: 30s
path: '/federate'
params:
'match[]':
- …
```
> allow params to be set for metrics endpoints

- helm/prometheus/templates/secret.yaml
Seems like a typo. The line `{{ toYaml .Values.serviceMonitorsSelector | indent 4 }}` does not belong here
> Remove problematic line

- helm/prometheus/README.md
- helm/prometheus/templates/prometheus.yaml
- helm/prometheus/templates/rules.yaml
- helm/prometheus/templates/servicemonitors.yaml
- helm/prometheus/values.yaml
This updates the prometheus Helm chart so `matchLabels` isn't hard coded in the serviceMonitorSelector. You'll have to specify how to match via values.yaml.
Example usage:
```yaml
serviceMonitorsSelector:
matchExpressions:
- key: k8s-app
operator: Exists
serviceMonitors:
- name: "alertmanager"
serviceMonitorSelectorLabels:
k8s-app: alertmanager
selector:
matchLabels:
alertmanager: main
namespaceSelector:
matchNames:
- monitoring
endpoints:
- port: http
interval: 30s
```
Also fixes/removes the `.Values.serviceMonitorSelector` typo in the `servicemonitors.yaml` template.
This is a breaking change compared to current parameter functionality.
Also related to #507 (should fix / clear up usage confusion).
> helm/prometheus: don't limit selectors to MatchLabels

- helm/kube-prometheus/charts/exporter-kube-dns/templates/_helpers.tpl
- helm/kube-prometheus/charts/exporter-kube-scheduler/templates/_helpers.tpl
- helm/kube-prometheus/charts/exporter-kube-state/templates/_helpers.tpl
Hi, 
In testing, I found some of objects created with truncated name, like `abcd-monitor-exporter-no`, `abcd-monitor-exporter-ku`, which is exactly 24 characters long.
But Kubernetes now accept service names up to 63 characters (https://github.com/kubernetes/kubernetes/pull/29523), and helm had updated their charts too (https://github.com/kubernetes/helm/pull/1740).
> Update charts to accept fullname up to 63 characters

- contrib/kube-prometheus/README.md
Fix link to ServiceMonitor documentation in kube-prometheus/README.md. Fixes #613.
> Fix ServiceMonitor documentation link

- contrib/kube-prometheus/docs/How-to-monitor-an-external-secure-etcd-cluster.md
- contrib/kube-prometheus/docs/Monitoring external etcd.md
Documentation on how to monitor an etcd cluster with Prometheus Operator
> Documentation Add doc to monitor a secure etcd cluster, typically set up via kube-aws

- Documentation/api.md
- pkg/client/monitoring/v1/types.go
- pkg/client/monitoring/v1alpha1/types.go
- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
New field in PrometheusSpec IamRole will allow users to specify
IAM role to be used by the prometheus pod, this requires kube2iam
for the pod to be able to assume the IAM role.
Fixes #580
> PrometheusSpec: add ObjectMeta field that propagates labels and annotations to prometheus Pods.

- Documentation/design.md
- Documentation/user-guides/running-exporters.md
- Documentation/user-guides/storage.md
- helm/kube-prometheus/values.yaml
- helm/prometheus/values.yaml
I noticed that most references to TPR in the design doc had been updated to CRD, but not all of them.
This PR replaces TPR with CRD or resource throughout the documentation.
> Changed TPR to CRD in Documentation

- contrib/kube-prometheus/assets/prometheus/rules/kube-apiserver.rules
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml
Fixes #560
@fabxc 
/cc @eedugon @dmcnaught
> kube-prometheus: exclude pod log subresource from latency alerts

- Documentation/api.md
- pkg/client/monitoring/v1/types.go
- pkg/prometheus/promcfg.go
allow to customize the scrape_interval in the global section of the prometheus
> parameterize the global scrape_interval in prometheus config

- helm/alertmanager/templates/alertmanager.yaml
- helm/kube-prometheus/charts/exporter-kube-api/templates/servicemonitor.yaml
- helm/kube-prometheus/charts/exporter-kube-controller-manager/templates/servicemonitor.yaml
- helm/kube-prometheus/charts/exporter-kube-dns/templates/servicemonitor.yaml
- helm/kube-prometheus/charts/exporter-kube-etcd/templates/servicemonitor.yaml
- helm/kube-prometheus/charts/exporter-kube-scheduler/templates/servicemonitor.yaml
- helm/kube-prometheus/charts/exporter-kube-state/templates/servicemonitor.yaml
- helm/kube-prometheus/charts/exporter-kubelets/templates/servicemonitor.yaml
- helm/kube-prometheus/charts/exporter-kubernetes/templates/servicemonitor.yaml
- helm/kube-prometheus/charts/exporter-node/templates/servicemonitor.yaml
- helm/prometheus/templates/prometheus.yaml
- helm/prometheus/templates/servicemonitors.yaml
What is the status of helm charts provided in this repo? They seem to see no love. If they are not supported maybe removing them is an option?
> v1 in API in helm charts

- Jenkinsfile
This PR reduces the amount of builds again. In addition it keeps all PR
builds for at least one month, so long running community PRs don't loose
their test logs.
@brancz Let me know if these numbers are still ok for you?
> tests: Reduce amount of kept builds

- helm/kube-prometheus/charts/exporter-kube-api/templates/configmap.yaml
- helm/kube-prometheus/charts/exporter-kube-state/templates/deployment.yaml
- helm/kube-prometheus/charts/exporter-kube-state/templates/service.yaml
- helm/kube-prometheus/charts/exporter-node/templates/configmap.yaml
* Synced the K8SApiServerLatency ALERT with 858fa3e44d8c50d4d74dcba38a63afce601cbc75 so it ignores "log" subresource
* Fixed labels and selectors on the kube-state subchart
* Synced a few more node alerts from ae861894ba8765a1798cb1c9d4b910fd70506626 / edb7b932ffacc3332c1b0927348386c5d02150a6
> A few fixes for kube-prometheus chart

- helm/kube-prometheus/charts/exporter-node/templates/deamonset.yaml
* add tolerations to allow node-exporter running on all nodes
* Sync from e87acbd88b57fe2cf8dfcb7e403a68e3eb3444d5
> kube-prometheus: add tolerations to node-exporter chart

- Jenkinsfile
As our Jenkins worker is running out of disk space quickly, we should remove all unneeded docker images periodically.
@bison Thanks for the hint!
> tests: Add cleanup job to remove old docker images periodically

- helm/alertmanager/templates/alertmanager.yaml
- helm/alertmanager/templates/ingress.yaml
- helm/alertmanager/templates/service.yaml
- helm/alertmanager/values.yaml
- helm/prometheus/templates/ingress.yaml
- helm/prometheus/templates/prometheus.yaml
- helm/prometheus/templates/service.yaml
- helm/prometheus/values.yaml
* Allows the user to specify labels on the following resources: service, ingress, alertmanager and prometheus
For me personally came from the need to add `dns: route53` to the service of both alertmanager and prometheus.
> charts: Allow custom labels on prometheus and alertmanager

- pkg/prometheus/operator.go
- Avoid resetting nodename
- Fixed error in a log line
> Fixing #644

- helm/alertmanager/templates/servicemonitor.yaml
- helm/alertmanager/values.yaml
- helm/prometheus-operator/templates/create-servicemonitor-job.yaml
- helm/prometheus-operator/templates/servicemonitor-configmap.yaml
- helm/prometheus-operator/values.yaml
- helm/prometheus/templates/servicemonitor-prometheus.yaml
- helm/prometheus/values.yaml
@mgoodness I didn't add the `serviceMonitor`for prometheus-operator because there's a circular dependency.
What do you think it's the right way to do:
1 - Run a job to apply the serviceMonitor after the creation of `tpr` or
2- Add a new chart on kube-prometheus to create the serviceMonitor for prometheus-operator
> add serviceMonitor to alertmanager, prometheus-operator and prometheus

- helm/kube-prometheus/charts/exporter-kube-api/templates/servicemonitor.yaml
- helm/kube-prometheus/charts/exporter-kube-controller-manager/templates/servicemonitor.yaml
- helm/kube-prometheus/charts/exporter-kube-dns/templates/servicemonitor.yaml
- helm/kube-prometheus/charts/exporter-kube-etcd/templates/servicemonitor.yaml
- helm/kube-prometheus/charts/exporter-kube-scheduler/templates/servicemonitor.yaml
- helm/kube-prometheus/charts/exporter-kube-state/templates/servicemonitor.yaml
- helm/kube-prometheus/charts/exporter-kubelets/templates/servicemonitor.yaml
- helm/kube-prometheus/charts/exporter-kubernetes/templates/servicemonitor.yaml
- helm/kube-prometheus/charts/exporter-node/templates/servicemonitor.yaml
- helm/prometheus/templates/prometheus.yaml
* Removes `app=prometheus` from servicemonitor objects
* Also removes it from the serviceMonitor slector for prometheus
* This allows alertmanager servicemonitor to be selected
note: app on alertmanager is set to alertmanager
> kube-prometheus: remove app label from servicemonitors

- scripts/jenkins/kubernetes-vanilla.tfvars
The installer changed the tectonic_admin_password_hash variable to
tectonic_admin_password.
> tests: Fix password variable definition

- Documentation/custom-configuration.md
We've had many issues about custom configurations with the Prometheus Operator, and there is a lack of documentation around it. While it's not the primarily intended use of the Prometheus Operator, there are a few legitimate use cases for it.
Most recently #671
@fabxc @ant31
> Documentation: Add docs on how to use a custom configuration

- Jenkinsfile
Archiving the /build folder served the purpose of better cleaning up
clusters in case the cleanup steps fail. On the downside it takes a lot
of space and it is difficult to manage.
This patch removes the archive steps.
> tests: Don't archive Tectonic installer build folder

- contrib/kube-prometheus/hack/grafana-dashboards-configmap-generator/templates/grafana-deployment-template.yaml
In the generated manifest for the grafana deployment at /contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml the version was bumped to 4.5.2 but seems it was overlooked in this templated version of the file.
> [kube-prometheus] Update to Grafana 4.5.2 in template

- cmd/operator/main.go
- pkg/alertmanager/operator.go
- pkg/prometheus/operator.go
An empty value means the Prometheus Operator will continue to list watch
against all namsepaces, therefore this is a non-breaking, backward
compatible change.
@fabxc @ant31
> *: scope list watching to configurable namespace

- contrib/kube-prometheus/hack/grafana-dashboards-configmap-generator/bin/grafana_dashboards_generate.sh
The merge was missing a new line at the end of the merge, so only
the first datasource was being put into the ConfigMap.
> Fix merging of -datasource.json files

- contrib/kube-prometheus/assets/grafana/kubernetes-control-plane-status-dashboard.json
- contrib/kube-prometheus/manifests/grafana/grafana-dashboards.yaml
If a cluster is HA, then topk returns the top 1 max api error rate for _each_ apiserver peer. As the displayed graph is a singlestat, this results in a multiseries error as Grafana expects a scalar for each point in time, not a scalar. We're making sure of this by using max over all api error rates.
@fabxc @ant31
> kube-prometheus: fix multiple series error in grafana dashboard

- contrib/kube-prometheus/hack/grafana-dashboards-configmap-generator/bin/grafana_dashboards_generate.sh
As talked in https://github.com/coreos/prometheus-operator/pull/670, moving the fix one line ahead, to cover all possible scenarios.
> newline bugfix modified in grafana configmap generator

- scripts/jenkins/post-e2e-tests.sh
In our Jenkinsfile we include the `wsCleanup()` step. This does not fail
the build even though it was not able to successfully clean up the
workspace.
In addition, with this patch we make sure ourself that the workspace is
cleaned up after the test execution.
> tests: Make sure to delete folders created by root

- Documentation/user-guides/running-exporters.md
Linking to `user-guides/cluster-monitoring.md` results in a link to `https://coreos.com/operators/prometheus/docs/latest/user-guides/user-guides/cluster-monitoring.html` (duplicated `user-guides`) in the [Create a Matching ServiceMonitor](https://coreos.com/operators/prometheus/docs/latest/user-guides/running-exporters.html#create-a-matching-servicemonitor) doc.
> Fix link to cluster-monitoring document

- contrib/kube-prometheus/manifests/k8s/kubeadm/kube-controller-manager.yaml
- contrib/kube-prometheus/manifests/k8s/kubeadm/kube-scheduler.yaml
Fix issue [618](https://github.com/coreos/prometheus-operator/issues/618)
Add two manifests for kube-scheduler & kube-controller-manager discovered by prometheus-operator, which are set up by kubeadm. 
For me, it works well.
> Add manifests for kubeadm setup tool

- pkg/prometheus/statefulset.go
`v0.14.0` introduced using the `PodManagementPolicy`, however that field is not allowed to be mutated after creation and causes the Prometheus Operator to error out when updating the operator from `v0.13.0` as previously the statefulsets did not have this field set.
@ant31 @fabxc
> prometheus: ignore if pod management policy is updated

- contrib/kube-prometheus/manifests/kube-state-metrics/kube-state-metrics-deployment.yaml
- helm/kube-prometheus/charts/exporter-kube-state/templates/deployment.yaml
- helm/kube-prometheus/charts/exporter-kube-state/values.yaml
Do not specify static resource settings in the kubernetes-deployment to avoid
unnecessary replacement of pods when the manifest is reapplied (`kubectl
apply`).
The addon-resizer will dynamically set the pod compute resource values. If the
values are also set statically in the deployment configuration, reapplying the
configuration will result in the pods getting replaced. Without the static
resource, the deployment configuration can be reapplied, and the pods will not
be replaced.
This change was also made in the upstream kube-state-metrics example manifests.
https://github.com/kubernetes/kube-state-metrics/pull/285
> Omit static compute resource requests and limits from deployment

- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
ExternalLabels now have a stable ordering in the generated ConfigMap prometheus.yaml file.
> Generate ExternalLabels deterministically

- helm/alertmanager/templates/secret.yaml
- helm/alertmanager/values.yaml
User can now specify custom templates (as described in [1]) in  `templateFiles` in `values.yaml`.
Eg.
```
templateFiles:
template_1.tmpl: |-
.... template file
```
Also has to add:
```
templates:
- '*.tmpl'
```
in `config` (the config that populates `alertmanager.yaml`).
[1] https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/alerting.md
> Allow templating for alertmanager

- helm/kube-prometheus/charts/exporter-node/templates/deamonset.yaml
Some flags have been renamed in 0.15.0
Keeping back-compatibility with if
> Helm Chart - Add support to node-exporter >= 0.15.0

- contrib/kube-prometheus/assets/prometheus/rules/kubelet.rules.yaml
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml
Alerts for making sure that all daemonsets are running properly.
I first tried with 5 min but a rolling cluster update with kops would trigger them, so I bumped up to 10m.
> Daemonset rules

- helm/kube-prometheus/charts/exporter-node/templates/deamonset.yaml
- helm/kube-prometheus/charts/exporter-node/templates/service.yaml
- helm/kube-prometheus/charts/exporter-node/values.yaml
- helm/kube-prometheus/requirements.yaml
- helm/kube-prometheus/values.yaml
Allows you to:
* omit `node-exporter` deployment by setting `deployExporterNode` to `False`.
* listen on a different port (so 2 versions of node exporter can coexist, eg testing out a new version)
> Configurable node exporter

- contrib/kube-prometheus/README.md
After cloning the repo I wanted to deploy kube-prometheus into my running minikube. I did the steps mentioned in the docu which brought me to the following exception:
namespace "monitoring" created
error: the path "manifests/prometheus-operator" does not exist
Waiting for Operator to register custom resource definitions.................................................................................................................^C
> Fix docu concerning initial deployment

- Documentation/api.md
- cmd/po-docgen/api.go
- Fix broken links of Kubernetes API Objects.
https://kubernetes.io/docs/api-reference/v1.6/ are not available, moved to https://v1-6.docs.kubernetes.io/docs/api-reference/v1.6/.
- Add TOC section for api docs and back-to-toc links.
`po-docgen` tool is very handy. I use it in some projects I participate. To help readers navigate on github website, I added TOC support.
> Improvements for API docs

- contrib/kube-prometheus/hack/scripts/generate-rules-configmap.sh
but for backwards compatibility, lets allow both
> Promtool appends .yml, not .yaml

- Documentation/user-guides/kube-prometheus-on-kubeadm.md
- contrib/kube-prometheus/docs/kube-prometheus-on-kubeadm.md
This getting started guide covers a simple deployment of kube-prometheus
and assumes you have deployed using kubeadm.
Hopefully this helps clears up #618 
I went ahead and took a stab at creating some initial documentation for how to get `kube-prometheus` up and running after installing a cluster with `kubeadm`. Any feedback is welcome. 
I wasn't exactly sure where I should put the documentation, so if there is a better place to put this, just let me know and I can move it around.
> Documentation: Added kubeadm documentation #618

- contrib/kube-prometheus/hack/cluster-monitoring/deploy
- contrib/kube-prometheus/hack/cluster-monitoring/teardown
NAMESPACE feature in scripts implies it works. Warning ensures
that users are aware that its use requires further changes.
Alleviates #765
> contrib: namespace warning to kube-prometheus

- contrib/kube-prometheus/assets/prometheus/rules/kubernetes.rules.yaml
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml
Hi! :)
This small PR fixes `cluster:container_cpu_usage:ratio` rule for K8s metrics rules.
> Fix cluster:container_cpu_usage:ratio rule

- .travis.yml
- Makefile
- helm/hack/e2e-test.sh
- helm/hack/helm-package.sh
- helm/hack/wait-pods-running-state.sh
- helm/kube-prometheus/requirements.yaml
- scripts/create-minikube.sh
- scripts/delete-minikube.sh
- scripts/travis-e2e-helm.sh
- scripts/travis-e2e.sh
This PR will enable e2e tests on the helm charts. It will setup kube-prometheus and prometheus-operator and wait until all the pods/containers are in ready state.
> Enable e2e tests on helm charts

- helm/prometheus-operator/templates/servicemonitor-configmap.yaml
Correct me if I'm wrong but shouldn't it be `http` to match deployment manifest? 
https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus-operator/templates/deployment.yaml#L32
> Fix operator endpoint

- contrib/kube-prometheus/assets/grafana/pods.dashboard.py
- contrib/kube-prometheus/manifests/grafana/grafana-dashboards.yaml
CPU
Memory
Pods dashboard
- CPU now shows the requested value and the limit
- Memory now shows the limit
> Adding requested and limit values to CPU and limit value to memory

- .travis.yml
- Makefile
- helm/hack/e2e-test.sh
- helm/hack/helm-package.sh
- helm/hack/sync-repo.sh
- helm/kube-prometheus/requirements.yaml
Automatically package helm charts after a PR
Add prometheus-operator and grafana as requirement for kube-prometheus
Avoid chart overriding, comparing the generated hash and the hash in the server
Before merge this PR it's required to configure the aws credentials on travis ci.
> Helm review

- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml
after change to prometheus.rules.yaml in c4be29f65.
IOW, this is the result of running `make generate` with current master.
> Regenerate prometheus-k8s-rules.yaml

- helm/kube-prometheus/Chart.yaml
My previous PR synced with s3 and overwrite the kube-prometheus chart so the hash comparison is failing, time to bump the kube-prometheus version 🍺.  
``` 
+cur_hash=($(md5sum ${HELM_CHARTS_PACKAGED_DIR}/${tgz}))
++md5sum /tmp/helm-packaged/kube-prometheus-0.0.3.tgz
++tr -d '"'
++jq .ETag -r
++aws s3api head-object --bucket coreos-charts --key stable/kube-prometheus-0.0.3.tgz
+remote_hash=e7060a65a706c35df8e6dc537077e425
+'[' kube-prometheus-0.0.3.tgz '!=' index.yaml ']'
+'[' ac658a06e34db8d7cbafaf87e41b40ab '!=' e7060a65a706c35df8e6dc537077e425 ']'
+echo 'ERROR: Current hash should be the same as the remote hash. Please bump the version of chart {kube-prometheus-0.0.3.tgz}.'
ERROR: Current hash should be the same as the remote hash. Please bump the version of chart …
```
> Bump kube-prometheus version

- helm/hack/helm-package.sh
I realize to support versioning on the helm server it's required to download the current index file from the remote server. It also avoid the error below because the kube-prometheus is missing from the index.yaml 
```
$ helm install --name kube-prometheus coreos/kube-prometheus --namespace=monitoring
Error: file "coreos/kube-prometheus" not found
```
> merge helm index file while packaging

- helm/README.md
As discussed in #861. It's not detailed, but it is 100% better that current non-existent README :-)
It provide the vital info that you need to install `prometheus-operator` first, and then `kube-prometheus` second.
> A stub of a README for the Helm chart with vital bootstrap info

- Documentation/user-guides/getting-started.md
- example/user-guides/getting-started/example-app-deployment.yaml
The current link only links to one of the manifests you need, so I thought changing it to the folder made more sense.
> Fix link to RBAC manifest

- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
Pods can potentially be unschedulable if a user only provides a limit, as the limit may be smaller than the default request we're setting. This PR makes sure, that we adjust the memory request if only a limit is given and it's smaller.
@ant31
> prometheus: Add ensure memory request is smaller or equal to limit

- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/manifests/kube-state-metrics/kube-state-metrics-cluster-role.yaml
- contrib/kube-prometheus/manifests/kube-state-metrics/kube-state-metrics-deployment.yaml
- contrib/kube-prometheus/manifests/kube-state-metrics/kube-state-metrics-service.yaml
- contrib/kube-prometheus/manifests/node-exporter/node-exporter-cluster-role-binding.yaml
- contrib/kube-prometheus/manifests/node-exporter/node-exporter-cluster-role.yaml
- contrib/kube-prometheus/manifests/node-exporter/node-exporter-daemonset.yaml
- contrib/kube-prometheus/manifests/node-exporter/node-exporter-service-account.yaml
- contrib/kube-prometheus/manifests/node-exporter/node-exporter-service.yaml
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-service-monitor-kube-state-metrics.yaml
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-service-monitor-node-exporter.yaml
This PR introduces the [kube-rbac-proxy](github.com/brancz/kube-rbac-proxy) to protect the node-exporter as well as kube-state-metrics metrics with authentication as well as authorization.
@ant31
> kube-prometheus: Add RBAC authorization to metrics endpoints

- cmd/operator/main.go
Pull request for https://github.com/coreos/prometheus-operator/issues/823
> for glog, re-using flag.Commandline instead of a new flagset

- helm/grafana/templates/grafana-deployment.yaml
In some clusters, using "localhost" as the grafana
url for grafana-watcher, doesn't resolve to
127.0.0.1 or the correct container IP, but to some
unrelated IP.
This workaround just skips DNS resolution by directly
using localhost's IP. It doesn't fix the underlying issue,
which is unknown atm.
Fixes #875.
Signed-off-by: Daniel Mohr <daniel.mohr@supercrunch.io>
> grafana-watcher: access grafana at 127.0.0.1

- helm/kube-prometheus/requirements.yaml
- helm/prometheus/Chart.yaml
- helm/prometheus/templates/prometheus.yaml
The prometheus helm chart supports passing in a static config, but because the serviceMonitorsSelector is defined by default, it is not usable. If a config is defined, the serviceMonitorsSelector shouldn't be set.
> helm/prometheus: support not having a serviceMonitorSelector

- contrib/kube-prometheus/assets/prometheus/rules/kube-state-metrics.rules.yaml
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml
- helm/exporter-kube-state/templates/kube-state-metrics.rules.yaml
With kube-state-metrics 1.2-rc0 being out I needed to update our rules. I thus added some more summaries and fixed some changed queries.
> Update kube-state-metrics rules to 1.2

- contrib/kube-prometheus/assets/prometheus/rules/kubernetes.rules.yaml
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml
if there's more than 1 certs that's going to expire on a bucket, sum is > 0 and fires an alert. 
Send a warning for 7 days, 1 day, and critical if expired.
(We can remove the 1 day if it's redundant)
> Add cert expiration rule

- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-roles.yaml
- helm/prometheus/templates/clusterrole.yaml
Fixes https://github.com/coreos/prometheus-operator/issues/867
> Add role rules permissions to get metrics from kubelet

- helm/alertmanager/Chart.yaml
- helm/exporter-kube-state/Chart.yaml
- helm/grafana/Chart.yaml
- helm/kube-prometheus/requirements.yaml
- helm/prometheus/Chart.yaml
This PR is intended to bump helm charts that haven't have the version bumped, after that the travis build history should be green again.
> Bump helm charts 

- helm/prometheus-operator/Chart.yaml
- helm/prometheus-operator/templates/_helpers.tpl
The change avoids `prometheus-operator` being deployed as `prometheus-operator-prometheus-operator-1234567890-abcde`. The newer function will avoid the duplication and deploy as `prometheus-operator-1234567890-abcde`.
This updates the Helm chart to follow newer best practice for helper functions, where the fullname template avoids doubling up on the release/chart name:
https://github.com/kubernetes/helm/blob/7c79d1c76534074d5708eae2c5ef88ae044941db/pkg/chartutil/create.go#L237-L249
> Update 'fullname' helper function to current version that avoids double-named deployments

- helm/exporter-kubelets/Chart.yaml
- helm/exporter-kubelets/templates/servicemonitor.yaml
- helm/exporter-kubelets/values.yaml
- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
Read cAdvisor metrics from secure Kubelet port instead of cAdvisor port when using HTTPS
This is equivalent to what @brancz did for kube-prometheus in #908. See commit 8928e07
The required RBAC permissions for nodes/metrics are already included in helm/prometheus/templates/clusterrole.yaml as part of #901
> helm/exporter-kubelets: Read cAdvisor metrics from secure Kubelet port

- helm/README.md
- helm/exporter-kube-state/Chart.yaml
- helm/exporter-kube-state/templates/clusterrole.yaml
- helm/exporter-kube-state/templates/clusterrolebinding.yaml
- helm/exporter-kube-state/templates/deployment.yaml
- helm/exporter-kube-state/templates/role.yaml
- helm/exporter-kube-state/templates/rolebinding.yaml
- helm/exporter-kube-state/templates/serviceaccount.yaml
- helm/exporter-kube-state/values.yaml
- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
- helm/kube-prometheus/values.yaml
- helm/prometheus/Chart.yaml
- helm/prometheus/templates/clusterrole.yaml
- helm/prometheus/templates/clusterrolebinding.yaml
- helm/prometheus/templates/prometheus.yaml
- helm/prometheus/templates/serviceaccount.yaml
- helm/prometheus/values.yaml
At present, you can't deploy this chart to a cluster that does __Not__ have `RBAC` enabled without knowing which sub-charts have `RBAC` resources included.
The docs state that one can toggle `RBAC` when deploying the `kube-prometheus` Parent-chart by providing the `--set rbacEnable` flag.  Correct me if I am wrong but that flag is a __no-op__ (It essentially does nothing).
Both the `prometheus` and `exporter-kube-state` charts include `RBAC` resources.  Therefore, one must namespace the argument like `--set exporter-kube-state.rbacEnable <BOOLEAN>` to override the default.
I'm assuming these charts will typically be deployed together, so modifying `RBAC` to be set globally makes sense, while still allowing the sub-charts to be configured on a standalone basis. 
For example running  `helm …
> Make RBAC global

- Documentation/rbac.md
- Documentation/user-guides/getting-started.md
- bundle.yaml
- example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
OwnerReferencesPermissionEnforcement admission plugin is on by default
in OpenShift, and without this change, the operator cannot deploy.
> prometheus-operator ClusterRole should specify finalizer subresource

- contrib/kube-prometheus/hack/grafana-dashboards-configmap-generator/bin/grafana_dashboards_generate.sh
- contrib/kube-prometheus/hack/grafana-dashboards-configmap-generator/templates/grafana-dashboards-template.yaml
- contrib/kube-prometheus/hack/scripts/generate-manifests.sh
- contrib/kube-prometheus/manifests/grafana/grafana-dashboards.yaml
#968 introduced using Grafana v5, which also provisions dashboards from disk. This however also requires declaring the dashboard sources in a file. This declaration was static in #968, whereas it depends on the number of configmaps generated.
@ant31 @fabxc
> kube-prometheus/hack: Add generation for grafana dashboard source file

- example/storage/persisted-prometheus.yaml
- helm/kube-prometheus/values.yaml
There are still some examples showing the deprecated StorageSpec fields.  This updates the `persisted-prometheus.yaml` example and the`values.yaml` in the kube-prometheus helm chart.
> Remove deprecated StorageSpec examples

- contrib/kube-prometheus/manifests/prometheus-operator/prometheus-operator-cluster-role.yaml
Add a missing 'prometheuses/finalizers' resource to the operator cluster role.
Without this role, the operator will fail to create a default secret for a
Prometheus instance in the absence of any service monitors.
The fix seems to already be present in the `examples` version of the role; this
patch brings the contrib version in line with the example.
> Add missing resource to operator role

- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
- helm/kube-prometheus/values.yaml
Some of us use an external alertmanager. Add an option to exclude alertmanager. It still includes it by default.
> helm: add ability to exclude alertmanager from kube-prometheus

- Documentation/rbac.md
- Documentation/user-guides/getting-started.md
- bundle.yaml
- contrib/kube-prometheus/manifests/prometheus-operator/prometheus-operator-cluster-role.yaml
- example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
Add a missing resource to the operator's cluster role allowing it to correctly
manager alertmanagers.
> Give operator permission to manager alertmanagers

- helm/README.md
- helm/alertmanager/Chart.yaml
- helm/alertmanager/values.yaml
- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
- helm/kube-prometheus/values.yaml
Update the values.yaml for kube-prometheus and alertmanager to be valid
templates and provide a better example. Also delete the --set reference
in the documentation since it is set by default in values.yaml.
Closes #979
> Update kube-prometheus values for storageSpec

- helm/kube-prometheus/requirements.yaml
- helm/prometheus/Chart.yaml
- helm/prometheus/templates/servicemonitors.yaml
Adds the `prometheus` label to templated ServiceMonitors so the default serviceMonitorsSelector (`prometheus: {{ .Release.Name }}`) matches against any defined ServiceMonitors. Expected this to match by default -- I think it used to.
> helm/prometheus: add expected label to templated ServiceMonitors so they are discovered by default

- helm/grafana/Chart.yaml
- helm/grafana/templates/dashboards-configmap.yaml
- helm/kube-prometheus/requirements.yaml
This fixes a wrong indentation of serverDashboardFiles in the configmaps and fixes errors with conversion from YAML to JSON.
This brings it to the same line as the datasource and makes it valid.
Current behaviour on master
```
data:
extra-dashboard.json: |
{
"test": "test2"
}
prometheus-datasource.json: |
{
"access": "proxy",
"basicAuth": false,
"name": "prometheus",
"type": "prometheus",
"url": "http://k8s-monitor-prometheus.infrastructure:9090"
}
```
Behaviour with this fix:
```
data:
extra-dashboard.json: |
{
"test": "test2"
}
prometheus-datasource.json: |
{
"access": "proxy",
"basicAuth": false,
"name": "prometheus",
"type": "prometheus",
"url": "http://k8s-monitor-prometheus.infrastructure:9090"
}
```
You can reproduce this with the following values file
```
dataSource: …
```
> Fix indentation of serverDashboardFiles

- contrib/kube-prometheus/grafana-image/Makefile
- contrib/kube-prometheus/hack/grafana-dashboards-configmap-generator/templates/grafana-deployment-template.yaml
- contrib/kube-prometheus/manifests/grafana/grafana-deployment.yaml
Updating to the latest grafana beta, tested on my cluster and appears to be working as expected.
A few screenshots just to show it's working (you can verify the version at the bottom of the first screenshot):
> Update to grafana 5.0.0-beta5

- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s.yaml
- pkg/prometheus/statefulset.go
Updates to latest Prometheus, notably this fixes an issue with alert manager where Prometheus was sending alert manager data in an unexpected format which was triggering one of the standard kube prometheus alerts.
https://github.com/prometheus/prometheus/issues/3543
Tested manually in my cluster, upgrade from v2.2.0-rc.0 to v2.2.0-rc.1 went smoothly and resolved the alerting issues with kube prometheus.
The part I haven't tested directly is the statefulset.go code change which sets a new default version, but since I haven't touched any of the other code I would assume it should work? Does CI cover that?
> Update to Prometheus v2.2.0-rc.1

- cmd/operator/main.go
- pkg/alertmanager/operator.go
- pkg/alertmanager/statefulset.go
- pkg/prometheus/operator.go
- pkg/prometheus/statefulset.go
This adds more SecurityContext handling to #1029
For context, OpenShift automatically sets group/user for security reasons.
@ant31 @fabxc
> *: Adapt SecurityContext handling

- Documentation/api.md
- example/prometheus-operator-crd/prometheus.crd.yaml
- example/prometheus-operator-crd/servicemonitor.crd.yaml
- pkg/client/monitoring/v1/openapi_generated.go
- pkg/client/monitoring/v1/types.go
The _RelabelConfig_ is confusing and connotes, that it is about `<relabel_config>`-section of the configuration, but in reality it is about `<metric_relabel_configs>`-section.
#1014
> documentation: clarify _RelabelConfig_ usage

- helm/grafana/Chart.yaml
- helm/grafana/templates/svc.yaml
- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
I was trying to add annotations to the Grafana service earlier and noticed that they weren't being passed. This change successfully passes them.
> Update Grafana service to use annotation values if provided.

- cmd/operator/main.go
- contrib/prometheus-config-reloader/Makefile
- contrib/prometheus-config-reloader/examples/prometheus-config-reloader.yaml
- contrib/prometheus-config-reloader/main.go
- helm/prometheus-operator/Chart.yaml
- helm/prometheus-operator/README.md
- helm/prometheus-operator/values.yaml
Resolves #1002 
Errors from `func (w *volumeWatcher) Refresh()` should be propagated. Right now, errors for refreshing the rules are ignored and may result in a Prometheus instance without rules, or without the latest rules loaded.
> prometheus-config-reloader: propagate errors for refreshing config files

- contrib/kube-prometheus/hack/example-service-monitoring/deploy
- contrib/kube-prometheus/manifests/examples/example-app/prometheus-frontend-role-binding.yaml
- contrib/kube-prometheus/manifests/examples/example-app/prometheus-frontend-role.yaml
- contrib/kube-prometheus/manifests/examples/example-app/prometheus-frontend-service-account.yaml
- contrib/kube-prometheus/manifests/examples/example-app/prometheus-frontend.yaml
added service account, role and role binding for the prometheus frontend
example, also updated prometheus to use the correct service account
fixes #1049
> example service monitoring updated with missing config

- contrib/kube-prometheus/docs/kube-prometheus-on-kubeadm.md
One of the `sed` commands for updating the `kubeadm` systemd file (`/etc/systemd/system/kubelet.service.d/10-kubeadm.conf`) was missing the reference to the file itself, which would cause it to hang indefinitely if ran as declared.
I also wrapped this second `sed` in an `if grep ...` check, in order to make the operation idempotent.
> docs: Add missing argument in `kubeadm` workaround script.

- helm/grafana/Chart.yaml
- helm/grafana/values.yaml
- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
This PR upgrades the image on grafana Chart to 5.0.0
There are other changes that can be applied given the changes on version 5, like removing the grafana-watcher image and adding dashboard and datasources configs given the new format but I think is better to dedicate efforts on https://github.com/brancz/kubernetes-grafana and use it in the future instead of trying to refactor the current grafana Chart.
> [helm] Upgrade grafana image to 5.0.0

- pkg/prometheus/operator.go
- pkg/prometheus/promcfg.go
The remote_read & remote_write basicAuth configuration wasn't looking for the associated secrets, and was instead embedding the raw BasicAuth contents into Prometheus' config. 
Refactored the basicAuth secret function & added support to resolve the remote secrets.
> prometheus: fix remote read & write basicAuth support

- pkg/alertmanager/statefulset.go
- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
This changes Prometheus and Alertmanager Pods to mount the data volume under the same directory as specified as a volume in the respective `Dockerfile`.
@ant31 @fabxc @derekwaynecarr @ironcladlou
> *: Use data directory defined as volume in Dockerfile

- Documentation/api.md
- example/prometheus-operator-crd/prometheus.crd.yaml
- pkg/client/monitoring/v1/openapi_generated.go
- pkg/client/monitoring/v1/types.go
- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
This adds the ability to authenticate against Alertmanager with a bearer token read from file. It allows us to use a ServiceAccount token in a Prometheus Pod to authenticate against Alertmanager with it.
@ant31 @fabxc @derekwaynecarr @ironcladlou
> prometheus: Add ability to authenticate with bearer token from file

- Makefile
LC_ALL when set takes precedence over LC_CTYPE and might cause
the tr command to fail with 'illegal byte sequence' when
generating the random string.
> e2e: ensure C locale when generating random string for namespace

- Documentation/user-guides/alerting.md
- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/hack/scripts/generate-rules-configmap.sh
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s.yaml
- example/user-guides/alerting/prometheus-example-rules.yaml
- example/user-guides/alerting/prometheus-example.yaml
In some cases we have been using `alert-rules` in some cases
`prometheus-rulefiles`. This led to confusion [1]. Instead, unify the
Prometheus rules configmap labels to:
```yaml
labels:
role: alert-rules
```
[1] https://github.com/coreos/prometheus-operator/issues/1102
Fixes #1102
> Unify rule file label accross repository

- contrib/kube-prometheus/hack/example-service-monitoring/deploy
- contrib/kube-prometheus/hack/example-service-monitoring/teardown
- contrib/kube-prometheus/manifests/examples/example-app/example-app.yaml
- contrib/kube-prometheus/manifests/examples/example-app/prometheus-frontend-alertmanager-discovery-role-binding.yaml
- contrib/kube-prometheus/manifests/examples/example-app/prometheus-frontend-alertmanager-discovery-role.yaml
- contrib/kube-prometheus/manifests/examples/example-app/prometheus-frontend-service-account.yaml
- contrib/kube-prometheus/manifests/examples/example-app/prometheus-frontend-svc.yaml
- contrib/kube-prometheus/manifests/examples/example-app/servicemonitor-frontend.yaml
The current example-app setup in the kube-prometheus project is able to
discover scraping targets in the default namespace. It is not able to
discover the configured Alertmanager in the monitoring namespace.
This patch adds an alertmanager-discovery rbac role, to permit the
above described action. In addition it does the following cleanups:
- Remove kubeconfig configuration in deploy and teardown script. kubectl
chooses .kube/config whenever KUBECONFIG is not set by default
- Remove namespace specification option via NAMESPACE env var. In most
of the manifests the metadata/namespace was hardcoded anyways, in
addition in the promtheus frontend role binding the service account
namespace is hardcoded to default as well.
- Instead of `kubectl {apply,delete}` individual manifests, the deploy …
> contrib/kube: Add rbac role to discover alertmanager

- contrib/kube-prometheus/manifests/examples/example-app/servicemonitor-frontend.yaml
The `prometheus-frontend` role of the example app kubeprometheus section
is scoped to the default namespace. Thereby the frontend Prometheus
instance is not able to discover anything outside of the default
namespace. We might as well restrict the front end service monitor to
the default namespace too.
> contrib/kube: Restrict example-app servicemonitor to default ns

- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
- helm/kube-prometheus/values.yaml
- helm/prometheus/Chart.yaml
- helm/prometheus/values.yaml
Change default for `secrets` in prometheus-chart from empty map to empty list. Avoids helm complaining about being unable to merge a map and a table.
> Helm: change defaults for secrets from empty map to empty list

- helm/exporter-kube-state/Chart.yaml
- helm/exporter-kube-state/templates/deployment.yaml
- helm/exporter-kube-state/values.yaml
- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
We have been having kube-state crashing on us constantly because of
memory limits. In our cluser with 10 nodes this setting worked, well.
Anyway, you can now tweak the values to what you need.
> Addon resizer memory config hooks

- Documentation/api.md
- example/prometheus-operator-crd/alertmanager.crd.yaml
- pkg/alertmanager/statefulset.go
- pkg/alertmanager/statefulset_test.go
- pkg/client/monitoring/v1/openapi_generated.go
- pkg/client/monitoring/v1/types.go
- test/e2e/alertmanager_test.go
- test/framework/alertmanager.go
- test/framework/context.go
With Alertmanager v0.15.0 the HA command line flag prefix changes from
"mesh" to "cluster" and peer ports need to be specified. This patch
enables running Alertmanager v0.15.0 with the Prometheus operator
without breaking backward compatibility.
In addition it does the following refactoring:
- Instead of generating the stateful set for an old AM version, and then
addressing all necessary changes up to the newest version, generate an
up to date stateful set version and address any changes necessary for
backward compatibility.
- Add unit tests for the various flag changes in between Alertmanager
version.
- Add v0.15.0 mesh initialization test
> Support Alertmanager v0.15.0

- Documentation/api.md
- example/prometheus-operator-crd/alertmanager.crd.yaml
- pkg/alertmanager/statefulset.go
- pkg/alertmanager/statefulset_test.go
- pkg/client/monitoring/v1/openapi_generated.go
- pkg/client/monitoring/v1/types.go
- pkg/client/monitoring/v1/zz_generated.deepcopy.go
For sidecar proxies it may be desirable to add additional secrets to be mounted so they can be consumed by the sidecar.
@ant31 @fabxc @mxinden
> alertmanager: Allows specifying additional secrets

- helm/exporter-kube-etcd/Chart.yaml
- helm/exporter-kube-etcd/templates/servicemonitor.yaml
- helm/exporter-kube-etcd/values.yaml
- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
In order to use this chart in our environment we need to specify a TLS configuration
this will allow us to pass one.
Fixes #1162
> charts: Pass TLS config to etcd service monitor

- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-service-coredns-metrics.yaml
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-service-monitor-coredns.yaml
- helm/exporter-coredns/.helmignore
- helm/exporter-coredns/Chart.yaml
- helm/exporter-coredns/templates/_helpers.tpl
- helm/exporter-coredns/templates/service.yaml
- helm/exporter-coredns/templates/servicemonitor.yaml
- helm/exporter-coredns/values.yaml
- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
- helm/kube-prometheus/values.yaml
With CoreDNS becoming a first class citizen it should be an optional part
of the kube-prometheus deployment.
Fixes: #1174
Note: I don't know how this fits into the existing testing pipeline since it includes CoreDNS which may not be part of the e2e testing environment
> charts: Add Core DNS Support

- Makefile
CI on master branch is failing because helm sync is not exporting exporter-coredns to s3.
Looking forward to move all helm charts to kubernetes upstream and avoid this flaky CI caused by helm. 💀
> Package exporter-coredns during helm-sync-s3

- pkg/alertmanager/statefulset.go
Alertmanager needs a routable IP address via the
`--cluster.listen-address` in order for other nodes in an Alertmanager
cluster to be able to reach it. This patch sets the
`--cluster.listen-address` to the k8s pod ip + `6783` port.
Fixes https://github.com/prometheus/alertmanager/issues/1312
//CC @gmauleon
> alertmanager: Pass pod ip to --cluster.listen-address

- test/e2e/alertmanager_test.go
- test/framework/alertmanager.go
- test/framework/helpers.go
This patch adds an e2e test. It creates a silence on alertmanager 0, and
checks if that silence is gossiped to alertmanager 1 and 2.
This should prevent regressions like https://github.com/prometheus/alertmanager/issues/1312
> alertmanager: Test if Alertmanagers gossip silences

- contrib/kube-prometheus/assets/prometheus/rules/node.rules.yaml
- contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-rules.yaml
- helm/exporter-node/Chart.yaml
- helm/exporter-node/templates/node.rules.yaml
- helm/kube-prometheus/requirements.yaml
Currently, node recording rules features incorrect idle CPU accounting. This change aims to fix that.
Also removed negative regex match, since guest CPU time (albeit, rarely present on Kubernetes nodes) contributes to the overall non-idle CPU time.
> Fixed CPU accounting in recording rules

- pkg/alertmanager/operator.go
- pkg/k8sutil/k8sutil.go
- pkg/prometheus/operator.go
If a user:
1. deploys the Prometheus operator without CRD validation
2. creates an invalid CRD instance (e.g. Servicemonitor)
3. restarts the Prometheus operator
it will crash-loop with a difficult to understand error message, failing
to parse the invalid CRD instance.
This patch improves the error feedback to the user, to identify the
invalid CRD more easily. The Prometheus operator will keep
crash-looping to enforce a valid CRD state on startup.
Fixes https://github.com/coreos/prometheus-operator/issues/1202
> crd: Enrich Prometheus operator CRD registration error handling

- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/values.yaml
The kube-prometheus chart didn't have default configuration exposed for passing down the values to the Prometheus chart.
> Adding Secrets for Prometheus Object, updating AlertManager wording

- contrib/kube-prometheus/docs/kube-prometheus-on-kubeadm.md
In kubeadm 1.10 (and perhaps earlier versions, not sure), ctrl-mgr and scheduler pods' label key is `component=` rather than `k8s-app=`, which is the selector key used for kube-prometheus exporters for these components.
> Ensure statuses of ctrl-mgr and scheduler are fetched

- Documentation/api.md
- Documentation/design.md
- Documentation/rbac.md
- Documentation/user-guides/getting-started.md
- bundle.yaml
- example/prometheus-operator-crd/prometheus.crd.yaml
- example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
- pkg/client/monitoring/v1/openapi_generated.go
- pkg/client/monitoring/v1/types.go
- pkg/client/monitoring/v1/zz_generated.deepcopy.go
- pkg/prometheus/operator.go
- test/e2e/prometheus_test.go
- test/framework/namespace.go
So far a Prometheus object could only select ServiceMonitors inside its
own namespace. This patch enables a Prometheus object to select
ServiceMonitors outside its own namespace via the
`ServiceMonitorNamespaceSelector` field in the Prometheus spec.
Use case: There is one Prometheus inside the `monitoring` namespace,
which is supposed to monitor applications across namespaces for an
entire Kubernetes cluster.  Each app team is supposed to manage its own
ServiceMonitors. Instead of granting each app team access to the
`monitoring` namespace to manage its ServiceMonitor objects,
ServiceMonitors can be shipped along with the application itself in each
application namespace.
//CC @ironcladlou
> ServiceMonitor: Enable Prometheus to select ServMon outside own ns

- contrib/kube-prometheus/jsonnet/prometheus-operator/prometheus-operator-cluster-role.libsonnet
- contrib/kube-prometheus/manifests/prometheus-operator/prometheus-operator-cluster-role.yaml
Fixes the following errors i observed when setting up kube-operator
```
ts=2018-04-18T08:15:52.913335939Z caller=operator.go:353 component=prometheusoperator msg="syncing nodes into Endpoints object failed" err="synchronizing kubelet endpoints object failed: retrieving existing kubelet endpoints object failed: endpoints \"kubelet\" is forbidden: User \"system:serviceaccount:monitoring:prometheus-operator\" cannot get endpoints in the namespace \"kube-system\""
ts=2018-04-18T08:42:52.915294813Z caller=operator.go:353 component=prometheusoperator msg="syncing nodes into Endpoints object failed" err="synchronizing kubelet endpoints object failed: creating kubelet endpoints object failed: endpoints is forbidden: User \"system:serviceaccount:monitoring:prometheus-operator\" cannot create …
```
> prometheus-operator RBAC permission

- helm/alertmanager/Chart.yaml
- helm/alertmanager/templates/configmap.yaml
- helm/alertmanager/templates/servicemonitor.yaml
- helm/alertmanager/values.yaml
- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
The value of the prometheus label is fixed to `Release.Name`, this means that alertmanager and prometheus should be deployed on the same release. In cases where this is not desirable or possible is useful to be able to specify a custom value for that label.
This can be more flexible allowing any generic set of labels but I didn't want to complicate the PR for now and preferred to maintain compatibility.
> [helm/alertmanager] Choose custom prometheus label value

- .travis.yml
- scripts/travis-push-docker-image.sh
Push all git tags and `master` branch builds to `quay.io/coreos/prometheus-operator`, and all other git branches to `quay.io/coreos/prometheus-operator-dev`.
> quay: Push docker images to quay for all git branches

- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
- helm/prometheus/Chart.yaml
- helm/prometheus/templates/configmap.yaml
- helm/prometheus/templates/ingress.yaml
- helm/prometheus/templates/prometheus.yaml
- helm/prometheus/templates/rules.yaml
- helm/prometheus/templates/secret.yaml
- helm/prometheus/templates/service.yaml
- helm/prometheus/templates/servicemonitor-prometheus.yaml
- helm/prometheus/templates/servicemonitors.yaml
- helm/prometheus/values.yaml
Similar to #1226, will be handy to specify a custom value for the prometheus label on the prometheus Chart too.
Default value of .Release.Name is kept.
> [helm/prometheus] Custom prometheus label value

- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
- helm/prometheus/Chart.yaml
- helm/prometheus/templates/_helpers.tpl
- helm/prometheus/templates/prometheus.yaml
- helm/prometheus/templates/serviceaccount.yaml
- helm/prometheus/values.yaml
On the cases where `global.rbacEnable: false` the `serviceAccountName` attribute of the Prometheus is not defined so is not possible to define a ServiceAccount outside the Chart and let the Prometheus object use it.
This change allows the case where custom rbac objects like ClusterRole, ServiceAccount and bindings are managed outside the Chart (so `global.rbacEnable: false`) and we want that the Prometheus objects uses that externally defined account.
When installing prometheus on an specific namespace I want to define a custom role that gives access only to resources inside the namespace and with that a custom RoleBinding, so having full control of the ServiceAccount, makes sense to use that account on the Prometheus Chart instead of relying on the preconfigured account.
> [helm/prometheus] Custom ServiceAccountName when rbac disabled

- Documentation/api.md
- example/prometheus-operator-crd/servicemonitor.crd.yaml
- pkg/client/monitoring/v1/openapi_generated.go
- pkg/client/monitoring/v1/types.go
- pkg/client/monitoring/v1/zz_generated.deepcopy.go
- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
With the _additional-scrape-config_ feature (https://github.com/coreos/prometheus-operator/pull/1246) via Kubernetes secrets, the _static-configs_ feature in Service Monitors is redundant.
I suggest reverting the latter one, as _additional-scrape-config_ enables users to do a greater range of custom configurations.
@brancz @metalmatze What do you think?
> service-monitor: Revert static targets configuration in service monitors

- contrib/kube-prometheus/jsonnet/kube-state-metrics/kube-state-metrics-role-binding.libsonnet
- contrib/kube-prometheus/manifests/kube-state-metrics/kube-state-metrics-role-binding.yaml
The addon resizer was referring to an incorrect role binding and was unable to access the API.  This changes the rolebinding name to refer to the actually defined rolebinding.
Without this change, you get a lot of messages like this after deploying to a cluster with rbac enabled:
```
monitoring/kube-state-metrics-5d8784b89d-qw9r2[addon-resizer]: E0426 02:02:19.908809       1 nanny_lib.go:95] pods "kube-state-metrics-5d8784b89d-qw9r2" is forbidden: User "system:serviceaccount:monitoring:kube-state-metrics" cannot get pods in the namespace "monitoring": Unknown user "system:serviceaccount:monitoring:kube-state-metrics"
```
Note that I couldn't easily get the ksonnet stuff building, so I just changed both the jsonnet file and the yaml manually.
> kube-prometheus: fix addon-resizer role binding

- helm/alertmanager/Chart.yaml
- helm/alertmanager/README.md
- helm/alertmanager/templates/alertmanager.yaml
- helm/alertmanager/templates/ingress.yaml
- helm/alertmanager/values.yaml
- helm/grafana/Chart.yaml
- helm/grafana/README.md
- helm/grafana/templates/NOTES.txt
- helm/grafana/templates/ingress.yaml
- helm/grafana/values.yaml
- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
- helm/kube-prometheus/templates/NOTES.txt
- helm/kube-prometheus/values.yaml
- helm/prometheus/Chart.yaml
- helm/prometheus/README.md
- helm/prometheus/templates/ingress.yaml
- helm/prometheus/templates/prometheus.yaml
- helm/prometheus/values.yaml
Instead of using the String ``fqdn`` to configure the hostname in the Ingresses, the List ``hosts`` is now used to configure the hostnames for the Ingresses.
> Added support for multiple hostnames to alertmanager/prometheus/grafana

- helm/prometheus-operator/Chart.yaml
- helm/prometheus-operator/templates/clusterrole.yaml
Seeing 403s in the kube-apiserver logs and error in prometheus-operator logs trying to watch namespaces. This seems to be a new thing.
Environment:
- Kubernetes v1.10.1
- Installed with helm 2.8.1
- prometheus-operator chart 0.0.22
- kube-prometheus chart 0.0.31 (probably not relevant)
```
{
"log":{
"kind":"Event",
"apiVersion":"audit.k8s.iogv1beta1",
"metadata":{
"creationTimestamp":"2018-05-01T16:42:08Z"
},
"level":"Request",
"timestamp":"2018-05-01T16:42:08Z",
"auditID":"1a65c54b-7ea3-4ad7-a297-c401477eebd6",
"stage":"ResponseStarted",
"requestURI":"/api/v1/namespaces?resourceVersion=221057u0026timeoutSeconds=475u0026watch=true",
"verb":"watch",
"user":{
"username":"system:serviceaccount:monitoring:prometheus-operator",
"uid":"ee069c7e-4b52-11e8-bc29-0aa27986b75e",
"groups":[ …
```
> Prometheus operator clusterrole needs namespace/watch permissions

- Documentation/api.md
- pkg/client/monitoring/v1/openapi_generated.go
- pkg/client/monitoring/v1/types.go
- pkg/prometheus/operator.go
The empty selector is meant as the "all" selector in Kubernetes, this change allows using the all selector to be used for the namespace selector of the Prometheus resource.
@mxinden
> prometheus: Allow all selector for namespaces

- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
- helm/prometheus/Chart.yaml
- helm/prometheus/templates/service.yaml
In the case where `prometheusLabelValue` is not specified, the Prometheus CRD [is using a different default label than the service](https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus/templates/prometheus.yaml#L9), resulting in the service not being able to select the right pods.
> Fix prometheus service default pod selector in the prometheus chart

- contrib/grafana-watcher/README.md
https://github.com/coreos/prometheus-operator/issues/1025#issuecomment-369225236 and https://github.com/coreos/prometheus-operator/issues/1251#issuecomment-384079856 mention this, but I didn't see it reflected in the docs.
> contrib/grafana-watcher: add deprecation notice

- contrib/kube-prometheus/manifests/prometheus-rules.yaml
@brancz @mxinden 
CI is failing on #1321 and #1316 because a PR got merged without running `make generate`
> Fix CI running make generate

- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/values.yaml
Add back kube-state-metrics to the Prometheus service monitor selector.
> Add kube-state-metrics to Prometheus service monitor selector

- contrib/kube-prometheus/build.sh
According to the man pages of `rm` and the `-f` option:
> Attempt to remove the files without prompting for confirma- tion,
> regardless of the file's permissions.  If the file does not exist, do
> not display a diagnostic message or modify the exit status to reflect an
> error.  The -f option overrides any previous -i options.
This patch prevents the `build.sh` script from failing if files do not
exist when attempting to delete them.
> contrib/kube-prometheus: add `-f` to `rm` in `build.sh`

- test/e2e/alertmanager_test.go
- test/framework/alertmanager.go
Instead of comparing full configs, just check for a unique keyword. This
makes the test more robust to upstream format changes.
> e2e/alertmanager: Check if config contains string in ReloadConfig

- test/e2e/alertmanager_test.go
Update TestAlertmanagerVersionMigration versions to `v0.14.0` and
`v0.15.0-rc.1`.
> e2e/alertmanager: Update version migration test to recent version

- Makefile
- contrib/kube-prometheus/README.md
- contrib/kube-prometheus/build.sh
> actually just seconds after I merged I realized, but can you just re-embed this into the readme in kube-prometheus? looks like our generation make target is not picking that up
@brancz Follow up for https://github.com/coreos/prometheus-operator/pull/1334
> docs: Run embedmd on both Docs and kube-prometheus README.md

- helm/exporter-kube-state/Chart.yaml
- helm/exporter-kube-state/templates/deployment.yaml
- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
This is to fix https://github.com/coreos/prometheus-operator/issues/1306#issuecomment-387434365. 
The "Toleration" field in `values.yaml` is out side of "kube_state_metric" field so we dont need it here.
The current `values.yaml` is:
```
kube_state_metrics:
image:
blah blah
service:
blah blah
addon_resizer:
blah blah
image:
blah blah
resources:
blah blah
tolerations: {}     <--- And Toleration here is out side of those above
```
> ISSUE-1306: Fix the Toleration field

- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/templates/NOTES.txt
We encountered the same issue as [#1342](https://github.com/coreos/prometheus-operator/issues/1342).
When installing `kube-prometheus:0.0.66` without Node Exporter or Grafana, it fails as values are not set.
> Fix kube-prometheus chart not deploying when some features are disabled

- Documentation/user-guides/cluster-monitoring.md
This PR adds the node-exporter ServiceAccount to the Cluster monitoring guide. Without
the ServiceAccount the node-exporter pods are unable to start.
Fixes #1352
> docs: Add node-exporter ServiceAccount to documentation

- test/e2e/README.md
The current E2E testing readme indicates that you need to have an etcd operator image created prior to testing the prometheus operator, which was a little confusing. It looks like this was just a copy and paste issue from the etcd operator E2E test readme. This PR updates the readme to reflect that it's a prometheus operator image that is required.
> Typo fix in e2e test readme

- helm/prometheus-operator/Chart.yaml
- helm/prometheus-operator/templates/servicemonitor-configmap.yaml
Hello,
Looks like there are duplicating selectors in the service monitor of the prometheus-operator helm chart. This PR just removes the empty one.
> prometheus-operator chart: remove redundant Label selector

- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
- helm/prometheus/Chart.yaml
- helm/prometheus/templates/prometheus.yaml
Hello,
This one should fix broken yaml in case of using `.Values.prometheusLabelValue` in the prometheus helm chart
> prometheus chart: fix identation on serviceMonitorSelector

- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus-operator/prometheus-operator.libsonnet
- contrib/kube-prometheus/manifests/0prometheus-operator-clusterRole.yaml
- contrib/kube-prometheus/manifests/prometheus-rules.yaml
(This is the first PR I've ever created for this `coreos/prometheus-operator` repo.)
This PR (hopefully) resolves the comments that were added today to #1324 - about the following error in the `prometheus-operator` pod logs:
`E0517 17:06:40.310569 1 reflector.go:322] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:300: Failed to watch *v1.Namespace: unknown (get namespaces)`
Can someone please tell me how to run [kube-prometheus/build.sh](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/build.sh) (so that I can also add to this PR the corresponding change to https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/0prometheus-operator-clusterRole.yaml)? I looked at the latest …
> kube-prometheus: add the watch verb (to the namespace apiGroup for the prometheus-operator ClusterRole).

- test/e2e/prometheus_test.go
@mxinden I'm not exactly sure why but in CI the statefulset is consistently updated twice after creation, we should figure out whether this is the expected behavior, but for now this unblocks all other PRs.
> test/e2e: StatefulSet is updated twice after creation

- contrib/kube-prometheus/jsonnet/kube-prometheus/alertmanager/alertmanager.libsonnet
- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet
The defaults are still with the same names as before. Prometheus is still called `k8s` and Alertmanager is still `main`. I call them both `metalmatze` in my cluster.
Already got it working. :blush:
> Make the Prometheus & Alertmanager name configurable

- Makefile
Enable bash pipefail flag for all Makefile operations. This arised when
running `make jsonnet`, where `jsonnet` failed, but the rest of the pipe
covered the error.
> Makefile: Enable bash pipefail

- .travis.yml
If both the *generate* as well as the *e2e* tests on a patch fail, a
user does not need to wait for the second (fixed) iteration of the
*generate* tests to pass until the user gets the *e2e* failure feedback.
> travis: Move e2e tests to first stage

- test/framework/prometheus.go
We have seen repeated failures of this test. I was facing difficulties reproducing this locally. To ensure it is not a flake, let's run this multiple times on travis with a fine tuned timeout.
> e2e: Fine tune WaitForPrometheusFiringAlert timeouts

- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
- helm/prometheus/Chart.yaml
- helm/prometheus/templates/_helpers.tpl
- helm/prometheus/templates/configmap.yaml
Before this change a release name of "kube-prometheus" will have a prometheus pod called "prometheus-kube-prometheus-prometheus".
With this change the same release will have a pod name "prometheus-kube-prometheus"
> [helm/prometheus] Use contains on prometheus.fullname template

- Documentation/rbac.md
- Documentation/user-guides/getting-started.md
- bundle.yaml
- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus-operator/prometheus-operator.libsonnet
- contrib/kube-prometheus/manifests/0prometheus-operator-clusterRole.yaml
- example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
Since PR 460 [1] the Prometheus Operator is using Kubernetes Custom Resource
Definitions instead of Kubernetes Third Party Resources. Permissions to
handle Third Party Resources in the RBAC rules of the Prometheus
Operator is thereby obsolete.
[1] https://github.com/coreos/prometheus-operator/pull/460
//CC @brancz @ant31
> rbac: Remove Third Party Resources rules

- helm/grafana/Chart.yaml
- helm/grafana/templates/dashboards-configmap.yaml
- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
When installing the Helm charts the datasource for prometheus in graphana is not configured correctly, see issue #1412. Removed `-prometheus` from datasource URL in Helm chart
> fixed prometheus datasource configuration in graphana configmap

- pkg/client/monitoring/v1/alertmanager.go
- pkg/client/monitoring/v1/alertmanager_test.go
- pkg/client/monitoring/v1/prometheus.go
- pkg/client/monitoring/v1/prometheus_test.go
Fix a conversion issue which prevents updates to Prometheus resource timestamp
fields where the timestamp is a.) a value type and b.) a read-only API field
(i.e. creationTimestamp).
> Fix conversion of Prometheus timestamp fields

- .travis.yml
- cmd/po-rule-cm-to-rule-file-crds/main.go
- pkg/prometheus/rule_configmap_migration.go
- pkg/prometheus/rule_configmap_migration_test.go
This patch adds a cli tool to migrate existing Prometheus rule config
maps to Prometheus rule file CRDs.
Usage:
```bash
cd cmd/po-rule-cm-to-rule-file-crds
go install
po-rule-cm-to-rule-file-crds \
--rule-config-map=../../contrib/kube-prometheus/manifests/prometheus-rules.yaml \
--rule-crds-destination=.
```
> cmd/po-rule-cm-to-rule-file-crds: Add migration CLI tool

- cmd/operator/main.go
- contrib/prometheus-config-reloader/Makefile
The prometheus-config-reloader will be released alongside the
prometheus-operator. Thereby it holds the same version.
For now we will manually hardcode that version. In the future this could
be achieved dynamically via a compiler flags.
> prometheus-config-reloader: Hardcode version

- contrib/kube-prometheus/jsonnet/kube-prometheus/jsonnetfile.json
- hack/generate/jsonnetfile.json
- jsonnet/prometheus-operator/.gitignore
- jsonnet/prometheus-operator/jsonnetfile.json
This is a follow up to #1443, changing the version of the prometheus-operator jsonnet package to the now existent `master` version.
@mxinden
> *: Use all jsonnet from master branch

- helm/exporter-kube-etcd/Chart.yaml
- helm/exporter-kube-etcd/templates/etcd3.rules.yaml
- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
- Fix helm etcd alerts using the right kube-etcd label 
- ~~This PR also fix the broken CI running `make generate`~~
> [helm] use the right kube-etcd label

- contrib/kube-prometheus/jsonnet/kube-prometheus/alerts/node.libsonnet
- contrib/kube-prometheus/manifests/prometheus-rules.yaml
When NodeDiskRunningFull is alarmed 4 alerts are generated. 3 of those are for the following mountpoints: `/etc/resolv.conf`, `/etc/hosts`, `/etc/hostname` and the last one is for the `/` mountpoint.
A good example is https://github.com/coreos/prometheus-operator/issues/1180#issuecomment-382799514
N.B. Seems the automation to update the helm charts is broken /cc @gianrubio so I'm unsure if I should update them manually.
> NodeDiskRunningFull ignore etc files mountpoints

- contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus.libsonnet
- contrib/kube-prometheus/manifests/grafana-dashboardDatasources.yaml
- contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml
- contrib/kube-prometheus/manifests/grafana-deployment.yaml
This updates the Grafana stack, most notably, that all dashboards are now in their own ConfigMap.
@mxinden @metalmatze
> kube-prometheus: Use 1 ConfigMap per Grafana dashboard

- test/e2e/main_test.go
To improve the ability to debug the Prometheus Operator e2e tests, print
all Kubernetes events on test failure.
> e2e: Print Kubernetes events on test failures

- Makefile
- cmd/operator/main.go
- cmd/prometheus-config-reloader/main.go
- pkg/version/version.go
The Prometheus config reloader image is released along with the
Prometheus Operator image, tagged with the same semver version. In order
to default to the Prometheus Operator version if no Prometheus config
reloader image is specified, the content of `VERSION` needs to be passed
during compile time.
> pkg/version: Pass Prometheus Operator version via ldflags

- Documentation/user-guides/getting-started.md
This PR adds in the documentation the fact the ServiceMonitors must be installed in the same namespace as Prometheus Operator.
Related to this issue: https://github.com/coreos/prometheus-operator/issues/1435
> Documentation Update

- README.md
With PR #1481, I removed the ROADMAP.md file but did not delete the reference to that file inside the README.md. This commit fixes that.
> docs: Removed reference to ROADMAP.md file

- Documentation/user-guides/cluster-monitoring.md
- Makefile
- contrib/kube-prometheus/jsonnet/kube-prometheus/node-exporter/node-exporter.libsonnet
- contrib/kube-prometheus/manifests/grafana-dashboardDatasources.yaml
- contrib/kube-prometheus/manifests/node-exporter-daemonset.yaml
Node exporter needs to run in the host network, not in the pod network
in order to pick up network metrics of the node.
Fixes https://github.com/coreos/prometheus-operator/issues/1473
> kube-prometheus: Run node-exporter in host network

- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
- helm/prometheus/Chart.yaml
- helm/prometheus/templates/prometheus.yaml
- helm/prometheus/templates/secret.yaml
- helm/prometheus/values.yaml
This should help Helm users take advantage of the flexibility of the `additionalAlertManagerConfigs` field added to `PrometheusSpec`.
Fixes #1456
> add additionalAlertManagerConfigs to helm chart

- contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml
- contrib/kube-prometheus/manifests/prometheus-rules.yaml
This update pulls in 3 new great changes from the kubernetes monitoring mixin:
* Runbook links
* Stable dashboard IDs (this means drill down in Grafana dashboards will work)
* Job and CronJob alerts
@mxinden
> kube-prometheus: Update kubernetes monitoring mixing

- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
- helm/kube-prometheus/values.yaml
- helm/prometheus/Chart.yaml
- helm/prometheus/templates/prometheus.yaml
- helm/prometheus/values.yaml
Hi there,
I've been working on using Thanos with the kube-prometheus helm charts but I had to add some features to make it work. So now I'm contributing it back.
It adds:
- Prometheus sidecarsSpec field : necessary to add thanos's sidecar component to a Prometheus instance.
- Prometheus labels field as podMetadata.labels : necessary to make the thanos-peer service to work with thanos's sidecar component.
> Add sidecar containers field to Prometheus Helm chart

- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
- helm/kube-prometheus/values.yaml
- helm/prometheus/Chart.yaml
- helm/prometheus/README.md
- helm/prometheus/templates/prometheus.yaml
Currently the `ruleNamespaceSelector` cannot be specified in the prometheus chart.
> Added ruleNamespaceSelector to kube-prometheus and prometheus charts.

- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/values.yaml
The default serviceMonitorsSelector that the prometheus chart provides is sufficient and having one set in kube-prometheus makes it impossible to just get the default behaviour (without actually overriding it).
> kube-prometheus: Remove default serviceMonitorsSelector

- contrib/kube-prometheus/docs/developing-prometheus-rules-and-grafana-dashboards.md
Fix missing and broken links in [developing-prometheus-rules-and-grafana-dashboards](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/developing-prometheus-rules-and-grafana-dashboards.md)
> docs: fix missing and broken links

- helm/prometheus-operator/Chart.yaml
- helm/prometheus-operator/templates/servicemonitor-configmap.yaml
The port create by operator is `web` not `http` which will lead prometheus scraping no data.
> fix: wrong port name

- pkg/alertmanager/statefulset.go
- pkg/prometheus/statefulset.go
This pull request allows users that have more control over setting volumeclaim template. Specifically the volume claim name . If a person doesn't set the name then it is inserted for you by default as it has been doing for statefulset. This is needed more since using gluster as a storageclass , the name is too long . Giving user the ability to set their name for themselves, people that want to migrate to using gluster won't have this issue anymore since the user can set a short name and wont break anything for people already using volume claim template.
> allow seting volume name via volumetemplateclaimtemplate in prom and alertmanager

- contrib/kube-prometheus/README.md
- contrib/kube-prometheus/examples/etcd.jsonnet
- contrib/kube-prometheus/jsonnet/kube-prometheus/jsonnetfile.json
- contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-static-etcd.libsonnet
This adds an easy to configure mixin to the kube-prometheus library to monitor a static set of etcd nodes.
@mxinden
> kube-prometheus: Add kube-prometheus mixin to configure static etcd

- pkg/prometheus/statefulset.go
As described in https://github.com/coreos/prometheus-operator/issues/1169#issuecomment-402659888, thanos sidecar container did not have prometheus data directory mounted inside it.
* Mounted prometheus data volume inside thanos on `/prometheus` path
* Override default `tsdb.path` directory to `storageDir` of prometheus operator (default `/prometheus`)
> Mount prometheus data volume into thanos sidecar (#1169)

- pkg/prometheus/operator.go
- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
- pkg/prometheus/rules.go
- pkg/prometheus/rules_test.go
- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
- test/e2e/prometheus_test.go
- test/framework/config_map.go
- test/framework/prometheus.go
- test/framework/prometheus_rule.go
`k8s.io/api/core/v1.MaxSecretSize` specifies the hard limit Kubernetes
has on the size of config maps [1]. If a set of Prometheus Rule Files
exceeds this limits, they are split onto multiple config maps. If there
is more than one rule config map for a Prometheus, its configuration
secret and its statefulset spec are adjusted accordingly.
The smallest entity to split by is a Prometheus rule file. This patch
does not split an individual rule file, if it exceeds the limit by
itself.
[1] https://github.com/kubernetes/kubernetes/pull/19909/
Closes https://github.com/coreos/prometheus-operator/issues/1472
> prometheus: Split rule config map if it exceeds Kubernetes limit

- helm/exporter-kube-etcd/Chart.yaml
- helm/exporter-kube-etcd/templates/service.yaml
- helm/exporter-kube-etcd/values.yaml
- helm/kube-prometheus/Chart.yaml
- helm/kube-prometheus/requirements.yaml
Kubeadm uses different labels when it creates the pods. Other exporters allow selecting these, but etcd is set up by kubeadm has an additional discrepancy
> helm: Allow setting pod selector on etcd

- cmd/operator/main.go
- cmd/prometheus-config-reloader/main.go
- pkg/prometheus/operator.go
It would be nice if all moving parts of the prometheus operator would support json-formatted structured logging.
Providing this as an early stage PR to gather feedback on it.
For upstream prometheus, there's a PR available here: https://github.com/prometheus/common/pull/136/files
> operator: Support json as a log format

- cmd/operator/main.go
- contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml
- contrib/kube-prometheus/manifests/grafana-deployment.yaml
- contrib/kube-prometheus/manifests/prometheus-rules.yaml
- pkg/alertmanager/operator.go
- pkg/prometheus/operator.go
In certain Prometheus Operator deployment scenarios it is desirable to
manage CRD creation outside of the operator. Likewise, it can be
desirable to scope the permissions of the Prometheus Operator so that it
does not have cluster-level access. This commit enables operation in
these situations by adding a flag to configure whether or not the
Prometheus Operator should try to create CRDs itself.
> pkg: add flag to toggle CRD creation in operator

- helm/kube-prometheus/Chart.yaml
- helm/prometheus/templates/rules.yaml
- If having a release that contains `prometheus` then those extra rules ConfigMap names will be something like `prometheus-prometheus-rules`
- Having the `rules` suffix clashes with the ConfigMap name for the default prometheus rules.
> [helm/prometheus] Rename extra rules

- Documentation/user-guides/cluster-monitoring.md
- Documentation/user-guides/getting-started.md
- bundle.yaml
- contrib/kube-prometheus/manifests/0prometheus-operator-deployment.yaml
- example/non-rbac/prometheus-operator.yaml
- example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
- jsonnet/prometheus-operator/prometheus-operator.libsonnet
- test/e2e/main_test.go
- test/framework/alertmanager.go
- test/framework/framework.go
- test/framework/pod.go
When handling big Kubernetes objects, marshalling objects is memory
intense. This can be reproduced with the end-to-end test
`TestPrometheusRulesExceedingConfigMapLimit`. This patch doubles the
memory request and limit of the Prometheus Operator deployment to 100mb
and 200mb.
> bundle.yaml: Bump Prometheus Operator memory request and limit

- helm/kube-prometheus/README.md
I am fairly familiar with prometheus-operator and it took me a little digging to notice what these flags did so I think it would be useful to document it for new users. Maybe it belongs in Documentation?
> Add documentation bit about ignoring controlplane targets on managed K8s

- pkg/client/monitoring/v1/alertmanager_test.go
- pkg/client/monitoring/v1/prometheus_test.go
small fix suggested from goreportcard.
cc @mxinden
> pkg/client/monitoring: spelling mistake

- helm/README.md
If people look at the readme they most likely have no clue what helm is, give them a small pointer.
> Fix typo, point to helm install

- contrib/kube-prometheus/experimental/metrics-server/metrics-server-cluster-role.yaml
Without this access the logs of metrics-server will show the following error line:
```
unable to fully scrape metrics from source kubelet_summary:k8s-1: unable to fetch metrics from Kubelet k8s-1 (10.8.10.14): request failed - "403 Forbidden", response: "Forbidden (user=system:serviceaccount:kube-system:metrics-server, verb=get, resource=nodes, subresource=stats)",
```
and `kubectl top nodes` will give no results
> metrics-server: enable access to nodes/stats

- cmd/operator/main.go
As noted in
https://github.com/openshift/cluster-monitoring-operator/pull/52#discussion_r204747221,
the Prometheus Operator should also register process metrics.
cc @brancz
> cmd/operator: add process collector

- contrib/kube-prometheus/README.md
- contrib/kube-prometheus/docs/GKE-cadvisor-support.md
Chatting in https://github.com/coreos/prometheus-operator/issues/1623 it sounds like prior to 1.11, downgrading to https _is_ the correct approach.
This adds the jsonnet approach to to the docs, and adds a reference to it from the README
> Update GKE kubelet scraping docs

- contrib/kube-prometheus/jsonnet/kube-prometheus/kube-state-metrics/kube-state-metrics.libsonnet
- contrib/kube-prometheus/manifests/kube-state-metrics-clusterRole.yaml
- contrib/kube-prometheus/manifests/kube-state-metrics-role.yaml
Add `apps` to apiGroups for daemonsets, deployments, and replicasets to support core workloads api `apps/v1`.
https://kubernetes.io/blog/2018/01/core-workloads-api-ga/
Tested on Kubernetes:
```
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
> adjust rbac apiGroups to support core workloads api apps/v1

- pkg/prometheus/operator.go
`client-go/tools/cache.ListAllByNamespace` tries to search the given
cache by the namespace index. If that index is not present, it logs a
warning message and iterates over the objects itself [1].
Initially to remove the log line, but as a side effect also to improve query
speed, this patch adds the namespace index to all used SharedIndexInformers in
the Prometheus and Alertmanager operator.
[1]
```golang
items, err := indexer.Index(NamespaceIndex, &metav1.ObjectMeta{Namespace: namespace})
if err != nil {
// Ignore error; do slow search without index.
glog.Warningf("can not retrieve list of objects using index : %v", err)
for _, m := range indexer.List() {
```
Fixes https://github.com/coreos/prometheus-operator/issues/1694
//CC @prune998
> client-go/informers: Add namespace indexer to SharedIndexInformers

- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/.gitignore
- contrib/kube-prometheus/Makefile
- contrib/kube-prometheus/jsonnet/kube-prometheus/jsonnetfile.json
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/0prometheus-operator-0alertmanagerCustomResourceDefinition.yaml
- contrib/kube-prometheus/manifests/0prometheus-operator-0prometheusCustomResourceDefinition.yaml
- contrib/kube-prometheus/manifests/0prometheus-operator-0servicemonitorCustomResourceDefinition.yaml
- contrib/kube-prometheus/manifests/0prometheus-operator-deployment.yaml
- contrib/kube-prometheus/manifests/kube-state-metrics-clusterRole.yaml
- contrib/kube-prometheus/manifests/kube-state-metrics-role.yaml
This pull request introduces all the changes necessary to properly lock against jsonnet dependencies with jsonnet-bundler. It also locks the prometheus-operator dependency against `v0.22.2` in kube-prometheus.
The pull request to implement this in jsonnet-bundler is still pending, but will be merged should CI succeed here. Then I will revert the second commit of this pull request.
@mxinden @squat @metalmatze
> Jsonnet locking

- pkg/prometheus/operator.go
`client-go/tools/cache.ListAllByNamespace` tries to search the given
cache by the namespace index. If that index is not present, it logs a
warning message and iterates over the objects itself [1].
Initially to remove the log line, but as a side effect also to improve query
speed, this patch adds the namespace index to all used SharedIndexInformers in
the Prometheus and Alertmanager operator.
[1]
```
items, err := indexer.Index(NamespaceIndex, &metav1.ObjectMeta{Namespace: namespace})
if err != nil {
// Ignore error; do slow search without index.
glog.Warningf("can not retrieve list of objects using index : %v", err)
for _, m := range indexer.List() {
```
> client-go/informers: Add namespace indexer to SharedIndexInformers (-> `master`)

- pkg/prometheus/rules.go
We are mistakingly not returning an error and allowing a function to
continue.
cc @mxinden @brancz
> pkg: return err

- contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml
- jsonnet/prometheus-operator/prometheus-operator.libsonnet
- pkg/prometheus/operator.go
- scripts/delete-minikube.sh
- test/e2e/prometheus_test.go
- Introduce the 'prometheus_operator_triggered_total'
Prometheus metric counter, differentiated in label dimensions:
- triggered_by
- monitoringv1.PrometheusesKind
- monitoringv1.ServiceMonitorsKind
- monitoringv1.PrometheusRuleKind
- "ConfigMap"
- "Secret"
- "StatefulSet"
- "Namespace"
- action
- "add"
- "delete"
- "update"
- Add increase hooks of above mentioned metric to all Kubernetes
informer handlers and add simple log line on debug level.
- Add condition to Kubernetes informer update handlers to only preceed
when previous resource version is not equal to new resource version.
This will prevent triggering a reconciliation loop on informer resyncs.
Relates to https://github.com/coreos/prometheus-operator/issues/1659.
> prometheus: Improve metrics and stop reconciling on no update

- contrib/kube-prometheus/jsonnetfile.lock.json
This PR updates the `jsonnetfile.lock.json` to be updated with the content it should truly have.
@mxinden
> kube-prometheus: Fix jsonnet lock file

- Documentation/user-guides/storage.md
The `storageClassName` field was missing
> storage docs

- pkg/prometheus/operator.go
Instead of increasing the Prometheus Rule trigger counter, the
ServiceMonitor trigger counter was increased.
> prometheus: Fix wrong metric increase

- pkg/prometheus/operator.go
- pkg/prometheus/rules.go
If the operator is not watching all namespaces, then the namespace
informer is not started. This means that all operations that depend on
listing namespaces based on the informer will not work. This commit
modifies those operations so that they work in a single-namespace
configuration.
cc @mxinden @brancz 
~~Note: still needs a little more tweaking; there is some configuration that is causing the Prometheus-k8s instances to crashloop.~~ Disregard, crashlooping was due to a manually deployed alerting rule that was missing quotes around a string.
> pkg: don't rely on ns informer if ns selected

- pkg/prometheus/rules.go
- pkg/prometheus/rules_test.go
Instead of iterating over a map, iterate over a sorted array of map
keys. This is relevant e.g. in a case with two small and one large
RuleFile. [small, large, small] results in three ConfigMaps, [small,
small, large] results in two.
Related to https://github.com/coreos/prometheus-operator/issues/1659.
//CC @Capitrium
> pkg/prometheus: Make Rule ConfigMap bin packing deterministic

- helm/prometheus/README.md
> helm: fix typo in prometheus README.md

- pkg/alertmanager/statefulset.go
- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
- test/e2e/prometheus_test.go
- test/framework/prometheus.go
Users have reported high CPU usage of the Prometheus Operator when
adding an annotation to a Prometheus object. The Operator would update
the respective StatefulSet in an infinite loop.
Whether a given StatefulSet needs updating is determined by the hash of
the inputs needed to generate the StatefulSet, which is calculated and
then attached to the StatefulSet as an annotation. On subsequent
reconciliations this hash is compared to the hash of the new inputs.
The function to build the StatefulSet definition is passed the
Prometheus object. This is done by value, not by reference. This does
not enforce a deep copy but merely a shallow copy. In the build function
the new StatefulSet would inherit the annotation map of the Prometheus
object. Next the input hash would be added to this map, …
> pkg/*/statefulset.go: Do not mutate shared object

- contrib/kube-prometheus/README.md
- contrib/kube-prometheus/examples/additional-namespaces.jsonnet
This adds some documentation to make clearer how to monitor additional namespaces. Originally this comes from #1773.
@mxinden @squat @s-urbaniak
> kube-prometheus: Add docs on monitoring additional namespaces

- Makefile
Adding `make clean` target to main Makefile. This helps a lot debugging
jsonnet vendoring issues.
**Up for discussion. Let me know if you feel unsafe adding this.**
Relevant `git clean` manual entry:
```man
-d
Remove untracked directories in addition to untracked files.
If an untracked directory is managed by a different Git repository, it
is not removed by default. Use -f option twice if you really want to
remove such a directory.
-f, --force
If the Git configuration variable clean.requireForce is not set to
false, git clean will refuse to delete files or directories unless given
-f, -n or -i. Git will refuse to delete directories with .git sub
directory or file unless a second -f is given.
-X
Remove only files ignored by Git. This may be useful to rebuild
everything from scratch, but …
```
> Makefile: Add clean target

- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/jsonnet/kube-prometheus/node-exporter/node-exporter.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/node-exporter-daemonset.yaml
Fixes https://github.com/prometheus/node_exporter/issues/474 in the operator
Fixes #569 (by making the mount explicit)
> kube-prometheus: bind mount host rootfs into node exporter

- cmd/operator/main.go
- pkg/alertmanager/operator.go
- pkg/listwatch/listwatch.go
- pkg/prometheus/operator.go
- pkg/prometheus/rules.go
This is a large PR broken into two logical commits that can be separate PRs if needed.
I have tested these changes on an Openshift cluster as part of https://github.com/openshift/cluster-monitoring-operator with several different configurations:
* single namespace, i.e. `--namespaces=x`
* multiple namespaces, i.e. `--namespaces=x,y` and `--namespaces=x --namespaces=y`
* all namespaces, i.e. no `--namespaces` flag so `v1.NamespaceAll` is used
First:
This commit adds multi-namespace support to the Prometheus Operator. PO
now allows all informers to react to changes to multiple, individually
configured, namespaces, i.e. without specifying v1.NamespaceAll. This is
important for cases where the Prometheus Operator does not have
privileges to List all namespaces but should still administer …
> *: add multi-namespace support to Prometheus Operator

- pkg/prometheus/operator.go
- pkg/prometheus/operator_test.go
If a node doesn't have an IP address, currently all endpoint updating is
aborted. This change lets the addressable nodes get updated, and increments an
error counter for alerting on this condition.
Fixes #1815
> Don't abort kubelet endpoints update because of nodes without addresses

- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/jsonnet/kube-prometheus/node-exporter/node-exporter.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml
- contrib/kube-prometheus/manifests/node-exporter-daemonset.yaml
- contrib/kube-prometheus/manifests/prometheus-rules.yaml
Currently, we are mounting `/root` from the host as `/host/root`.
Instead simply `/` from the host should be mounted.
This fixes it
> kube-prometheus: fix root typo in node-exporter

- cmd/operator/main.go
Even though a golang map is a reference type, initializing the object
inside one of its methods changes the reference.
This fact caused issues inside the `namespaces` method `Set` which would
initialize `ns` if it is `nil`.
//CC @squat @s-urbaniak
> cmd/operator: Fix namespaces flag initialization

- pkg/prometheus/promcfg_test.go
I wrote a test to validate the additionalAlertmanagerConfigs. I thought there was a bug originally (there isn't), but this test seems useful to have.
> pkg/prometheus: test promcfg's generation of the additionalAlertmanagerConfigs

- contrib/kube-prometheus/jsonnet/kube-prometheus/alerts/node.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/prometheus-rules.yaml
Only trigger disk running full alerts when the disk capacity is over 85%
and use recording rule of the kubernetes-mixin to only consider real
physical filesystems.
I chose 85% because the kubelet garbage collects unused container
images at 80% disk usage.
@mxinden @squat @s-urbaniak @metalmatze
> Better disk alert

- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml
In the [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) we now override the dashboard's timezone to default to what is configured in Grafana itself. This updates the dependency and the generated configmap.
@brancz @squat
> contrib/kube-prometheus: Use default timezone in dashboards

- pkg/alertmanager/statefulset.go
- pkg/prometheus/statefulset.go
IPv6 pod IPs need to be enclosed in square brackets.  This closes #1858.
> Add square brackets around pod IPs

- Documentation/rbac.md
- Documentation/user-guides/getting-started.md
- Makefile
- bundle.yaml
- example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
- jsonnet/prometheus-operator/prometheus-operator.libsonnet
- test/e2e/alertmanager_test.go
- test/e2e/main_test.go
- test/e2e/prometheus_test.go
- test/framework/context.go
- test/framework/framework.go
- test/framework/pod.go
- test/framework/prometheus.go
Refactor test framework to support multi namespace end-to-end tests. Add
basic multi namespace end-to-end test:
- Creating two namespaces with one firing Prometheus alerting rule each.
- Create Prometheus which selects Prometheus rules out of both namespaces.
- Configure Prometheus Operator to only watch one namespace.
=> Expect Prometheus to only fire one alert.
> test/e2e: Add multi namespace end-to-end test

- contrib/kube-prometheus/README.md
With those changes, diff does show any differences between generated manifests
with and without the version override in a top level jsonnet file.
> contrib/kube-prometheus: Update README with up-to-date default versions

- Gopkg.lock
- pkg/alertmanager/statefulset.go
- pkg/k8sutil/k8sutil.go
- pkg/k8sutil/k8sutil_test.go
- pkg/prometheus/statefulset.go
This commit replaces `.` characters in Volume names for Secrets
with `-` characters. The reason for this is that Volume names must be
valid DNS-1123 labels. [0]
[0] https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#volume-v1-core.
Fixes #1893
cc @brancz @yskopets
> pkg: allow periods in secret name

- contrib/kube-prometheus/README.md
- contrib/kube-prometheus/manifests/grafana-deployment.yaml
- Add instructions to the readme to make it quick to access the dashboards from the default quickstart manifest deployment
> Add dashboards to readme

- contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-thanos.libsonnet
This is distributed as a library that the user is meant to import.
example:
```
kp =  (import 'kube-prometheus/kube-prometheus.libsonnet') +
(import 'kube-prometheus/kube-prometheus-thanos.libsonnet') +
{
_config+:: {...}
};
```
> Add initial thanos support to kube-prometheus

- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml
- contrib/kube-prometheus/manifests/prometheus-rules.yaml
Hello,
this is a follow-up on PR #1938 (closed because I had to rewrite the history).
I ran jb update in contrib/kube-prometheus,
then make generate-in-docker in the root.
> contrib/kube-prometheus: Run jb update and generate all manifests.

- contrib/kube-prometheus/jsonnet/kube-prometheus/alerts/alertmanager.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/prometheus-rules.yaml
cc @brancz @sichvoge 
This commit removes the handwritten Alertmanager down alert since there is already an automatically generated `X down` alert for every job.
> remove duplicate alertmanager down alert

- contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-anti-affinity.libsonnet
- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet
This will set podAntiAffinity for Prometheus & Alertmanager signaling the kube scheduler to schedule pods on different nodes.
I've tested these updated mixins in my private cluster. Works great and as expected.
I'm kind of suprised we didn't had this. 😇 
Closes #1930 
/cc @brancz
> contrib/kube-prometheus: Set antiAffinity for Prometheus & Alertmanager

- example/thanos/querier-deployment.yaml
- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
- test/e2e/prometheus_test.go
This supersedes #1934, as I can't push to that branch.
The only change is reverting to using `tsdb.path` for the sidecar.
I've tested this branch running on my cluster and so far it seems good.
> pkg/prometheus: Update Thanos to 0.1.0

- README.md
As these docs are outdated, this patch removes the link in the
README.md.
> README.md: Remove to docs hosted on coreos.com

- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/prometheus-serviceMonitorApiserver.yaml
- contrib/kube-prometheus/manifests/prometheus-serviceMonitorKubeControllerManager.yaml
Recently, we received a bug report that the etcd dashboard shows clusters that aren't real clusters like apiserver and kube-controllers.
Screenshot: https://bugzilla.redhat.com/attachment.cgi?id=1485839
Bug Report: https://bugzilla.redhat.com/show_bug.cgi?id=1631926
Apparently some Kubernetes components expose the `etcd_server_has_leader` metric as well, as they are probably vendoring etcd as library which then registers these metrics.
You can take a look at all `etcd_` prefix metrics by running `kubectl proxy` in one terminal and then run `curl -s http://localhost:8001/metrics | grep etcd_` in another terminal.
This will eventually be fixed on the Kubernetes side with the metrics overhaul:
kubernetes/kubernetes#67476 (comment)
As a workaround, we propose to simply drop the …
> contrib/kube-prometheus: Drop etcd metrics by apiserver & kube controller

- contrib/kube-prometheus/README.md
With pinning the kube-prometheus dependency for the generated
`/manifest` folder, one needs to update the `jsonnetfile.lock.json` on
`*.jsonnet` file changes.
Originated from: https://github.com/coreos/prometheus-operator/pull/1983
> kube-prometheus/README.md:  Add jb update to contrib guide

- CHANGELOG.md
As @squat mentioned in https://github.com/coreos/prometheus-operator/pull/1995#discussion_r224437818 we should make it obvious that the `--namespace` flag changed to `--namespaces` and now takes a comma-separated list of namespaces as string.
/cc @squat @mxinden
> Changelog: Add note about changed namespaces flag in v0.24

- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/README.md
- contrib/kube-prometheus/jsonnet/kube-prometheus/jsonnetfile.json
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/0prometheus-operator-0alertmanagerCustomResourceDefinition.yaml
- contrib/kube-prometheus/manifests/0prometheus-operator-0prometheusCustomResourceDefinition.yaml
- contrib/kube-prometheus/manifests/0prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
- contrib/kube-prometheus/manifests/0prometheus-operator-0servicemonitorCustomResourceDefinition.yaml
- contrib/kube-prometheus/manifests/0prometheus-operator-clusterRole.yaml
- contrib/kube-prometheus/manifests/0prometheus-operator-deployment.yaml
After releasing the operator yesterday kube-prometheus also should use the new operator version.
/cc @squat
> contrib/kube-prometheus: Update to use prometheus-operator v0.24

- Documentation/api.md
- cmd/po-docgen/api.go
I've found that the pipe characters in `[0-9]+(ms|s|m|h|d|w|y)` as seen in markdown tables generated from types were actually parsed as column separators by Github's markdown parser.
This PR adds an escape function to po-docgen and uses it to escape pipe characters when generating a markdown table.
Ran `make generate` to rebuild the docs following this fix.
> Fix api docs not escaping pipe character in tables

- contrib/kube-prometheus/jsonnet/kube-prometheus/alerts/alertmanager.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/prometheus-rules.yaml
The problem was two folded as far as I can see:
`label_replace()` replaced a no longer existing label and has been updated. The `GROUP_LEFT()` failed because there were multiple time series with both `controller="alertmanager"` and `controller="promethus"`. I've therefore added the `controller="alertmanager"` matcher.
Fixes #2000
Simply update your kube-prometheus stack from master for this fix.
/cc @squat
> contrib/kube-prometheus: Fix AlertmanagerConfigInconsistent alert

- Documentation/network-policies.md
- example/networkpolicies/alertmanager.yaml
- example/networkpolicies/grafana.yaml
- example/networkpolicies/kube-state-metrics.yaml
- example/networkpolicies/node-exporter.yaml
- example/networkpolicies/prometheus.yaml
Kubernetes spec requires protocol to be capitalized, eg: `TCP` not `tcp`
Before:
```
Error from server (Invalid): error when creating "prometheus-network-policies.yaml": NetworkPolicy.extensions "alertmanager-web" is invalid: spec.ingress[0].ports[0].protocol: Unsupported value: "tcp": supported values: "TCP", "UDP"
Error from server (Invalid): error when creating "prometheus-network-policies.yaml": NetworkPolicy.extensions "alertmanager-mesh" is invalid: spec.ingress[0].ports[0].protocol: Unsupported value: "tcp": supported values: "TCP", "UDP"
Error from server (Invalid): error when creating "prometheus-network-policies.yaml": NetworkPolicy.extensions "grafana" is invalid: spec.ingress[0].ports[0].protocol: Unsupported value: "tcp": supported values: "TCP", "UDP"
Error from server …
```
> example: capitalise network policies protocol

- Makefile
- hack/generate-in-docker.sh
This PR attempts to fix an issue that arises when running `make generate-in-docker` on a host where SELinux is in `Enforcing` mode. The `:Z` mount option is needed so docker labels the files appropriately to allow the container to write to the volume.
Using this flag comes with a notable warning as seen here: https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label
> If you use selinux you can add the z or Z options to modify the selinux label of the host file or directory being mounted into the container. This affects the file or directory on the host machine itself and can have consequences outside of the scope of Docker.
Moving the generate-in-docker command outside of Makefile into it's own script in `hack/` allows for more flexibility in detecting SElinux.
I have …
> Fix generate-in-docker when selinux is in enforcing mode on host

- contrib/kube-prometheus/README.md
- contrib/kube-prometheus/examples/internal-registry.jsonnet
- contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-config-mixins.libsonnet
- contrib/kube-prometheus/jsonnet/kube-prometheus/lib/image.libsonnet
- contrib/kube-prometheus/jsonnet/kube-prometheus/lib/lib.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/sync-to-internal-registry.jsonnet
- jsonnet/prometheus-operator/prometheus-operator.libsonnet
Some people have Kubernetes deployments in restricted environments without internet access and need to source images from internal repositories.
This PR introduced such support in kube-prometheus:
- A jsonnet script to output docker pull/tag/push commands to synchronize upstream images used by kube-prometheus to an internal registry.
- A mixin to mutate `_config.imageRepos` to point images at that internal registry.
- Document those two points above.
> kube-prometheus: support Kubernetes installs sourcing all images from an internal repository

- contrib/kube-prometheus/jsonnetfile.lock.json
kube-prometheus now contains a script, sync-to-internal-registry.jsonnet, that
depends on commit 8c6a68760010347134e41f3aa3d73c68eb094a1b to work. Bump the prometheus-operator hash accordingly.
EDIT: removed the kube-prometheus bump and amended the commit, because it was actually a downgrade, not a bump.
> contrib/kube-prometheus: Bump the prometheus-operator jsonnet dep

- contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-thanos.libsonnet
If this Service is in the wrong namespace none of the peers are able to find each other.
> contrib/kube-prometheus: thanos-peers service misses namespace

- pkg/alertmanager/statefulset.go
- pkg/k8sutil/k8sutil.go
- pkg/prometheus/statefulset.go
When creating the `Service` for a `Prometheus`/`Alertmanager` instance, the Operator will now correctly update `metadata.ownerReferences`.
Resolves #1945
> Set Owner References on Created Services

- contrib/kube-prometheus/jsonnet/kube-prometheus/alerts/alertmanager.libsonnet
- contrib/kube-prometheus/jsonnet/kube-prometheus/alerts/tests.yaml
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/prometheus-rules.yaml
If the Alertmanager peers have a partition within one cluster we'd like to alert on that fact.
This rule will compare the reported number of members by each peer against the total number (count) of peers in the cluster.
/cc @mxinden
> Add AlertmanagerMembersInconsistent alerting rule

- contrib/kube-prometheus/docs/exposing-prometheus-alertmanager-grafana-ingress.md
- contrib/kube-prometheus/examples/ingress.jsonnet
It took me a bit of searching to find that `externalURL` is set in the `prometheus` object/kind spec.
Per the comment below have added the suggested merge into the example ingress.
https://github.com/coreos/prometheus-operator/pull/1838#issuecomment-417747427
One could then duplicate the whole lot for alertmanager. I can add Alertmanager to PR if not too verbose?
> kube-prometheus: Example jsonnet ingress, add externalURL

- README.md
We often get users, that first install the bundle and then helm or the jsonnet based kube-prometheus stack, which collides with the quickstart bundle (eg. https://github.com/coreos/prometheus-operator/issues/2084). Therefore clarifying here.
@mxinden @squat @metalmatze @s-urbaniak
> README.md: Clarify quickstart vs. kube-prometheus

- contrib/kube-prometheus/README.md
- contrib/kube-prometheus/examples/jsonnet-snippets/kubespray.jsonnet
- contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-kubespray.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
Add config files and documentation for Kubespray clusters.
The discovery services are almost the same as the kubeadm ones, the only change is the selector's name. Maybe someone jsonnet fluent could factor them?
> Add support for Kubespray clusters

- Documentation/design.md
We want to at least mention Thanos in our docs so we can point people to that documentation when questions arise.
/cc @sichvoge @brancz
> Documentation: Add Thanos section on current state

- Documentation/compatibility.md
- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/examples/minikube.jsonnet
- contrib/kube-prometheus/examples/prometheus-pvc.jsonnet
- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/prometheus-prometheus.yaml
- contrib/kube-prometheus/sync-to-internal-registry.jsonnet
- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
This will set Prometheus v2.5.0 as default version for Prometheus in the kube-prometheus stack.
> *: Update to Proemtheus v2.5.0 as default

- cmd/operator/main.go
- pkg/alertmanager/operator.go
- pkg/alertmanager/statefulset.go
- pkg/prometheus/operator.go
- pkg/prometheus/statefulset.go
This was previously a very poor attempt at achieving something similar to what PodSecurityPolicies are for, therefore I am removing this code. There are no compatibility issues, as for any supported volume types, the kubelet sets the ownership recursively for all files of a volume before mounting.
Fixes #2102
@mxinden @metalmatze @squat @s-urbaniak '
/cc @ctron
> *: Remove attempting to set "secure" security context

- contrib/kube-prometheus/README.md
- contrib/kube-prometheus/docs/developing-prometheus-rules-and-grafana-dashboards.md
- contrib/kube-prometheus/example.jsonnet
- contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus.libsonnet
- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus-adapter/prometheus-adapter.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/prometheus-adapter-apiService.yaml
- contrib/kube-prometheus/manifests/prometheus-adapter-clusterRole.yaml
- contrib/kube-prometheus/manifests/prometheus-adapter-clusterRoleBinding.yaml
- contrib/kube-prometheus/manifests/prometheus-adapter-clusterRoleBindingDelegator.yaml
- contrib/kube-prometheus/manifests/prometheus-adapter-clusterRoleServerResources.yaml
- contrib/kube-prometheus/manifests/prometheus-adapter-configMap.yaml
- contrib/kube-prometheus/manifests/prometheus-adapter-deployment.yaml
- contrib/kube-prometheus/manifests/prometheus-adapter-roleBindingAuthReader.yaml
- contrib/kube-prometheus/manifests/prometheus-adapter-service.yaml
- contrib/kube-prometheus/manifests/prometheus-adapter-serviceAccount.yaml
kube-prometheus already scrapes cAdvisor and knows all the metrics necessary for the metrics.k8s.io API.
The Prometheus Adapter implements this interface and forwards the request from Kubernetes to Prometheus while translating to PromQL.
This is still WIP:
1. The container image used in this deployment is not yet available and needs to be locally build
2. Before deploying this, the `gencerts.sh` inside `experimental/custom-metrics-api` needs to be run. We should probably integrate this into the Prometheus Adapter.
/cc @brancz @s-urbaniak
> contrib/kube-prometheus: Add Prometheus Adapter to stack

- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus-adapter/prometheus-adapter.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/prometheus-adapter-deployment.yaml
This will make sure that there's always a /tmp in the container.
Related to https://github.com/coreos/prometheus-operator/issues/2116.
/cc @s-urbaniak @brancz
> contrib/kube-prometheus: Mount tmpfs to /tmp in Prometheus Adapter

- hack/generate/build-rbac-prometheus-operator.sh
This commit simplifies the build-rbac-... script
to directly loop over the output of `jq` rather than build a
bash-specific array variable using `mapfile`.
xref: https://github.com/openshift/cluster-monitoring-operator/pull/150
cc @metalmatze
> hack/generate: simplify jsonnet build loop

- contrib/kube-prometheus/README.md
Currently there is no documentation on the Pod Anti-Affinity mixin which makes it
difficult to find. To address this, this PR adds a section to the README on how one
can use it.
> kube-prometheus: Add documentaton to README on the Pod Anti-Affinity mixin

- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/jsonnet/kube-prometheus/node-exporter/node-exporter.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/node-exporter-daemonset.yaml
This commit adjusts the RBAC proxy for the node-exporter DaemonSet to
only listen on the Pod IP. It also adjusts the ports used by the
node-exporter Pod so that both containers are listening on 9100. The
actual node-exporter listens on 127.0.0.1:9100, while the RBAC proxy
listens on <PODIP>:9100. This ensures that port 9101 is not taken on
the host networking namespace.
cc @brancz @s-urbaniak re: our conversation from earlier in the day.
I think that putting the node-exporter on hostPort 9100 and exposing
the RBAC proxy on the containerPort 9100 is a better option than
taking up another port for the proxy. With this new configuration, the
proxy listens on the Pod IP (i.e. the node's IP since we are on host network)
and the node exporter listen's on the node's localhost. The service NATs …
> node-exporter RBAC proxy listen on Pod IP

- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus-adapter/prometheus-adapter.libsonnet
It should be easier to configure the Prometheus Adapater's prometheusURL from jsonnet. Hence, we move the prometheusURL into the _config and reference it as argument in the Deployment.
As this is a nop for the manifests themselves, nothing needs to be generated.
/cc @s-urbaniak @brancz
> contrib/kube-prometheus: Add prometheusURL to adapter's jsonnet config

- Documentation/rbac-crd.md
- example/rbac/prometheus-operator-crd/prometheus-operator-crd-cluster-roles.yaml
The cluster role is broken. The items in the list must be quoted individually.
See https://kubernetes.slack.com/archives/C09NXKJKA/p1543244788508000.
> Fix broken cluster role

- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet
Got the following error when calling jsonnet:
```
vendor/kube-prometheus/prometheus/prometheus.libsonnet:43:44-47 Expected token then but got (IDENTIFIER, "and")
[if $._config.prometheus.rules != null and $._config.prometheus.rules != {} then "rules"]:
```
Changing `and` to `&&` fixes that.
> fix syntax error in prometheus.libsonnet

- contrib/kube-prometheus/docs/exposing-prometheus-alertmanager-grafana-ingress.md
the operator spec key is named "externalUrl", rather than "externalURL"
> fix breaking typo

- Makefile
Remove GOARCH=amd64 to prevent cross-compiling go binaries for multi-arch container builds.
@brancz
> Remove GOARCH=amd64 to prevent cross-compiling go binaries

- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/jsonnet/kube-prometheus/kube-state-metrics/kube-state-metrics.libsonnet
- contrib/kube-prometheus/jsonnet/kube-prometheus/node-exporter/node-exporter.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/kube-state-metrics-deployment.yaml
- contrib/kube-prometheus/manifests/node-exporter-daemonset.yaml
- pkg/alertmanager/statefulset.go
- pkg/prometheus/statefulset.go
As kube-prometheus depends on the [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) and that ships with the _CPUThrottlingHigh_ alert we should at least increase the CPU limits for our small container sidecars.
I've measured these proposed values in my personal cluster and they do not get throttled more than 50% for more than 15min anymore and are therefore less noisy, but are still within some decent limit margin.
/cc @brancz @mxinden 
Note: I yet need to create the updated `jsonnetfile.lock.json` with re-generated manifest. But I'll do that once we have decided on the values.
> Increase CPU limits for small containers to not being throttled as often

- Makefile
- pkg/listwatch/listwatch.go
- pkg/listwatch/listwatch_test.go
Currently, listwatch is racy, as revealed by the following error, when
running in k8s:
```
W1128 16:49:11.288643       1 reflector.go:270] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:403: watch of *v1.ConfigMap ended with: too old resource version: 14464 (19288)
panic: send on closed channel
goroutine 1373 [running]:
github.com/coreos/prometheus-operator/pkg/listwatch.newMultiWatch.func1(0x17f1c00, 0xc00084cab0, 0xc0002bbce0)
/home/sur/go/src/github.com/coreos/prometheus-operator/pkg/listwatch/listwatch.go:181 +0x4f
created by github.com/coreos/prometheus-operator/pkg/listwatch.newMultiWatch
/home/sur/go/src/github.com/coreos/prometheus-operator/pkg/listwatch/listwatch.go:175 +0x298
```
This fixes it by ensuring that the event sender channel is closed,
once all sender …
> pkg/listwatch: fix racy multiwatch

- contrib/kube-prometheus/examples/ingress.jsonnet
Per: https://github.com/coreos/prometheus-operator/pull/2172
> kube-prometheus: Fix ExternalUrl key typo in ingress example

- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/jsonnet/kube-prometheus/alertmanager/alertmanager.libsonnet
- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/alertmanager-alertmanager.yaml
- contrib/kube-prometheus/manifests/prometheus-prometheus.yaml
As #2109 removed setting the securityContext in the reconciliation loop of the operator and this broke quite a few people we want to set this as default in the manifests again.
/cc @brancz @squat
> Set the securityContext for Prometheus and Alertmanager in manifests

- contrib/kube-prometheus/jsonnet/kube-prometheus/kube-state-metrics/kube-state-metrics.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/kube-state-metrics-clusterRole.yaml
With https://github.com/kubernetes/kube-state-metrics/commit/40f293dbde2f69ad0b5ae5875e2f19fed0b749e5 kube-state-metrics exposes metrics about poddisruptionbudgets. Hence kube-state-metrics needs the permissions to collect those metrics via its cluster role.
Thanks @metalmatze for the hint!
> kube-prometheus: Add poddisruptionbudgets to ksm cluster role 

- pkg/prometheus/operator.go
- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
With the discussion happening in #2221 we stumbled upon the fact that we already create the Prometheus StatefulSet with `podManagementPolicy: Parallel`. However, we never see this being applied with the StatefulSets themselves and the Pods are managed with `OrderedReady`.
As it turns out we pass in an empty string to `makeStatefulSet` so that the StatefulSet doesn't contain this key value pair in the applied struct. Kubernetes defaults to `OrderedReady`.
https://github.com/coreos/prometheus-operator/compare/master...metalmatze:prometheus-parallel-pod-management?expand=1#diff-94707ea811ea06be1af9eb4049a2e13bL1018
@squat and I can't find a reason anymore why we should pass this down and now always set `podManagementPolicy: Parallel`. The StatefulSet can't be updated with this field anyway …
> pkg/prometheus: Do not pass podManagementPolicy and stick with Parallel

- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet
Presently `jobLabel` is missing from to the ServiceMonitor for CoreDNS. This results in a prometheus job name matching the name of the selected service, for example `kube-dns-prometheus-discovery` with [kube-prometheus-kops](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-kops.libsonnet#L17:L21).
The result is that the CoreDNS absent AlertRule does not work out of the box, because it is matching a jobLabel of `kube-dns`. 
Had to hunt down how this works, the Absent alerts are dynamically generated from [monitoring-mixins/alerts/absent_alerts.libsonnet](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/alerts/absent_alerts.libsonnet), which iterates through `_config.jobs`.
A manual workaround is …
> contrib/kube-prometheus: Add jobLabel to ServiceMonitorCoreDNS

- cmd/prometheus-config-reloader/Dockerfile
For kubernetes clusters which do not allow running images as root user this is required. 
For all others it does not hurt though.
> Use nobody

- cmd/lint/main.go
For now this is a standalone binary that I simply use by running `go run ./cmd/lint prometheus.yaml`.
It will then log errors if the YAML (that is first converted to JSON so that we can use `decoder.
DisallowUnknownFields()`) find something that is wrong.
Example:
```
$ go run ./cmd/lint contrib/kube-prometheus/manifests/prometheus-prometheus.yaml                                                                                                  
2019/01/08 12:40:18 prometheus is invalid: json: unknown field "nodeSelectors"
exit status 1
```
It should help us debug and identify typos and other mistakes more quickly.
We can also integrate the functionality some other place, but I also like the standalone binary.
/cc @brancz @s-urbaniak  @squat
> Lint YAML against our CRD defintions

- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet
This PR adds SessionAffinity ClusterIP to the prometheus service to prevent grafana from querying different instances when loading/updating metrics.
> Add SessionAffinity ClusterIP to prometheus service

- Gopkg.toml
'github.com/ericchiang/k8s' is not used anywhere, so the override is not
needed.
> Gopkg.toml: Remove unnecessary override

- contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus.libsonnet
- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus-adapter/prometheus-adapter.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/grafana-deployment.yaml
- contrib/kube-prometheus/manifests/grafana-service.yaml
- contrib/kube-prometheus/manifests/prometheus-adapter-deployment.yaml
- contrib/kube-prometheus/manifests/prometheus-service.yaml
This prevented the grafana service from being applied to a cluster as `labels` was not in metadata.
@metalmatze @squat @s-urbaniak @mxinden
> Fix grafana label

- contrib/kube-prometheus/README.md
- contrib/kube-prometheus/examples/jsonnet-snippets/kops-coredns.jsonnet
- contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-kops-coredns.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
This adds a mixin to fix the metrics ingestion for CoreDNS on kops.
The [`kubeDnsPrometheusDiscoveryService`](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-kops.libsonnet#L17:L21) from the `kube-prometheus-kops` mixin is optionally overridden to replace the kube-dns ports with the correct ones for CoreDNS metrics.
CoreDNS uses port `metrics: 9153` to expose prometheus metrics. 
kube-dns used `'http-metrics-skydns: 10055` and `http-metrics-dnsmasq: 10054`. 
With #2233 now merged this should make the `CoreDNSDown` alert work out of the box on kops + CoreDNS.
It's not entirely clear to me if the kube-dns metrics ingestion on kops is working out of the box. If not, perhaps this change can be made the default and the …
> contrib/kube-prometheus: Add kops CoreDNS prometheus discovery service

- contrib/kube-prometheus/README.md
- contrib/kube-prometheus/jsonnet/kube-prometheus/node-exporter/node-exporter.libsonnet
We have a conflict on port 9100 so we must change the port which node exporter runs on. I've not used jsonnet before so there is a good change I've done something silly but this seems to wfm.
> kube-prometheus: Added ability to configure nodeExporter port

- contrib/kube-prometheus/jsonnet/kube-prometheus/node-exporter/node-exporter.libsonnet
Seeing this error on all the node_exporter pods after updating kube-prometheus:
`node_exporter: error: unknown long flag '--path.rootfs', try --help`
https://github.com/coreos/prometheus-operator/pull/2285 added `--path.rootfs=/host/root` to the nodeExporter args, however the nodeExporter default version is `v0.16.0` which doesn't support this flag. 
Support for `--path.rootfs` was added in node exporter v0.17.0 https://github.com/prometheus/node_exporter/pull/1058.
> Fix node exporter crash looping

- contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-thanos.libsonnet
This will add the [Thanos compactor](https://github.com/improbable-eng/thanos/blob/master/docs/components/compact.md) as a StatefulSet next to the other components. The Thanos compactor exposes metrics on port `10902` but the other ports for gossip etc are not needed.
It would be good to somehow limit the number of replicas this StatefulSet can run to exactly 0 or 1.
Even if the user wants to `kubectl scale statefulset thanos-compactor --replicas 2` it should fail, as the can be at most one compactor running per object storage.
Any ideas on how to achieve this?
/cc @brancz @squat @s-urbaniak @mxinden @bwplotka
> contrib/kube-prometheus: Add Thanos compactor as StatefulSet

- pkg/prometheus/promcfg.go
I've tried my hand at the go workflow and applied the fix outlined by @ViniciusSouza in https://github.com/coreos/prometheus-operator/issues/2218#issuecomment-449349056
Fixes #2218
> Fix for omitting source_labels where they are unnecessary

- Documentation/rbac.md
- Documentation/user-guides/getting-started.md
- bundle.yaml
- example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
- jsonnet/prometheus-operator/prometheus-operator.libsonnet
This commit adds the delete verb to the services rule of the prometheus
operator role. It also gives the prometheus operator the power to get,
delete, create, and update the finalizers subresource of services.
fixes: https://github.com/coreos/prometheus-operator/issues/2279
cc @brancz @metalmatze
> jsonnet/prometheus-operator: delete services 

- README.md
As we now have a dedicated channel on Kubernetes Slack, why not link to it from the README?
> Add README badge for Slack channel

- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml
- contrib/kube-prometheus/manifests/prometheus-rules.yaml
This fixed the CPUThrottlingHigh which would trigger two alerts for just one container in some cases:
See https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/137
/cc @squat @brancz @mxinden
> contrib/kube-prometheus: Update kubernetes mixin for fixed CPUThrottlingHigh

- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
This commit guards against a nil pointer dereference caused when an
Endpoint's port is 0 and the targetPort is nil.
Fixes: https://github.com/coreos/prometheus-operator/issues/2156
cc @brancz @metalmatze
> pkg/prometheus: guard against nil targetPort

- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet
Manifest generation fails if this option is not set. Instead, remove the
option and require users to patch the object in case they need it.
See https://github.com/coreos/prometheus-operator/pull/2300#issuecomment-456113717 for more details.
> kube-prometheus: Remove enableAdminAPI configuration option

- contrib/kube-prometheus/README.md
Resources can be created _and_ updated with `apply` without receiving errors
> Use kubectl apply instead of create

- test/e2e/alertmanager_test.go
- test/e2e/main_test.go
- test/e2e/prometheus_test.go
- test/framework/alertmanager.go
- test/framework/helpers.go
- test/framework/namespace.go
We want to know a bit more about the internal error that occurred while waiting for the Alertmanager mesh to get ready.
While working on this change, I also saw several calls to `Core()` which is deprecated and updated these.
/cc @mxinden
> test: Return pollError when waiting for Alertmanager mesh

- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/prometheus-roleSpecificNamespaces.yaml
This commit removes get/list/watch on nodes for the Prometheus-k8s
instance, as Prometheus pods do not need that privilege for anything.
cc @brancz @metalmatze @mxinden
>  contrib/kube-prometheus: remove node role

- Documentation/rbac-crd.md
- example/rbac/prometheus-operator-crd/prometheus-operator-crd-cluster-roles.yaml
In case the `view` is not aggregated to `admin`, you would need to grant a user both `admin` and `view` roles on the same namespace to be able to edit and get the resources respectively. This means that an `admin` on the namespace would be able to `create` the resource object, but not `get` it. 
This change aggregates the view to the admin role, so that the admin can now `get` on the resource as well.
> Aggregate prometheus-crd-view role to admin

- contrib/kube-prometheus/experimental/custom-metrics-api/README.md
- contrib/kube-prometheus/experimental/custom-metrics-api/deploy.sh
- contrib/kube-prometheus/experimental/custom-metrics-api/teardown.sh
- Adding -f flag at the deploy.sh script to fit with new kubectl versions
- removing namespace flag when port-forwarding the sample-app service
> custom metrics API quick fix

- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/prometheus-rules.yaml
- contrib/kube-prometheus/manifests/prometheus-serviceMonitorApiserver.yaml
- contrib/kube-prometheus/manifests/prometheus-serviceMonitorKubelet.yaml
As described in https://github.com/google/cadvisor/issues/1925, the container network metrics are disabled and therefore cause more confusion than gain as they are always set to 0. This PR removes those at ingestion time, and also drops unnecessary high cardinality metrics from the Kubernetes API.
@metalmatze @mxinden @squat @s-urbaniak
> Reduce metrics

- test/framework/alertmanager.go
For debugging flakes on Travis we want to print the addresses of mesh peers on error:
Example flake:
https://travis-ci.org/coreos/prometheus-operator/jobs/484394692#L1121-L1124
Replacing https://github.com/coreos/prometheus-operator/pull/2341
>  test/framework: Improve WaitForAlertmanagerInitializedMesh debugging

- README.md
Unable to redeploy a clean version without this fix as `prometheusrules.monitoring.coreos.com` still exists.
> docs: add prometheusrules CRD to cleanup steps

- cmd/operator/main.go
- pkg/alertmanager/operator.go
- pkg/alertmanager/statefulset.go
- pkg/alertmanager/statefulset_test.go
- pkg/prometheus/operator.go
- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
Fix: https://github.com/coreos/prometheus-operator/issues/2364
Following the conversation in https://github.com/coreos/prometheus-operator/pull/2371
> fix: config reloader memory and cpu as params

- cmd/operator/main.go
- pkg/alertmanager/statefulset_test.go
- pkg/prometheus/statefulset_test.go
Running in a test cluster with docker 1.09.2 shows max memory to be about 17Mi, and the container starts ok with a limit of 20Mi. But increase this to 25Mi to be sure
fixes: #2409
> Increase memory to 25Mi for reloader

- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus-adapter/prometheus-adapter.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml
- contrib/kube-prometheus/manifests/prometheus-adapter-apiService.yaml
- contrib/kube-prometheus/manifests/prometheus-adapter-clusterRoleBinding.yaml
`APIRegistration` went v1 in Kubernetes v1.10. Upgrading seems safe.
Also:
- remove unnecessary namespace from prometheus-adapter ClusterRoleBinding
- update Grafana dashboardDefinitions (side effect of `jb update`)
Signed-off-by: Michael Goodness <mike.goodness@ticketmaster.com>
> Upgrade prometheus-adapter APIService to v1

- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/jsonnet/kube-prometheus/node-exporter/node-exporter.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/node-exporter-daemonset.yaml
Node-exporter should be running on any linux node, no exception.
@mxinden @s-urbaniak 
cc @sichvoge
> node-exporter tolerate any taint

- Documentation/rbac.md
- Documentation/user-guides/getting-started.md
- bundle.yaml
- example/non-rbac/prometheus-operator.yaml
- example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
- example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
- example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
- example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
- jsonnet/prometheus-operator/prometheus-operator.libsonnet
- test/e2e/main_test.go
This adds a common `app.kubernetes.io/name: prometheus-operator` label to all resources, as [recommended](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) by SIG-Apps.
It also replaces the `k8s-app` label used in the Deployment and Service. That's a potentially disruptive change, since a Deployment's `spec.selector` is immutable. If prometheus-operator is already deployed, it will have to be deleted first.
Not sure how to get new `0prometheus-operator` manifests generated for kube-prometheus.
> Operator labels

- Documentation/user-guides/getting-started.md
- bundle.yaml
- example/non-rbac/prometheus-operator.yaml
- example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
- jsonnet/prometheus-operator/prometheus-operator.libsonnet
#2427 introduced a bug to the prometheus-operator Deployment. Including the version in the selector will result in an orphaned ReplicaSet when the version is changed. This separates labels into two objects, leaving `apps.kubernetes.io/version` out of the one used by the selector.
> Fix operator selector

- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus-adapter/prometheus-adapter.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/prometheus-adapter-configMap.yaml
This pull request configures the Prometheus adapter for the resource metrics API to be consistent with what is displayed in the "Kubernetes / USE Method / Node" dashboard.
https://bugzilla.redhat.com/show_bug.cgi?id=1656868
@mxinden @s-urbaniak
> Consistent metrics usage in adapter and dashboards

- contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-thanos.libsonnet
As per https://github.com/improbable-eng/thanos/issues/601
We need to enable the `'--query.auto-downsampling'` flag
So that grafana can browse data beyond the Raw Data period of prometheus/sidecar
Dashboard showing 70d data of prometheus and alertmanager config-reloads
> Allow browsing of downsampled thanos data in Grafana

- pkg/prometheus/operator.go
- pkg/prometheus/rules.go
- pkg/prometheus/statefulset.go
Currently, we are watching all configmaps amongst all configured tenant namespaces. This is very costly in certain deployment use cases where we have:
a) many namespace tenants
b) kubernetes controllers running in those namespace doing leader election using k8s intrinsics
Here, we can observe quite a high CPU usage of the prometheus operator of up to 15% CPU "idle" usage:
A profile revealed most CPU time spent in the reconciliation loop:
```
(pprof) top10 -cum
Showing nodes accounting for 0.03s, 0.32% of 9.33s total
Dropped 359 nodes (cum <= 0.05s)
Showing top 10 nodes out of 271
flat  flat%   sum%        cum   cum%
0     0%     0%      6.11s 65.49%  github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).processNextWorkItem
0     0%     0%      6.11s 65.49% …
```
> pkg/prometheus: watch configmaps having the prometheus-name selector

- Documentation/user-guides/cluster-monitoring.md
The kube-scheduler and kube-cluster-manager are not visible from a managed EKS cluster.  They are likely run inside the managed control plane as a black box.  This means you cannot use Prometheus to scrape these components and must rely on your cloud provider for metrics.
> Document components that can't be scraped on EKS

- contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-managed-cluster.jsonnet
Per: https://github.com/coreos/prometheus-operator/issues/2437#issuecomment-470027546
Thanks to @brancz for sharing the snippet originally. Any breakages mine :)
A patch/snippet to exclude monitoring of components that are commonly unavailable in managed clusters.
Prometheus targets page does not show Scheduler and Controller targets.
Alerts don't fire for Scheduler or Controller but rules are still generated by kube-prometheus (added todo).
Have been using the jobs snippet in our clusters for some time.
Service Monitor section is new, seems to generate correct json/yaml and be working in an existing Prometheus cluster (applied over top, not from fresh).
> contrib/kube-prometheus: Jsonnet snippet for managed kubernetes clusters

- contrib/kube-prometheus/jsonnet/kube-prometheus/alerts/prometheus.libsonnet
* `tsdb_wal_corruptions_total metric` name should be `prometheus_tsdb_wal_corruptions_total`
> Fix PrometheusTSDBWALCorruptions alert

- contrib/kube-prometheus/README.md
I noticed this when reading the docs: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#error-retrieving-kubelet-metrics
> contrib/kube-prometheus: fix GKE cAdvisor readme link

- contrib/kube-prometheus/jsonnet/kube-prometheus/kube-prometheus-kops.libsonnet
This fixes metrics for kops installations using kube-dns. 
kube-dns-prometheus-discovery was updated to `metrics:10055` from `http-metrics-skydns:10055`. 
The CoreDNS ServiceMonitor for kops expects `metrics:10055`.
> contrib/kube-prometheus: Fix metrics for kops installations using kube-dns

- README.md
Add a note about differences between kubernetes-operator and
kube-prometheus, explain differences in release archives and versioning.
Fixes #2510
> docs: add differences between operator and kube-prometheus

- .travis.yml
- Makefile
- contrib/kube-prometheus/Makefile
- contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml
- contrib/kube-prometheus/tests/e2e/travis-e2e.sh
- hack/generate-in-docker.sh
- scripts/create-minikube.sh
- scripts/jsonnet/Dockerfile
- scripts/travis-e2e.sh
Attempt to update travis scripts to use latest versions of minikube (v0.35.0), kubernetes (v1.13.4) and jsonnet (v0.12.1). 
* `dist: xenial` is required for the default minikube bootstrapper (kubeadm) as it depends on systemd
* bump go to latest `1.11.x`
* enable caching of go build cache to speed up builds
* enable go build cache when running `po-jsonnet` container
* remove redundant `kube-dns` check from e2e scripts
* `create_minikube.sh`: use minikube config to set defaults, add `kube-addon-manager` check
* `Dockerfile`: use latest jsonnet `v0.12.1`, replace wget with curl
> Update travis to latest minikube, k8s, jsonnet

- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml
- contrib/kube-prometheus/manifests/prometheus-rules.yaml
Resolves https://github.com/coreos/prometheus-operator/issues/2525
This is a re-generation of jsonnet for kubernetes-mixin.
Let me know if this have not generated correctly. I found that running `jb update` updated all jsonnet deps (which is a lot of changes not related to this fix). I minimized this by only updating the jsonnetlock file dep.  for kubernetes-mixin and running `jb install` instead.
> Fix node:node_disk_saturation rules to return value in seconds

- .travis.yml
This doesn't change anything for us. It just eases enabling CI on forked repositories.
> specify go import path in CI

- Documentation/user-guides/cluster-monitoring.md
- contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet
- contrib/kube-prometheus/jsonnetfile.lock.json
- contrib/kube-prometheus/manifests/prometheus-serviceMonitorKubelet.yaml
These metrics can still be valuable to troubleshoot components running in cgroups on the host, outside the scope of Kubernetes pods. Previously we were dropping these (somewhat intentionally), but it turns out that was a bit too aggressive.
https://bugzilla.redhat.com/show_bug.cgi?id=1694766
@metalmatze @squat @s-urbaniak @mxinden @paulfantom
> Fix non container metrics

- pkg/alertmanager/statefulset.go
- test/e2e/alertmanager_test.go
> ## 0.16.2 / 2019-04-03
> 
> Updating to v0.16.2 is recommended for all users using the Slack, Pagerduty,
> Hipchat, Wechat, VictorOps and Pushover notifier, as connection errors could
> leak secrets embedded in the notifier's URL to stdout.
> 
> * [BUGFIX] Redact notifier URL from logs to not leak secrets embedded in the URL (#1822, #1825)
> * [BUGFIX] Allow sending of unauthenticated SMTP requests when `smtp_auth_username` is not supplied (#1739)
https://github.com/prometheus/alertmanager/releases/tag/v0.16.2
>  pkg/alertmanager: Update to v0.16.2 

- cmd/operator/main.go
- pkg/alertmanager/statefulset.go
- pkg/alertmanager/statefulset_test.go
- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
This PR introduces the ability to fully disable limits on the sidecar containers next to Prometheus and Alertmanager.
@mxinden @squat @s-urbaniak @metalmatze @paulfantom
> *: Allow disabling limits on sidecars

- pkg/alertmanager/statefulset.go
- test/e2e/alertmanager_test.go
See https://github.com/prometheus/alertmanager/releases/tag/v0.17.0 for
release docs.
> pkg/alertmanager: Update to Alertmanager v0.17.0

- Documentation/network-policies.md
- Documentation/user-guides/getting-started.md
- example/networkpolicies/alertmanager.yaml
- example/networkpolicies/grafana.yaml
- example/networkpolicies/kube-state-metrics.yaml
- example/networkpolicies/node-exporter.yaml
- example/networkpolicies/prometheus.yaml
- example/user-guides/getting-started/example-app-deployment.yaml
- test/framework/ressources/basic-auth-app-deployment.yaml
Next to StatefulSet and Deployment API groups, we should also update all deprecated API groups in the examples and Documentation.
Closes #2592
/cc @s-urbaniak @mxinden @paulfantom @brancz
> Update API groups in examples and Documentation

- bundle.yaml
- example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
- example/rbac/prometheus-operator/prometheus-operator-service.yaml
- hack/generate/prometheus-operator-rbac.jsonnet
Background:
Currently, the Service and ServiceMonitor for the Prometheus Operator are not added to the generated bundle.yaml. 
The issue with the Service and ServiceMonitor not being bundled is seen when a cluster has multiple namespaces with the prometheus-operator pods running, and you'd have to manually create a Service in front of each of the operator pods.
Changes in this PR:
- Add the Service and ServiceMonitor object already present in the jsonnet to the bundle
> Add prometheus-operator Service and Servicemonitor to Bundle

- bundle.yaml
- hack/generate-bundle.sh
Users installing the bundle.yaml most likely do not yet have the
ServiceMonitor CRD available in their cluster, therefore having this
object in the bundle.yaml would break them.
/cc @brancz @aditya-konarde
> Ignore ServiceMonitor in bundle.yaml

- cmd/prometheus-config-reloader/main.go
- cmd/prometheus-config-reloader/main_test.go
This PR introduces a new `STATEFULSET_ORDINAL_NUMBER` environment variable in the prometheus config reloader, by regexing the numbers from the end of  `POD_NAME`. This allows a prometheus configuration with
```
externalLabels:
prometheus_replica: $(STATEFULSET_ORDINAL_NUMBER)
```
The motivation for this is our current setup:
- Multiple prometheuses running in the same cluster, deployed into the same namespace
- All write to the same long-term storage database
- Remote-read from the database is used to execute rules, pulling data from multiple prometheuses, but requiring distinction between the replicas
> Config reloader pod ordinal number

- Documentation/rbac.md
- Documentation/user-guides/getting-started.md
- bundle.yaml
- example/non-rbac/prometheus-operator.yaml
- example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
- example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
- example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
- example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
- example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
- example/rbac/prometheus-operator/prometheus-operator-service.yaml
- jsonnet/prometheus-operator/prometheus-operator.libsonnet
- test/e2e/main_test.go
Per https://github.com/coreos/prometheus-operator/pull/2427#issuecomment-491923629, this fixes the SIG Apps [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) from `apps.kubernetes.io/...` to `app.kubernetes.io/...` (app is singular).
It also updates the `app.kubernetes.io/version` label to `v0.30.0` in the places it was still `v0.29.0`.
It might should be noted that changing selectors requires recreating Deployments.
> *: fix sig-apps recommended labels

- scripts/jsonnet/Dockerfile
- download go-bindata to temporarily satisfy openshift/cmo CI requirements
- add `/.cache` to allow installations with `go get` when `GOPATH` is set to other directory than `/go`.
This unblocks CI in openshift/telemeter and openshift/cluster-monitoring-operator.
/cc: @brancz @s-urbaniak
> scripts/jsonnet: add go-bindata to satisfy openshift/cmo

- cmd/operator/main.go
- pkg/prometheus/operator.go
It is often convenient to limit operator to particular Prometheus objects, comes handy in testing or in some namespace specific situations, where "local" Prometheus runs alongside cluster-wide Prometheus.
This adds `--prometheus-instance-selector` switch with a syntax same as `kubectl get -l`.
> Prometheus selector CLI switch

- scripts/jsonnet/Dockerfile
- Update jsonnet to 0.13.0
- Use only jsonnetfmt from google/jsonnet (C++ version)
- use go version of jsonnet as it is ~3x faster than C++ version.
Speed test for 0.13.0 (generating files in openshift/cluster-monitoring-operator repo):
C++ version:
```
real    0m25.563s
user    0m25.107s
sys     0m0.590s
```
Go version:
```
real    0m7.763s
user    0m9.052s
sys     0m0.558s
```
/cc: @brancz @metalmatze @s-urbaniak @squat
> update jsonnet container to use go-jsonnet and jsonnetfmt

- scripts/jsonnet/Dockerfile
Enable go modules to allow using path@version notation in `go get ...`
Tested locally as this is not tested in CI.
Follow-up to #2625
/cc @brancz @s-urbaniak
> scripts/jsonnet: enable path@version notation in go get

- scripts/jsonnet/Dockerfile
Use go modules only when downloading go-jsonnet. Otherwise this will fail when downloading other go binaries.
Follow-up to #2626 
Output when running locally:
```
$ docker build -t jsonnet-ci -f scripts/jsonnet/Dockerfile .
Sending build context to Docker daemon  119.5MB
Step 1/12 : FROM golang:1.12-stretch
---> 7ced090ee82e
Step 2/12 : ENV JSONNET_VERSION 0.13.0
---> Using cache
---> 7fadc5b61b7c
Step 3/12 : RUN apt-get update -y && apt-get install -y g++ make git jq gawk python-yaml &&     rm -rf /var/lib/apt/lists/*
---> Using cache
---> 1dddbc1ec188
Step 4/12 : RUN curl -Lso - https://github.com/google/jsonnet/archive/v${JSONNET_VERSION}.tar.gz |     tar xfz - -C /tmp &&     cd /tmp/jsonnet-${JSONNET_VERSION} &&     make && mv jsonnetfmt /usr/local/bin &&     rm -rf …
```
> scripts/jsonnet: use go modules only for go-jsonnet

- Makefile
- bundle.yaml
- example/non-rbac/prometheus-operator.yaml
- example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
- jsonnet/prometheus-operator/prometheus-operator.libsonnet
- scripts/generate-bundle.sh
- scripts/generate/prometheus-operator-non-rbac.jsonnet
I'm not exactly sure why, I went down to re-generating ksonnet.4 but for some reason `withReadOnlyRootFilesystem` is not available anymore. In order to move forward I removed it for now.
@paulfantom @squat @metalmatze @s-urbaniak
> Bump manifest version

- Documentation/network-policies.md
- example/networkpolicies/alertmanager.yaml
- pkg/alertmanager/statefulset.go
- pkg/alertmanager/statefulset_test.go
Alertmanager default port for clustering is now 9094 over both tcp and udp. This patch brings that change to the operator.
More or less an up-to-date version of #1601, as rebasing that one would have been painful.
Fixes #1574
> alertmanager/statefulset: move gossip port to 9094

- pkg/alertmanager/statefulset.go
Increase terminationGracePeriod to 120 seconds as it cannot be 0. More in statefulSet docs: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#deployment-and-scaling-guarantees
[Bug was discovered in openshift](https://bugzilla.redhat.com/show_bug.cgi?id=1721922) when trying to apply taints and tolerations and alertmanager pods spec weren't updated with config from statefulset spec.
/cc @brancz @s-urbaniak
> pkg/alertmanager: increase terminationGracePeriod to 120

- Documentation/user-guides/monitoring-kubernetes-ingress.md
@brancz I am following up on your request from https://github.com/prometheus/docs/pull/1373 to submit a PR for this documentation here.
I wanted to spin up Prometheus in Kubernetes so I could monitor ingress to my cluster. I spent some time hacking away at getting a working config and I felt it would be useful to write up my process for documentation.
Using the Prometheus Operator came off as the easiest way to deploy Prometheus in my cluster to collect metrics from Envoy.
I have documented the steps you need to take to get:
- An example application running in Kubernetes
- Ambassador running and exposing the application to the internet
- Prometheus running in cluster and scraping ingress statistics from Envoy
I have made a couple of clarifying edits from the original PR I submitted …
> Create documentation for ingress monitoring

- Documentation/thanos.md
according to https://github.com/coreos/prometheus-operator/pull/2629 `peers` has been removed due to deprecation.
Documentation needs to be updated accordingly, since other wise when someone specifies `peers` and a value for it, they will get an error similar to 
```ts=2019-07-10T13:09:21.386620549Z caller=main.go:292 msg="Unhandled error received. Exiting..." err="creating CRDs failed: waiting for Prometheus crd failed: timed out waiting for Custom Resource: failed to list CRD: v1.PrometheusList.Items: []*v1.Prometheus: v1.Prometheus.Spec: v1.PrometheusSpec.Thanos: v1.ThanosSpec.Resources: v1.ResourceRequirements.Requests: Limits: unmarshalerDecoder: unable to parse quantity's suffix, error found in #10 byte of ...|y\":\"768mi\"},\"request|..., bigger context …
```
> Adjust thanos-sidecar doc

- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
This function will return an empty slice if set namespaceSelector any=true.
``` Go
func getNamespacesFromServiceMonitor(m *v1.ServiceMonitor) []string {
nsel := m.Spec.NamespaceSelector
namespaces := []string{}
if !nsel.Any && len(nsel.MatchNames) == 0 {
namespaces = append(namespaces, m.Namespace)
}
if !nsel.Any && len(nsel.MatchNames) > 0 {
for i := range nsel.MatchNames {
namespaces = append(namespaces, nsel.MatchNames[i])
}
}
return namespaces
}
```
Later when generate k8s sd config, it will check if this slice is nil, but empty slice is not nil. I change the nil check to check len() == 0. I think it will be more clear.
``` Go
if namespaces != nil {
k8sSDConfig = append(k8sSDConfig, yaml.MapItem{
Key: "namespaces",
Value: yaml.MapSlice{
{ …
```
> refact check logic in namespaceSelector

- pkg/alertmanager/statefulset.go
- pkg/prometheus/statefulset.go
When using default podManagementPolicy (`OrderedReady`) it is possible to create a
situation where alertmanager pod objects won't be reconciled with a
statefulset and thus preventing alertmanager from being deployed.
One of such cases is when alertmanager was deployed and afterwards admin
applied taints to all nodes causing pod eviction. Next tolerations were
applied however due to OrderedReady policy one alertmanager pod was still left in
Pending state preventing reconciliation.
While testing manually with `podManagementPolicy: Parallel` alertmanager pods were scheduled correctly.
We are already using `podManagementPolicy: Parallel` for prometheus statefulset (https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L805), but this wasn't propagated to …
> pkg/alertmanager: change podManagementPolicy to parallel to prevent statefulset reconciliation from hanging

- scripts/create-minikube.sh
All the tests are failing, as suggested in https://github.com/coreos/prometheus-operator/pull/2684#issuecomment-514260866 bumping minikube version should do the trick.
> scripts: Bump minikube version

- .github/stale.yml
This is an adapted example of probot/stale bot to manage issues lifecycle. With such setup issues won't be closed, but only marked as "stale" after 60d of inactivity. Issues with label `kind/feature` are exempted from this rule.
I am open to any changes in that config.
Fixes #2686
Actions needed after merging:
- adding `stale` label to labels set in https://github.com/coreos/prometheus-operator/labels
- enabling [probot/stale GitHub app](https://github.com/marketplace/stale) for this repo (can be only done by organization admin).
/cc @brancz @metalmatze
> .github: add stale bot configuration

- pkg/prometheus/statefulset.go
Whilst the service port is created by default, the metrics endpoint for the sidecar is never started.
> thanos: expose metrics endpoint

- cmd/operator/main.go
- go.mod
- pkg/alertmanager/operator.go
- pkg/listwatch/listwatch.go
- pkg/listwatch/listwatch_test.go
- pkg/listwatch/namespace_denylist.go
- pkg/listwatch/namespace_denylist_test.go
- pkg/prometheus/operator.go
- test/e2e/denylist_test.go
- test/e2e/main_test.go
- test/e2e/prometheus_test.go
- test/framework/framework.go
Currently, it is possible to explicitly watch for namespaces with the --namespaces option.
If unset, all namespaces are being watched.
The reverse is not possible today, namely exclude (deny) namespaces from being watched.
This fixes it by introducing the --deny-namespaces option.
It is mutually exclusive with --namespaces.
cc @brancz @metalmatze @LiliC @paulfantom @squat
> *: support --deny-namespaces

- pkg/listwatch/listwatch.go
- pkg/listwatch/namespace_denylist.go
Whenever a multi-listwatch contains only one listwatch, it
would simply use the underlying listwatch without any wrapper. This
improves performance and eliminates unnecessary go routines. This commit
fixes a regression [0] where a denylist-listwatch would wrap underlying
listwatches even if the denylist was empty.
[0] https://github.com/coreos/prometheus-operator/pull/2710/files#diff-b33bee110e95fb2f22d9da56b1630d89R68-R74
cc @s-urbaniak @brancz @LiliC @metalmatze
> pkg/listwatch: fix listwatch wrapping regression

- pkg/listwatch/namespace_denylist.go
- pkg/listwatch/namespace_denylist_test.go
The original implementation of the denylist-listwatch does not properly
filter out namespace objects as they are not namespaced. Nevertheless,
the denylist-listwatch is applied to the multi-namespace listwatch. This
means that changes to blacklisted namespaces would be handled by
unsuspecting informers.
This commit ensures that namespaces are correctly filtered.
cc @s-urbaniak @brancz @LiliC @metalmatze
> pkg/listwatch: ensure namespace objects are denied

- .github/stale.yml
Accidentally  we didn't disable this feature and stale bot closed a lot of issues after default 7 days of inactivity. Issues were manually reopened and this PR prevents such thing from happening again
/cc @LiliC
> do not close stale issues

- scripts/jsonnet/Dockerfile
* Adds `golangci-lint` and `promtool`
* Introduces multi-stage builds to skim down image size
> Add golangci-lint and promtool to jsonnet-ci

- scripts/jsonnet/Dockerfile
Since this image is used only by CI systems, I don't see much benefit in
optimizing its size and number of layers. In this case, it only clouds
Dockerfile readability. Additionally, it breaks already established
CI pipelines.
A follow-up to https://github.com/coreos/prometheus-operator/pull/2742. We still see CI failures due to changes in this image.
/cc @kakkoyun @s-urbaniak
> scripts/jsonnet: revert optimizations in jsonnet-ci image

- cmd/prometheus-config-reloader/Dockerfile
As far as I can see, changing the ownership of the p-c-m binary should be unnessecary.
Droping the chown removes a potential attack vector as a non-privileged user
might be able alter content of the binary during runtime.
> prometheus-config-reloader: Remove unneeded Ownership change

- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
We still want to probe Prometheus, even if it's only listening on `localhost:9090`. The only real option here is to run `wget -q localhost:9090` inside the container, so we actually have the right loopback.
/cc @aditya-konarde @LiliC @kakkoyun @s-urbaniak @paulfantom
> Add exec probes with wget localhost:9090 to Prometheus if listenLocal

- cmd/operator/main.go
- pkg/alertmanager/operator.go
- pkg/prometheus/operator.go
- test/e2e/alertmanager_instance_namespaces_test.go
- test/e2e/denylist_test.go
- test/e2e/main_test.go
- test/e2e/prometheus_instance_namespaces_test.go
- test/e2e/prometheus_test.go
- test/framework/framework.go
- test/framework/prometheus.go
This adds two new command line parameters to prometheus operator:
--prometheus-instance-namespaces: Namespaces where Prometheus custom resources
and corresponding Secrets, Configmaps and StatefulSets are watched/created.
If set this takes precedence over --namespaces or --deny-namespaces
for Prometheus custom resources.
--alertmanager-instance-namespaces: Namespaces where Alertmanager custom resources
and corresponding StatefulSets are watched/created.
If set this takes precedence over --namespaces or --deny-namespaces
for Alertmanager custom resources.
This allows fine grained configuration of reconcilation for prometheus/alertmanager
instances to certain namespaces while allow- or deny-listing other namespaces for less
critical custom resources like ServiceMonitors, PodMonitors, etc. …
> cmd/operator: add [prometheus,alertmanager]-instance-namespaces cmdline parameter

- Makefile
This should prevent issues when PWD env var is not set correctly.
Closes #2701
> *: reference current directory by make built-in

- .travis.yml
- scripts/travis-e2e.sh
- test/e2e/main_test.go
Splitting e2e test runs into 2 separate CI jobs to workaround 50-minute timeout on travis jobs.
> allow running only part of e2e tests and use it in CI

- pkg/prometheus/operator.go
- pkg/prometheus/operator_test.go
By adding current StatefulSet Spec as a source of computed hash we can
improve detection of manual changes to prometheus SS and force their
rollback.
/cc @brancz @LiliC
> Improve detection of StatefulSet changes

- pkg/prometheus/operator.go
- pkg/prometheus/promcfg.go
Change switch/case to simpler if/else
Extract common namespace selector code to function
Make newConfigGenerator private because struct and methods are private
> pkg/prometheus/promcfg.go: minor simplifications

- cmd/operator/main.go
- pkg/alertmanager/operator.go
- pkg/prometheus/operator.go
* As stated in #2238, the use of the `--crd-apigroup` when moving to kube generators,
this change just removes the flag to avoid confusion to anyone using this flag.
> Remove dead custom API group code

- scripts/jsonnet/Dockerfile
Since we started recommending usage of that container image to others, I think it now makes sense to reduce its size. 
This is based on changes made by @kakkoyun and reverted due to problems with CI.
tested locally :)
> scripts/jsonnet: reduce jsonnet-ci image size

- pkg/alertmanager/statefulset.go
- pkg/prometheus/statefulset.go
When using `storage.volumeClaimTemplate` there are some scenarios that require setting `creationTimestamp`
There have been two issues reported around this:
- https://github.com/coreos/prometheus-operator/issues/2824
- https://github.com/coreos/prometheus-operator/issues/2399
An interesting side-effect of this happening is that the timestamp is propagated into the statefulset configuration as well, but this doesn't happen transparently from an operational standpoint - the stateful set is deleted and re-created because updates are forbidden.
Regardless of the implementation of someone's work-around for this (either setting the timestamp to `metav1.Now()` all the time, or only setting it if it is unset) someone moving to an environment where this is required from one where it was not will …
> Fix StatefulSet being needlessly re-created

- cmd/operator/main.go
- pkg/alertmanager/operator.go
- pkg/prometheus/operator.go
We ran into this by surprise a couple of times, which affects our SLA, so we'd like to have more info on when it happens. The logging appears like 
```
level=info 
ts=2019-11-15T15:47:11.035387855Z 
caller=operator.go:1135 
component=prometheusoperator 
msg="resolving illegal update of Prometheus StatefulSet"
details="&StatusDetails{Name:prometheus-prometheus,Group:apps,Kind:StatefulSet,Causes:[{FieldValueForbidden Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden spec}],RetryAfterSeconds:0,UID:,}"
```
An even more extreme version of this might be to have an optional switch that would stop reconciliation if this happens to let someone review what's going to happen.
> Add metric for statefulset re-create and increase logging

- pkg/alertmanager/statefulset.go
At the moment, it's not possible to rename the port names for the mesh ports.  While that behavior would be nice, it would involve a lot of work.
By swapping the names around, we're able to cater to Istio's naming requirements without affecting the user.
> Rename `mesh` ports to be prefixed with protocol

- pkg/admission/admission_test.go
Make sure that https://github.com/coreos/prometheus-operator/issues/2837 doesn't come back.
> Add regression test for humanizePercentage for Prom 2.11

- pkg/prometheus/operator.go
We have no way currently to detect that the Prometheus operator can't synchronize the nodes' endpoints.
Ref. https://bugzilla.redhat.com/show_bug.cgi?id=1695910
> pkg/prometheus: add metrics about node endpoints synchronization

- pkg/k8sutil/k8sutil.go
- test/e2e/main_test.go
- test/framework/crd.go
- test/framework/framework.go
Some fields were being left out of the created CRDs due to missing information during yaml unmarshalling.
> Fix unmarshalling crd yaml

- cmd/operator/main.go
- pkg/alertmanager/operator.go
- pkg/operator/operator.go
- pkg/prometheus/operator.go
Related to #2727 
There's no way to detect that the operator fails to list and watch resources. This PR adds metrics on which we could alert.
> *: instrument operator's list and watch operations

- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
When using prometheus with listenLocal=true the wget probe in the pod
failed because the created download file prevents further successfull
wget runs.
Using /dev/null for the wget output file fixes that.
Fixes #2921
> operator: modified prometheus wget probe when listenLocal

- .gitignore
- Documentation/user-guides/linting.md
- Makefile
- README.md
- cmd/lint/Dockerfile
- scripts/travis-push-docker-image.sh
Build and publish the lint executable as separate image, useful to have in CI pipelines to validate the CRD yaml files.
> lint: add operator lint command as separate container image

- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
When the operator transfers all labels and annotations from the source
prometheus object to the generated statefulset this also kubectl managed
annotations.
These annotations will cause the generated statefulset to be pruned when
the source prometheus is applied with kubectl apply --prune.
Cleanup of the statefulset is managed by the garbage collection via
owner references of the prometheus object (which can be pruned).
To fix this do not transfer any kubectl.kubernetes.io/ annotations to
the generated statefulset.
Closes gh-2642
Signed-off-by: Julian Taylor <juliantaylor108@gmail.com>
> fix generated statefulset being pruned by kubectl

- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
Currently when passing `--config-reloader-(cpu|memory)` values those are
used only for limits. This PR sets the same values for requests.
I wasn't sure if the options for the requests should have been passed
with separate options but I thought this was a good compromise in the
meantime.
The initial question was brought up in https://github.com/coreos/kube-prometheus/issues/376
> prometheus-operator: set config-reloader containers resources

- Documentation/user-guides/exposing-prometheus-and-alertmanager.md
Fix #2960 
Fix broken links and remove spec.version in examples of Exposing Prometheus and Alertmanager documentation
> Update Exposing Prometheus and Alertmanager documentation

- Documentation/rbac.md
- Documentation/user-guides/getting-started.md
- bundle.yaml
- example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
- jsonnet/prometheus-operator/prometheus-operator.libsonnet
> jsonnet/prometheus-operator: restrict api extension RBAC rules

- Documentation/user-guides/linting.md
- Makefile
- cmd/po-lint/Dockerfile
- scripts/travis-push-docker-image.sh
* use [`quay.io/coreos/po-tooling`](https://quay.io/coreos/po-tooling) instead of [`quay.io/coreos/jsonnet-ci`](https://quay.io/coreos/jsonnet-ci)
* use `po-lint` from [`quay.io/coreos/po-tooling`](https://quay.io/coreos/po-tooling) image instead of building another image.
I believe this closes #2954
> Switch tooling image

- pkg/prometheus/operator.go
Changes in kubernetes v1.17 cause an update loop due to validation
errors cause by setting the 'apiVersion' and 'kind' fields in the
StatefulSet spec.  These two fields are set to empty strings by
the Kube API server, and v1.17 added validation that does not
allow these fields to be modified.
Fixes #2950
> prevent prometheus sts update loop

- pkg/alertmanager/operator.go
- pkg/prometheus/operator.go
I was getting tired of seeing the deprecation warnings in the logs on every sync.  This changes the prometheus and alertmanager operators to only warn when a Prometheus or Alertmanager resource is added or updated.
> reduce verbosity of deprecation checks

- example/thanos/prometheus-service.yaml
- example/thanos/prometheus-servicemonitor.yaml
- example/thanos/prometheus.yaml
- example/thanos/query-deployment.yaml
- example/thanos/query-service.yaml
- example/thanos/sidecar-service.yaml
- example/thanos/thanos-ruler-service.yaml
- example/thanos/thanos-ruler.yaml
- pkg/thanos/rules.go
This PR does:
1. Bump thanos image version to v0.10.1  in example manifests
2. Explicitly add `namespace: default` in the manifests to make sure the query and ruler service discovery work.
3. Add `-` to make thanos ruler configmap name more readable (also consistent to prometheus configmap name)
> Fix thanos ruler example

- pkg/alertmanager/statefulset.go
- pkg/prometheus/statefulset.go
- pkg/thanos/statefulset.go
- test/e2e/prometheus_test.go
Prometheus image should default to latest version in compatibility
matrix.  Also updates Alertmanager and Thanos to latest stable versions.
> update default image versions

- pkg/prometheus/operator.go
- pkg/thanos/operator.go
When we reach this code path, `err` is always `nil`.
> *: remove nil error from logs

- pkg/alertmanager/statefulset.go
- pkg/alertmanager/statefulset_test.go
- pkg/prometheus/statefulset_test.go
- pkg/thanos/statefulset.go
- pkg/thanos/statefulset_test.go
kubectl-managed annotations will cause the generated statefulset to be pruned
when the source alertmanager is applied with kubectl apply --prune.
To fix this do not transfer any kubectl.kubernetes.io/ annotations to
the generated statefulset.
This is the same problem as fixed in #2944 but for alertmanager rather than
prometheus.
Fixes #3029
Signed-off-by: Alex Conlin-Oakley <alexconlin@gmail.com>
> fix alertmanager statefulset being pruned by kubectl

- pkg/thanos/statefulset_test.go
Flaky test found in https://travis-ci.org/coreos/prometheus-operator/builds/654476206?utm_source=github_status&utm_medium=notification. 
We need to sort the results because the map is unordered.
> Fix flaky test in thanos ruler

- pkg/prometheus/operator.go
Prometheus only actually uses the Endpoints but it helps humans to have them be the same.
> Make the ports on the kubelet Service and Endpoints match.

- Dockerfile
- Makefile
- cmd/prometheus-config-reloader/Dockerfile
I found it hard to build prometheus-operator for arm64 target.
I'm suggesting this little change allowing the use of variables OS and ARCH to specify the target architecture.
Those variables are passed to golang through GOOS and GOARCH variable, and to docker build through build-args.
> Simplify multi-arch building.

- pkg/thanos/operator.go
- pkg/thanos/operator_test.go
- pkg/thanos/statefulset.go
Make sure the labels applied to the pods match the labels which
the status function uses for searching.
> fix thanos-ruler status reporting

- pkg/alertmanager/operator.go
- pkg/operator/operator.go
- pkg/prometheus/operator.go
- pkg/thanos/operator.go
This prevents the alertmanager and thanos-ruler operators from getting
into a statefulset update loop similar to the fix that was
already applied to the prometheus operator.
Fixes #3048
> prevent statefulset update loop

- pkg/thanos/statefulset.go
Due to a problem in the way thanos handles a web.route-prefix set
to '/' (https://github.com/thanos-io/thanos/issues/2207), the value
should only set if the user has set a value for it.  If it's set
to empty string, no argument should be passed, so that thanos
uses it's own default value.
> only set thanos web.route-prefix if it was set by user

- example/thanos/prometheus.yaml
- example/thanos/query-deployment.yaml
- example/thanos/thanos-ruler.yaml
- go.mod
- go.sum
- pkg/prometheus/statefulset.go
- pkg/thanos/statefulset.go
- vendor/github.com/thanos-io/thanos/pkg/reloader/reloader.go
- vendor/github.com/thanos-io/thanos/pkg/runutil/runutil.go
- vendor/modules.txt
This version of thanos includes some new CLI options for configuring TLS support in thanos-ruler.
> update thanos to v0.11.0

- pkg/thanos/operator.go
- pkg/thanos/statefulset.go
- pkg/thanos/statefulset_test.go
Fixes #3056
Basically the Thanos Ruler statefulset object is constantly being updated whenever a PrometheusRule object undergoes a CRUD operation. This PR makes it so that:
- We no longer look for the specific name of the ConfigMap created, instead using globs to match zero or more ConfigMaps. The container arguments will now not get updated if one or more configmap names are created.
- We do a check on the StatefulSet that the operator wants to generate for Thanos Ruler. If it does not need to be updated, it won't be.
> Fix constant Thanos Ruler Statefulset generation

- scripts/tooling/Dockerfile
Updating dependencies:
- jsonnet 0.15.0
- golanglint 1.23.6
- promtool 2.16.0
- jsonnet-bundler ~0.3.0~ 0.3.1 (when it gets released :slightly_smiling_face: )
WIP until jsonnet-bundler 0.3.0 is released
/cc @metalmatze @brancz
> scripts/tooling: use latest and greatest tooling binaries

- pkg/alertmanager/statefulset.go
Instead of just appending user defined containers to the alertmanager
pods, use k8sutil.MergePatchContainers so that the default containers
can be modified.
> pkg/alertmanager: mergepatch alertmangaer containers

- pkg/thanos/operator.go
- pkg/thanos/statefulset.go
- pkg/thanos/statefulset_test.go
Changes to the ThanosRuler objects were being ignored by the operator.
This was due to copying the hash annotation of the old statefulset
to the new one before doing the comparison, thus they were always
appearing to be equal.
There doesn't seem to be any reason why we are copying the annotations
from the old statefulset to the new one, so this has been removed.
Fixes #3081
> pkg/thanos: fix thanos statefulset sync updates

- cmd/operator/main.go
- cmd/po-docgen/compatibility.go
- pkg/alertmanager/statefulset.go
- pkg/alertmanager/statefulset_test.go
- pkg/operator/defaults.go
- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
- pkg/prometheus/statefulset.go
- pkg/thanos/statefulset.go
- test/e2e/prometheus_test.go
- test/framework/prometheus.go
This moves the default image versions and urls from multiple
packages into a single location in the operator package.
This has the advantage of easier maintenance and ensuring that
the default Thanos sidecar image doesn't become out of
sync with the default image used for Thanos Ruler.
This is a subset of #3003, to try to reduce the complexity of that one.
> consolidate container image defaults

- pkg/alertmanager/statefulset.go
- pkg/prometheus/promcfg.go
- pkg/prometheus/statefulset.go
From the godoc:
ParseTolerant allows for certain version specifications that do not
strictly adhere to semver specs to be parsed by the semver library.
It currently trims spaces, removes a "v" prefix, and adds a
0 patch number to versions with only major and minor components specified.
> use tolerant parsing of version strings

- pkg/prometheus/rules.go
- pkg/thanos/rules.go
As we modify the PrometheusRule when generating the content, we need to make first a DeepCopy of the PrometheusRule object to be able to modify in-place. Currently we were modifying the cached PrometheusRule object, which caused changes to not propagate to the orginal object.
Side note: we need to refactor the prometheus and thanos ruler common code to avoid not missing fixing these kids of errors in the future!
cc @coreos/team-monitoring
> Do not modify the PrometheusRule cache object

- pkg/thanos/statefulset.go
This change uses the named port instead of the numerical value for the
governing service. It also ensures that the container port isn't exposed
when ListenLocal is true.
> pkg/thanos: fix thanos-ruler-operated service

- cmd/prometheus-config-reloader/main.go
Add --rules-dirs to expose the directory watching feature of the reloader library.
> prometheus-config-reloader: support for watching rules directory

- Documentation/user-guides/storage.md
After looking for documentation about persistent storage, it was surprising to see the files had existed and then been deleted.   Thankfully, git is persistent storage.  :-)
From https://github.com/coreos/prometheus-operator/issues/2905
"It seems like we should bring those docs back."  
"Would you like to shoot us a PR with fixed links re-introducing these docs?"
> restore storage.md file

- cmd/operator/main.go
- pkg/alertmanager/operator.go
- pkg/alertmanager/statefulset.go
- pkg/alertmanager/statefulset_test.go
- pkg/prometheus/operator.go
Fixes #2934. This is a more complete version of #2936.
There are two changes in this PR:
- Allow specifying the cluster domain.
- This allows using FQDNs for referencing the alertmanager so that the DNS search domain isn't used.
- This is something that is global to the cluster so I placed it in the operator configuration instead of alertmanager configuration.
- Remove the `.svc` extension on the alertmanager url when he cluster domain is not specified.
- The default search domain is `.svc.<cluster-domain>` so this reduces the amount of DNS calls when the cluster domain isn't specified from 6 to 2 (1 for ipv4, 1 for ipv6).
(cc @oded-dd)
> Allow setting the cluster domain so alertmanager makes fewer DNS calls

- Makefile
When using the Makefile, if the ARCH or OS arg is not specified, we
should default to the current "go env" value rather than default to
amd64/linux.
> Default ARCH/OS to current "go env" value

- RELEASE.md
Discussed this offline with @lilic and it seems a good idea to adopt a 6-weeks release cadence like Prometheus and Thanos do.
I've picked the dates so that the RC date for prometheus-operator is 2 weeks after the Prometheus RC.
> RELEASE.md: introduce release schedule

- RELEASE.md
Taken from the [Prometheus instructions](https://github.com/prometheus/prometheus/blob/master/RELEASE.md#2-draft-the-new-release). It is less error-prone that `git push --tags`.
> RELEASE.md: improve instructions to tag a release

- cmd/operator/main.go
Note: this changes two of the TLS CLI flags to make the naming more consistent.  I think it's a low risk change at this point since we haven't yet had a release with these flags.
> Tls improvements

- Makefile
The `$(MAKE)` variable is intended for running the same make again,
recursively, propagating the outer make's settings. This is not what is
intended here: the Docker layer is there to insulate the generation
process from the host. Use plain `make` in the container.
Fixes
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/Applications/Xcode.app/Contents/Developer/usr/bin/make\": stat /Applications/Xcode.app/Contents/Developer/usr/bin/make: no such file or directory": unknown.
```
Signed-off-by: Matthias Rampke <mr@soundcloud.com>
> Fix `make generate-in-docker` on macOS

- Makefile
- scripts/travis-push-docker-image.sh
- conditionally set ARCH when building for ARM (ARMv7)
- allow building prometheus-config-reloader image for different cpu architectures
- adjust script responsible for pushing images to quay to push cross-architecture images and build image manifest
Following command allows building image for ARM devices
```
make image GOARCH=armv7
```
Manifest creation was tested on https://quay.io/repository/paulfantom/prometheus-config-reloader?tab=tags and https://quay.io/repository/paulfantom/prometheus-operator?tab=tags
Fixes #3162
Fixes #2946
> Multi-arch images (adding ARMv7 & ARM64)

- scripts/travis-push-docker-image.sh
`docker manifest` command needs access to /etc/docker/cert.d which is prevented by default
Follow-up to #3177 
/cc @brancz
> Workaround for https://github.com/docker/for-linux/issues/396

- Documentation/compatibility.md
- pkg/operator/defaults.go
Add prometheus v2.17.2 to compatibility matrix
Signed-off-by: Benjamin <benjamin@yunify.com>
> Update compatibility matrix

- pkg/alertmanager/operator.go
- pkg/listwatch/listwatch.go
- pkg/listwatch/listwatch_test.go
- pkg/prometheus/operator.go
- pkg/thanos/operator.go
Service/pod monitors and rules resources watched by the operator
can live in different namespaces than the configmaps and secrets
associated to the Prometheus custom resources.
Before this change, we had only one namespace informer scoped to the
monitor/rule namespaces. Whenever a change of configmap or secret was
detected, the operator couldn't retrieve the associated namespace
because it didn't exist in the monitor/rule namespaces and the
reconciliation wouldn't happen.
With this change, separate namespace informers are used when the
monitors/rules and prometheus namespaces aren't identical.
Closes #3181
> *: create separate namespace informers if needed

- Documentation/user-guides/exposing-prometheus-and-alertmanager.md
Starting in Version 0.22.0, ingress definitions using the annotation nginx.ingress.kubernetes.io/rewrite-target are not backwards compatible with previous versions. In Version 0.22.0 and beyond, any substrings within the request URI that need to be passed to the rewritten path must explicitly be defined in a capture group.
> Update exposing-prometheus-and-alertmanager.md for nginx ingress 0.22.0+

- Documentation/rbac.md
- Documentation/user-guides/getting-started.md
- example/rbac/prometheus/prometheus-cluster-role.yaml
Pulled in the `RBAC` yaml for the prometheus-operator and saw that it couldn't target our kube state / node exporter metrics, complaining about a 403.
> Add nodes/metrics to allowable resources

- .travis.yml
Caching of the go modules directory can cause build problems if the
cache is shared between multiple branches.
Related to #3209
> travis.yml: remove caching of go directories

- .travis.yml
Fixes issue where the cache difference between branches was causing build failures.
> remove go module caching in travis CI for release-0.38 branch

- pkg/alertmanager/statefulset.go
- pkg/alertmanager/statefulset_test.go
- test/e2e/alertmanager_test.go
- test/framework/alertmanager.go
AlertManager in a single-node setup will try to broadcast silences and notification logs to itself. The messages are queued forever, leading to the error message when it reaches the max queue size.
More info
- https://github.com/prometheus/alertmanager#high-availability
- https://github.com/prometheus/alertmanager/issues/1814
Fixes #3196
> Automaticly disable high availability mode for 1 replica alertmanager

- Documentation/troubleshooting.md
While the examples only use named ports I just put in the, quoted, port number as a shortcut but this obviously isn't a valid port _name_ so the service was not being scraped. Eventually I figured out that I need a named port. By adding this section it'll hopefully save someone else some time in getting the ServiceMonitor properly laid out.
> Documentation: Add troubleshooting section about using port name not number.

- pkg/prometheus/statefulset.go
This fixes a double definition of the `--log.level` and `--log.format`
flags in the thanos sidecar.
Fixes #3222
> thanos sidecar: log flags double definition

- README.md
In #3176 `make generate-in-docker` was removed in favor to `make generate`.
> README.md: fix contributing guidelines

- pkg/alertmanager/statefulset.go
Instead of just appending user defined containers to the alertmanager
pods, use k8sutil.MergePatchContainers so that the default containers
can be modified.
This is a backport of https://github.com/coreos/prometheus-operator/pull/3080
/cc @coreos/team-monitoring
> pkg/alertmanager: mergepatch alertmanager containers

- Makefile
Fix #3285 by using @dgrisonnet [suggestion](https://github.com/coreos/prometheus-operator/issues/3285#issuecomment-645486457).
@lilic can you test it?
> fix `make` targets on darwin

- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
Quick follow up as described in https://github.com/coreos/prometheus-operator/pull/2832#pullrequestreview-428695780.
@lilic @pgier @simonpasquier @auhlig
> pkg/prometheus: Allow enforcing namespace label in Probe configs

- pkg/prometheus/operator.go
- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
Fixes prometheus config for Probe.
1. If only ProbeSelector is set, PodMonitorSelector and ServiceMonitorSelector not set, it will do nothing.
2. Relabelings are not added for Probe.
> fix probe promcfg

- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
Both scrapeInterval and evaluationInterval are on 30s. This commit changes this to 1m and updates the tests included with it.
Reason:
- These defaults are not documented for the Prometheus Operator
- These defaults differ from official Prometheus documentation. See: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#duration
> Normalize default durations

- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
PodMonitors already default to relabeling namespace, pod and container
into the target labels. ServiceMonitors should do the same to allow easy
correlation between signals.
@coreos/team-monitoring
> pkg/prometheus: Ensure relabeling of container label in ServiceMonitors

- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
Tried probe with ingress locally and found this problem. The point is that we should put relabeling configs for Blackbox exporter after relabeling configs for Ingress SD, otherwise `__address__` will be changed to proberURL, so it would go wrong here https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/promcfg.go#L788.
Verification.
probe
``` yaml
kind: Probe
metadata:
name: ingress
namespace: default
labels:
probe: test
spec:
jobName: test
prober:
url: blackbox-prometheus-blackbox-exporter:9115
targets:
ingress:
selector:
matchLabels:
probe: test
namespaceSelector:
matchNames:
- default
module: http_2xx
interval: 15s
```
Ingress
``` yaml
apiVersion: extensions/v1beta1
kind: Ingress …
```
> Fix probe ingress configs

- pkg/alertmanager/statefulset.go
- pkg/alertmanager/statefulset_test.go
alertmanager pods cannot be rolled out without downtime when labels are changed
Fixes #3120 for alertmanager
> decouple alertmanager pod labels from selector labels

- Documentation/compatibility.md
- pkg/operator/defaults.go
Bump to latest release. v2.19.2 contains some bug fixes.
> Update prometheus compatibility matrix to v2.19.2

- pkg/namespace-labeler/labeler.go
There should be an empty line between license header and package
declaration otherwise the license gets interpreted as package
documentation by godoc.
> pkg/namespace-labeler: fix whitespace

- pkg/alertmanager/statefulset.go
- test/e2e/alertmanager_test.go
- test/framework/alertmanager.go
Via the configMaps and secrets fields we can add additional
files that should be mounted into the /etc/alertmanager directory.
These can then be used for templates (e.g. e-mail templates).
If those change we want to reload the alertmanager in order
to urge it to take the changed files into account.
closes #3309
----
I was thinking about how to potentially refine the `testAMReloadConfig` e2e test, but since the reload would not change the config that is exposed in via the API endpoint we could not check against anything. Ultimately the only component we could test against would be a metric, e.g. the Alertmanager config reload timestamp metric (`alertmanager_config_last_reload_success_timestamp_seconds`). I was not really certain whether this is something you would like to have in the test …
> reload alertmanager on configmap/secret change

- pkg/listwatch/listwatch.go
- pkg/listwatch/listwatch_test.go
This fixes a known bug https://github.com/coreos/prometheus-operator/issues/3218 as well as an unknown until the 0.39 release where List and Watch were producing a large amount of errors most likely due to a combination of bumping client-go, using multi namespace watcher and removing the CRD management done by operator. This left the option of the multi list watcher to create a wrong set of resourceVersions because of duplicates, most likely due to large amount of resources filling the cache at startup. As all of these things combined is very rare, even hard to reproduce, which is why this was most likely not experienced by a lot of users, hence lack of bug reports. 
Note: I really want to move away from using a custom multi namespace watcher very soon so did not spend too much time on …
> listwatch: do not duplicate resource versions

- Documentation/compatibility.md
- pkg/operator/defaults.go
Prometheus v0.20.0 has been released yesterday. Thanos hadn't been updated in a while so setting it to the latest stable (v0.14.0).
> Bump Prometheus and Thanos versions

- cmd/operator/main.go
- pkg/prometheus/operator.go
Fixes #3298 
Supersedes #3299 
This PR allows us to set a field selector. This follows the discussion about not wanting an opinionated selector in the code. With this option we can both exclude:
```
--secret-field-selector='type!=helm.sh/release.v1'
```
and select:
```
--secret-field-selector='type=prometheus.io/whatever-we-want'
```
Because this is a field selector, we can chain the selectors using `,`.
The only restriction is that you can't use an OR operator here.
Moreover, the default value (empty string) is equivalent to `fields.Everything` so this is not a breaking change !
⚠️ Note, some errors may come from the WatchList if the Field Selector is valid but refused by the Kube API (for instance: field label <xxx> is not supported)
While they are properly reported, it seems that the …
> add SecretListWatchSelector to reduce memory and CPU footprint

- pkg/alertmanager/operator.go
- pkg/operator/operator.go
- pkg/prometheus/operator.go
- pkg/thanos/operator.go
This change adds a new `prometheus_operator_resources` metric that keeps
track of the number of resources currently managed by the operator. The
metric is broken down by controller and type of resource.
> pkg: instrument resources being tracked by the operator

- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
Since `0.35.0` release, some fields have been deprecated:
- `spec.baseImage`
- `spec.tag`
- `spec.sha`
In code, pkg/prometheus/statefulset.go line 284 and later, operator build prometheusImagePath using deprecated fields and spec.Version. At line 287, if spec.Image is defined, operator will simply replace prometheusImagePath value with spec.Image value.
This skip the version, which is not propagated anymore to statefulset definition.
This patch intends to be able to use either version or tag information to set Prometheus version for statefulset.
This brings back the old behaviour while keeping the deprecation mechanism
> Propagate Prometheus image version to statefulset

- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
Reverts coreos/prometheus-operator#3308
See follow up discussion in the reverted PR about the reasoning.
@lilic @paulfantom
> Revert "Normalize default durations"

- test/e2e/denylist_test.go
- test/e2e/prometheus_instance_namespaces_test.go
- test/e2e/prometheus_test.go
- test/framework/prometheus.go
In order to check if prometheus is able to scrape a target, we are
querying the /api/v1/targets endpoint and checking if the number of
active targets is equal to the one we expect. However, active targets
displayed by the API can sometimes be unhealthy. For example, when the
scraped target responds 401 Unauthorized, the target is still considered
active but its health will be set to "down". Because of that,
unauthorized scrapes will be considered valid in the tests.
Thus, in order to verify that prometheus is allowed to scrape a target,
we also need to check if it is healthy.
Example of active target being down:
```json
{
"status": "success",
"data": {
"activeTargets": [
{
"..."
"lastError": "server returned HTTP status 401 Unauthorized",
"lastScrape": "2020-07-24T09:54:42.018550304Z", …
```
> test/framework: fix prometheus active targets polling

- Documentation/api.md
- Documentation/compatibility.md
- Documentation/custom-configuration.md
- Documentation/design.md
- Documentation/exposing-metrics.md
- Documentation/high-availability.md
- Documentation/network-policies.md
- Documentation/rbac.md
- Documentation/troubleshooting.md
- Documentation/user-guides/alerting.md
- Documentation/user-guides/basic-auth.md
- Documentation/user-guides/exposing-prometheus-and-alertmanager.md
- Documentation/user-guides/getting-started.md
- Documentation/user-guides/monitoring-kubernetes-ingress.md
- Documentation/user-guides/running-exporters.md
- Documentation/user-guides/storage.md
- cmd/po-docgen/api.go
- cmd/po-docgen/compatibility.go
Update existing compatibility warning in docs to reflect the switch to apiextensions.k8s.io/v1 CRD in v0.39.0 which requires kubernetes v1.16 or newer (#3175, #3187).
> docs: update compatibility warning

- Makefile
shellcheck was the last tooling part that was run in a container and there was [a report on slack](https://kubernetes.slack.com/archives/CFFDS2Z7F/p1596126350177400) that it may not work correctly. This change allows to run the same version of shellcheck as previously but not in a container, it uses a similar mechanism to one used for other tools.
@lilic could you verify it works on OSX? I assume it should, but don't have a platform to check. You can do this by running `make shellcheck`.
> decontainerize shellcheck

- pkg/prometheus/promcfg.go
- pkg/prometheus/promcfg_test.go
It is already set above using the sd metadata, no need to overwrite it back to __address__.
> 🐛 Don't overwrite __param_target

- .travis.yml
- scripts/travis-push-docker-image.sh
Two changes allowing to push images to another quay repository:
- Additional CI job triggered only on branches which are not `master` with additional environment variables.
- Script change allowing to use `REPO` and `REPO_PROMETHEUS_CONFIG_RELOADER` set outside of `travis-push-docker-image.sh` script. 
Before merging this we need to set QUAY_COREOS_USERNAME and QUAY_COREOS_PASSWORD in travis settings.
> secondary stage to push images to quay.io/coreos

- pkg/listwatch/listwatch.go
https://github.com/prometheus-operator/prometheus-operator/pull/3340 added a workaround to err out if multiple resource versions are reported from api server.
However the preceeding List function allows multiple resource versions to slip through.
This causes potential cascading failures.
Note: as #3340 this is not a final fix but a try to cause additional cascading failures due to different resource versions being reported by API server.
/cc @lilic @brancz @paulfantom @metalmatze
> WIP pkg/listwatch: err out with multiple resource versions in List

- go.mod
- go.sum
- pkg/alertmanager/statefulset.go
- pkg/operator/image.go
- pkg/operator/image_test.go
- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
- pkg/thanos/statefulset.go
Image can contain tag already, this checks if it does it just returns
the image. Otherwise sha/digest takes priority over tag and lastly
version is taken due to historic reasons.
cc @prometheus-operator/prometheus-operator-reviewers
> pkg/operator/image.go: Adjust image path building

- go.mod
- go.sum
- pkg/alertmanager/statefulset.go
- pkg/operator/image.go
- pkg/operator/image_test.go
- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
- pkg/thanos/statefulset.go
- vendor/github.com/docker/distribution/LICENSE
- vendor/github.com/docker/distribution/digestset/set.go
- vendor/github.com/docker/distribution/reference/helpers.go
- vendor/github.com/docker/distribution/reference/normalize.go
- vendor/github.com/docker/distribution/reference/reference.go
- vendor/github.com/docker/distribution/reference/regexp.go
- vendor/github.com/opencontainers/go-digest/.mailmap
- vendor/github.com/opencontainers/go-digest/.pullapprove.yml
- vendor/github.com/opencontainers/go-digest/.travis.yml
- vendor/github.com/opencontainers/go-digest/CONTRIBUTING.md
- vendor/github.com/opencontainers/go-digest/LICENSE
- vendor/github.com/opencontainers/go-digest/LICENSE.docs
- vendor/github.com/opencontainers/go-digest/MAINTAINERS
- vendor/github.com/opencontainers/go-digest/README.md
- vendor/github.com/opencontainers/go-digest/algorithm.go
- vendor/github.com/opencontainers/go-digest/digest.go
- vendor/github.com/opencontainers/go-digest/digester.go
- vendor/github.com/opencontainers/go-digest/doc.go
- vendor/github.com/opencontainers/go-digest/go.mod
- vendor/github.com/opencontainers/go-digest/verifiers.go
- vendor/modules.txt
This ports the fix that landed in master. cc @s-urbaniak @brancz PTAL.
Should we mention this in the release notes of 0.41 or how do we go forward when adding a patch like this?
> [0.41]: pkg/operator/image.go: Adjust image path building

- .github/CODEOWNERS
This will allow github to automatically assign people to PRs.
I took a liberty of assigning all PRs which touch any tooling (`scripts/`) directory to myself. This is just a test to see what is possible :)
> .github: add codeowners file

- pkg/apis/monitoring/v1/types.go
- pkg/apis/monitoring/v1/types_test.go
- test/e2e/prometheus_test.go
This was flagged by
[golangci-lint](https://staticcheck.io/docs/checks#SA4022). The check
was for the address of the pointer, not the value. Add a test (failing
on master) to verify this, and fix the validation logic.
Follow-up to #2716.
Signed-off-by: Matthias Rampke <matthias@rampke.de>
> Fix validation logic for SecretOrConfigMap

- example/mixin/alerts.yaml
- jsonnet/mixin/alerts/alerts.libsonnet
- pkg/alertmanager/operator.go
- pkg/operator/operator.go
- pkg/prometheus/operator.go
- pkg/thanos/operator.go
We already have the `prometheus_operator_reconcile_errors_total` metric
to track the number of reconciliation attempts that failed but we miss
the number of attempts which makes it harder to alert on it. With this
change, we can compute the ratio of reconciliations that failed.
> pkg: add prometheus_operator_reconcile_operations_total metric

- test/e2e/prometheus_test.go
After #3413, it appears that some of the sub-tests in
`testPromArbitraryFSAcc` aren't useful because the outcome doesn't
depend on the value of ArbitraryFSAccessThroughSMsConfig.Deny. In all
cases, the test should succeed.
> test/e2e: remove duplicated subtests
