Makefile
Before this change, the following error occurs for the shellcheck
target (which is a prerequisite for other targets like format):
```
In ./scripts/generate/vendor/github.com/ksonnet/ksonnet-lib/scripts/install_jsonnet.sh line 7:
JSONNET_VERSION=$
^-------------^ SC2034: JSONNET_VERSION appears unused. Verify use (or export if used externally).
For more information:
https://www.shellcheck.net/wiki/SC2034 -- JSONNET_VERSION appears unused. V...
make: *** [Makefile:246: shellcheck] Error 1
```
=> Fix shellcheck Make target (ignore vendored files)

.travis.yml, Makefile, pkg/prometheus/promcfg_test.go
This test generates the same configuration many times, for each
Prometheus version, to see if it is deterministic. As the compatibility
matrix grows, test times increase. Now, this sometimes fails in CI
because Travis kills jobs after 10 minutes of no output.
Run each version as a subtest, and run tests with `-v`, so that output
is produced after each version. This avoids the no-output timeout.
Parallelize testing for each Prometheus version.
When the tests are run with `-short` (as in `make test-unit`), only try
one hundred iterations. With the race detector on, as in that target, this takes
around 5 seconds. Without the race detector, short tests on this
package now run quick enough for fast iteration in an IDE.
Add an additional target and Travis job for running the long tests, but …
=> Avoid CI timeouts in TestConfigGeneration

pkg/alertmanager/statefulset.go
Alertmanager in cluster mode resolves the DNS name of each peer and
caches its IP address which uses on regular intervals to 'refresh'
the connection.
In high-dynamic environment like kubernetes, it's possible that
alertmanager pods come and go on frequent intervals. The default timeout
value of 6h is not suitable in that case as alertmanager will keep
trying to reconnect to a non-existing pod over and over until it gives
up and remove that peer from the member list. During this period of
time, the cluster is reported to be in a degraded state due to the
missing member.
As such, it's best to use a lower value which will allow the
alertmanager to remove the pod from the list of peers soon
after it disappears.
Related: https://github.com/prometheus/alertmanager/issues/2250
=> pkg/alertmanager: Use lower value for --cluster.reconnect-timeout

cmd/operator/main.go, pkg/k8sutil/metrics.go
This change adds 3 metrics tracking client-go requests to the Kubernetes API:
* `prometheus_operator_kubernetes_client_http_requests_total`, counter
with a `status_code` label.
* `prometheus_operator_kubernetes_client_http_request_duration_seconds`,
summary with a `endpoint` label.
* `prometheus_operator_kubernetes_client_rate_limiter_duration_seconds`,
summary with a `endpoint` label.
This is inspired by https://github.com/prometheus/prometheus/blob/06a6621b6ca85c0db4b4226400676f710b5d2f9a/discovery/kubernetes/client_metrics.go
=> Instrument client-go requests

example/thanos/thanos-ruler-service.yaml
Signed-off-by: Benjamin <benjamin@yunify.com>
Thanos ruler UI cannot be accessed if target port is HTTP :
The default http port name is web : 
https://github.com/prometheus-operator/prometheus-operator/blob/master/pkg/apis/monitoring/v1/thanos_types.go#L135
https://github.com/prometheus-operator/prometheus-operator/blob/master/pkg/thanos/statefulset.go#L38
=> Change thanos ruler's http port to the default web

.github/workflows/ci.yaml, scripts/push-docker-image.sh
Follow-up to https://github.com/prometheus-operator/prometheus-operator/pull/3475
- fixing issues with alertmanager e2e test failures due to cluster not being fully initialized
- fixing issues with image builds from releases (tagged builds)
- add pushing `master` tag to main image repositories
=> CI fixes after release

.github/workflows/ci.yaml, go.mod, scripts/go.mod
Due to issues with go 1.14 it would be good to switch to the recent golang version. This version is also used now to build kubernetes.
=> Switch to go 1.15

pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
Removing liveness probe to prevent killing prometheus pod during WAL replay.
This should be reverted around kubernetes 1.21 release. At that point `startupProbe` should be added.
Closes #3391
/cc @brancz
=> pkg/prometheus: remove liveness probe

README.md, helm/README.md
This PR updates chart references from the deprecated [stable/prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) chart to the [prometheus-community/kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) chart based on the deprecation notice listed [here](https://github.com/helm/charts/tree/master/stable/prometheus-operator#%EF%B8%8F--deprecated).
=> helm: update chart reference

scripts/push-docker-image.sh
Previous version had issues with pushing images to `master` branch. This one solves the issue and brings the script to a version very similar to one used previously in travis CI.
=> scripts: more robust checking for image tag and repo name

example/mixin/alerts.yaml, jsonnet/mixin/alerts/alerts.libsonnet
port https://github.com/prometheus-operator/kube-prometheus/pull/610
This is necessary to move prometheus-operator alerts out of kube-prometheus
=> jsonnet/mixin/alerts: add list alerts

Documentation/rbac.md
The CRD management functionality was removed in v0.39, but the rbac doc
is still mentioning it.
As reported in this comment: https://github.com/prometheus-operator/prometheus-operator/issues/3438#issuecomment-679479224, this can be quite confusing.
=> Documentation/rbac.md: remove CRD mananagement mention

pkg/k8sutil/k8sutil.go
When updating the service, set the `IPFamily` attribute of the service spec.
fixes https://github.com/prometheus-operator/prometheus-operator/issues/3411
---
Along with https://github.com/n1kofr, I am also experiencing the issue where prometheus operator is failing to sync/update governing services. The root cause I believe is within these lines of code https://github.com/prometheus-operator/prometheus-operator/blob/master/pkg/k8sutil/k8sutil.go#L108-L129. When prometheus-operator is updating the service, the svc object in the CreateOrUpdateService function does not have the IPFamily attribute set in its object spec, thus it's effectively nil which explains the following error;
```log
E0921 17:20:17.185103       1 operator.go:322] Sync "system/prometheus-operator-kube-p-alertmanager" …
```
=> Update CreateOrUpdateService in k8sutil

example/mixin/alerts.yaml, jsonnet/mixin/alerts/alerts.libsonnet, pkg/alertmanager/operator.go, pkg/listwatch/listwatch.go, pkg/operator/operator.go, pkg/prometheus/operator.go, pkg/thanos/operator.go, test/e2e/main_test.go, test/e2e/prometheus_instance_namespaces_test.go
The namespaces listerwatcher shouldn't return an error when some of the monitored namespaces don't exist. Otherwise the operator will block while waiting for the informers to sync their cache and it will never be able to reconcile resources.
Closes #3347
=> Don't block when namespace aren't found

pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
Reduce the number of processes in play by using [`exec`][1] to transition to the `curl`/`wget` command without creating a new process.  Besides increasing efficiency, this may reduce the chance of [leaking zombie processes][2], or at least reduce the number of processes leaked when an exec-probe zombificaiton occurs.
The `ListenLocal` stuff landed in ca15e870da (#1051), the conditional get/exec probe logic landed in 8011f6364c (#2763), and the conditional `wget`/`curl` logic landed in 5eb9cb53db (#2763).
[1]: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#exec
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1878772
=> pkg/prometheus/statefulset: Exec requests in local probes

example/mixin/alerts.yaml, jsonnet/mixin/alerts/alerts.libsonnet, pkg/alertmanager/operator.go, pkg/operator/operator.go, pkg/prometheus/operator.go, pkg/prometheus/rules.go, pkg/thanos/operator.go, pkg/thanos/rules.go
This change adds two metrics:
* `prometheus_operator_managed_resources`, the number of resources managed by the controller per state (either selected or rejected).
* `prometheus_operator_syncs`, number of sync operations per status and controller.
It also adds a new `PrometheusOperatorSyncFailed` alert that fires when `prometheus_operator_syncs{status="failed"}` is greater than 0.
Closes #3327
=> Add metrics for selected/rejected resources and sync status

example/thanos/prometheus-cluster-role-binding.yaml, example/thanos/prometheus-cluster-role.yaml
Hi,
trying to making work the example, I found the rbac for the thanos example was out of date. I used the same permissions specifieds in: [https://github.com/kiddo3/prometheus-operator/blob/master/Documentation/rbac.md](https://github.com/kiddo3/prometheus-operator/blob/master/Documentation/rbac.md)
=> update thanos example rbac

.github/stale.yml
Automatically closing issues after an extended period of inactivity.
Closes #3568
=> .github: close non-feature issues after 120d of inactivity

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
The target_limit configuration field is only supported since Prometheus
v2.21.0. In the initial commit implementing target limits for the
Prometheus resource, we forgot to check which Prometheus version is
being deployed.
=> pkg/prometheus: ensure minimal version for target limits

pkg/admission/admission.go
The webhooks were failing as they aren't returning an apiVersion or kind in the response.
Closes #3473
=> Fix broken AdmissionReview

pkg/alertmanager/operator.go, pkg/informers/informers.go, pkg/prometheus/operator.go, pkg/thanos/operator.go, test/e2e/main_test.go, test/e2e/prometheus_test.go
When the operator detects a change to a secret, service monitor, ..., it
enqueues the object's namespace and triggers a reconciliation for each
operated resource that watches this namespace. Instead of looping over
all operated resources, the operator stopped after the first resource.
If 2 Prometheus objects were depending on the same secret (referenced by
additionalScrapeConfigs for instance) then only one of them would be
reconciled when the secret was updated.
The regression has been introduced by #3440.
Fixes #3552
=> *: fix reconciliation when 2 resources share the same secret

Documentation/rbac.md, Documentation/user-guides/getting-started.md, bundle.yaml, example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml, example/rbac/prometheus/prometheus-cluster-role.yaml, jsonnet/prometheus-operator/prometheus-operator.libsonnet
Specify necessary permissions to use Probes with Ingress selectors.
=> example/rbac: add prometheus permissions to list ingresses

Documentation/user-guides/alerting.md
Hi,
Reading the doc I find interesting to improve the doc, on how you can also specify you're custom secret name in the configuration.
=> improve documentation alertmanager configuration

Documentation/user-guides/webhook.md, test/framework/ressources/prometheus-operator-mutatingwebhook.yaml, test/framework/ressources/prometheus-operator-validatingwebhook.yaml
This PR resolves #3584 by updating all references to the deprecated api group `admissionregistration.k8s.io/v1beta1`
=> tests, docs: update admissionregistration.k8s.io/v1beta1 to admissionregistration.k8s.io/v1

pkg/alertmanager/amcfg.go, pkg/alertmanager/operator.go, test/e2e/alertmanager_test.go
Instead of silently discarding invalid PagerDuty configurations when
generating the whole Alertmanager configuration, we reject those upfront
so it can be detected with the `prometheus_operator_managed_resources`
metric.
cc @grdryn
=> pkg/alertmanager: skip invalid PagerDuty configs

pkg/prometheus/collector.go
Included EnforcedSampleLimit also as a metric for Prometheus when specified.
Closes #3400
=> Include EnforcedSampleLimit as a metric  as mentioned in (#3400)

pkg/apis/monitoring/go.mod, pkg/apis/monitoring/go.sum, pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
I think this dependency is usually not needed any longer, given that the standard library has the likes of errors.New, and fmt.Errorf.
My understanding is that apis/monitoring is a standalong module now to make it easier for other projects to import it, with a minimal set of transitive dependecies to worry about. If I'm correct, then github.com/pkg/errors is an easy one to keep out.
I noticed this while catching up with the recent changes around AlertManagerConfigs, so it was only recently introduced in #3593.
=> Remove pkg/errors dep from apis/monitoring module

Documentation/user-guides/webhook.md
`admissionReviewVersions` and `sideEffects` fields are now required for `admissionregistration.k8s.io/v1`
=> Fix admission webhook example

pkg/alertmanager/operator.go, pkg/operator/operator.go, pkg/prometheus/operator.go, pkg/thanos/operator.go
#3451 added 2 new informers on namespace resources for `Alertmanager` and `AlertmanagerConfig` but the controller wasn't modified to wait for synchronization to be complete before starting the reconciliation loop.
This change also replaces the use of `cache.WaitForCacheSync` by `cache.WaitForNamedCacheSync` as recommended in the the [`k8s.io/client-go` doc](https://pkg.go.dev/k8s.io/client-go/tools/cache#WaitForCacheSync).
=> pkg/alertmanager: wait for namespace informers syncs

pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go, pkg/alertmanager/statefulset.go, test/e2e/alertmanager_test.go, test/e2e/main_test.go
The user-provided secret containing the base Alertmanager configuration
may also include additional data (such as template files) that should be
copied to the final secret so the Alertmanager container can get access
to.
Closes #3638
=> pkg/alertmanager: copy user data to the generated config secret

cmd/operator/main.go
New unified reloader takes more memory than the two previous ones.
Solves https://github.com/prometheus-operator/prometheus-operator/issues/3659
=> operator cmd: set --config-reloader-memory to 50Mi instead of 25Mi.

pkg/prometheus/operator.go
This PR adds a sanity check for Probes, so that empty targets will not end up in a nil pointer dereference.
Closes: #3517
=> add sanity check for empty probe targets

example/thanos/prometheus-cluster-role-binding.yaml, example/thanos/prometheus-cluster-role.yaml
Remove redundant namespace on `ClusterRole` and `ClusterRoleBinding` in Thanos example.
`ClusterRole` and `ClusterRoleBinding` resources are cluster-wide, setting the namespace on these resources does nothing.
=> Remove redundant namespace on ClusterRole and ClusterRoleBinding in Thanos example

README.md
The blog post is from 2016, but it's market as outdated and redirects to getting started guide anyway.
=> Link to getting started guide instead of blog

Documentation/user-guides/linting.md
Fixes a bug in the example script as mentioned in #3667 
**Expected:**
Example script lints a sub-directory full of Prometheus Operator CRD files with ether local po-lint or Dockerized version
**Actual:**
Because the previous Docker image was deprecated/removed, the script no longer works; leaving no working po-lint example using the po-tooling docker image.
I updated the script to use the new po-tooling docker image.
I would be happy to simplify the docs significantly by instead providing two short and separate examples for users without the need for a new user to parse this shell script to understand how to run the docker / local commands.
=> docs: fix linting user-guide with updated docker image

pkg/prometheus/promcfg.go
This fixes matching labels with empty values when using Exists/NotExists operators.
I faced this issue while using the following bits of configuration:
ServiceMonitor:
```yaml
kind: ServiceMonitor
metadata:
name: generic
namespace: myns
spec:
endpoints:
- port: metrics
selector:
matchExpressions:
- key: scrape-metrics
operator: Exists
```
Service
```yaml
apiVersion: v1
kind: Service
metadata:
labels:
app.kubernetes.io/component: storage
app.kubernetes.io/name: fluentd
scrape-metrics: ""
name: fluentd
namespace: myns
spec:
clusterIP: None
ports:
- name: metrics
port: 24231
targetPort: metrics
selector:
app.kubernetes.io/component: storage
app.kubernetes.io/name: fluentd
```
The following selector should have matched `scrape-metris: ""` label, but it …
=> promcfg: Change label regex to match empty strings

.github/lock.yml
As in title. Previously discussed on slack.
=> .github: lock closed threads after 21 days of inactivity

pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go, pkg/alertmanager/types.go, test/e2e/alertmanager_test.go
Depending on the integration, the default value of 'send_resolved' can
be either 'true' or 'false'. This means that we need to represent it as
a pointer to bool in the Alertmanager configuration struct so the field
isn't rendered if nil.
=> pkg/alertmanager: change 'send_resolved' fields to *bool

.github/PULL_REQUEST_TEMPLATE.md
Just a simple PR template that includes a field for the changelog. It is a first step to having automated changelog generation from PRs (part of #3288).
=> .github: add initial template for PRs

CHANGELOG.md
I missed this one :facepalm: 
Right now I put it only on `master` branch, do we want it in release branch too?
After this is merged I'll adjust release notes to include this.
Note: we really need to get this done: https://github.com/prometheus-operator/prometheus-operator/issues/3288
=> add info about horizontal sharding to changelog

pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go
Fix for #3726 - original code initializes a list of Responder with an empty first object, which results in the config rendering with an invalid responder.
```release-note:bug
Omit invalid (empty) responder from opsgenie config
```
=> fix #3726 - omit empty responder from list

Documentation/design.md, Documentation/thanos.md
First attempt at providing some doc for https://github.com/prometheus-operator/prometheus-operator/issues/3740
This adds the missing CRDs to the design doc.
=> Documentation: Add missing CRDs to design doc

.github/workflows/ci.yaml
I've just noticed that the "publish" action builds with Go 1.14.x.
```
$ docker run --rm quay.io/prometheus-operator/prometheus-operator:master
level=info ts=2020-12-23T11:04:49.784627835Z caller=main.go:235 msg="Starting Prometheus Operator" version="version=0.44.1, branch=master, revision=02a5bac9610299372e9f77cbbe0c824ce636795b)"
level=info ts=2020-12-23T11:04:49.784670957Z caller=main.go:236 build_context="(go=go1.14.13, user=simonpasquier, date=20201222-12:15:23)"
```
**Release Note**
```release-note:none
```
=> .github: specify Go version for publish action

pkg/alertmanager/operator.go, test/e2e/alertmanager_instance_namespaces_test.go, test/e2e/main_test.go
When `--alertmanager-instance-namespaces` is defined, it should only
restrict the discovery of Alertmanager resource. Because of a bug, the
flag also applied to AlertmanagerConfig resources.
Closes #3754
```release-note:bug
fix discovery of `AlertmanagerConfig` resources when `--alertmanager-instance-namespaces` is defined.
```
=> *: fix discovery of AlertmanagerConfig resources

pkg/alertmanager/operator.go, pkg/prometheus/operator.go
`--alertmanager-instance-selector` should only apply to
Alertmanager resources and not AlertmanagerConfig.
```release-note:bug
Apply `--alertmanager-instance-selector` selector to Alertmanager resources only.
```
=> pkg/alertmanager: remove label selector for AlertmanagerConfig

pkg/operator/types.go
Signed-off-by: Sergiusz Urbaniak <sergiusz.urbaniak@gmail.com>
```release-note:none
```
We have done all the groundwork for openapi to recognize the `nil` value for `CreationTimestamp`. We can remove the central hack of initializing the non-nil zero value.
Nevertheless asking for a critical set of eyes @prometheus-operator/prometheus-operator-reviewers 
Fixes #2824
=> pkg/operator: remove CreationTime zero value hack

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Right now when creating staticConfig Probes namespace label is not populated. This PR aims to fix this that
```release-note:enhancement
Add namespace label to static probe metrics
```
=> Add namespace label to static probes

Documentation/additional-scrape-config.md
Two steps in the instructions have the same result, making one of them redundant.
We remove the more "complicated" one (purely subjective and a feeling).
This is a minor fix of the documentation on additional scrape configs.
```release-note:none
```
=> Docs: Remove redundant step for add. scrape config

SECURITY.md
~Moved~ Copied security policy information to separate file as it is treated differently by github (more in [github docs](https://docs.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository))
I also removed an unused link in README.
```release-note:none
```
=> *: copy information about security policy to separate file

README.md, pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go
This PR updates the `checkAlertmanagerRoutes` function to not return an error when a route's receiver is not set. This is a valid configuration in Prometheus and is specified as valid configuration in the prometheus-operator API documentation.
Fixes #3748 
```
release-note:Fix child routes to not require a receiver
```
=> Do not return error when sub-route does not contain a receiver

governance.md
As previously discussed, here's the Thanos governance doc adapted to Prometheus Operator (literally search and replace). I also took the chance to register the twitter handle and a google group, which I'll add everyone to once we merge this doc.
@prometheus-operator/prometheus-operator-reviewers 
@prometheus-operator/kube-prometheus-reviewers 
@prometheus-operator/prometheus-operator-triage
=> Add governance doc

pkg/alertmanager/operator.go, pkg/k8sutil/k8sutil.go, pkg/k8sutil/k8sutil_test.go, pkg/k8sutil/merge.go, pkg/prometheus/operator.go, pkg/thanos/operator.go, test/e2e/alertmanager_test.go, test/e2e/main_test.go, test/e2e/prometheus_test.go, test/e2e/thanosruler_test.go
Fixes: #2018
This PR adds functionality to preserve any labels and annotations manually added by user on Services, Endpoints and Stateful Sets managed by the Operator. Labels and Annotations are preserved as long as the do not conflict with those added by the Operator.
Questions:
- I did not introduce it for Secrets yet as I am not sure if there is a use case for that, but I will add it for consistency sake if requested.
- Do we want e2e test for this functionality?
```release-note:bug
Preserve user added labels and annotations on Services, Endpoints and StatefulSets
```
=> Fix: Preserve user added labels and annotations on Services, Endpoints and StatefulSets

go.mod, go.sum
Fix for [CVE-2021-3121](https://nvd.nist.gov/vuln/detail/CVE-2021-3121)
```release-note:none
```
=> go.mod: update github.com/gogo/protobuf to v1.3.2

pkg/prometheus/statefulset_test.go
- release-note:none
Small drive-by PR found while browsing the codebase.
=> statefulset_test: Fix typo in variable name

pkg/prometheus/operator.go
This is helpful to identify which system sets those objects up.
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
```release-note:enhancement
Add app.kubernetes.io/managed-by label to kubelet service and endpoint objects.
```
=> operator: Set managed-by labels for kubelet endpoint/svc

pkg/alertmanager/amcfg.go, test/e2e/alertmanager_test.go
closes: https://github.com/prometheus-operator/prometheus-operator/issues/3835
```release-note:bug
fix the loss of EmailConfig.headers key
```
=> fix the loss of EmailConfig.headers key

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/support.md
https://github.com/helm/charts has been deprecated. Update to new location https://github.com/prometheus-community/helm-charts.
```release-note:REPLACEME
```
=> Update Helm installation repository url.

cmd/operator/main.go, pkg/alertmanager/statefulset_test.go, pkg/operator/config.go, pkg/operator/statefulset.go, pkg/prometheus/statefulset_test.go, pkg/thanos/statefulset_test.go
Config Reloader's CPU requests/CPU limits and Memory requests/Memory limits are set whatever is given to their respective flags, this allows them to be independently set (EG CPU requests of 100m but no CPU limits) #3825
```release-note:REPLACEME
[FEATURE] Allow Config Reloader CPU requests/limits and memory requests/limits to be set independently #3825 
```
=> Add flags for CPU/Memory requests/limits

pkg/prometheus/operator.go
Unfortunately the change I made was incomplete and caused a inconsistency. It should be managed-by and not part-of for endpoints as well.
Ref: https://github.com/prometheus-operator/prometheus-operator/pull/3834
=> Fix incomplete change in #3834

pkg/alertmanager/statefulset.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go, pkg/thanos/statefulset.go, pkg/thanos/statefulset_test.go
```release-note:enhancement
alertmanager/prometheus/thanos: Add common kubernetes labels to prometheus-operator managed statefulsets 
```
alertmanager/prometheus/thanos: Set common labels on stateful set
This is helpful to identify which system sets those objects up.  
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
Fixes https://github.com/prometheus-operator/prometheus-operator/issues/3839
=> Common labels for Alertmanager/Prometheus/ThanosRuler objects

pkg/prometheus/statefulset.go
Removes setup code for the readiness handler that gets immediately
reassigned. The setup targets prometheus' /-/healthy/ endpoint and would
be a bad readiness probe anyway.
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>
Really just a minor cleanup.
```release-note:REPLACEME
```
=> pkg/prometheus: remove dead code

.golangci.yml, pkg/prometheus/promcfg_test.go
I've got following PRs to enable the default linters but it's easier to review them one by one.
```release-note:none
```
=> pkg/prometheus: fix govet errors

.golangci.yml, cmd/operator/main.go, cmd/po-lint/main.go, cmd/prometheus-config-reloader/main.go, pkg/alertmanager/collector.go, pkg/alertmanager/operator.go, pkg/api/api.go, pkg/k8sutil/k8sutil.go, pkg/prometheus/collector.go, pkg/prometheus/operator.go, pkg/thanos/collector.go, pkg/thanos/operator.go, test/e2e/alertmanager_instance_namespaces_test.go, test/e2e/alertmanager_test.go, test/e2e/main_test.go, test/e2e/prometheus_instance_namespaces_test.go, test/e2e/prometheus_test.go, test/framework/admission-webhooks.go, test/framework/cluster_role_binding.go, test/framework/context.go, test/framework/framework.go, test/framework/prometheus.go, test/framework/role-binding.go, test/framework/secret.go, test/framework/service.go, test/framework/service_account.go, test/framework/thanosruler.go
Also fix the missing Thanos Ruler and Alertmanager collector metrics.
Follow-up of #3916 
```release-note:bug
Restore `prometheus_operator_spec_replicas` metrics for Alertmanager and Thanos ruler controllers.
```
=> *: fix golint errors

pkg/versionutil/cli_test.go
Fix ci unit test under mac os system.
```release-note:REPLACEME
Fix ci unit test under mac os system.
```
=> Fix ci unit test under mac os system

ADOPTERS.md
This PR adds Opstrace as a Prometheus Operator user to ADOPTERS.md
```release-note: 
Add Opstrace as a Prometheus Operator user to ADOPTERS.md
```
=> Add Opstrace as an adopter

Documentation/compatibility.md, pkg/operator/defaults.go, test/e2e/prometheus_test.go
This PR updates the prometheus and thanos versions to the latest ones
closes #3950 
```release-note:enhancement
Update Prometheus and Thanos versions
```
```release-note:bug
Fix configuration of remote write headers
```
=> Update prometheus and thanos versions

pkg/alertmanager/amcfg_test.go, pkg/alertmanager/types.go
Continuation of #3830. @mdostal-hci I tried to push to your branch but your fork is protected, anyway I've preserved your initial commit so you can get credit :)
Closes #3829 
I noticed that the global `resolve_timeout` field had a similar problem: if it wasn't defined in the main configuration secret, it would default to 0s.
```release-note:bug
Allow `smtp_require_tls` to be false
```
=> Fix handling of the global smtp_require_tls field in Alertmanager configuration

pkg/operator/defaults.go
=> pkg/operator: bump default Thanos version to v0.19.0

README.md
Support kind >=0.6.x  in  README file .
Reference : https://github.com/kubernetes-sigs/cluster-api/issues/1796
```release-note:REPLACEME
Support kind >=0.6.x  in  README file .
```
=> Support kind >=0.6.x  in  README file 

pkg/prometheus/operator.go
#3801 
I found some log by enable debug log level.
```
level=debug ts=2021-04-11T16:10:13.24178926Z caller=operator.go:1190 component=prometheusoperator msg="reconciling statefulset" statefulset=prometheus-main shard=0
level=debug ts=2021-04-11T16:10:13.242372418Z caller=operator.go:1225 component=prometheusoperator msg="new statefulset generation inputs match current, skipping any actions"
``` 
After my analysis, I found a bug. 
When the first shard is created, it exits the loop.
https://github.com/prometheus-operator/prometheus-operator/blob/fb16b71909dfe3feff2b5e77214002e10bad301d/pkg/prometheus/operator.go#L1214-L1219
If the hash value of the first shard in the next loop has not changed, it will exit the loop directly and it will not create the next shard. …
=> Fix inconsistency question between the number of pods and shard configuration

pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
Adds [default container annotation](https://kubernetes.io/docs/reference/labels-annotations-taints/#kubectl-kubernetes-io-default-container) to Prometheus pod, so that kubectl fetches logs from the Prometheus container if no container is specified. Requires kubectl >= 1.21.0.
Without patch:
```
$ kubectl logs -f prometheus-prometheus-0
error: a container name must be specified for pod prometheus-prometheus-0, choose one of: [prometheus config-reloader]
```
With patch:
```
$ kubectl logs -f prometheus-prometheus-0
level=info ts=2021-04-09T19:36:12.550Z caller=main.go:418 msg="Starting Prometheus" version="(version=2.26.0, branch=HEAD, revision=3cafc58827d1ebd1a67749f88be4218f0bab3d8d)"
...
```
```
$ kubectl logs -f prometheus-prometheus-0 prometheus
level=info ts=2021-04-09T19:36:12.550Z …
```
=> Adds default container annotation to Prometheus pod

pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go
Adds [default container annotation](https://kubernetes.io/docs/reference/labels-annotations-taints/#kubectl-kubernetes-io-default-container) to Alertmanager pod, so that kubectl fetches logs from the Alertmanager container if no container is specified. Requires kubectl >= 1.21.0.
e.g, without:
```
$ kubectl logs -f alertmanager-alertmanager-0
error: a container name must be specified for pod alertmanager-alertmanager-0, choose one of: [alertmanager config-reloader]
```
with:
```
$ kubectl logs -f alertmanager-alertmanager-0
level=info ts=2021-04-12T16:00:47.351Z caller=main.go:216 msg="Starting Alertmanager" version="(version=0.21.0, branch=HEAD, revision=4c6c03ebfe21009c546e4d1e9b92c371d67c021d)"
```
```release-note:enhancement
Add default …
```
=> Adds default container annotation to Alertmanager pod

pkg/thanos/statefulset.go, pkg/thanos/statefulset_test.go
Follow up to https://github.com/prometheus-operator/prometheus-operator/pull/3971 and https://github.com/prometheus-operator/prometheus-operator/pull/3978
```release-note:enhancement
Add default container annotation to Thanos ruler pod
```
=> Adds default container annotation to Thanos ruler pod

cmd/operator/main.go
Fixes #3959 
```release-note:bug
Fix incompatible timestamp field in json logs when emitted by HTTP server
```
=> Disable incompatible timestamp from go-kit logger used by HTTP server

CHANGELOG.md
=> CHANGELOG.md: fix typo

pkg/prometheus/operator.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
This makes the `prometheus.ConfigGenerator` type and its `GenerateConfig()`
method exported and available to consumers outside of the `prometheus` package.
Signed-off-by: Anthony J Mirabella <a9@aneurysm9.com>
```release-note:change
The prometheus.ConfigGenerator type and its GenerateConfig method are now exported.
```
=> pkg/prometheus: Export the `prometheus.ConfigGenerator` type

Documentation/network-policies.md, Documentation/user-guides/monitoring-kubernetes-ingress.md, Documentation/user-guides/storage.md, example/networkpolicies/alertmanager.yaml, example/networkpolicies/prometheus.yaml, example/thanos/prometheus-service.yaml, example/thanos/prometheus-servicemonitor.yaml, example/thanos/prometheus.yaml, example/thanos/query-deployment.yaml, example/thanos/query-service.yaml, example/thanos/sidecar-service.yaml, example/thanos/thanos-ruler-service.yaml, example/thanos/thanos-ruler.yaml, jsonnet/thanos/config.libsonnet, pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go, pkg/alertmanager/statefulset.go, pkg/prometheus/operator.go, pkg/prometheus/operator_test.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go, pkg/thanos/operator.go, pkg/thanos/operator_test.go, pkg/thanos/statefulset.go, test/e2e/alertmanager_test.go, test/framework/probe.go, test/framework/prometheus.go
Signed-off-by: Dustin Hooten <dustinhooten@gmail.com>
This PR replaces the `app` label names with `app.kubernetes.io/name` where appropriate. That was suggested in [this comment](https://github.com/prometheus-operator/prometheus-operator/issues/3706#issuecomment-734187876). It will allow users to specify an `app` label in `podMetadata` field of the PrometheusSpec.
Closes #3706
```release-note:change
Replace app label names with app.kubernetes.io/name
```
=> Replace app label names with app.kubernetes.io/name

pkg/alertmanager/operator.go, pkg/k8sutil/k8sutil.go, pkg/k8sutil/k8sutil_test.go, pkg/prometheus/operator.go
#3980 
ReSubmit #3933 and fix ci failures.
Optimize asset secret update logic , when secret data equal to exist data , the asset can avoid updates and reduce the pressure on k8s apiserver.
```release-note:REPLACEME
Optimize asset secret update logic.
```
=> [WIP]optimize assest secret update

bundle.yaml, example/non-rbac/prometheus-operator.yaml, example/rbac/prometheus-operator/prometheus-operator-deployment.yaml, jsonnet/prometheus-operator/prometheus-operator.libsonnet
This works with kubectl >= 1.21
Similar to https://github.com/prometheus-operator/prometheus-operator/pull/3978 and https://github.com/prometheus-operator/prometheus-operator/pull/3971 but for prometheus-operator
```release-note:enhancement
jsonnet: set default container in prometheus-operator pod 
```
=> jsonnet: set default container name for prometheus-operator pod

pkg/prometheus/operator.go
The configmaps informer should watch the same namespaces as the
Prometheus and secrets informers.
```release-note:bug
Watch configmaps from the Prometheus allowed namespaces only.
```
=> pkg/prometheus: fix watched namespaces for configmaps

Documentation/user-guides/getting-started.md
All CoreOS blog post links are redirecting to OpenShift blog landing page. Added wayback maching link to land on the CoreOS blog post for introducing operators blog post.
=> Fixed broken link to coreos blog post

pkg/alertmanager/operator.go, pkg/k8sutil/labels.go, pkg/k8sutil/labels_test.go, pkg/prometheus/operator.go, pkg/thanos/operator.go, test/e2e/alertmanager_instance_namespaces_test.go, test/e2e/alertmanager_test.go, test/e2e/denylist_test.go, test/e2e/main_test.go, test/e2e/prometheus_instance_namespaces_test.go, test/e2e/prometheus_test.go, test/e2e/thanosruler_test.go, test/framework/alertmanager.go, test/framework/namespace.go, test/framework/prometheus.go, test/framework/thanosruler.go
Say that you have a Prometheus spec with
`serviceMonitorNamespaceSelector: {monitored: "true"}` and
`serviceMonitorSelector: {}` as well as a service monitor in namespace
"foo" which has the `monitored="true"` label. Then the operator wouldn't
remove the service monitor's targets when the `monitored="true"` label
is removed from namespace "foo" as one would expect. If namespace "foo"
doesn't have the selecting label initially, adding it later wouldn't
trigger the reconciliation either.
The same issue existed for pod monitors, probes, rules (Prometheus and
Thanos ruler) and alertmanager configurations.
This change adds logic to deal with namespace updates and trigger the
reconciliation if the namespace's labels have changed in a way that may
return different resources than previously. …
=> Reconcile resources on namespace updates 

jsonnet/prometheus-operator/jsonnetfile.json
Drop the dependency on ksonnet from jsonnetfile.json. 
```release-node:change
Drop ksonnet as a dependency in jsonnetfile.json
```
=> Drop ksonnet as a dependency in jsonnetfile.json

pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, pkg/thanos/statefulset.go
We recently removed all `app` labels and replaced them with `app.kubernetes.io/name` (#3939). This can lead to issues with upgrades in user environments. Let's put a proper deprecation notice and keep `app` label on pods till 0.50 release.
```release-note:enhancement
leaves `app` label on pods indirectly managed by prometheus-operator. Deprecation notice: label should be removed in 0.50
remove `v` prefix from app.kubernetes.io/version in alertmanager pods
```
=> Keep `app` label and fix version label for alertmanager

.github/workflows/ci.yaml
Actions should run only on:
- all pull_requests
- pushes to:
- master/main branches
- release-* branches
- tags prefixed with `v`
This should reduce time spent waiting for CI.
```release-note:none
```
=> .github/workflows: run actions only in specific scenarios

pkg/alertmanager/amcfg.go, pkg/alertmanager/types.go, test/e2e/alertmanager_test.go
The bump of github.com/prometheus/common from v0.15.0 to v0.20.0
introduced a breaking change [1] for users that configure the
`http_config` parameter in the `global` section. In practice the
configuration generated by the operator would contain a
`follow_redirects: true` stanza that isn't supported by Alertmanager <=
v0.21.0.
Instead of importing the structs from github.com/prometheus/common, we
duplicate them in the internal representation of the Alertmanager
configuration.
[1] https://github.com/prometheus/common/commit/47ee79a16821e03c31ca741659d4f7919aed91c1
Closes #4009 
```release-note:REPLACEME
Don't generate broken Alertmanager configuration when `http_config` is defined in the global parameters.
```
=> *: fix global HTTP configuration for Alertmanager

pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
In #3939 the app label from prometheus, alertmanager and thanos pods was removed. 
This caused a breaking change which prevents seamless upgrades. 
The issue was fixed for alertmanager and thanos in #4010.
This change reverts the removal of the app label for prometheus pods.
Fixes #4050
```release-note:bug
added an `app` label on Prometheus pods 
```
=> pkg/prometheus/statefulset.go: revert app label

pkg/prometheus/statefulset.go
Unsets storage.tsdb.no-lockfile flag as locking behaviour has been reverted.
Close #4048
```release-note:change
Flag "storage.tsdb.no-lockfile" will now default to false
```
=> feat: unset storage.tsdb.no-lockfile flag

cmd/operator/main.go
`r.Watch` will wait already.
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>
```release-note:REPLACEME
```
=> operator: don't wait to retry watching certificate reloader

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
`module` parameter is optional in ProbeSpec and as such it shouldn't be passed to prometheus configuration when field is empty. Allowing such configuration extends usability of `Probe` CRD to other exporters that are based on similar concept to blackbox_exporter (for example [pagespeed_exporter](https://github.com/foomo/pagespeed_exporter)).
```release-note:bug
Generate correct scraping configuration for Probes with empty or unset `module` parameter
```
=> pkg/prometheus: allow Probes without "module" parameter

pkg/alertmanager/amcfg.go
When decoding from a kubernetes secret the slack url may have whitespace or escape characters appended to its suffix or prefix, this removes these so that it can correctly be parsed into alertmanager config
fixes #4037
```release-note:bug
Fixed bug in Alertmanager config where URLS that are taken from Kubernetes secrets might contain whitespace or newline characters
```
=> bugfix: Remove whitespace and escape characters from URLs that are taken from secrets

pkg/alertmanager/operator.go, pkg/prometheus/operator.go, pkg/thanos/operator.go
This is to make reason for stateful update failure more readable for the user
```release-note:REPLACEME
Make failure to update StatefulSet more readable
```
=> operator.go: Update failure message shown to user

.github/workflows/ci.yaml, Makefile, scripts/push-docker-image.sh
Signed-off-by: paulfantom <pawel@krupa.net.pl>
* add easy way to add new registries (just add their prefix to `REGISTRIES` var) 
* push images to github container registry
* ability to run locally
* better tagging of development images
```release-note:enhancement
Added publishing images on GitHub Container Registry
```
=> Support pushing images to other container registries

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Operator does not generate ``max_retries`` option in ``remote_write`` for Prometheus version 2.11.0 and higher. Prometheus no longer have this option since 2.11.0.
Please refer to [this issue](https://github.com/prometheus-operator/prometheus-operator/issues/3256) for more details.
Closes #3256
```release-note:enhancement
Operator does not generate ``max_retries`` option in ``remote_write`` for Prometheus version 2.11.0 and higher.
```
=> Issue #3256: ignore max_retries for Prometheus ver. 2.11.0+

pkg/prometheus/operator.go, test/e2e/alertmanager_instance_namespaces_test.go, test/e2e/alertmanager_test.go, test/e2e/denylist_test.go, test/e2e/main_test.go, test/e2e/prometheus_instance_namespaces_test.go, test/e2e/prometheus_test.go, test/e2e/thanosruler_test.go, test/framework/alertmanager.go, test/framework/config_map.go, test/framework/context.go, test/framework/crd.go, test/framework/event.go, test/framework/framework.go, test/framework/pod.go, test/framework/probe.go, test/framework/prometheus.go, test/framework/prometheus_rule.go, test/framework/thanosruler.go
This PR removes context.TODO() from most of the function calls. We still have some more to remove which needs to check further. Since the Go tests have no context wrapping them added a context.Context field to the [Framework](https://github.com/prometheus-operator/prometheus-operator/blob/2b93704fc1d1d5dbc4e7aa98c2a1425a48bbca42/test/framework/framework.go#L52-L61) struct, initialised it to context.Background() and propagated it to tests.
Remaining files which has context.TODO()
```
▒▓    ~/gi/s/prometheus-operator  on   remove_context_todo ⇣1⇡1  find . -name "*go" | xargs grep -l context.TODO       ✔  2.7.17   1.16.4   2.7.3   at admin/openshift-monitoring ⎈  at 18:50:34  ▓▒░
./test/framework/deployment.go
./test/framework/service.go
./test/framework/role-binding.go …
```
=> Remove context.TODO() from client_go function calls

pkg/alertmanager/operator.go, pkg/prometheus/operator.go, pkg/thanos/operator.go
This change is to have statefulset shard info in logger msg
Updated as per https://github.com/prometheus-operator/prometheus-operator/pull/4100#discussion_r650013812
```release-note:REPLACEME
Have statefulset shard info in logger msg
```
=> pkg/prometheus/operator.go: Update logger message

RELEASE.md
Adding myself for v0.51. We need someone for v0.50 (August 11th): I'll be on vacation this week but if nobody is available either, we can maybe delay a bit and I should be able to handle it the week after.
cc @prometheus-operator/prometheus-operator-reviewers 
```release-note:none
```
=> RELEASE.md: update release shepherd list

Makefile, pkg/alertmanager/statefulset.go, pkg/apis/monitoring/v1/types_test.go, pkg/listwatch/listwatch_test.go, pkg/prometheus/operator_test.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/statefulset.go, pkg/thanos/statefulset.go, pkg/thanos/statefulset_test.go, scripts/tools.go, test/e2e/prometheus_test.go
`go fmt` and `gofmt` produce different results and since we were running only the former, our "go report card" isn't reporting 100% :( This PR should change this state and prevent it in the future.
```release-note:none
```
=> Format code

Documentation/operator.md, Makefile, cmd/po-docgen/main.go, cmd/po-docgen/operator.go
po-docgen and Makefile are updated to automatically generate Document/operator.md from cmd/operator/main.go, by parsing the definition of flagset in the init() function.
There is a limitation that constants imported from other packages are not resolved into its final literal value, runtime string contatenation using fmt.Sprintf is not evaluated by the doc generator. However, constants in the same file is resolved and constant expressions such as string concatenation is evaluated.
```release-note:enhancement
Automatically Generate Document for Operator Executable.
```
=> Issue #3104: Automatically Generate Document for Operator Executable

pkg/k8sutil/k8sutil.go, pkg/k8sutil/k8sutil_test.go
Closes #3846
```release-note:enhancement
Preserve the dual-stack immutable fields on service sync.
```
=> Preserve the dual-stack immutable fields on service sync

.github/ISSUE_TEMPLATE/config.yml
This should redirect some people to slack channel and discussions forum instead of creating support-type issues.
Shamelessly taken from thanos - https://github.com/thanos-io/thanos/blob/main/.github/ISSUE_TEMPLATE/config.yml :)
/cc @prometheus-operator/prometheus-operator-reviewers 
```release-note:none
```
=> Add links to discussions and slack in "Create Issue"

Makefile
Fixes #3995
```release-note:enhancement
Set proper build context in version package
```
=> do not set build user context

pkg/operator/operator.go
When the cache sync operation takes more than a minute, the
WaitForNamedCacheSync() function would log "cache sync not yet
completed" only once. This change ensures that the message is logged
every minute until the operation completes.
```release-note:bug
fix logging when cache sync is stuck.
```
=> pkg/operator: fix logging in WaitForNamedCacheSync()

pkg/operator/operator.go
During heavy apiserver disruptions, the informers cache synchronization
done by the operator before running the informers might never return.
This results in the operator being stuck forever waiting for its
informers caches to be synchronized.
To prevent that, we introduce a timeout of 10 minutes in the context
passed to client-go to make sure that the sync will always return at
some point.
**Release Note**
```release-note:bug
Add a 10 minutes timeout to the informers cache synchronization
```
/cc @simonpasquier
=> Add timeout to the informers cache synchronization

pkg/alertmanager/operator.go, pkg/prometheus/operator.go, pkg/thanos/operator.go
If a cache sync times out, there's no need to continue since the
operator will exit eventually.
```release-note:none
```
=> pkg: exit early if caches can't be synced

pkg/k8sutil/k8sutil.go
- fix loading ClusterConfig from KUBECONFIG env
Currently, prometheus-operator support loading Kubeconfig from `KUBECONFIG` env, which is a recommended way setting kubeconfig in k8s' [official doc](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#set-the-kubeconfig-environment-variable). The code below is able to load kubeconfig if one's `KUBECONFIG` env points to a specific file, like we do in `kubectl --kubeconfig /path/to/config`. But in my case my `KUBECONFIG` env is not a path to a single file but concatenated with other path together like it's done in the [official doc](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#append-home-kube-config-to-your-kubeconfig-environment-variable) too …
=> fix loading clusterConfig from KUBECONFIG env

.github/workflows/publish.yaml
* Allow manually triggering workflow by adding workflow_dispatch
* Remove 'tags' keyword as it is not supported for workflow_run
* Fix condition to better detect an event (used example from      https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Fixes #4150 
```release-note:none
```
=> .github/workflows: publish untagged images

MAINTAINERS.md
As discussed internally. Let's unify who is a "maintainer" in prometheus-operator organization by joining @prometheus-operator/prometheus-operator-reviewers and @prometheus-operator/kube-prometheus-reviewers into one team :)
@kakkoyun @dgrisonnet @ArthurSens please verify if you agree with the data in this document.
```release-note:none
```
=> *: specify all maintainers of prometheus-operator organisation

RELEASE.md
I probably won't be able to do 0.52 nor 0.53 so volunteering for 0.50. Unless anyone from @prometheus-operator/prometheus-operator-reviewers wants to take this one ;)
```release-note:REPLACEME
```
=> *: volunteer as 0.50 release shepherd

Documentation/api.md, cmd/po-docgen/api.go
When browsing the API docs for the types provided by the operator,
it is hard to find out where exactly each type is used.
This commit modifies the code generation tool to add links under every
type to the types where it is referenced.
Here is an example of what the docs for `SecretOrConfigMap` would look like: https://github.com/fpetkovski/prometheus-operator/blob/add-api-docs-backlinks/Documentation/api.md#secretorconfigmap
```release-note:none
```
=> Add API documentation backlinks

.github/workflows/publish.yaml
Follow-up to https://github.com/prometheus-operator/prometheus-operator/pull/4152
I tested the #4152 on a repository with only one depending workflow and GitHub docs are not great at explaining how `workflow_run.workflows` work. Turns out that list is ORed and not ANDed, so `publish` workflow would run after any other workflow specified in list is completed. This in turn causes publishing images 3 times in prometheus-operator.
This fix would cause to run `publish` workflow only after `e2e` workflow is completed and wait for `checks` and `unit` workflows to be successfully completed too. `e2e` workflow was chosen to be a trigger because it 
is running for an order of magnitude longer than the other 2 workflows.
```release-note:none
```
=> .github/workflows: improve image publishing

pkg/prometheus/collector.go
Include Shards count as a metric as mentioned in #4168
Closes #4168
- release-note:feature
```
Adds prometheus_operator_spec_shards metric for exposing the number of shards set on prometheus operator spec
```
=> Include Shards count as a metric as mentioned in #4168

cmd/operator/main.go, cmd/prometheus-config-reloader/main.go, go.mod, go.sum, pkg/admission/admission.go, pkg/admission/admission_test.go, pkg/alertmanager/amcfg.go, pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go, pkg/api/api.go, pkg/listwatch/listwatch.go, pkg/listwatch/namespace_denylist.go, pkg/listwatch/namespace_denylist_test.go, pkg/operator/operator.go, pkg/operator/server.go, pkg/prometheus/operator.go, pkg/prometheus/promcfg.go, pkg/prometheus/rules.go, pkg/thanos/operator.go, pkg/thanos/rules.go, scripts/errcheck_excludes.txt
Using github.com/go-kit/log instead of github.com/go-kit/kit reduces the
list of things this project depends on. This commit also removes the
wrapper for k8s.io/klog because none of the k8s libraries depend on it
anymore.
```release-note:none
```
=> *: switch to github.com/go-kit/log

pkg/operator/config-reloader.go
Add mapping between the port name `reloader-web` and the actual port number, which was dropped in v. 0.49.0.
Fixes: #4162 
```release-note
Add port name mapping to ConfigReloader to avoid reloader-web probe failure.
```
=> Update ConfigReloader to add port name mapping

go.sum, pkg/prometheus/rules.go, pkg/prometheus/rules_test.go, pkg/thanos/rules.go
This functionality is available in the custom validation admission webhook
but for environments where the webhooks cannot be enabled this patch enables
in-band validation of prometheus rules as well.
Fixes #4181 
_Validate prometheus rules when generating rule file content_
=> Validate prometheus rules when generating rule file content

pkg/k8sutil/k8sutil.go, pkg/k8sutil/k8sutil_test.go
There are some special annotations set by kubectl when performing actions like a rolling restart, that should be preserved in the statefulset, for the command to be executed successfully.
Relevant issue: #4155 
```release-note
Preserve annotations set by kubectl
```
=> Propagate annotations set by kubectl when updating statefulsets

pkg/admission/admission.go, pkg/admission/admission_test.go
Fixes #4199
Reuse the same logic used for synchronous rule validation
introduced in https://github.com/prometheus-operator/prometheus-operator/pull/4184
```release-note
Handle Thanos rules partial_response_strategy field in validating admission webhook
```
=> Handle Thanos rules partial_response_strategy field in validating admission webhook

pkg/k8sutil/k8sutil.go
This change fixes the CreateOrUpdateSecret() function to handle update
conflicts properly by copying the last known ResourceVersion version
into the updated resource defintion [1]. Without it, the update
operation could overwrite the current version of the secret if a change
had happened between the get and update operations.
Closes #4070
[1]
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
```release-note
Handle update conflicts properly for secrets to avoid overwriting …
```
=> pkg/k8sutil: handle update conflicts for secrets

pkg/prometheus/promcfg.go
Remove check for prometheus 1.x since its no longer supported
Fixes #4244
```release-note
Removed check for prometheus 1.x
```
=> pkg/prometheus/promcfg.go: Remove check for prometheus 1.x

.github/workflows/publish.yaml
Image publishing is still broken and images for 0.50 had to be created manually. To make publishing work again I am removing all job dependencies and simplifying it to push images regardless of other CI jobs. This means we should get images even if there are flaky tests (like https://github.com/prometheus-operator/prometheus-operator/issues/4070) and we should get them faster. It also means if `master` is broken, published images also may be broken, which in turn should allow easier debugging. 
_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box …
=> .github: publish images without looking at other jobs

pkg/alertmanager/amcfg.go
Some services apparently don't have username in auth basic authentication. Enable specifying empty username so the webhook receiver can work with them.
Sample usecase: sending monitoring alert heartbeat to OpsGenie via webhook.
* [OpsGenie authentication](https://docs.opsgenie.com/docs/authentication)
- [x ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
```release-note
- Allow empty username for HTTP Auth Basic
```
=> alertmanager: enable empty basic auth username

pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go, pkg/alertmanager/operator.go, pkg/alertmanager/types.go
This change supports https://github.com/prometheus/alertmanager/pull/2534 in the managed secret and allows config to accept the Slack webhook URL as a file path.
Fixes #4045 
```release-note
Adds `slack_api_url_file` globally and `api_url_file` in Slack config to the managed secret to support reading URL from file
```
=> alertmanager: Support Slack webhook URL via file path in config

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, test/e2e/main_test.go, test/e2e/prometheus_test.go, test/framework/prometheus.go
Whenever `enforcedNamespaceLabel` is defined, the operator should add a final relabeling configuration that sets the enforced label to the namespace's value. It was effective for the `relabel_configs` field but not for `metric_relabeling_configs`. The assumption was that dropping metric relabeling entries that tried to alter the enforced label was enough but it appears that the `labelmap` action could be used to bypass the enforcement.
```release-note
Ensure that the namespace label is always enforced with metricRelabelConfigs.
```
=> Fix enforce namespace label

.github/workflows/publish.yaml, scripts/push-docker-image.sh
The workflow didn't work properly when tagging releases because it
wasn't enabled for tag events. We exclude all tags that start by `pkg`
since they are only relevant for Go sub-modules.
```release-note
```
=> *: fix action and script publishing images

pkg/alertmanager/amcfg.go, pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go, pkg/common/validations.go, pkg/operator/validations.go, pkg/prometheus/promcfg.go, pkg/thanos/statefulset.go, pkg/thanos/statefulset_test.go
Add validations for duration fields in alertmanager and thanos
```release-note
Added input validations for duration fields in alertmanager and thanos
```
cc: @simonpasquier
=> Add validations for duration fields in alertmanager and thanos

pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go
First of thank you so much for the hard work put into this operator, I really appreciate it as it makes manging Prometheus and dependencies a lot easier 💯 
The operator can merge configuration when the
[`AlertmanagerConfigSelector`](https://github.com/prometheus-operator/prometheus-operator/blob/83fe36566f4e0894eb5ffcd2638a0f039a17bdeb/pkg/apis/monitoring/v1/types.go#L1547)
is defined. We are validating (using upstream alertmanager) and
parsing (using internal config) even if we don't need to load config in
memory since the user opted to manage the configuration via the secret.
This can cause problems where there is a missmatch between alertmanager
configuration and the operator internal amcfg struct, for example
prometheus-operator#4174.
Only validate the configuration from upstream …
=> alertmanager: only load cfg when writing cfg

ADOPTERS.md, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
This PR modifies the Prometheus StatefulSet to:
- add a startup probe (fixes https://github.com/prometheus-operator/prometheus-operator/issues/3211),
- restore the liveness probe (follow-up of https://github.com/prometheus-operator/prometheus-operator/pull/3502),
- decrease the failure threshold of the readiness probe (fixes https://github.com/prometheus-operator/prometheus-operator/issues/3671).
(I’m not sure if this is only a bugfix.)
```release-note
Rework Prometheus StatefulSet probes so that failures are detected early while still tolerating slow startups due to WAL recovery.
```
=> Rework Prometheus StatefulSet probes

Makefile, test/e2e/prometheus_test.go
This commit reduces the runtime of Prometheus e2e tests from 40 minutes
to less than 30 minutes. It does so by implementing two changes:
* reducing the scraping time for the tlsRemoteWrite test from 30s to 5s
* increasing the parallelism for e2e tests from 2 to 4.
According to the docs[1], the Github runners have 2 CPUs and our tests
do not seem to be CPU bound. Since each Github Actions job runs on a
dedicated VM, doubling the parallelism should not be problematic for now.
[1] https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources …
=> test: Reduce runtime of e2e tests

Makefile
A recent commit increased the concurrency for e2e tests and made it
double the amount of CPUs available on Github Runners. This seems to
have introduced some flakes in the e2e tests.
This commit reverts the concurrency setting and sets it to be the same
as the number of CPUs.
cc @simonpasquier @paulfantom
```release-note
```
=> test: Reduce e2e test concurrency

.mdox.validate.yaml, CONTRIBUTING.md, Documentation/api.md, Documentation/design.md, Documentation/thanos.md, Documentation/user-guides/exposing-prometheus-and-alertmanager.md, Documentation/user-guides/storage.md, README.md, RELEASE.md, bundle.yaml, contrib/kube-prometheus/README.md, example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml, governance.md, jsonnet/prometheus-operator/prometheusrules-crd.json, pkg/alertmanager/types.go, pkg/apis/monitoring/v1/types.go, pkg/versionutil/doc.go, scripts/push-docker-image.sh
Updating default branch name from `master` to `main` for prometheus-operator docs.
This PR amends also links to other projects which changed default branch name from `master` to `main`. It also amends our container publishing script to work with `main` branch and tags. Due to the latter I am marking this as a CHANGE in changelog.
```release-note
Deprecated container …
```
=> docs: Swapping default branch names

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml, jsonnet/prometheus-operator/alertmanagerconfigs-crd.json, pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go, pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go, pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
Fixes #4087 
```release-note
Support updated matching syntax for inhibit rules in AlertManagerConfig CRD
```
=> Support updated matching syntax for inhibit rules in AlertManagerConfig CRD

ADOPTERS.md, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Take values for labels (in regex) in "()" to be compatible with RE2 rules
Fixes #4391
```release-note
Fixed regex in relabel_configs
```
=> pkg/prometheus/promcfg*.go: Fix regex in relabel_configs

pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go, pkg/alertmanager/operator.go, test/e2e/alertmanager_test.go
Depends on #4309 
Related to #4087 
```release-note
Support updated matching syntax for routes in AlertManagerConfig CRD
```
=> Support updated matching syntax for routes in AlertManagerConfig CRD

Documentation/rbac.md
Fixes the version label used in Kubernetes resources that are part of the documentation.
```release-note
```
=> Documentation: use the correct version in Documentation files

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml, jsonnet/prometheus-operator/alertmanagerconfigs-crd.json, pkg/alertmanager/amcfg_test.go, pkg/alertmanager/validation.go, pkg/alertmanager/validation_test.go, pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
Elements in the routes `groupBy` list must be unique and furthermore, when the special value '...' is provided, there must be no other elements in the list.
Fixes #4402 
```release-note
Ensure group_by values are unique in alertmanager config
```
=> Ensure group_by values are unique in alertmanager config

Makefile
This allows invoking `make generate` from systems where bash is not in
/bin/bash (such as NixOS).
Instead, this will pick up `bash` from $PATH.
See https://www.reddit.com/r/linuxadmin/comments/975nok/binbash_vs_usrbinenv_bash/
```release-note
The `Makefile` will now pick up `bash` from `$PATH`, instead of hardcoding it to /bin/bash. This will fix running it on systems where bash is elsewhere.
```
=> Makefile: use /usr/bin/env bash instead of /bin/bash

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/types.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Prometheus added a feature flag to enable/disable retries on HTTP 429 (too many requests) responses.
Feature got introduced with: prometheus/prometheus#8477. This feature is very useful if rate limiting got hit but the requests should be or not be retried later.
Closes #4192.
```release-note
Added support for RetryOnRateLimit in Prometheus Remote Write Config
```
=> Add support for retry_on_http_429 in Prometheus Remote Write config

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Prometheus in agent mode fail-fast if alerting or rules_files is present in its configuration.
This commit removes those sections from the config if not necessary, aiming to make it possible to run Prometheus in agent mode with the Prometheus Custom Resouce.
I'll leave this PR as a draft until there is consensus if we really want to do this, or if we prefer to only support agent mode with a dedicated PrometheusAgent Custom Resource.
Changes were made based on this comment: https://github.com/prometheus-operator/prometheus-operator/issues/3989#issuecomment-974137486
_What type of changes …
=> pkg/prometheus: Make CR compatible for agent mode

Documentation/user-guides/alerting.md, example/user-guides/alerting/prometheus-example-rule-namespace-selector.yaml
As raised in https://github.com/prometheus-operator/prometheus-operator/issues/4412,
there's no example or docs on how to use `metav1.LabelSelector` to
select namespaces.
This is even more confusing, as the
prometheus.spec.{rule,podMonitor,probe}NamespaceSelector fields (and
some others) use the `NamespaceSelector` type.
It might make sense to move those to `metav1.LabelSelector` as well
(https://github.com/prometheus-operator/prometheus-operator/issues/4412#issuecomment-971892883),
but let's start documenting how to use the ones we already have.
_What type of changes does your code …
=> Document ruleNamespaceSelector

pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
The /-/ready handler returns OK only after the TSDB initialization has
completed. The WAL replay can take a significant time for large setups
hence we enable the startup probe with a generous failure threshold (15
minutes) to ensure that the readiness probe only comes into effect once
Prometheus is effectively ready. We don't want to use the /-/healthy
handler here because it returns OK as soon as the web server is started
(irrespective of the WAL replay).
```release-note
use /-/ready endpoint for the startup probe
```
=> pkg/prometheus: use /-/ready for the startup probe

pkg/operator/sharded-secret.go, pkg/operator/sharded-secret_test.go, pkg/prometheus/operator.go, pkg/prometheus/operator_test.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go, test/e2e/prometheus_test.go
k8s secrets have a default size limitation of 1048576 bytes. Once this
size gets exceeded the k8s API server will refuse to update the secret.
This introduces a sharding approach where all tls-assets are distributed
over shards of tls asset secrets and mounted into the prometheus pod
through volume projection.
Fixes #4353
```release-note
- Add tls-assets secret …
```
=> Add tls-assets secret sharding

pkg/alertmanager/operator.go, pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go
k8s secrets have a default size limitation of 1048576 bytes. Once this
size gets exceeded the k8s API server will refuse to update the secret.
This introduces the sharding approach used in prometheus controller
to the alermanager controller.
Fixes #4353
Refs #4427
```release-note
- Add tls-assets secret sharding for alertmanager to support a high amount of tls assets
```
=> Add tls-assets sharding to alertmanager

Documentation/api.md, Documentation/user-guides/alerting.md, cmd/po-docgen/api.go
As noticed in #4449, the Kubernetes API website for 1.17 isn't accessible anymore. Eventually we'll get rid of po-docgen (see #4376) so this is only fixing the issue at hand.
```release-note
```
=> cmd/po-docgen: fix links to the Kube API documentation

bundle.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml, jsonnet/prometheus-operator/alertmanagerconfigs-crd.json, pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
There was a typo in the alertmanagerconfig CRD which could lead to a correct pattern not recognized. 
@simonpasquier let me know if you want me to target the v0.53.0 branch as well
```release-note
Fix validation pattern for month in AlertManagerConfig CRD
```
=> Fix validation pattern in alertmanagerconfig CRD

.github/workflows/release.yaml
This commit adds a Github workflow which uploads the manifests in
bundle.yaml to a release once it is created.
Fixes https://github.com/prometheus-operator/prometheus-operator/issues/4457
```release-note
```
=> Upload bundle.yaml when a release is created

pkg/alertmanager/amcfg.go
Following my comment on #4468 that wrapping the returned error would be better.
cc @PhilipGough 
```release-note
```
=> pkg/alertmanager: wrap errors from store.GetSecretKey()

bundle.yaml, example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml, example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml, jsonnet/prometheus-operator/podmonitors-crd.json, jsonnet/prometheus-operator/probes-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/servicemonitors-crd.json, pkg/apis/monitoring/v1/types.go, pkg/prometheus/operator.go, pkg/prometheus/operator_test.go
Fixes #2503, #3942
This PR is to add validation for relabelling configs
```release-note
Added validations for relabel configs
```
=> pkg/prometheus: Add validations for relabel configs

bundle.yaml, example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml, jsonnet/prometheus-operator/thanosrulers-crd.json, pkg/apis/monitoring/v1/thanos_types.go
To be consistent with Prometheus and Alertmanager resources, `kubectl get thanosrulers` will display the number of configured replicas for each resource.
```release-note
add Replicas column for Thanos Ruler
```
=> pkg/apis: add Replicas column for Thanos Ruler

pkg/alertmanager/types.go
Close the drift between internal httpClientConfig and [the latest `HTTPClientConfig` from Prometheus ](https://github.com/prometheus/common/blob/00591a3ea9c0d18f6bc983818a23901d4154077f/config/http_config.go#L178-L199)
Add follow_redirects and support oauth config.
```release-note
Support following redirects and Oauth2 in HTTP Client config in raw alertmanager config …
```
=> alertmanager: Add follow_redirects and oauth fields to httpClientConfig

ADOPTERS.md
We are repeatedly failing link checking in `make check-docs`.
I believe we are being bitten by https://github.com/bwplotka/mdox/issues/22 since polarsignals.com redirects to www.polarsignals.com
Updated the link to avoid the redirect and circumvent bug in tooling.
=> docs: Update link in adopters file which fixes ci failures

pkg/k8sutil/k8sutil.go, pkg/versionutil/cli.go
The operator sets the User-Agent value to
"PrometheusOperator/<operator's version>".
```release-note
Set User-Agent for the kubernetes client.
```
=> pkg/k8sutil: set User-Agent for k8s client

Documentation/rbac.md, bundle.yaml, example/rbac/prometheus-operator/prometheus-operator-deployment.yaml, example/rbac/prometheus-operator/prometheus-operator-service-account.yaml, jsonnet/prometheus-operator/prometheus-operator.libsonnet, pkg/prometheus/statefulset.go
This is part of initiative to tighten security in kube-prometheus - https://github.com/prometheus-operator/kube-prometheus/issues/1589
This takes care of jsonnet deployment manifests for the operator itself (preventing token automount on SA level and specifying it directly on pod-level in Deployment object). Additionally, it explicitly specifies token automount for prometheus server, as without this kubernetes SD cannot work. Latter option allows to unset token automount on SA-level for prometheus server.
_What type of changes does your code introduce to the Prometheus operator? Put an `x` …
=> Specify SA token automounting on pod-level

pkg/alertmanager/operator.go, pkg/alertmanager/statefulset.go, pkg/prometheus/operator.go, pkg/prometheus/statefulset.go, pkg/thanos/operator.go, pkg/thanos/statefulset.go
```
We have observed an issue where the operator fails to update
a sts and must delete, recreate, a race can occur.
The delete is a foreground cascading delete which causes
the sts to remain visible via the API server for an unknown
amount of time.
We have observed for all resources, the operator is receiving a
multitude of update requests before the delete is finalized.
This is causing a hot-loop of delete, recreate cycles which in
some cases appear never to resolve without manual intervention
i.e. (deleting the sts in the background).
Since the foreground delete will add a …
```
=> Address race condition in recreate flow for statefulset

pkg/admission/admission.go, pkg/alertmanager/operator.go, pkg/alertmanager/validation.go, pkg/alertmanager/validation_test.go
checkAlertmanagerConfigResource() now calls ValidateAlertmanagerConfig()
first which is easier to maintain (IMHO) than the individual check*()
functions invoking their respective validate*() functions.
cc @PhilipGough 
```release-note
```
=> pkg/alertmanager: refactor validation of AlertmanagerConfig resources

pkg/operator/validations.go, pkg/prometheus/operator.go, pkg/prometheus/operator_test.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
This change adds validation for scrapeTimeout to avoid specifying
higher value than scrapeInterval at prometheus, servicemonitor, podmonitor and probe levels
Fixes #4485
```release-note
Added scrapeTimeout validation to avoid invalid value being accepted
```
=> pkg/prometheus: Add validation for ScrapeTimeout

bundle.yaml, example/rbac/prometheus-operator/prometheus-operator-deployment.yaml, jsonnet/prometheus-operator/prometheus-operator.libsonnet
This is part of the initiative to tighten security in kube-prometheus - https://github.com/prometheus-operator/kube-prometheus/issues/1595.
If a container, e.g. Prometheus-operator, needs to write to the filesystem, a strict volume mount should be used.
Following remediation docs from https://hub.armo.cloud/docs/c-0017
```release-note
Forbid write access to root …
```
=> jsonnet: Forbid write access to root filesystem

pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
This PR modifies the Prometheus StatefulSet to restore the liveness probe (follow-up of https://github.com/prometheus-operator/prometheus-operator/pull/3502 and https://github.com/prometheus-operator/prometheus-operator/pull/4369).
(I’m not sure if this is only a bugfix.)
```release-note
Restore Prometheus StatefulSet liveness probe so that deadlocks are detected and recovered from.
```
=> Restore Prometheus StatefulSet liveness probe

pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
Merging #4387 introduced syntax errors because the Handler field of the
HTTPProbe was changed to ProbeHandler.
This commit fixes the errors and makes sure the compilation succeeds again.
```release-note
```
=> Fix syntax errors after merge

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml, jsonnet/prometheus-operator/servicemonitors-crd.json, pkg/apis/monitoring/v1/types.go
Fix #4537 .
```release-note
```
=> optimize doc

.mdox.validate.yaml, Makefile
This PR tries to addresses the recent uptick of `mdox` CI failures (e.g, #4532, #4505) by increasing the request timeouts for `mdox` to one minute from the default 10s (as defined in [colly](https://github.com/gocolly/colly/blob/e63893d27834f749d7e2035c29ffe6c75c4c6ad4/colly.go#L980) which is the scraping framework used by mdox) and haven't come across the usual `net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)` error yet.
But other errors such as a TLS handshake timeout do happen from time to time.
Also, removes `ADOPTERS.md` from the list of checked files as content is not modified frequently, but is still error-prone.
Tested this a number of times locally and also on [GitHub Actions in my …
=> Make `mdox` less error-prone

Documentation/operator.md, cmd/operator/main.go, go.mod, go.sum, pkg/alertmanager/operator.go, pkg/operator/config.go
I want to use the operator to handle PrometheusRule CRDs in many namespaces but only handle Prometheus CRDs in one namespace.  I saw the default RBAC in the helm chart was far too broad and wrote my own, having secrets operations as Roles instead of ClusterRoles, attached only to the namespaces where I want to set up prometheus instances.  I noticed after setting `--namespaces` and `--prometheus-instance-selector` to different values, that list/watch of secrets was being attempted in the namespaces under `--namespaces`, with access denied.
Fixes #3544 (and #3298 in the case `--namespaces` …
=> use AlertmanagerConfigAllowList for alertmanager secret informer

pkg/alertmanager/statefulset.go, pkg/operator/config-reloader.go, pkg/prometheus/statefulset.go, pkg/thanos/statefulset.go
Following what has been done in https://github.com/prometheus-operator/kube-prometheus/pull/1610, https://github.com/prometheus-operator/kube-prometheus/pull/1600 and https://github.com/prometheus-operator/kube-prometheus/pull/1593. This PR also sets the same securityContext to all managed containers (I believe I haven't missed any 😅)
Prometheus statefulset still doesn't have `readonlyRootFilesystem: true`, because of https://github.com/prometheus-operator/prometheus-operator/issues/4562
_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that …
=> Add securityContext to managed containers

bundle.yaml, example/rbac/prometheus-operator/prometheus-operator-deployment.yaml, jsonnet/prometheus-operator/prometheus-operator.libsonnet
Signed-off-by: ArthurSens <arthursens2005@gmail.com>
This is part of the initiative to tighten security in kube-prometheus
We're reducing the attack surface by dropping all Linux capabilities since prometheus-operator doesn't need any to run smoothly
Following remediation docs from https://hub.armo.cloud/docs/c-0055
```release-note
Reduce attack surface by dropping Linux capabilities
```
=> jsonnet: Drop all linux capabilities

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/types.go
The remote read and write features are established enough in Prometheus
that we can drop the "EXPERIMENTAL" warning in the Prometheus CRD and
support them officially from now on.
If the format of the remote write/read configuration in Prometheus
changes in a breaking way, the operator should deal with it based on the
`spec.version` field of the Prometheus resource, just like it does for
other configuration fields.
```release-note
`remoteWrite` and `remoteRead` fields of the Prometheus CRD not considered experimental anymore.
```
=> *: mark remoteWrite and remoteRead as non-experimental

pkg/prometheus/promcfg_test.go
~~Not sure why the CI didn't catch it before but it looks like #4539 broke pkg/prometheus/promcfg_test.go.~~
Ok, the reason is that #4535 added `TestServiceMonitorWithEndpointSliceEnable` but it wasn't rebased on the most recent main.
```release-note
```
=> pkg/prometheus: fix test compilation after #4539

.github/workflows/e2e.yaml, .gitignore, Makefile, README.md, cmd/admission-webhook/Dockerfile, cmd/admission-webhook/main.go, cmd/operator/main.go, example/admission-webhook/deployment.yaml, example/admission-webhook/service-account.yaml, example/admission-webhook/service-monitor.yaml, example/admission-webhook/service.yaml, jsonnet/prometheus-operator/admission-webhook.libsonnet, pkg/admission/admission.go, pkg/operator/config.go, pkg/server/server.go, pkg/server/server_test.go, scripts/generate/admission-webhook.jsonnet, scripts/generate/build-admission-webhook-example.sh, scripts/push-docker-image.sh, test/framework/framework.go, test/framework/resources/alertmanager-config-validating-webhook.yaml, test/framework/resources/prometheus-operator-mutatingwebhook.yaml, test/framework/resources/prometheus-operator-validatingwebhook.yaml
Decouples the admission webhook logic into a standalone binary with the view to enabling a HA setup.
I don't view this as fully completing #4437, see [comment](https://github.com/prometheus-operator/prometheus-operator/issues/4437#issuecomment-1012080661), but I feel it could be merged as is without breaking anything.
* ~I have marked the relevant flags in the existing operator binary as deprecated.~ - reverted based on [comment](https://github.com/prometheus-operator/prometheus-operator/pull/4494#issuecomment-1012162998)
* I have marked four existing metrics as deprecated since I believe we can extract that info natively from the `apiserver_admission_webhook_rejection_count` and based on [this comment](https://github.com/prometheus-operator/prometheus-operator/pull/4494#discussion_r794361 …
=> Add standalone admission webhook

pkg/prometheus/operator.go, pkg/prometheus/operator_test.go
pkg/apis: Set default values for relabelConfigs
We had implemented validation logic for relabelling as in [prometheus](https://github.com/prometheus/prometheus/blob/9a2e93228e63a3fbac950ef0a639f754c3598c5d/model/relabel/relabel.go#L94-L133). Since default values for relabel configs are set [here](https://github.com/prometheus/prometheus/blob/9a2e93228e63a3fbac950ef0a639f754c3598c5d/model/relabel/relabel.go#L31-L36) in prometheus it works well but since default values in operator for these configs are not set explicitly [validation logic](https://github.com/prometheus-operator/prometheus-oper …
=> pkg/prometheus: Update validation for labelmap

pkg/prometheus/operator.go, pkg/prometheus/operator_test.go
Prometheus has a default relabel config that is different
from the natural zero values for the individual types.
The current validations create a situation where a valid configuration
that is marshaled and unmarshaled (e.g. when generating a
ServiceMonitor config) is suddenly no longer valid.
This changes the validation to accept both the zero values (as that
makes the most sense when writing the config by hand) and the
default config as it is used by Prometheus (see also
https://github.com/prometheus/prometheus/blob/v2.33.3/model/relabel/relabel.go#L122-L130). …
=> pkg/prometheus: support default relabel config in validation

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml, example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml, jsonnet/prometheus-operator/podmonitors-crd.json, jsonnet/prometheus-operator/probes-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/servicemonitors-crd.json, pkg/apis/monitoring/v1/types.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
This is a follow-up fix for #4598 (issue #4565).
This change also rewords the description of some fields.
```release-note
Added `__tmp_ingress_address` to preserve the initial host address of the ingress object.
```
=> *: Preserve ingress address in `__tmp_ingress_address`

pkg/client/listers/monitoring/v1/alertmanager.go, pkg/client/listers/monitoring/v1/podmonitor.go, pkg/client/listers/monitoring/v1/probe.go, pkg/client/listers/monitoring/v1/prometheus.go, pkg/client/listers/monitoring/v1/prometheusrule.go, pkg/client/listers/monitoring/v1/servicemonitor.go, pkg/client/listers/monitoring/v1/thanosruler.go, pkg/client/listers/monitoring/v1alpha1/alertmanagerconfig.go, pkg/client/versioned/clientset.go, pkg/client/versioned/fake/clientset_generated.go, pkg/client/versioned/fake/register.go, pkg/client/versioned/typed/monitoring/v1/fake/fake_alertmanager.go, pkg/client/versioned/typed/monitoring/v1/fake/fake_podmonitor.go, pkg/client/versioned/typed/monitoring/v1/fake/fake_probe.go, pkg/client/versioned/typed/monitoring/v1/fake/fake_prometheus.go, pkg/client/versioned/typed/monitoring/v1/fake/fake_prometheusrule.go, pkg/client/versioned/typed/monitoring/v1/fake/fake_servicemonitor.go, pkg/client/versioned/typed/monitoring/v1/fake/fake_thanosruler.go, pkg/client/versioned/typed/monitoring/v1/monitoring_client.go, pkg/client/versioned/typed/monitoring/v1alpha1/fake/fake_alertmanagerconfig.go, pkg/client/versioned/typed/monitoring/v1alpha1/monitoring_client.go
This is just a re-generation of the Kubernetes clients via the `make k8s-gen` command. A few comments and other small bits as generated by the Kubernetes tools have changed, which was resulting in a dirty tree after running this.
```release-note
```
=> Re-generate Kubernetes clients

Documentation/user-guides/running-exporters.md
Fix the service selector to target pods with the label `k8s-app: kube-state-metrics` as described in the documentation.
Fix typo in documentation.
=> Fix service selector

cmd/prometheus-config-reloader/main.go, cmd/prometheus-config-reloader/main_test.go, go.mod, go.sum
As discussed in #4273: proper configurable setup for config-reloader to support setting TLS parameter "skip TLS verify" when talking to Prometheus on a config reload. 
The only change is to the config-reloader command for skipping TLS verify. 
No flag is added since the solution intent was scoped to only supporting the config reloader for use in combination with the prometheus operator; no standalone application.
Support for this is then also not given. (Discussion can be found in the comments)
_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box …
=> TLS certificate verification skip for prometheus-config-reloader

Documentation/user-guides/webhook.md
ref issue 4618
Clarify distinction between behavior of prometheusrule webhooks.
_Clarify distinction between behavior of prometheusrule webhooks._
```release-note
```
=> clarify distinction between prometheusrule webhooks

.github/workflows/e2e.yaml, Makefile, example/admission-webhook/deployment.yaml, scripts/generate/admission-webhook.jsonnet, scripts/push-docker-image.sh, test/framework/framework.go
The end-to-end tests and jsonnet code were using
`quay.io/prometheus-operator/prometheus-admission-webhook` which doesn't
exist.
```release-note
```
=> *: use consistent image name for the admision webhook

bundle.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml, jsonnet/prometheus-operator/alertmanagers-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/thanosrulers-crd.json, pkg/apis/monitoring/v1/thanos_types.go, pkg/apis/monitoring/v1/types.go
pkg/apis/monitoring/v1: Add validations for log settings at CRD level
Related-to #4524
pkg/apis/monitoring/v1: Add validations for log settings at CRD level
```release-note
pkg/apis/monitoring/v1: Add validations for log settings at CRD level
```
=>  pkg/apis/monitoring/v1: Add validations for log settings at CRD level

test/e2e/alertmanager_test.go, test/framework/alertmanager.go
testUserDefinedAlertmanagerConfigFromSecret() starts failing with
Alertmanager v0.24.0-rc.0 because this version enforces no matcher on
the root route. Detected by #4644.
```release-note
```
=> test: remove matchers on root route

example/thanos/prometheus.yaml, example/thanos/query-deployment.yaml, example/thanos/thanos-ruler.yaml, jsonnet/thanos/config.libsonnet
thanos image v0.11.2 doesn't exist in the repository.
Fixes #4662
The examples have thanos image tag v0.11.2 with quay.io thanos / thanos registry.
But v0.11.2 doesn't exist in the registry.
As a result, example deployment failed to pull image.
```release-note
Update example thanos image tag to v0.25.1
```
=> example: update thanos version to v0.25.1

test/e2e/prometheus_test.go, test/framework/prometheus.go
Signed-off-by: santosh <bsantosh@thoughtworks.com>
e2e tests: Use prometheus as remote receiver for testPromRemoteWriteWithTLS
sample app is doubling up as a scrape target as well the receiver endpoint.
With this change, we would launch another prometheus with remote-write-receiver feature enabled and use it as receiver instead. We would run queries against receiver prometheus to validate if remote write was successful.
[fixes#4319](https://github.com/prometheus-operator/prometheus-operator/issues/4319)
```release-note
e2e tests: Use prometheus as remote receiver …
```
=> e2e tests: Use prometheus as remote receiver for testPromRemoteWriteWithTLS

pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go, pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go, pkg/alertmanager/statefulset.go, pkg/alertmanager/validation.go
This change reorganizes the code to have a clearer separation between
the different modes:
* Alertmanager configuration obtained from secret
* Alertmanager configuration obtained from AlertmanagerConfig objects
```release-note
```
=> pkg/alertmanager: refactor configuration provisioning

example/mixin/alerts.yaml, jsonnet/mixin/alerts/alerts.libsonnet
The alert expression has a time range of 10 minutes so it will not resolve "quickly" if the operator experiences a transient burst of watch errors.
Given that metrics are scraped every 30 seconds, it would be better to use a time range of 5 minutes (consistent with what Prometheus & Alertmanager are doing).
```release-note
Updated the time range for the alert PrometheusOperatorWatchErrors from 10m to 5m
```
=> Update time range for alert PrometheusOperatorWatchErrors

pkg/alertmanager/operator.go, pkg/operator/operator.go, pkg/prometheus/operator.go, pkg/thanos/operator.go
Signed-off-by: heylongdacoder <heylongdacoder@gmail.com>
_Fixes #3408 ._
```release-note
Add prometheus_operator_reconcile_duration_seconds histogram metrics
```
=> Add prometheus_operator_reconcile_duration_seconds histogram metrics

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml, example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml, jsonnet/prometheus-operator/podmonitors-crd.json, jsonnet/prometheus-operator/probes-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/servicemonitors-crd.json, pkg/apis/monitoring/v1/types.go, pkg/apis/monitoring/v1/zz_generated.deepcopy.go, pkg/operator/validations.go, pkg/prometheus/operator.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go, test/e2e/prometheus_test.go
pkg/apis: Add validations for time settings of prometheus at CRD level
test: Update e2e test for CRD validation
This is needed to avoid invalid values from user which would
cause problem for application to load or not work as expected
Related-to https://github.com/prometheus-operator/prometheus-operator/issues/4524
**Note:**  I haven't full covered all time fields in this since alertmanager uses time.ParseDuration for a few and I don't want to mix different types in same PR. 
pkg/apis: Add validations for time settings of prometheus at CRD …
=> pkg/apis: Add validations for time settings of prometheus at CRD level

.mdox.validate.yaml, MAINTAINERS.md, RELEASE.md
docs.github.com always return a 403 error when not requested from a browser.
```release-note
```
=> *: add docs.github.com to mdox exceptions

test/e2e/prometheus_test.go, test/framework/pod.go
I spotted that `testPromWebTLS()` started failing more often due to port forwarding not working as expected. Lets see if retrying helps.
```release-note
```
=> test: improve resiliency of testPromWebTLS()

pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go, pkg/alertmanager/types.go
Fixes #4714
```release-note
Fixed support for OpsGenie configurations with `api_key_file`. 
```
=> pkg/alertmanager: add support for `api_key_file` in OpsGenie config

pkg/prometheus/operator.go, pkg/prometheus/operator_test.go
The operator computes a hash value which is derived from different
inputs such as the Prometheus object, the operator's configuration, the
StatefulSet spec, etc. The operator records the hash value as an
annotation on the generated StatefulSet then it compares the current and
new values to decide whether an update of the StatefulSet is needed or
not.
Because the operator updates the status subresource in parallel, the
status field of the Prometheus object should not be taken into account
to compute the hash value.
The issue was indirectly detected when bumping the downstream github.com/openshift/prometheus-operator to v0.56.0. After this, we noticed more failures in the CI that could be explained by the Prometheus operator doing too many updates of the Prometheus statefulset. After …
=> pkg/prometheus: exclude status from hash computation

pkg/k8sutil/merge.go, pkg/k8sutil/merge_test.go
PR #4641 introduced a regression in MergePatchContainers(): the ordering
of the returned slice wasn't stable anymore meaning that the operator
could generate different StatefulSets from the same input parameters
leading to unnecessary deletions/creations of the pods.
```release-note
Avoid unnecessary creations and …
```
=> pkg/k8sutil: fix ordering in MergePatchContainers()

pkg/prometheus/operator.go, pkg/prometheus/operator_test.go, test/e2e/prometheus_test.go
Since the operator modifies the Prometheus status subresource, the
update event handler is called much more often than before which may
lead to higher CPU usage. To reduce the number of times the operator
runs the sync() method, it now compares the generation + labels +
annotations between the old and new objects (instead of using the
`resourceVersion` field) to decide whether a reconciliation is needed or
not. The same change is made for StatefulSet update handler.
This is inspired by `GenerationChangedPredicate`,
`LabelChangedPredicate` and `AnnotationChangedPredicate` from
controller-runtime.
Closes #4784 …
=> pkg/prometheus: reduce the number of reconciliations

example/mixin/alerts.yaml, jsonnet/mixin/alerts/alerts.libsonnet, jsonnet/mixin/config.libsonnet
At the moment the alert metrics are hardcoded to have only two labels, controller and namespace. This might be inconvenient. For example when managing multiple clusters, you might want to add a cluster-id label to your alerts. This change makes it possible to add custom labels similar to custom selectors.
```release-note
Add groupLabels config option to jsonnet mixin for alert label customization
```
=> jsonnet/mixin: add config option for group labels

pkg/alertmanager/amcfg.go
This is a small change to optimise noisy warning message when sanitizing opsgenie config. The warning should be logged only if both APIKey and APIKeyFile are configured. The PR adds a condition to check the same.
opsgenie-config: optimise warning log message during sanitize
```release-note
```
=> opsgenie-config: optimise warning log message during sanitize

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, jsonnet/prometheus-operator/alertmanagers-crd.json, pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, pkg/alertmanager/validation/validation.go, pkg/apis/monitoring/v1/types.go, test/e2e/alertmanager_test.go, test/e2e/main_test.go
This is needed to avoid invalid values from user which would
cause problem for application to load or not work as expected
Related-to prometheus-operator#4524
```release-note
Add validations for time settings of alertmanager at CRD level
```
=> pkg/apis: Add validations for time settings of alertmanager at CRD level

pkg/apis/monitoring/v1beta1/conversion_from.go, pkg/apis/monitoring/v1beta1/conversion_to.go
The `followRedirects` field was missed in #4709.
```release-note
Fixed missing conversion of the `followRedirects` field in HTTP configuration for AlertmanagerConfig v1beta1.
```
=> pkg/apis/monitoring/v1beta1: fix httpConfig conversion

pkg/prometheus/operator.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
makeStatefulSet() and friends should reuse the logger from the caller instead of creating a new logger.
cc @slashpai since you're mentioned in the TODO :)
```release-note
```
=> pkg/prometheus: don't instantiate a new logger

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml, example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml, example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml, jsonnet/prometheus-operator/podmonitors-crd.json, jsonnet/prometheus-operator/probes-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/servicemonitors-crd.json, pkg/apis/monitoring/v1/types.go, pkg/prometheus/operator.go, pkg/prometheus/operator_test.go
pkg/prometheus: Support upppercase and lowercase relabel actions
prometheus/prometheus#10641 introduced two
new relabel actions uppercase and lowercase. This commit
is to allow those actions using operator
```release-note
Add support for `uppercase` and `lowercase` relabel actions
```
=>  pkg/prometheus: Support upppercase and lowercase relabel actions

bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml, example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml, example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml, jsonnet/prometheus-operator/podmonitors-crd.json, jsonnet/prometheus-operator/probes-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/servicemonitors-crd.json, pkg/apis/monitoring/v1/types.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Adds support to specify relabel actions in CamelCase format
to follow https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#constants
and at the same time always downcase the value in the generated config.
Eventually remove the lowercase way of specifying actions once
monitoring.coreos.com/v2 is created …
=> pkg/apis: Add support to specify relabel actions in CamelCase

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/types.go, pkg/apis/monitoring/v1/zz_generated.deepcopy.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Looks like I missed this field in alertmanager in previous validation PR
Related-to #4524
```release-note
Add validation for Alertmanager timeout
```
=> pkg/apis: Add openapi validation for alertmanager timeout

pkg/alertmanager/amcfg.go
Signed-off-by: Ziqi Zhao <zhaoziqi9146@gmail.com>
fix #4715 
fix AlertmanagerConfig.Spec.Route nil panic
=> fix alertmanagerConfig.Spec.Route nil panic

pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go
Follow-up of #4853.
```release-note
```
=> pkg/alertmanager: add unit test for missing route

Documentation/api.md, scripts/docs/templates/pkg.tpl
The right navigation button of the Troubleshooting page should link to the API reference page.
```release-note
```
=> Fix weight of API reference documentation

pkg/alertmanager/operator.go, pkg/k8sutil/k8sutil.go, pkg/prometheus/operator.go, pkg/prometheus/rules.go, pkg/thanos/operator.go, pkg/thanos/rules.go, test/e2e/main_test.go, test/e2e/prometheus_test.go
Based on https://github.com/kubernetes/client-go/issues/308 the type meta is erased on object returned by cache informers.
`excludedFromEnforce` functionality introduced in #4397 is requiring the Kind and APIVersion for filtering.
Explicitly set them for each object type to have them available in filtering
```release-note
Fix Namespace enforcement exclusion on newly created Prometheus objects 
```
=> Namespace enforcement exclusion fails due to missing object type meta

pkg/prometheus/statefulset.go
Stating promtheus-operator v0.56.0, by default thanos-sidecar container failed to upload blocks to object storage as explained in https://github.com/prometheus-operator/prometheus-operator/issues/4928. This PR adds necessary permissions to thanos-sidecar container under securityContext level so that hard link creation action will be successful as it was needed before uploading block to object storage
_Please put a one-line changelog entry below. This will be copied to the changelog …
=> Add CAP_FOWNER capability to thanos-sidecar container

pkg/alertmanager/statefulset.go, pkg/prometheus/statefulset.go, pkg/thanos/statefulset.go
Remove unnecessary code:
* support for Prometheus v1 has gone away long time ago.
* makeStatefulSetSpec() functions don't need to deep-copy the object since it already happened before.
```release-note
```
=> [tech debt] clean up makeStatefulSetSpec() functions

bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/types.go
Reverts prometheus-operator/prometheus-operator#4735
In light of #4946 this needs some adjustments to make it compatible with HPA:
* it should scale the number of shards rather than the number of replicas.
* it should add a `selectorpath` (see https://book.kubebuilder.io/reference/generating-crd.html#scale)
=> Revert "pkg/apis: Add scale subresource for Prometheus"

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml, jsonnet/prometheus-operator/thanosrulers-crd.json, pkg/apis/monitoring/v1/thanos_types.go, pkg/thanos/statefulset.go, pkg/thanos/statefulset_test.go
Add the TracingConfigFile option to the Thanos Ruler similar to the Sidecar in in Prometheus spec.
This us useful/needed when the tracing config is a configmap and not a secret.
```release-note
Add TracingConfigFile option to ThanosRuler
```
=> Add TracingConfigFile option to ThanosRuler

Documentation/design.md
In the [PrometheusRule](https://prometheus-operator.dev/docs/operator/design/#prometheusrule)'s design description, it says
> Alerts and recording rules are reconciled by the Operatorand dynamically loaded without requiring any restart of Prometheus/Thanos Rulre.
and I think the space is missing between `Operator` and `and`. This PR adds it.
```release-note
```
=> Fix:  add missing space in `PrometheusRule` design description

.github/workflows/release.yaml, .gitignore, Makefile
Workaround for `kubectl apply` failing because of annotation being too
long.
Running `make stripped-down-crds.yaml` will generate a version of the CRDs with all description fields removed.
```release-note
```
=> Makefile: add stripped-down-crds.yaml target

pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
When configuring the Thanos sidecar to upload blocks to object storage, the container needs to the CAP_FOWNER capability. Otherwise it isn't required. This is a small improvement on top of #4931 to avoid granting more capabilities than needed.
```release-note
Removed CAP_FOWNER capability for the Thanos sidecar if it isn't needed.
```
=> pkg/prometheus: add CAP_FOWNER capability to Thanos only if needed

pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, pkg/k8sutil/k8sutil.go, pkg/k8sutil/k8sutil_test.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go, pkg/webconfig/config_test.go, test/e2e/main_test.go, test/e2e/prometheus_test.go
#4988 (84ffc50f68f619c0cb2e3e6999ea267a259b4635) introduced a change breaking users that pass additional secrets & configmaps and want to mount them in additional containers. In practice, the aforementioned commit appends a hash suffix to the volume name which makes it impossible for a user to reference the volume in a sidecar container.
This PR reverts to the old behavior for user-provided secrets/configmaps: the volume name is identical to the object name, except that invalid characters are replaced by `-` and the string is truncated to 63 chars.
```release-note …
```
=> Fixed secret and configmap volume names that need to be mounted in additional containers

pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
The capability added for fixing #4928 is not working, since it needs to be specified without the `CAP_` prefix as stated on [https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-capabilities-for-a-container](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-capabilities-for-a-container)
```release-note
fix: this remove the CAP_ prefix of the FOWNER capability on thanos-sidecar
```
=> fix: thanos-sidecar fowner capabilities

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/types.go, pkg/prometheus/operator.go, test/framework/prometheus.go
This is adding a new `ObservedGeneration int64 `json:"observedGeneration,omitempty"` to the `PrometheusCondition`. 
```release-note
```
=> feat: add observedGeneration attribute to the status conditions

pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
After hearing from different users, it doesn't seem like the Thanos sidecar needs the `FOWNER` capability. From a security standpoint, it's better not to ask for a capability that isn't required. And even if it is needed in some environments, it can be added using the strategic merge patch technique.
Closes #5023
```release-note
Removed FOWNER capability from the …
```
=> pkg/prometheus: remove FOWNER capability for Thanos sidecar

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml, jsonnet/prometheus-operator/alertmanagerconfigs-crd.json, jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet, pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go, pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
The current non-ascii apostrophe in API description for alertmanagerconfigs is using a non-ascii character as apostrophe in several places. This leads to certain tools having issues parsing/decoding the resulting CRD yamls.
*Before update*
```sh
file monitoring.coreos.com_alertmanagerconfigs.yaml
monitoring.coreos.com_alertmanagerconfigs.yaml: Unicode text, UTF-8 text
```
*After update*
```sh
file monitoring.coreos.com_alertmanagerconfigs.yaml 
monitoring.coreos.com_alertmanagerconfigs.yaml: ASCII text
```
```release-note
replace non ascii characters in descriptions …
```
=> replace non ascii apostrophe

.github/workflows/e2e.yaml, test/e2e/alertmanager_instance_namespaces_test.go, test/e2e/alertmanager_test.go, test/e2e/denylist_test.go, test/e2e/main_test.go, test/e2e/prometheus_instance_namespaces_test.go, test/e2e/prometheus_test.go, test/e2e/thanosruler_test.go, test/e2e/upgradepath_test.go, test/framework/admission-webhooks.go, test/framework/cluster_role.go, test/framework/cluster_role_binding.go, test/framework/crd.go, test/framework/deployment.go, test/framework/framework.go, test/framework/helpers.go, test/framework/namespace.go, test/framework/prometheus.go, test/framework/role-binding.go, test/framework/secret.go, test/framework/service.go, test/framework/service_account.go
PR #4758 was reverted because it broke CI. CI failed because it was out of sync with the main branch for a long time and some of the function signature changed.
This commit is based on PR #4758 and fix CI function signature error.
Fixes: #4067
Signed-off-by: heylongdacoder <heylongdacoder@gmail.com>
```release-note
```
=> test: re-add e2e test for Prometheus Operator upgrade path

Documentation/api.md, Makefile, pkg/apis/monitoring/v1/thanos_types.go
This got missed (and never noticed!) since #4899.
```release-note
```
=> *: Add ThanosRuler CRD to API reference

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/types.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
When `spec.thanos.listenLocal` is true, both gRPC and HTTP endpoints are configured to listen on the loopback interface. It is sometimes needed to listen on all interfaces for gRPC and on the loopback interface only for HTTP.
This commit introduces the `spec.thanos.grpcListenLocal` and `spec.thanos.httpListenLocal` fields to enable all possible use cases. `spec.thanos.listenLocal` is marked as deprecated since the new fields offer equivalent possibilities with fine-grained controls.
```release-note
Added `grpcListenLocal` and `httpListenLocal` fields to the Thanos …
```
=> pkg/prometheus: add `{grpc,http}ListenLocal` for Thanos sidecar

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, jsonnet/prometheus-operator/alertmanagers-crd.json, pkg/apis/monitoring/v1/types.go
xref https://github.com/prometheus-operator/website/issues/13
```release-note
```
=> *: fix unescaped characters in API doc

bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml, jsonnet/prometheus-operator/alertmanagers-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/thanosrulers-crd.json, pkg/apis/monitoring/v1/thanos_types.go, pkg/apis/monitoring/v1/types.go
This change adds the Available and Reconciled status to the `kubectl get prometheus` output.
```
$ oc get prometheus
NAME         VERSION   DESIRED   READY   RECONCILED   AVAILABLE   AGE
prometheus   v2.37.0   2         2       True         True        17d
```
The output also shows the Paused status when using the wide format.
```release-note
Add AVAILABLE and RECONCILED conditions to kubectl get output
```
=> *: show Prometheus conditions in kubectl get

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/types.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
Enabled support for "hostNetwork" in Prometheus Operator for Prometheus
Needed in many scenarios like:
1. To bypass the CNI network
2. In general to reduce the metrics traffic overhead on CNI network in clusters with large no of Nodes.
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
```release-note
feat : enable support for "hostNetwork" in Prometheus CRD
```
Fixes #2630
=> feat : enable support for "hostNetwork" in Prometheus CRD

pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go, pkg/operator/operator.go, pkg/operator/resource_reconciler.go, pkg/prometheus/operator.go, pkg/thanos/operator.go
This change extracts the code that watches statefulset-based resources and deals with state reconciliation. The PR reuses the same logic across Prometheus, Alertmanager and ThanosRuler which would facilitate the implementation of the status subresource for all of them.
```release-note
```
=> Refactor controller

Makefile
The release workflow failed because goyamltojson wasn't installed: 
https://github.com/prometheus-operator/prometheus-operator/actions/runs/3202923212/jobs/5232418936
```release-note
```
=> Makefile: fix stripped-down-crds.yaml target

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Closes #5076 
```release-note
Fixed generated configuration when `spec.tsdb.outOfOrderTimeWindow` is set.
```
=> pkg/prometheus: fix tsdb config generation

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, jsonnet/prometheus-operator/alertmanagers-crd.json, pkg/apis/monitoring/v1/types.go
It clarifies where the additional keys from the Alertmanager secret are located.
```release-note
```
=> pkg/apis/monitoring/v1: improve configSecret doc

example/admission-webhook/deployment.yaml, jsonnet/prometheus-operator/admission-webhook.libsonnet, test/framework/framework.go
Enables good default values (hard anti-affinity + rolling update maxUnavailable) ensuring no downtime on update when replicas > 1.
```release-note
Updated admission webhook deployment's jsonnet to avoid down-time on updates. 
```
=> jsonnet: improve admission webhook deployment to avoid down-time on updates

Documentation/user-guides/storage.md
The kubectl command had a typo.
```release-note
```
=> Documentation/user-guides/storage.md: fix typo

pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go, pkg/alertmanager/validation/validation.go, pkg/operator/validations.go, pkg/prometheus/operator.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, pkg/thanos/statefulset.go, pkg/thanos/statefulset_test.go
pkg: Remove validations which is already covered at CRD level
Update unit tests as well to incorporate this change
```release-note
pkg: Remove validations which is already covered at CRD level
```
=> pkg: Remove validations which is already covered at CRD level

example/admission-webhook/deployment.yaml, example/admission-webhook/service.yaml, jsonnet/prometheus-operator/admission-webhook.libsonnet, scripts/generate/admission-webhook.jsonnet, test/framework/framework.go, test/framework/resources/prometheus-operator-mutatingwebhook.yaml
The admission webhook service has to deployed with TLS enabled because the Kubernetes API only supports webhook URLs with a "https://" scheme.
This change also cleans up the end-to-end tests: there's no need to configure the Prometheus operator with TLS enabled since the Kubernetes API is configured to contact the dedicated admission webhook service.
```release-note
jsonnet: Enforced existence of the TLS secret for the admission webhook deployment.
jsonnet: Changed default port of the admission webhook service from 8443 to 443.
```
=> jsonnet: enforce TLS secret for the admission webhook

go.mod, go.sum
In the `go.mod` file it uses replace directive for github.com/prometheus/prometheus to replace the placeholder version of 1.99 with the latest version 0.38.1.
This PR will remove the prometheus package out of the replace directive, so that we can use directly the version 0.x.y which follows the real version 2.x.y. Next time when we update go packages using `go get -u github.com/prometheus/prometheus`, it will pick the latest version without modifying the replace directive.
```release-note
```
=> Remove "replace" directive of github.com/prometheus/prometheus in go.mod

Documentation/thanos.md
Replace deprecated usage of `baseImage` and `version` with the `image` field. Minor improvement to example text.
Signed-off-by: Paul Gier <paul.gier@datastax.com>
Updating the docs to remove use of deprecated API in the example.
- [ X ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)
update deprecated API usage in thanos readme
```release-note
update deprecated API usage in thanos readme
```
=> Documentation/thanos.md: update deprecated config example

pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go
Issue: https://github.com/prometheus-operator/prometheus-operator/issues/5130
Problem: Alertmanager supports both roleARN and access and secret keys for Sigv4 authentication, however in the current implementation of prometheus-operator the code does not check if the user has provided access and secret keys and simply calls GetSecretKey, if the user uses roleARN this will generate access to a nil pointer
Solution: Before calling GetSecretKey validate that the user has indeed provided access and a secret key
```release-note
Fixes nil pointer when roleARN is used …
```
=> Fixes nil pointer when roleARN is used instead of access and secret keys

Documentation/user-guides/exposing-prometheus-and-alertmanager.md
Only a single occurence in Documentation/user-guides/exposing-prometheus-and-alertmanager.md
Correct a single occurence of wrong containerPort number for alertmanager service in Documentation,
in the file Documentation/user-guides/exposing-prometheus-and-alertmanager.md
```release-note
Correct a typo with a single occurence in user-guides Documentation.
```
=> docs: Fix wrong containerPort for alertmanager svc

Documentation/user-guides/running-exporters.md
The change includes the current behavior of PodMonitor and ServiceMonitor objects. It also includes a reference of how to disable the behavior if needed. This should provide an answer to questions like #4065 and #4894 before they are opened.
```release-note
Add documentation of default monitor labels and how to configure them
```
Signed-off-by: Jeff Mace <jmace@vmware.com>
=> docs: Add documentation of default labels for monitor objects

pkg/admission/admission.go, pkg/operator/rules.go, pkg/operator/rules_test.go, pkg/prometheus/rules.go, pkg/prometheus/rules_test.go, pkg/thanos/rules.go
partial_response_strategy field is only applicable for Thanos so if a user sets this by mistake in PrometheusRule object prometheus errors this field is not found in rule format.
This commit is to fix that and allow this field only for Thanos
Fixes #5124
```release-note
Ignore PartialResponseStrategy for Prometheus …
```
=> pkg/prometheus: Ignore PartialResponseStrategy for Prometheus

pkg/thanos/statefulset.go, pkg/thanos/statefulset_test.go
Issue: https://issues.redhat.com/browse/OCPBUGS-2778
Problem: Some arguments are currently being passed to ThanosRuler using ENV vars. Those arguments are QueryConfig, AlertManagerConfig, ObjectStorageConfig and TracingConfig. These arguments should instead be read directly from the secrets instead of using ENV vars.
Solution: Modify the code to mount the secrets in the SecretKeySelector instead of assigning them to ENV variables
```release-note
-  ThanosRuler arguments (QueryConfig, AlertManagerConfig, ObjectStorageConfig and TracingConfig) are now directly read …
```
=> Modifies ThanosRuler arguments to be read from secrets instead of using ENV vars

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml, jsonnet/prometheus-operator/thanosrulers-crd.json, pkg/apis/monitoring/v1/thanos_types.go, pkg/thanos/statefulset.go, pkg/thanos/statefulset_test.go
```release-note
Added Thanos version field to CRD
```
=> pkg/apis: Add Thanos version field to CRD

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/types.go, pkg/apis/monitoring/v1/zz_generated.deepcopy.go, pkg/prometheus/operator.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Close: https://github.com/prometheus-operator/prometheus-operator/issues/4892
Problem: prometheus-operator implements multiple authentication methods for Prometheus to authenticate with Alertmanager instances but it does support basicAuth
Solution: this PR introduces basicAuth to the type AlertmanagerEndpoints
```release-note
Adds basicAuth to AlertmanagerEndpoints
```
=> Adds basicAuth to AlertmanagerEndpoints

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml, jsonnet/prometheus-operator/alertmanagers-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/thanosrulers-crd.json, pkg/apis/monitoring/v1/types.go
Close: https://github.com/prometheus-operator/prometheus-operator/issues/4922
Problem: StorageSpec defines the API for both Prometheus and Alertmanager but the comments only mentioned Prometheus. Furthermore, a hint was added for those who would like to control Volume management outside of the CRs
Solution: improve API documentation
```release-note
```
=> docs: Improves StorageSpec documentation

pkg/thanos/statefulset.go, pkg/thanos/statefulset_test.go
PR that introduced the regression: https://github.com/prometheus-operator/prometheus-operator/pull/5122
In the PR above Thanos started reading arguments from secrets instead of ENV vars, however, in the change, we forgot to specify a Path that is necessary when working with projection of secret keys to specific paths as can be seen in the k8s documentation [1]
[1] https://kubernetes.io/docs/concepts/configuration/secret/#projection-of-secret-keys-to-specific-paths
```release-note
Fixes regression introduced in thanos/statefulset.go when reading arguments from …
```
=> Fixes regression introduced in thanos/statefulset.go when reading arguments from secrets

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml, jsonnet/prometheus-operator/alertmanagers-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/thanosrulers-crd.json, pkg/apis/monitoring/v1/thanos_types.go, pkg/apis/monitoring/v1/types.go
Close: https://github.com/prometheus-operator/prometheus-operator/issues/5067
Problem: the field StatefulSetMinReadySeconds was introduced in 1.22 and until 1.25 when it stopped being alpha this field is not reset in the statefulset code, this makes it so if the field is specified and the feature gate is not enabled the stateful will just crash loop
Solution: improve the field comments to prevent users from using it if the feature is not enabled
```release-note
Improves comment on field MinReadySeconds for CommonPrometheusFields and AlertmanagerSpec
```
=> Improves comment on field MinReadySeconds for CommonPrometheusFields and AlertmanagerSpec

Documentation/user-guides/webhook.md
The goal of the change is:
* make it possible to include the webhook documentation on prometheus-operator.dev
* refresh the content
* encourage people to use cert-manager (or similar solution) to ease the deployment
```release-note
```
=> Documentation: update webhook guide

bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusrules.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml, jsonnet/prometheus-operator/prometheusrules-crd.json, pkg/apis/monitoring/v1/types.go
In PrometheusRule->RuleGroup structure, the property `PartialResponseStrategy` has an explicit default value set to an empty string, which is unnecessary and may cause some non-semantic comparator functions to return inequality when the property `PartialResponseStrategy` is omitted on either side. 
In the example below,  when applying a PrometheusRule object without the property `PartialResponseStrategy`, kubernetes will add that field with default value. 
```yaml
kind: PrometheusRule
metadata:
creationTimestamp: "2022-11-28T15:40:10Z"
generation: 1
labels:
app.kubernetes.io/component: exporter
app.kubernetes.io/name: kube-state-metrics
app.kubernetes.io/part-of: openshift-monitoring
app.kubernetes.io/version: 2.6.0
prometheus: k8s
role: alert-rules
name: kube-state-metrics-rules …
```
=> remove setting empty defalt value in CRD PrometheusRule.

pkg/alertmanager/statefulset.go, pkg/operator/image.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
Close: https://github.com/prometheus-operator/prometheus-operator/issues/4893
Problem: since the inception of the operator a lot of options were introduced to customize the image ran by the statefulset for both Prometheus and Alertmanager, this made it so some inconsistencies on how the version is calculated were introduced between the two.
Solution: this commit introduces the function GetVersion which has the goal of returning the tag of the image that will be used in the statefulsets. If the image is tagless or uses a SHA256 it will instead return the DefaultVersion for that component if Spec.Version is not defined.
_Please put a one-line changelog entry below. This will be …
=> Standardize how the Prometheus and Alertmanager versions are calculated

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml, jsonnet/prometheus-operator/alertmanagers-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/thanosrulers-crd.json, pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, pkg/apis/monitoring/v1/thanos_types.go, pkg/apis/monitoring/v1/types.go, pkg/operator/config-reloader.go, pkg/operator/config-reloader_test.go, pkg/operator/config.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go, pkg/thanos/statefulset.go, pkg/thanos/statefulset_test.go
Should be able to set imagePullPolicy for pods.
Fixes https://github.com/prometheus-operator/prometheus-operator/issues/2747
```release-note
Added ability to specify imagePullPolicy
```
=> Added ability to specify imagePullPolicy

test/e2e/main_test.go, test/e2e/thanosruler_test.go, test/framework/alertmanager.go, test/framework/thanosruler.go
Issue: https://github.com/prometheus-operator/prometheus-operator/issues/5187
The goal of the test is to validate the path TR -> Alertmanager.
We will create a firing alert that Thanos Ruler should propagate to
alertmanger.
```release-note
```
=> Introduces e2e test testTRAlertmanagerConfig

pkg/prometheus/operator.go, pkg/prometheus/promcfg.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
Problem: depending on the Prometheus version used some command line
arguments are valid where others aren't and the operator should log
a warning. Previously this was done with an "if/else" statement, however
since the operator now has ConfigGenerator we can use it to simplify the
code
Solution: start using the ConfigGenerator in prometheus/statefulset.
Unfortunately, when providing a default for a certain version or above it's not
entirely possible to get rid of the "if" part of the original "if/else"
statement
```release-note
Refactors version checks on …
```
=> Refactors version checks on prometheus/statefulset.go to use ConfigGenerator

pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go, pkg/alertmanager/types.go
Alertmanager v0.25.0 introduces new notifiers (Discord, Webex) + configuration fields that the operator needs to sanitize.
Global configuration:
* `smtp_auth_password_file`
* `victorops_api_key_file`
HTTP client configuration:
* `proxy_url` for OAuth2
* `min_version` & `max_version` for TLS
* `enable_http2`
Email configuration:
* `auth_password_file`
PagerDuty configuration:
* `routing_key_file`
* `service_key_file`
* `source`
VictorOps configuration:
* `api_key_file`
```release-note
Supported new fields from Alertmanager v0.25.0
```
=> pkg/alertmanager: sanitize configuration for v0.25.0

pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go, pkg/alertmanager/types.go
Alertmanager v0.25.0 introduces a new `location` field for time intervals. This change strips the field if the Alertmanager version isn't compatible.
```release-note
Support Location field for Alertmanager >= v0.25.0
```
=> pkg/alertmanager: sanitize Location field

.github/workflows/stale.yaml
The default value of 30 is too low for the repository and the action fails to process all issues and pull requests.
```release-note
```
=> Increase 'operations-per-run' for the stale action

pkg/alertmanager/operator_test.go, test/e2e/alertmanager_test.go
Signed-off-by: JoaoBraveCoding <jmarcal@redhat.com>
Goal is to try and clarify what each test is testing
```release-note
```
=> Adds comments to test related with AlertmanagerConfig

pkg/alertmanager/amcfg.go
Fixes #5253
Fixes unsupported types reported in #5253 
```release-note
Fix unsupported types in alertmanager route sanitizer log lines
```
=> fix: Unsupported types in log lines

pkg/apis/monitoring/v1/podmonitor_types_test.go, pkg/apis/monitoring/v1/probe_types_test.go
Re-adding tests from #4222 
Closes #4222 
```release-note
```
=> apis/v1: Add tests from #4222

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/prometheus_types.go
Fixes #5300
Rewording deprecation notices on `serviceMonitorSelector` and `podMonitorSelector` as per #5300.
```release-note
```
=> docs: Reword deprecation notices on *MonitorSelector

pkg/alertmanager/statefulset.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
Changes the emptyDir that is used to store Prometheus and Alertmanager configuration to use `tmpfs`. While the content is still readable if the host gets invaded while running, the data is wiped once the host is turned off, preventing leaking data from disks.
```release-note
Use tmpfs to store Prometheus and Alertmanager configuration
```
=> Use tmpfs to store Prometheus/Alertmanager config

pkg/operator/config.go, pkg/thanos/statefulset.go, pkg/thanos/statefulset_test.go
Signed-off-by: JoaoBraveCoding <jmarcal@redhat.com>
Issue: fixes #5317
Problem: see issue #5317
Solution: add arguments to Thanos container by iterating over the sorted list of the keys of the map ThanosRuler.Spec.Labels
```release-note
- fixes ThanoRuler StatefulSet re-creation bug if labels specified
```
=> Fixes ThanoRuler StatefulSet re-creation bug

pkg/alertmanager/operator.go, pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, pkg/operator/config.go, pkg/operator/config_reloader.go, pkg/operator/config_reloader_test.go, pkg/operator/config_reloader_test_lib.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go, pkg/thanos/operator.go, pkg/thanos/statefulset.go, pkg/thanos/statefulset_test.go
Problem: The name ReloaderConfig conflicted with the function under pkg/operator/config_reloader.go that would set ReloaderConfig, this function was previously called ReloaderResources which did not indicate clearly that other fields like image were also being configured. Furthermore each pkg/*/statefulset_test.go file was testing extensively the resources for the ReloadConfig sidecar which created a lot of code duplication.
Solution: Rename the type ReloaderConfig to ReloaderOperatorConfig since the config comes from the operator and refactor tests to extract the logic to the resources tests for ReloadConfig sidecar into a dedicated lib under pkg/operator/config_reloader_test_lib.go
_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that …
=> Renames ReloaderConfig to ReloaderOperatorConfig and refactors pkg/*/statefulset_test

Documentation/proposals/202212-scrape-config.md
This is a first shot at a proposal for ScrapeConfig, opening it early to take feedback in.
Related tickets:
* #2787 
* #3447
```release-note
```
=> docs: ScrapeConfig proposal

test/e2e/main_test.go, test/e2e/thanosruler_test.go
Closes https://github.com/prometheus-operator/prometheus-operator/issues/5187
Problem: Before this commit, the code path used by the field queryConfig was not being tested in e2e tests
Solution: This commit adds a test that validates that if queryConfig is set, then the operator will configure the ThanosRuler deployment correctly
```release-note
```
=> Adds e2e test to validate ThanosRuler queryConfig field

Documentation/api.md, pkg/apis/monitoring/v1/prometheus_types.go, pkg/prometheus/operator.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/statefulset.go, scripts/docs/config.json
This PR creates a common interface that can be used by `Prometheus` and, in the future, by `PrometheusAgent` CRDs. I'm also refactoring the config generation to use the new interface instead of the Prometheus object, as discussed in https://github.com/prometheus-operator/prometheus-operator/issues/3989#issuecomment-1408948890.
This is probably one of many PRs needed for us to finally introduce the PrometheusAgent CRD
```release-note
```
=> Generate Prometheus configuration through interface

cmd/admission-webhook/main.go, cmd/operator/main.go, test/instrumented-sample-app/main.go
via gosec linter - G112: Potential slowloris attack
https://medium.com/a-journey-with-go/go-understand-and-mitigate-slowloris-attack-711c1b1403f6
```release-note
Set Read/ReadHeaderTimeouts on http.Server instances
```
=> Set Read/ReadHeaderTimeouts on http.Server

cmd/prometheus-config-reloader/main.go, cmd/prometheus-config-reloader/main_test.go
This new argument enables you to increase (or decrease) the duration for config-reloader to wait after Prometheus' reload.
Fixes #5346
Allow the time waited for Prometheus' configuration reload to be customized. 
```release-note
- Add a new parameter `--reload-timeout` to prometheus-config-reloader to customize the wait time of prometheus' configuration reload.
```
=> config-reloader: add the reload-timeout argument

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, jsonnet/prometheus-operator/alertmanagers-crd.json, pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, pkg/apis/monitoring/v1/alertmanager_types.go
This PR reuses the same approach used for prometheus statefulset that adds `init-config-reloader` initContainer to alertmanager statefulset - #3955.
Effectively `init-config-reloader` will pregenerate the alertmanager config so `alertmanager` won't fail due to missing config.
Fixes #5357
```release-note
- Generate Alertmanager config before starting Alertmanager container
```
=> config-reloader: add init-config-reloader to alertmanager

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/prometheus_types.go, pkg/client/applyconfiguration/monitoring/v1/thanosspec.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
Add a BlockSize param to the ThanosSpec to allow configuration of the Prometheus min/max block duration when using the Thanos Sidecar.
Fixes: https://github.com/prometheus-operator/prometheus-operator/issues/4414
```release-note
apis: Add Thanos BlockSize control
```
=> apis: Add Thanos BlockSize control

cmd/po-lint/main.go, cmd/po-rule-migration/main.go, go.mod, go.sum, pkg/operator/rules.go, test/framework/crd.go
The package `github.com/ghodss/yaml` is no longer actively maintained. See discussion in https://github.com/ghodss/yaml/issues/75 and https://github.com/ghodss/yaml/issues/80. [`sigs.k8s.io/yaml`](https://github.com/kubernetes-sigs/yaml) is a permanent fork of `github.com/ghodss/yaml`.
The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, but `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. Changes can be seen here [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), mostly bug fixes.
```release-note
refactor: …
```
=> refactor: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

pkg/apis/monitoring/v1/prometheus_types.go, pkg/prometheus/operator.go, pkg/prometheus/statefulset.go, pkg/prometheus/statefulset_test.go
This PR was built on top of https://github.com/prometheus-operator/prometheus-operator/pull/5310, so I could re-use the `PrometheusInterface` interface.
It follows the same strategy, arguments that are not present in `CommonPrometheusFields` are being passed as extra arguments to the functions `makeStatefulSet` and `makeStatefulSetSpec`.
```release-note
```
=> Refactor: Use PrometheusInterface to generate statefulset

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml, jsonnet/prometheus-operator/alertmanagers-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/thanosrulers-crd.json, pkg/apis/monitoring/v1/alertmanager_types.go, pkg/apis/monitoring/v1/prometheus_types.go, pkg/apis/monitoring/v1/thanos_types.go
Add default value to the OpenAPI spec definition.
```release-note
Define default value for `spec.portName`.
```
=> api: define default value for `spec.portName`

pkg/prometheus/server/operator.go
This was introduced in #5401, it didn't cause a panic because the accessor methods never called the logger field.
```release-note
```
=> pkg/prometheus/server: fix nil accessor field

scripts/run-external.sh
Previously running `/scripts/run-external.sh` showed 
```
/scripts/run-external.sh : line 9: $1: unbound variable
```
which now shows 
```
ERROR: missing cluster name
usage: ❯ ./scripts/run-external.sh <clustername>
```
=> improve run-external script to show usage info

pkg/alertmanager/operator.go, pkg/informers/kube.go, pkg/operator/accessor.go, pkg/prometheus/server/operator.go
This patch uses  metadatainformer package to watch secrets and configmaps so that all content need not be loaded into memory thus reducing the amount of memory consumed.
Prometheus Operator now consumes less memory that before when there are lots of secrets and config-maps 
present in the cluster.
```release-note
- Optimised to consume less memory when there are lots of secrets or configmaps in the cluster. 
```
=> fix: improve memory usage by using metadata informer

.github/workflows/publish.yaml
After merging #5460 the publish job failed with 
````
2023-03-28T13:35:56.8753259Z denied: installation not allowed to Write organization package
```` 
IIUC when specifying a `permissions` entry, all entries not explicitly listed are set to `none`.
```release-note
```
=> ci: fix image push

Documentation/user-guides/webhook.md, bundle.yaml, example/admission-webhook/deployment.yaml, example/rbac/prometheus-operator/prometheus-operator-deployment.yaml, jsonnet/prometheus-operator/admission-webhook.libsonnet, jsonnet/prometheus-operator/prometheus-operator.libsonnet
This sets the default value for `securityContext.seccompProfile.type`.  When running with warnings for `PodSecurity "restricted:1.26.0` a message is emitted that this is unset.
Message
```
Warning: would violate PodSecurity "restricted:1.26.0": seccompProfile (pod or container "prometheus-operator" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/prometheus-operator created
```
As `RuntimeDefault` is already the used default this should have no user facing changes.
```release-note
Set a default for …
```
=> Ensure securityContext.seccompProfile.type is set

bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusrules.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml, jsonnet/prometheus-operator/prometheusrules-crd.json, pkg/apis/monitoring/v1/prometheusrule_types.go, test/e2e/rules_test.go
PrometheusRule CRD: declare spec.rules optional
Fixing #5480 
Marking this as BUGFIX, since declare a property from required to optional is an non breaking change which is fixing an issue.
```release-note
PrometheusRule CRD: declare spec.rules optional
```
=> PrometheusRule CRD: declare spec.rules optional

.github/ISSUE_TEMPLATE/support.md
We still have more issues related to kube-prometheus-stack than anything else here 😅. It feels like mentioning the appropriate support channels for it is easily missed in the middle of the rest of the markdown.
This change highlights the correct channels to the [new issue page](https://github.com/prometheus-operator/prometheus-operator/issues/new/choose)
```release-note
```
=> Highlight support channels for kube-prometheus-stack

Makefile
Sometimes, it's hard to identify the source of a formatting issue. `make check-docs` will complain about something that `make --always-make format generate` doesn't fix. `make docs` wasn't included in `make format`.
References:
- https://kubernetes.slack.com/archives/C01B03QCSMN/p1681670965886149
n/a
=> chore: Also format docs on make format

cmd/operator/main.go, pkg/k8sutil/k8sutil.go, pkg/prometheus/agent/operator.go
Move controller creation pre-requisites to validation method `CheckPrerequisites()` to avoid creating
controller object incase of validation failure. This is used for prometheus-agent controller as part of
this commit. These methods can be re-used for future CRD validation
and controllers
This change is result of alert fired during e2e test for prometheus-operator version upgrade in ocp https://github.com/openshift/prometheus-operator/pull/223. `PrometheusOperatorNotReady` was fired for `prometheus-agent` controller since CRD was not installed. Same alert will fire for upstream users who doesn't install prometheus-agent crd. This commit creates agent controller object only when validations are met.
_Describe the big picture of your changes here to communicate to the maintainers why we …
=> fix: Add validation method for controller and crd's 

pkg/k8sutil/k8sutil.go
We didn't report the error from `IsAPIGroupVersionResourceSupported`. Now wrapping it for easier debugging.
References:
- https://github.com/prometheus-operator/prometheus-operator/pull/5335#issuecomment-1526575149
```release-note
Report downstream errors when CRD validation fails
```
=> fix: Wrap downstream error when checking that a CRD is installed

pkg/operator/operator.go
This patch Fixes the number of  failed sync status is wrong.
It seems that the variable `failed`  is forgot to count.
```release-note
Fix the wrong number of failed sync status 
```
=> Fix number of failed sync status

pkg/prometheus/agent/operator.go, pkg/prometheus/resource_selector.go, pkg/prometheus/server/operator.go
The operator would panic on a nil pointer exception if the ScrapeConfig CRD isn't installed in the cluster. The root cause is the test in `(*ResourceSelector).SelectScrapeConfigs()` that checked the interface value against `nil`. The test would return `true` only if both the interface's concrete type and value are nil. While the concrete value was `nil`, the concrete type was `*informers.ForResource`.
Instead the controller will check that the `*informers.ForResource` variable isn't nil before calling
`(*ResourceSelector).SelectScrapeConfigs()`.
```release-note
```
=> fix: avoid panic when ScrapeConfig CRD isn't installed

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml, jsonnet/prometheus-operator/thanosrulers-crd.json, pkg/apis/monitoring/v1/thanos_types.go, pkg/apis/monitoring/v1/zz_generated.deepcopy.go, pkg/client/applyconfiguration/monitoring/v1/thanosrulerspec.go, pkg/thanos/statefulset.go, pkg/thanos/statefulset_test.go
Supports creating a VolumeMount in ThanosRuler objects
Closes #5538 
```release-note
- Add VolumeMounts to ThanosRuler CRD to allow Volumes to be mounted within Ruler
```
=> Support VolumeMounts in ThanosRuler

cmd/operator/main.go
common Kubernetes log configurations will not recognize the last log message of pod if it does not include a newline
I recently wasted some time debugging prometheus-operator constantly crashing while running with `hostNetwork: true`. I wasn't seeing any meaningful logs and the pod was exiting very quickly. It turned out that the port that the operator was attempting to acquire was already in use. I then wondered why this wasn't in the logs as it should be and found that my log viewing tool doesn't report the last text that a pod produces if it doesn't end in a newline.
Also I noted that every other output to stderr appends newlines so it would be good to be consistent as well.
```release-note
- Top level exit errors end with newline ensuring the logs don't get lost
```
=> operator: include newline in error messages

Makefile, jsonnet/prometheus-operator/prometheus-operator.libsonnet
Useful for people that import prometheus-operator.libsonnet and want to use the new ScrapeConfig CRD.
```release-note
```
=> jsonnet: add ScrapeConfig CRD to prometheus-operator.libsonnet

pkg/prometheus/agent/operator.go, test/e2e/main_test.go, test/e2e/prometheusagent_test.go, test/framework/prometheusagent.go, test/framework/status.go
Adds a simple e2e test that creates and deletes a PrometheusAgent resource.
Opening it as a draft because, even though tests pass and the code looks correct, I've noticed that the test doesn't behave as expected. The PrometheusAgent resource isn't reconciled for some reason and the test pass anyway
```release-note
```
=> Test PrometheusAgent creation and deletion

pkg/alertmanager/statefulset_test.go, pkg/prometheus/agent/statefulset_test.go, pkg/prometheus/server/statefulset_test.go, pkg/webconfig/config.go, pkg/webconfig/config_test.go, pkg/webconfig/tls_credentials.go, test/e2e/alertmanager_test.go, test/e2e/prometheus_test.go
The fix is to not use `subPath` when mounting web certificates. As per
[Kubernetes' documentation][1], mounts using subPath will not get updates. This
commit changes it to full mounts. Prometheus and Alertmanager use
[exporter-toolkit][2] which reloads the certs for every query.
This commit also extends Prometheus' and Alertmanager's stateful tests to check
prometheus-config-reloader arguments.
References:
* https://github.com/prometheus-operator/prometheus-operator/issues/5527
* https://github.com/prometheus-operator/prometheus-operator/pull/5535#discussion_r1194940482
[1]: https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod
[2]: https://github.com/prometheus/exporter-toolkit
Fixes #5527 
_What type of changes does your code introduce to the …
=> fix: Alertmanager and Prometheus don't pick up new certificates after renewal

Documentation/design.md
Hopping that it lands on the website :)
https://prometheus-operator.dev/docs/operator/design/
```release-note
```
=> Add PrometheusAgent to Design docs

ADOPTERS.md
More use cases for CERN as a prometheus adopter outside of the Kubernetes environment.
Update the CERN name to be inline with internal guidelines.
=> Fix CERN adopter to be more generic

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Fix relabelings issue in ScrapeConfig CRD, generate them correctly.
Fix #5610 
```release-note
Fix relabelings issue in ScrapeConfig CRD.
```
=> Fix relabelings for ScrapeConfig

test/e2e/scrapeconfig_test.go
The new ScrapeConfig e2e tests (#5575) deployed the operator + admission webhook + webhook configurations without cleaning the wehhook configurations after the tests completed. The end result was that some of the following tests were failing because the admission service wasn't present anymore (e.g. the creation of PrometheusRules failed).
In practice, the admission webhook is not required for the ScrapeConfig tests, hence this change deploys only the operator.
```release-note
```
=> chore: fix e2e tests

cmd/prometheus-config-reloader/main.go
When a Prometheus pod is terminated, the container runtime sends a SIGTERM signal [1] to all pod's containers. Prior this change, prometheus-config-reloader would return a non-zero exit code in this case which can lead to the pod being reported as failed for a brief period of time and create additional work on the statefulset controller's side. To be a good citizen, prometheus-config-reloader should handle the signal and return gracefully.
[1] https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination
```release-note
```
=> cmd/prometheus-config-reloader: add SIGTERM handler

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/prometheus_types.go
Prometheus rejects configuration with an empty value for the tracing endpoint. This is a follow-up from #5591. 
cc @ArthurSens @nicolastakashi 
```release-note
```
=> tracing: add MinLength validation to the `endpoint` field

pkg/thanos/statefulset.go, pkg/thanos/statefulset_test.go
Fix missing .spec.serviceName in the Thanos Ruler statefulset
Fixes: #5631 
```release-note
fix: Missing .spec.serviceName in the Thanos Ruler statefulset
```
=> fix: Missing .spec.serviceName in the Thanos Ruler statefulset

Documentation/operator.md, cmd/operator/main.go
~~Related to what was discussed in #5446, this PR changes the default resource requirements, but only for PrometheusAgent pods.~~
~~The number I've chosen is random, we probably want to discuss the final number~~
After discussing on the #prometheus-operator-dev Slack channel and gathering numbers from different production environments, we have good confidence that decreasing the CPU request from 100m to 10m isn't going to harm users.
```release-note
[CHANGE] Default CPU requirements of config-reloader set to 10m
```
=> Change default resource requirements for config reloader

cmd/prometheus-config-reloader/main.go, cmd/prometheus-config-reloader/main_test.go, pkg/operator/config_reloader.go, pkg/prometheus/promcfg.go, pkg/prometheus/statefulset.go
The SHARD and POD_NAME variables were defined in different places.
```release-note
```
=> chore: use constants for env variables

cmd/operator/main.go, pkg/prometheus/server/operator.go
This PR moves the prerequisites check for `ScrapeConfig` CRD to `operator/main.go`.
Fixes: https://github.com/prometheus-operator/prometheus-operator/issues/5546
```release-note
Move the prerequisites check for `ScrapeConfig` CRD from `server/operator.go` to `operator/main.go`.
```
=> Move prerequisite check

pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go, pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Since optional field should be of type pointer
in Kubernetes convention
```release-note
Update MetricPath type in ScrapeConfig to *string
```
=> pkg/apis: Update MetricPath type in ScrapeConfig

Documentation/api.md, pkg/apis/monitoring/v1/podmonitor_types.go, pkg/apis/monitoring/v1/probe_types.go, pkg/apis/monitoring/v1/servicemonitor_types.go, pkg/apis/monitoring/v1/zz_generated.deepcopy.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
References:
* https://github.com/prometheus-operator/prometheus-operator/pull/5658#discussion_r1227145581
* https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required
n/a
=> chore: Move limits to *uint64 and add optional markers

cmd/operator/main.go, pkg/prometheus/agent/operator.go
This PR removes the duplicate prerequisites check for `ScrapeConfig` CRD in `pkg/prometheus/agent/operator.go`.
Fixes: https://github.com/prometheus-operator/prometheus-operator/issues/5546
```release-note
Removes the duplicate prerequisites check for `ScrapeConfig` CRD in `pkg/prometheus/agent/operator.go`.
```
=> Delete duplicate prerequisite check

pkg/thanos/operator.go, test/framework/thanosruler.go
This was a TODO to be resolved after v0.66.0 gets released.
```release-note
```
=> chore: remove RulerStatus() function

scripts/run-external.sh
This patch simplifies running operator out of cluster by just running `./scripts/run-external.sh`
A sample run will look like the following 
```
❯ ./scripts/run-external.sh -c
🔆🔆🔆  Set Cluster  🔆🔆🔆 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🔔 Using cluster - 'kind-po'
🔆🔆🔆  Ensure no other prometheus-operator is running  🔆🔆🔆 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✅ No pods with matching label app.kubernetes.io/name=prometheus-operator running in cluster
🔆🔆🔆  Building Operator  🔆🔆🔆 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
❯ make operator 
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -X …
```
=> simplify running operator out of cluster

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Follow up to https://github.com/prometheus-operator/prometheus-operator/pull/5586 as to make the review easier, this PR removed the test `TestProbeStaticTargetsConfigGeneration` and splits this test into 3 separate tests as to test different parts of the code in isolation
```release-note
```
=> tests: refactors probe test into generic test function

.gitattributes
We've recently enabled a Github app that labels PRs by their diff size. Any PR that touches generated files is almost always labeled as XXL, which is not always true if we ignore generated files.
This PR properly configured generated files to be ignored in the Github diff, so they get labeled correctly. See: https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
```release-note
```
=> Hide generated files from Github diff

pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go, pkg/prometheus/statefulset.go, pkg/prometheus/store.go
This commit partially address https://github.com/prometheus-operator/prometheus-operator/issues/5455 by refactoring server and agent operator code that updates the prometheus config secrets. It moves the common functionalities to pkg/prometheus (prompkg).
The refactor adds the following functions
Store Related
* AddRemoteWritesToStore
* AddRemoteReadToStore
* AddAPIServerConfigToStore
Operator Related
* MakeCompressedSecretForPrometheus
GH: https://github.com/prometheus-operator/prometheus-operator/issues/5455
=> refactor: move common steps from server and agent to prompkg

pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, test/e2e/alertmanager_test.go, test/e2e/main_test.go
add etc/alertmanager/config to watched-dir when init pods to support config reload when template files are modified.
#5708 
```
=> alertmanager: add etc/alertmanager/config

Documentation/thanos.md
From issue [#5722](https://github.com/prometheus-operator/prometheus-operator/issues/5722), add example for the Alertmanager Configuration for Thanos Ruler.
```release-note
```
=> docs: Improve Thanos Ruler doc with examples

pkg/prometheus/promcfg.go
Also use stringMapToMapSlice() in generateScrapeConfig().
```release-note
```
=> chore: use generics for stringMapToMapSlice()

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml, jsonnet/prometheus-operator/scrapeconfigs-crd.json, pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go, pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go, pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Fixes #5592
```release-note
Add http params to ScrapeConfig
```
=> pkg/apis: Add params to ScrapeConfig

bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/thanosrulers-crd.json, pkg/apis/monitoring/resource.go, pkg/apis/monitoring/v1/types.go
I have duplicated the consts in `monitoring/resource.go` otherwise it will cause a circular-dependency . 
```release-note
Add ScrapeConfigs to ObjectReference
```
Closes https://github.com/prometheus-operator/prometheus-operator/issues/5544
=> Add ScrapeConfigs to ObjectReference

go.mod, pkg/client/go.mod
I missed the update in #5774.
```release-note
```
=> chore: bump prometheus-operator in go.mod files

pkg/alertmanager/operator.go
When you run a prometheus-operator from the main or release-0.67 branch, and declare an alertmanager CR which alertmanager version less than v0.25.0, then all your declared alertmanagerConfig CRs will be skipped due to unnecessary check for receiver configs of discord type. So fix it.
An alertmanager CR with alertmanager v0.24.0:
```
kind: Alertmanager
metadata:
labels:
app: alertmanager
name: ecms
namespace: default
spec:
alertmanagerConfigMatcherStrategy:
type: None
alertmanagerConfigNamespaceSelector: {}
alertmanagerConfigSelector:
matchLabels:
emla.io/used-by: ecms
clusterPeerTimeout: 60s
configSecret: alertmanager
image: prom/alertmanager-linux-amd64:release-0.24-es
logLevel: info
replicas: 2
retention: 120h
routePrefix: /
serviceAccountName: …
```
=> Do not check the am version if no discord configs

.gitattributes, CONTRIBUTING.md, Makefile, go.mod, go.sum, pkg/webconfig/config_test.go, pkg/webconfig/testdata/HTTP_config_with_all_parameters.golden, pkg/webconfig/testdata/TLS_config_with_all_parameters_from secrets.golden, pkg/webconfig/testdata/minimal_TLS_config_with_certificate_from_configmap.golden, pkg/webconfig/testdata/minimal_TLS_config_with_certificate_from_secret.golden, pkg/webconfig/testdata/minimal_TLS_config_with_client_CA_from configmap.golden, scripts/update-golden-files.sh
I'm adding golden file supports on `webconfig` package, solves #5741
```release-note
adding golden file supports on `webconfig` package
```
=> chore: adding golden files support on webconfig tests

pkg/thanos/operator.go
Reflecting the same changes as https://github.com/prometheus-operator/prometheus-operator/commit/bd658c582c697e256b0c17b329b9d46fdc452eb9#diff-c8f4eb63862907c2cd9e067b2cf70e03f4e134075bd28f507dade553850d4fa3L1627 in ThanosRuler CRD
```release-note
reduce the number of reconciliations on ThanosRuler objects.
```
=> reduce the number of reconciliations

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
fix https://github.com/prometheus-operator/prometheus-operator/issues/5176. 
By adding a sharding relabeling rule, prometheus operator will shard targets in the probe across the prometheus cluster.
```release-note
support sharding for probe.
```
=> support sharding for probe

pkg/alertmanager/statefulset.go, pkg/prometheus/statefulset.go, pkg/thanos/statefulset.go
From the Go docs:
> "If the map is nil, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary. Example: https://go.dev/play/p/Cw_wnqYzemu
```release-note
statefulset: remove redundant nil check around Labels and Annotations
```
=> statefulset: remove redundant nil check around Labels and Annotations

.github/workflows/e2e.yaml
helm/kind-action seems to be more maintained than engineerd/setup-kind.
helm/kind-action seems to be more maintained than engineerd/setup-kind.
```release-note
```
=> chore: use helm/kind-action

.github/dependabot.yml
To avoid needing to manually open PRs like #5824, we can configure Dependabot to update them together :)
Here is the documentation for Dependabot's new feature: https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/
```release-note
```
=> Update k8s libs together

test/framework/status.go
I hope it fixes #5556 😅, would need to merge and keep an eye out if we still get rate limits in tests to make sure.
```release-note
```
=> Get status less frequently to avoid rate limits

go.mod, go.sum, pkg/alertmanager/amcfg_test.go, pkg/alertmanager/operator_test.go, pkg/alertmanager/validation/v1beta1/validation_test.go, pkg/operator/statefulset_reporter.go, pkg/prometheus/agent/operator.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/server/operator.go, pkg/prometheus/server/operator_test.go, pkg/prometheus/server/statefulset_test.go, pkg/prometheus/statefulset.go, test/e2e/alertmanager_test.go, test/e2e/prometheus_test.go, test/e2e/scrapeconfig_test.go, test/framework/alertmanager.go, test/framework/framework.go, test/framework/prometheus.go, test/framework/thanosruler.go
Remove usage of the deprecated `k8s.io/utils/pointer` package.
Needs #5804 first.
```release-note
```
=> Upgrade k8s utils

Documentation/user-guides/scrapeconfig.md, Documentation/user-guides/webhook.md
Noticed after opening https://github.com/prometheus-operator/website/pull/58. 
The Prometheus-Agent guide is already using 153
```release-note
```
=> Fix collapsing user-guide weights

pkg/prometheus/resource_selector.go, pkg/prometheus/resource_selector_test.go
I noticed that probes, service monitors, pod monitors and scrape configs with invalid relabel configs were not rejected by the operator. This PR fixes it.
```release-note
reject ServiceMonitor, PodMonitor, Probe and ScrapeConfig with invalid relabel configs.
```
=> fix: reject monitors with invalid relabel configs

.github/workflows/automerge-dependabot.yaml
I've tested this in one of coralogix's private repositories and it worked without changing codeowners :) 
I believe it shouldn't be different here
```release-note
```
=> Auto-approve dependabot PRs

pkg/assets/store.go, pkg/prometheus/resource_selector.go, pkg/prometheus/resource_selector_test.go
This is a follow-up of #5841. For the same reason that we didn't continue from the outer loop, invalid ScrapeConfig objects were not rejected.
```release-note
reject ScrapeConfig with invalid secret key references.
```
=> fix: reject invalid ScrapeConfigs

.github/workflows/e2e.yaml, .github/workflows/test-prom-version-upgrade.yaml, test/e2e/main_test.go
As our compatibility matrix grows, the tests assuring we can upgrade from one Prometheus version to the next are taking up to 1~2h to complete. We aim to accelerate our e2e tests that are required to pass on Pull Requests by moving this test to a separate CI, that runs once a day.
```release-note
```
=> Run PrometheusVersionUpgrade tests separately

pkg/alertmanager/amcfg_test.go, pkg/alertmanager/testdata/skeleton_base_multiple_alertmanagerconfigs.golden
While reviewing the code base, I realized that we don't have a test validating the generation of the Alertmanager configuration when multiple AlertmanagerConfig objects are reconciled.
Kudos to @nicolastakashi for the golden files implementation: it works like a breeze.
```release-note
```
=> chore: add unit test with multiple AlertmanagerConfigs

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, test/e2e/scrapeconfig_test.go
I am first testing if e2e test fails for current code and then I will uncomment the fix. Also added unit test missed in feature PR
Fixes https://github.com/prometheus-operator/prometheus-operator/issues/5870
```release-note
Fix KuberenetesSDConfigs in ScrapeConfig
```
=>  fix: Fix KuberenetesSDConfigs in ScrapeConfig

Documentation/troubleshooting.md
This is only partially documented in the kube-prometheus README but it comes up often in the issues. Hopefully some people will find it helpful.
```release-note
```
=> Document server-side apply for CRDs

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/testdata/external_label_specified_along_with_reserved_labels.golden
API document says following about externalLabels field:
```
// The labels to add to any time series or alerts when communicating with
// external systems (federation, remote storage, Alertmanager).
// Labels defined by `spec.replicaExternalLabelName` and
// `spec.prometheusExternalLabelName` take precedence over this list.
```
But in code externalLabels were applied after reserved labels.
This commit is to fix that.
_Please put a one-line changelog entry below. This will be copied …
=> fix:  apply externalLabels after reserved labels in prometheus

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml, jsonnet/prometheus-operator/alertmanagerconfigs-crd.json, jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet, pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go, pkg/alertmanager/types.go, pkg/alertmanager/validation/v1alpha1/validation.go, pkg/alertmanager/validation/v1beta1/validation.go, pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go, pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go, pkg/apis/monitoring/v1beta1/alertmanager_config_types.go, pkg/apis/monitoring/v1beta1/conversion_from.go, pkg/apis/monitoring/v1beta1/conversion_to.go, pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go, pkg/client/applyconfiguration/monitoring/v1alpha1/telegramconfig.go, pkg/client/applyconfiguration/monitoring/v1beta1/telegramconfig.go
Fixes #5858
```release-note
feat: add bot_token_file in TelegramConfig
```
=> feat: add bot_token_file in TelegramConfig

Documentation/operator.md, cmd/operator/main.go, pkg/alertmanager/operator.go, pkg/k8sutil/k8sutil.go, pkg/operator/config.go, pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go, pkg/thanos/operator.go, scripts/run-external.sh
The `--as` argument allows to run the operator while impersonating a different user. It's useful to run the operator outside of the cluster as a service account instead of `kubeadmin`.
```release-note
Add `--as` CLI argument to the Prometheus operator.
```
=> feat: add `--as` CLI argument

pkg/alertmanager/operator.go
To set the status subresource, the operator make use of ApplyStatus() instead of UpdateStatus()  to avoid informer errors.
- replace UpdateStatus() for ApplyStatus() in order to avoid informer errors.
=> enhancement: Replace UpdateStatus() for ApplyStatus() to avoid informer errors

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/prometheus_types.go
This only fixes a typo in comments and documentation.
```release-note
- Fix `objec` --> `object` typo
```
=> Fix objec --> object typo

pkg/alertmanager/operator.go, pkg/operator/operator.go, pkg/thanos/operator.go
To set the status subresource, the operator make use of ApplyStatus() instead of UpdateStatus()  to avoid informer errors.
- replace UpdateStatus() for ApplyStatus() in order to avoid informer errors.
=>  replace UpdateStatus() for ApplyStatus ThanosRuler

pkg/operator/applyconfiguration.go, pkg/operator/operator.go, pkg/prometheus/agent/operator.go, pkg/prometheus/applyconfiguration.go, pkg/prometheus/server/operator.go
To set the status subresource, the operator make use of ApplyStatus() instead of UpdateStatus()  to avoid informer errors.
- replace UpdateStatus() for ApplyStatus() in order to avoid informer errors.
=> replace UpdateStatus() for ApplyStatus Prometheus

.github/workflows/automerge-dependabot.yaml
Yet another PR trying to make #5849 pass 🥲.
The latest attempt failed to push because it was on a detached HEAD reference. This PR forces the checkout to be on the PR branch
```release-note
```
=> Checkout branch ref on Dependabot workflows

cmd/operator/main.go, pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go, pkg/listwatch/listwatch.go, pkg/listwatch/listwatch_test.go, pkg/operator/config.go, pkg/operator/resource_reconciler.go, pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go, pkg/thanos/operator.go, test/e2e/alertmanager_instance_namespaces_test.go, test/e2e/prometheus_instance_namespaces_test.go, test/e2e/scrapeconfig_test.go, test/framework/framework.go
When the operator was configured to select only a limited number of
namespaces, it would not watch for namespace changes. It means that the
operator may not reconcile when a namespace label is added/removed
(affecting which objects should be selected or not).
This change enables the operator to use a privileged namespace
lister/watcher whenever the service account has the needed permissions.
**IMPORTANT:** it also requires Kubernetes >= 1.22 to be effective but the
operator will degrade to the less efficient implementation if this condition isn't met.
xref #3847 (one more PR required to fix it completely). …
=> fix: reconcile on namespace changes

Documentation/proposals/202309-controller-id.md
This PR adds a new proposal for PO regarding the usage of
`controller-id` for handling several instances in different namespaces
or rogue Prometheus' CRD usage.
=> Add controller-id proposal

pkg/alertmanager/operator.go, pkg/listwatch/listwatch.go, pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go, pkg/thanos/operator.go, test/e2e/prometheus_instance_namespaces_test.go
This change implements a poll-based namespace lister/watcher when the operator's service account isn't granted the list & watch permissions on all namespaces. Instead of sending a watch request, the controller will get every configured namespace every 15 seconds and sends the expected watch events when a namespace is added/updated/deleted.
It still requires the service account to be granted the get permission on the configured namespaces.
Closes #3847
```release-note
detect changes without list/watch perms on namespaces
```
=> fix: detect changes without list/watch perms on namespaces

scripts/run-external.sh
This change allows to run the operator locally as a different user:
```
export IMPERSONATE_USER=system:serviceaccount:default:system
./run/run-external.sh -c
```
_not classifying it as a bug fix because it's not relevant for end users._
```release-note
```
=> fix: get IMPERSONATE_USER from current environment

pkg/prometheus/resource_selector.go, pkg/prometheus/resource_selector_test.go
If secret reference is nil it will cause operator to crash, hence updating the validate function for ec2 and consul sd configs to check for secret only if provided in config.
Fixes #5936
```release-note
fix: Fix consul sd config
```
=> fix: Update consul validate func

pkg/prometheus/resource_selector.go, pkg/prometheus/resource_selector_test.go
If secret reference is nil it will cause operator to crash, hence updating the validate function for ec2 sd config to check
for secret only if provided in config.
Noticed this when https://github.com/prometheus-operator/prometheus-operator/issues/5936 logged. Since this change is not released yet we don't need to put in changelog I guess as bugfix
```release-note
```
=> fix: Update ec2 validate func

pkg/prometheus/server/operator.go
The current Prometheus Operator implementation checks for the presence of spec.serviceMonitorSelector, spec.podMonitorSelector, and spec.probeSelector to determine if the Prometheus configuration should be treated as unmanaged. However, the documentation specifies that the operator should also check for spec.scrapeConfigSelector. This PR aligns the implementation with the documentation by adding the necessary check for spec.scrapeConfigSelector.
Closes #5928
```release-note
Ensure that the operator checks for spec.scrapeConfigSelector when determining if the Prometheus configuration should be treated as unmanaged.
```
=> add: scrapeConfigSelector check

Dockerfile
* Fixing #5338
* Add OCI labels in the Dockerfile
```release-note
Add OCI labels in the Dockerfile
```
=> Fixing #5338 | Add OCI labels in the Dockerfile

pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go
If multiple Alertmanager clusters are deployed on the same cluster, it can happen
that because pod IP addresses are recycled, an Alertmanager instance from cluster B
connects with cluster A.
`--cluster.label`  flag was introduced in alertmanager `v0.26`, this helps to block
any traffic that is not meant for the cluster.
The value is hardcoded and the value is guaranteed to be unique in a given cluster but
if there's a use case, we can consider a new field in the CRD.
This commit sets default `--cluster.label` flag as namespace/name
when Alertmanager version used is >= v0.26
_What type of …
=> fix: add --cluster.label to alertmanager

.golangci.yml, pkg/admission/jsonpatch.go, pkg/alertmanager/amcfg.go, pkg/alertmanager/operator.go, pkg/alertmanager/statefulset.go, pkg/alertmanager/validation/v1alpha1/validation.go, pkg/alertmanager/validation/v1beta1/validation.go
@simonpasquier @slashpai, I was thinking about adding https://github.com/fatih/faillint to our CI to make sure we're not using certain functions/packages. 
This could help us to fix https://github.com/prometheus-operator/prometheus-operator/issues/4682, and to make sure we don't re-introduce unwanted packages in the future
```release-note
```
=> Enable depguard linter against github.com/pkg/errors

pkg/alertmanager/operator.go, pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go, pkg/thanos/operator.go
A race condition in appears when using [Pulumi](https://www.pulumi.com/) to delete a prometheus instance custom resouce from a Kubernetes cluster.
I've created a demo repo https://github.com/mheers/pulumi-prometheus-operator-race-condition to reproduce the behaviour.
Deleting the CR with pulumi will get the operator stuck in a loop. The operator will try to delete the prometheus instance but will fail with errors exported to https://github.com/mheers/pulumi-prometheus-operator-race-condition/blob/main/logs/operator.log
```release-note
Fixes race condition when deleting alertmanager or prometheus instances
```
=> fixes race condition when deleting alertmanager, prometheus and thanosruler instances

cmd/operator/main.go, internal/log/log.go
client-go functions can avoid costly logging evaluations by using this pattern:
```
if klog.V(2).Enabled() { klog.Info("log this") }
```
With this change, the klog verbosity is set to zero (except at debug log level where it is 6) to ensure that the performance optimization is preserved.
```release-note
Enable klog verbose level only when the log level is debug.
```
=> fix: set verbosity log level only for debug

pkg/k8sutil/secrets.go, pkg/k8sutil/secrets_test.go, pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go
Additional scrape, Alertmanager and alert relabeling configurations which are references to secret keys can be declared as optional. If the optional bool pointer is nil, the operator should consider that the reference isn't optional. It used to be the case before #5720 but the logic was inverted by accident.
```release-note
consider nil optional to be false for additional configs
```
=> change: consider nil optional to be false for additional configs

.golangci.yml, pkg/thanos/operator.go, pkg/thanos/rules.go, pkg/thanos/statefulset.go
Related to https://github.com/prometheus-operator/prometheus-operator/issues/4682
```release-note
```
=> Enable depguard in more packages

.golangci.yml, test/e2e/alertmanager_test.go, test/e2e/denylist_test.go, test/e2e/prometheus_instance_namespaces_test.go, test/e2e/prometheus_test.go
Related to https://github.com/prometheus-operator/prometheus-operator/issues/4682
(only one PR left!!!)
```release-note
```
=> Enable depguard in e2e tests

test/e2e/alertmanager_test.go, test/e2e/main_test.go
Added a e2e test for alertmanager field "AlertmanagerConfigMatcherStrategy"
Fixes #5705
Signed-off-by: Patrick Niederlöhner <16616161+Pati93@users.noreply.github.com>
Added a e2e test for alertmanager field "AlertmanagerConfigMatcherStrategy"
```release-note
- Add a e2e test for alertmanager field "AlertmanagerConfigMatcherStrategy"
```
=> test(e2e-alertmanager): add alertmanager e2e test

test/e2e/alertmanager_test.go
The last merged PR #5983 broke the test compilation.
```release-note
```
=> chore: fix e2e tests compilation

Makefile
Avoid stripping away the "description" field that collided with kubebuilder's appended "description" metadata field while generating the CRD schema.
Fixes: #5129
=> fix: do not strip essential fields

cmd/operator/main.go, pkg/admission/admission.go, pkg/admission/admission_test.go
Remove deprecated metrics entirely, namely:
* prometheus_operator_rule_validation_triggered_total
* prometheus_operator_rule_validation_errors_total
* prometheus_operator_alertmanager_config_validation_triggered_total
* prometheus_operator_alertmanager_config_validation_errors_total
***
PTAL https://github.com/prometheus-operator/prometheus-operator/pull/5706/files#r1358257173 for more context.
```release-note
The following deprecated metrics will not be registered anymore.
* prometheus_operator_rule_validation_triggered_total
* …
```
=> change: drop deprecated metrics

Documentation/operator.md, cmd/admission-webhook/main.go, cmd/operator/main.go
This change mitigates CVE-2023-44487 by disabling HTTP2 connections by default and forcing HTTP/1.1 until the Go standard library and golang.org/x/net are fully fixed. Right now, it is possible for authenticated and unauthenticated users to hold open HTTP2 connections and consume huge amounts of memory.
It is possible to revert back the change by using the `--web.enable-http2` argument.
Before this change:
```
curl -kv https://localhost:8443/metrics
*   Trying 127.0.0.1:8443...
* Connected to localhost (127.0.0.1) port 8443 (#0)
* ALPN: offers h2,http/1.1
[...]
* ALPN: server accepted h2
[...]
* using HTTP/2
* h2h3 [:method: GET]
* h2h3 [:path: /metrics]
* h2h3 [:scheme: https]
* h2h3 [:authority: localhost:8443]
* h2h3 [user-agent: curl/8.0.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 …
```
=> fix: disable HTTP2 connections by default

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/prometheus_types.go, pkg/apis/monitoring/v1/zz_generated.deepcopy.go, pkg/client/applyconfiguration/monitoring/v1/alertmanagerendpoints.go, pkg/prometheus/operator.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/server/operator.go, pkg/prometheus/store.go, pkg/prometheus/testdata/AlertmanagerSigv4_Invalid_Prom_Version.golden, pkg/prometheus/testdata/AlertmanagerSigv4_Valid_Prom_Version.golden
Fixes: #6033
```release-note
Add AWS sigv4 auth to Prometheus's Alertmanager endpoints
```
=> prometheus: Add AWS sigv4 auth to Alertmanager endpoints

README.md
Seems to be necessary for it to work.
https://github.com/kubernetes/minikube/issues/6061
Ran E2E tests locally, had issues getting a RBAC minikube cluster to start without the NODE param.
- [] `FEATURE` (non-breaking change which adds functionality)
```release-note
docs: Add node to auth mode when running minikube e2e tests
```
=> docs: Add node to auth mode when running minikube e2e tests

Makefile, bundle.yaml, example/alertmanager-crd-conversion/patch.json, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml, example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml, example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml, example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml, jsonnet/prometheus-operator/alertmanagerconfigs-crd.json, jsonnet/prometheus-operator/alertmanagers-crd.json, jsonnet/prometheus-operator/podmonitors-crd.json, jsonnet/prometheus-operator/probes-crd.json, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/prometheusrules-crd.json, jsonnet/prometheus-operator/scrapeconfigs-crd.json, jsonnet/prometheus-operator/servicemonitors-crd.json, jsonnet/prometheus-operator/thanosrulers-crd.json, scripts/generate/append-operator-version.sh
Include operator version in CRD annotations, PTAL https://github.com/prometheus-operator/prometheus-operator/pull/4498 for details.
Fixes: #4344.
***
This patch builds on top of @paulfantom's PR by (a) rebasing it against `main` and (b) adding support for the corresponding GNU `sed`-based behavior in MacOS using BSD `sed`.
***
```release-note
- Include operator version in CRD annotations ("prometheus-operator.dev/version").
```
=> enhancement: include operator version in CRD annotations

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml, jsonnet/prometheus-operator/alertmanagers-crd.json, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/thanosrulers-crd.json, pkg/apis/monitoring/v1/alertmanager_types.go, pkg/apis/monitoring/v1/prometheus_types.go, pkg/apis/monitoring/v1/thanos_types.go
Document common (reserved) labels in:
* `alertmanager`
* `prometheus`
* `thanos-ruler`
Fixes #4549.
Document overriding behavior for common (reserved) labels.
```release-note
- Document overriding behavior in common (reserved) labels for `alertmanager`, `prometheus`, and `thanos-ruler.
```
=> docs: overriding behavior for common labels

cmd/admission-webhook/main.go
After disabling HTTP2 connections by default in #6028 started seeing verbose logging in admission webhook pods like:
`ts=2023-11-06T01:50:34.601774794Z caller=stdlib.go:105 caller=server.go:3215 msg="http: superfluous response.WriteHeader call from main.newSrv.func1 (main.go:173)" `
Go doc says If WriteHeader is not called explicitly, the first call to Write will trigger an implicit
WriteHeader(http.StatusOK).
This fix is to change the order of the method invocation so log doesn't complain about this
_What type of changes does your code introduce to the Prometheus operator? Put an `x` in …
=> fix: remove verbose logging admission-webhook

jsonnet/prometheus-operator/prometheus-operator.libsonnet
Adds flag to enable liveness and readiness for the config-reloader container from jsonnet.
```release-note
Expose flag to enable the reloader probes in the jsonnet configuration.
```
=> add flag to enable liveness and readiness for the config-reloader container from jsonnet

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml, jsonnet/prometheus-operator/scrapeconfigs-crd.json, pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go, pkg/client/applyconfiguration/monitoring/v1alpha1/k8sselectorconfig.go, pkg/client/applyconfiguration/monitoring/v1alpha1/kubernetessdconfig.go, test/e2e/scrapeconfig_test.go
add service,pod,endpoints,endpointslice,ingress roles
to KubernetesSDConfigs in ScrapeConfig CRD
Fixes #6086
```release-note
feat:  support service,pod,endpoints,endpointslice,ingress roles
to KubernetesSDConfigs in ScrapeConfig CRD
=> feat: support remaining roles in kubernetesSD

bundle.yaml, example/rbac/prometheus-operator/prometheus-operator-deployment.yaml, jsonnet/prometheus-operator/prometheus-operator.libsonnet, pkg/alertmanager/operator.go, pkg/informers/informers.go, pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go
The secrets and configmaps informers only need to store the name, namespace and resource version of the objects: the event handlers don't look at the other metadata fields. By stripping the rest of the metadata, we can save a fair share of memory on clusters with lots of secrets/configmaps.
Example with a kind cluster running 16,384 secrets (in 128 namespaces), each secret has 4 annotations of 1,024 chars each.
In all cases, we see a big spike at the start of the operator which is expected because it fetches all data for the informers from the Kubernetes API. Depending on when the GC kicks in, the max allocated memory can remain high for longer:
The maximum memory usage with/without the change is similar but once the situation settles, we see a ~80% decrease in memory usage with this PR …
=> feat: optimize memory usage of secret/configmap informers

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml, jsonnet/prometheus-operator/scrapeconfigs-crd.json, pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go, pkg/client/applyconfiguration/monitoring/v1alpha1/consulsdconfig.go
some of the json tags were not following Kubernetes conventions hence updating those
```release-note
change: update json tags for ConsulSD configs
```
=> change: update json tags for ConsulSD configs

pkg/prometheus/promcfg.go, pkg/prometheus/testdata/AdditionalScrapeConfigs_one_prometheus_shard.golden, pkg/prometheus/testdata/AdditionalScrapeConfigs_sharded prometheus.golden, pkg/prometheus/testdata/AdditionalScrapeConfigs_unsharded_prometheus.golden, pkg/prometheus/testdata/TestAdditionalScrapeConfigsAdditionalScrapeConfig.golden
Currently sharding relabels are automatically added to additional scrape configs. However, users might have custom sharding relabels similar to the issue in #6063. We should skip those if we find an action with the value `hashmod` already there.
Fixes #6063.
Without this change the sharded tests would have duplicate hashmod functions.
```release-note
fix(shards): Skip …
```
=> fix(shards): Skip adding shard relabel rules automatically if already set

pkg/alertmanager/operator.go, pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go
Skip appending sources with the same key for ConfigMaps and Secrets in the AlertmanagerConfiguration.
Fixes: #5905
=> fix: handle duplicate sources

cmd/operator/main.go, pkg/kubelet/controller.go, pkg/kubelet/controller_test.go, pkg/operator/config.go, pkg/prometheus/server/operator.go, pkg/prometheus/server/operator_test.go
This commit moves the Kubelet endpoints reconciliation loop from the Prometheus controller to a separate controller.
```release-note
```
=> chore: create kubelet endpoints controller

.github/workflows/stale.yaml
As discussed in the last office hours, let's start closing stale PRs :) 
```release-note
```
=> Update stale workflow to close stale PRs

.github/workflows/automerge-dependabot.yaml
Another attempt to fully automate version bump of kubernetes go libraries (sorry for the amount of noise so far folks 😞)
As mentioned [here](https://github.com/prometheus-operator/prometheus-operator/pull/6091#issuecomment-1814334673), I've finally got a response from Github Support team telling me that they intentionally do not trigger CI workflows from commits coming from the `github-actions` user to avoid recursive loops.
This PR changes the token used to clone, commit and push during the workflow, using a PAT from [prom-op-bot](https://github.com/prom-op-bot).
Hopefully the last one of many 🤞 😢 
<details><summary>Github support response</summary>
</details>
_Please put a …
=> Use Prom-Op bot PAT token in dependabot workflow

go.mod, go.sum, pkg/server/server.go
This commit removes the dependency on
`github.com/brancz/kube-rbac-proxy` which was only needed to reload the TLS certificate and key files dynamically.
Instead the operator and admission webhook server use the `DynamicServingCertificateController` from `k8s.io/apiserver` which is a proven solution.
```release-note
```
=> chore: use apiserver controller to reload certs

Documentation/user-guides/strategic-merge-patch.md
For lists strategic merge patch can have surprising results where a list is replaced instead of added to. The operator offers workarounds for that, which should be explicitly mentioned.
=> documentation: mention additionalArgs

.golangci.yml, Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml, jsonnet/prometheus-operator/alertmanagerconfigs-crd.json, jsonnet/prometheus-operator/alertmanagers-crd.json, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/thanosrulers-crd.json, pkg/apis/monitoring/v1/alertmanager_types.go, pkg/apis/monitoring/v1/prometheus_types.go, pkg/apis/monitoring/v1/types.go, pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go, pkg/prometheus/operator.go, pkg/prometheus/promcfg.go, pkg/prometheus/server/operator.go, pkg/prometheus/server/statefulset.go, pkg/prometheus/server/statefulset_test.go
This change ensures that deprecated CRD fields are properly commented which make them reported by Go linters.
```release-note
```
=> chore: mark deprecated fields correctly

Documentation/proposals/202305-scrapeclasses.md
Taking over #5572 
Proposal to add scrape classes to facilitate the use of non-safe TLS elements in a scrape configuration, e.g. in the Istio use case.
A draft implementation is available: https://github.com/prometheus-operator/prometheus-operator/pull/5618. Links to significant code changes: [prom api](https://github.com/prometheus-operator/prometheus-operator/pull/5618/files#diff-b4a3c944005e67c959c04552108ff3b629b572d7244d586b0558651bd96eacda), [scrape class](https://github.com/prometheus-operator/prometheus-operator/pull/5618/files#diff-255c0aca616a1cdf4385c88d1d063a6c86360fedf99f7fc76bb967034e68897cR642-R652), [podmonitor api](https://github.com/prometheus-operator/prometheus-operator/pull/5618/files#diff-ed302c709df2a336b5712f4f4442e4972be00571fd5293c61e0f65f752b9e10a), …
=> chore: adding scrape classe

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, jsonnet/prometheus-operator/alertmanagers-crd.json, pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, pkg/apis/monitoring/v1/alertmanager_types.go, pkg/apis/monitoring/v1/zz_generated.deepcopy.go, pkg/client/applyconfiguration/monitoring/v1/alertmanagerspec.go
Fixes #6158.
It adds a dedicated field for cluster.label option in alertmanager. Default is to leave it blank, if it is not set. More background is mentioned in #6158 
```release-note
alertmanager `--cluster.label` (introduced `v0.26.0`) can be reconfigured with a dedicated field now.
```
=> dedicated field for cluster_label

Makefile, TESTING.md
Covers the comment https://github.com/prometheus-operator/prometheus-operator/pull/5903#discussion_r1397249107
```release-note
```
=> Add separate Makefile targets for e2e-tests

example/mixin/alerts.yaml, jsonnet/mixin/alerts/alerts.libsonnet, pkg/operator/resource_reconciler.go
This commit introduces 2 new counters:
* `prometheus_operator_status_update_errors_total`
* `prometheus_operator_status_update_operations_total`
The metrics have a `controller` label whose value is one of `alertmanager`, `prometheus`, `prometheus-agent` or `thanos`.
It also adds a new alerting rule `PrometheusOperatorStatusUpdateErrors` to the mixin which fires when a controller fails to update the status of the objects that it manages.
```release-note
Add `prometheus_operator_status_update_errors_total` and `prometheus_operator_status_update_operations_total` …
```
=> feat: add metrics tracking status updates

.github/workflows/automerge-dependabot.yaml
After months of trying to make this automation work, I declare myself defeated 😓 
I'll way for Github to provide support for running scripts in Dependabot PRs out-of-the-box
Thanks for your patience and sorry for the trouble @simonpasquier and @philipgough 
```release-note
```
=> Disable dependabot automation targeting k8s libs

.golangci.yml, pkg/kubelet/controller_test.go, pkg/operator/config_test.go, pkg/prometheus/agent/statefulset_test.go, pkg/prometheus/resource_selector_test.go, pkg/prometheus/server/statefulset_test.go, pkg/prometheus/statefulset_test.go, pkg/versionutil/cli_test.go, test/e2e/config_reloader_test.go, test/e2e/rules_test.go, test/e2e/scrapeconfig_test.go
By enabling the `testifylint` linter.
I'm particularly fond of this one as I think that testify is super ambiguous sometimes and easy to make mistakes 😬.
```release-note
```
=> Prevent mistakes with testify lib

.golangci.yml, pkg/prometheus/promcfg.go, pkg/thanos/statefulset_test.go, test/framework/prometheus.go
By enabling the `unconvert` linter
```release-note
```
=> Prevent unnecessary type conversions 

Documentation/rbac.md, Documentation/user-guides/prometheus-agent.md, bundle.yaml, cmd/operator/main.go, example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml, jsonnet/prometheus-operator/prometheus-operator.libsonnet, pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go, pkg/operator/operator.go, pkg/operator/rules.go, pkg/prometheus/agent/operator.go, pkg/prometheus/resource_selector.go, pkg/prometheus/resource_selector_test.go, pkg/prometheus/server/operator.go, pkg/prometheus/server/rules.go, pkg/thanos/operator.go, pkg/thanos/rules.go
Continuation of the work started by @rexagod in #6030 
Fixes #3611 
```release-note
Emit events when the controller rejects a resource, owing to an invalid configuration. These are:
* AlertmanagerConfig
* PodMonitor
* Probe
* PrometheusRule
* ScrapeConfig
* ServiceMonitor
```
=> feat: emit events for invalid configurations

pkg/apis/monitoring/v1/prometheus_types.go, pkg/apis/monitoring/v1alpha1/prometheusagent_types.go, pkg/client/versioned/typed/monitoring/v1/fake/fake_prometheus.go, pkg/client/versioned/typed/monitoring/v1/prometheus.go, pkg/client/versioned/typed/monitoring/v1alpha1/fake/fake_prometheusagent.go, pkg/client/versioned/typed/monitoring/v1alpha1/prometheusagent.go, test/e2e/main_test.go, test/e2e/prometheus_test.go, test/e2e/prometheusagent_test.go, test/framework/prometheus.go, test/framework/prometheusagent.go
Addresses comment https://github.com/prometheus-operator/prometheus-operator/pull/5962#discussion_r1430123922
```release-note
```
=> Add UpdateScale and GetScale methods

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/prometheus_types.go, pkg/client/applyconfiguration/monitoring/v1/remotewritespec.go
The Kubernetes API conventions say:
> All letters in the acronym should have the same case, using the
> appropriate case for the situation.
Since no release includes the field yet, it's ok to change the name.
Follow-up of #6192 
```release-note
```
=> chore: fix field name to comply with conventions

.github/workflows/checks.yaml
ref: 
https://github.com/prometheus-operator/prometheus-operator/actions/runs/7457201435/job/20289014732
https://github.com/prometheus-operator/prometheus-operator/actions/runs/7481957028/job/20364568306?pr=6198
```
/usr/bin/tar: ../../../go/pkg/mod/go-simpler.org/sloglint@v0.1.2/go.sum: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/go-simpler.org/sloglint@v0.1.2/cmd/sloglint/main.go: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/go-simpler.org/sloglint@v0.1.2/sloglint.go: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/go-simpler.org/sloglint@v0.1.2/.goreleaser.yml: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/go-simpler.org/sloglint@v0.1.2/go.mod: Cannot open: File exists
/usr/bin/tar: …
```
=> chore: fix golangci-lint `Files Exists` errors

pkg/thanos/statefulset.go
The SubPath attribute is needed in a VolumeMount if a user wants to mount a single file instead of a directory.
If adding a SubPath in the ThanosRuler spec, it is not added to the final ruler statefulset. This should fix that bug.
This is an incredibly simple change, and just adds the missing key in the volumeMounts map
```release-note
- Generate missing SubPath field in statefulset for spec.volumeMounts in ThanosRuler
```
=> ruler: add subpath to volumeMounts if specified

pkg/thanos/statefulset.go
* ruler: pass spec.volumeMount as-is
Cherry-picking #6243 into release branch
```release-note
ruler: add subpath to volumeMounts if specified
```
=> ruler: add subpath to volumeMounts if specified (#6243)

pkg/prometheus/resource_selector.go, pkg/prometheus/resource_selector_test.go
A typo bug has been introduced in this [PR](https://github.com/prometheus-operator/prometheus-operator/pull/6078/files) at the authentication method check. 
I've recreated the [PR](https://github.com/prometheus-operator/prometheus-operator/pull/6254) to be based on release-0.71
_Please put a one-line changelog entry below. This will be copied to the changelog file …
=> fix: azuresdconfig typo

pkg/apis/monitoring/v1beta1/conversion_from.go, pkg/apis/monitoring/v1beta1/conversion_to.go, test/e2e/alertmanager_test.go
The continue field was lost in the conversion between v1beta1 and v1alpha1. When creating a v1beta1 object with `continue: true`, the object was saved with `continue: false`.
```release-note
Fix conversion of the `.spec.route.continue` field between v1alpha1 and v1beta1 AlertmanagerConfig versions
```
=> fix: convert `continue` field between v1alpha1 and v1beta1 AlertmanagerConfig versions

pkg/informers/informers.go, pkg/informers/informers_test.go
This change modifies the `PartialObjectMetadataStrip` function to return the object unmodified if casting to `*v1.PartialObjectMetadata` fails. When the informer processes a deleted object, its type can be `cache.DeletedFinalStateUnknown`.
The issue has been reported to me out of band. Prometheus operator's logs:
```
level=error ts=2024-02-09T10:27:27.971343994Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth
msg="github.com/coreos/prometheus-operator/pkg/informers/informers.go:110: Failed to watch *v1.PartialObjectMetadata: unable to sync list result: internal error: 
cannot cast object cache.DeletedFinalStateUnknown{Key:\"openshift-kube-apiserver/etcd-client-3\", Obj:(*v1.PartialObjectMetadata)(0xc000e69200)} to PartialObjectMetadata"
```
_What type of changes does your …
=> fix: don't fail metadata transform on unknown types

Documentation/compatibility.md, pkg/operator/defaults.go, pkg/operator/rules_test.go
If we wait 2 days for the release, we can get Prometheus 2.50 as default prom version 🤔
=> Update default Thanos version

Documentation/user-guides/scrapeconfig.md
In the docs for scrapeConfig, the example of scrapeConfig in prometheus CR was incorrect. In prometheus CR, in scrapeConfigSelector, there should be matchLabels and then the scrapeConfig label.
In the [docs](https://prometheus-operator.dev/docs/user-guides/scrapeconfig/#static_config), this is provided in the prometheus CR example.
```
spec:
scrapeConfigSelector:
prometheus: system-monitoring-prometheus
```
Instead, it should be:
```
spec:
scrapeConfigSelector:
matchLables:
prometheus: system-monitoring-prometheus
```
fixes #6350
_What type of changes does your code introduce to the …
=> docs: correct example of scrapeConfigSelector in scrapeConfig doc

pkg/prometheus/agent/operator.go
Add `enqueueForPrometheusNamespace` to secret update handler
It will fix #6309
```release-note
Add enqueueForPrometheusNamespace in secret update handler
```
=> Fix: enqueue in updating secret

pkg/prometheus/promcfg.go
This PR adds more context to the deprecation warnings to know which resource (pod and service monitor) is using deprecated values as the current message is not really helpful to track the resource with issues.
This PR also adds some extra logs for other deprecations.
```release-note
```
=> Add extra context to warnings

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/prometheus_types.go
Remove experimental tag from sharding option
This commit changes the docs so that future prometheus operator users know the option is out of experimental. The sharding option is used for many years by multiple contributers.
- [ x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)
It is only a change to the docs. The nature of the change came from a discussion with the maintainers @ArthurSens  and @nicolastakashi  about the state of sharding done by the operator.
```release-note
Remove experimental tag from sharding option in prometheus CRD
```
=> Documentation: Remove experimental tag from sharding option

pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go, test/e2e/main_test.go, test/e2e/prometheus_instance_namespaces_test.go, test/e2e/scrapeconfig_test.go, test/framework/scrapeconfig.go
The ScrapeConfigs added in a different namespace from the Prometheus CR that selects them are not being picked up. We suspect it might be because of how the `enqueueForNamespace()` function works. This PR aims to prove that this is indeed the issue and consequentially also fix it.
- [ x] `BUGFIX` (non-breaking change which fixes an issue)
Tests added to `main_test.go`
```release-note
Fix ScrapeConfig not picked up bug
```
=> Fix: ScrapeConfigs Selection Issue Across Different Namespaces

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml, jsonnet/prometheus-operator/alertmanagers-crd.json, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/thanosrulers-crd.json, pkg/apis/monitoring/v1/alertmanager_types.go, pkg/apis/monitoring/v1/prometheus_types.go, pkg/apis/monitoring/v1/thanos_types.go
These 3 features have been there for so long that we agreed to remove the experimental warning on them.
This commit also makes the wording more consistent for all fields which are still considered experimental (either from the operator standpoint or from Prometheus standpoint).
```release-note
Declare PodMonitor, Probe and Thanos sidecar as officially supported.
```
=> Document PodMonitor, Probe and Thanos sidecar as stable

bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml, jsonnet/prometheus-operator/alertmanagerconfigs-crd.json, jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet, pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go, pkg/apis/monitoring/v1alpha1/validation.go, pkg/apis/monitoring/v1alpha1/validation_test.go, pkg/apis/monitoring/v1beta1/alertmanager_config_types.go, pkg/apis/monitoring/v1beta1/validation.go, pkg/apis/monitoring/v1beta1/validation_test.go
- fixes #6353
- fixes MonthRange regex.
- adds more unit tests to cover the numerical month values.
unit test only, I left E2E for the CI.
```release-note
- fix AltermanagerConfig CRD field muteTimeIntervals.timeIntervals.months regex pattern.
```
=> fix: Crd AltermanagerConfig field muteTimeIntervals.timeIntervals.months regex pattern |[1-12] isn't correct (#6353)

CONTRIBUTING.md
Documentation on deploying the local code in a local cluster seems like a good fit in [CONTRIBUTING.md](https://github.com/prometheus-operator/prometheus-operator/blob/main/CONTRIBUTING.md). However, it has not been removed from [TESTING.md](https://github.com/prometheus-operator/prometheus-operator/blob/main/TESTING.md) where it was originally part of, because it seems relevant there too.
- [x ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.) …
=> Docs: Include Local Deployment in CONTRIBUTING.md

Documentation/user-guides/scrapeconfig.md
Clarifies how `http_sd` and `file_sd` are different. Fixes #5940
```release-note
Docs to differentiate `http_sd` and `file_sd`
```
=> Update http_sd description for clarity

cmd/operator/main.go
Only start each controller when its crd is provided and manageable by the operator, and fail the operator if no controllers start.
Fixes #6140
Check locally with some crds not provided.
Before the change:
```
level=warn ts=2024-02-29T14:21:04.383739949Z caller=klog.go:118 component=k8s_client_runtime func=Warningf msg="pkg/mod/k8s.io/client-go@v0.29.2/tools/cache/reflector.go:229: failed to list *v1.Prometheus: the server could not find the requested resource (get prometheuses.monitoring.coreos.com)"
level=error ts=2024-02-29T14:21:04.383844053Z caller=klog.go:126 component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.29.2/tools/cache/reflector.go:229: …
```
=> Check if controllers' CRDs are provided and manageable by operator

pkg/prometheus/resource_selector.go, pkg/prometheus/resource_selector_test.go
If a user specify a non-parsable proxyUrl it was not validated/rejected but will break reloading and restarting of Prometheus due to possible invalid syntax. This commit adds validation and rejects the invalid ones
```release-note
fix: add proxyURL …
```
=> fix: add proxyURL validation for smon,pmon and probe

pkg/prometheus/resource_selector.go, pkg/prometheus/resource_selector_test.go
Add the validation for Kuma Server:
https://github.com/prometheus-operator/prometheus-operator/pull/6327#discussion_r1547614584
```release-note
feat(kuma): Add validation for kuma server
```
=> feat(kuma): Add validation for kuma server

pkg/apis/monitoring/v1/types.go, pkg/prometheus/resource_selector.go, pkg/prometheus/resource_selector_test.go
fix: #6177    
additional checks on the role selectors vs. the main role added
```
Add checks for selectors in KubernetesSDConfig
```
=> chore: Add checks for selectors in KubernetesSDConfig (#6177)

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/prometheus_types.go, pkg/apis/monitoring/v1/zz_generated.deepcopy.go, pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go, pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go, pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go, pkg/prometheus/server/statefulset_test.go, pkg/prometheus/statefulset.go, test/framework/prometheus.go
It allows different actors to manipulate the list of enabled features using server-side apply.
```release-note
define `.spec.enableFeatures` list as a set of unique values.
```
=> change: define enableFeatures list as a set

Documentation/api.md, pkg/apis/monitoring/v1/prometheus_types.go, pkg/apis/monitoring/v1/zz_generated.deepcopy.go, pkg/namespacelabeler/labeler.go, pkg/namespacelabeler/labeler_test.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/resource_selector.go, pkg/prometheus/resource_selector_test.go, pkg/prometheus/testdata/GenerateRelabelConfig.golden, pkg/prometheus/testdata/ProbeSpecConfig_targets_static_config.golden, test/e2e/prometheus_test.go
Replacement field with `""` value was omitted in the generated config earlier. This bug was fixed by checking for a nil value of its pointer, rather than the string value.
Closes #6443 
```release-note
```
=> Fix: Empty replacement is not possible when Action is Replace

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>
When only `relabeling` is configured in a `ScrapeClass` object, the `TLSConfig` field is nil. This causes a panic when the `TLSConfig` field is accessed in the `ScrapeClass` object.
I'm not sure about the business logic of the `ScrapeClass` TLSConfig field, but from pure Go perspective, it should fix the panic.
```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1ad78e1]
goroutine 386 [running]:
github.com/prometheus-operator/prometheus-operator/pkg/prometheus.(*ConfigGenerator).MergeTLSConfigWithScrapeClass(0x20d7080?, 0xc00172b420, 0xc000fe6d08?)
/home/runner/work/prometheus-operator/prometheus-operator/pkg/prometheus/promcfg.go:417 +0x81 …
```
=> fix: ScrapeClass TLSConfig nil pointer exception

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
Cherry-pick of #6507
```release-note
[BUGFIX] Fix ScrapeClass TLSConfig nil pointer panic when only relabeling is configured.
```
=> fix: ScrapeClass TLSConfig nil pointer exception (#6507)

pkg/k8sutil/metrics.go
controller-runtime also calls `metrics.Register()` during init and this function can be called only once. To ensure that the k8s client metrics get updated, the global variables need to be set again by the operator.
https://github.com/kubernetes-sigs/controller-runtime/blob/67b27f27e514bd9ac4cf9a2d84dec089ece95bf7/pkg/metrics/client_go_adapter.go#L42-L55 https://github.com/kubernetes/client-go/blob/aa7909e7d7c0661792ba21b9e882f3cd6ad0ce53/tools/metrics/metrics.go#L129-L170
Closes #6513  …
=> fix: register k8s metrics

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/prometheus_types.go, pkg/apis/monitoring/v1/zz_generated.deepcopy.go, pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go, pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go, pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go, pkg/prometheus/agent/statefulset.go, pkg/prometheus/agent/statefulset_test.go, pkg/prometheus/server/statefulset.go, pkg/prometheus/server/statefulset_test.go
Fixes https://github.com/prometheus-operator/prometheus-operator/issues/6270
```release-note
Make `automountServiceAccountToken` configurable for the Prometheus Operator StatefulSet
```
=> fix: make automountServiceAccountToken configurable

.github/workflows/stale.yaml
I was going through the list of open PRs today and noticed that we have many abandoned draft PRs where the majority have merge conflicts.
I was confused since we have workflows closing stale issues and PRs, until I noticed that we have an exception for drafts in our workflow.
I'm creating this PR to start a discussion about whether we want to close stale draft PRs as well. 
(I'm in favor)
=> Consider draft PRs electable for staleness

Documentation/troubleshooting.md
Fixes minor documentation glitch at https://github.com/prometheus-operator/prometheus-operator/issues/6552
Proof-reading done
```release-note
- Minor documentation fix for the troubleshooting section.
```
=> doc: fix sample port name used

TESTING.md
Updating Testing.md to add the steps for making the images with podman and adding them to kind cluster.
Closes #6488 
Tested the steps on a Mac machine with podman was able to run the alertmanger tests.
```release-note
Added Testing steps for using podman with Kind for running automated E2E tests.
```
=> Add testing steps for podman with kind

bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml, jsonnet/prometheus-operator/alertmanagerconfigs-crd.json, pkg/alertmanager/validation/v1beta1/validation_test.go, pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go, pkg/apis/monitoring/v1alpha1/validation_test.go, pkg/apis/monitoring/v1beta1/alertmanager_config_types.go, pkg/apis/monitoring/v1beta1/validation_test.go
fixes: #4882
Template string allowed for Responder.Type
```
Template string allowed for Responder.Type
```
=> chore: Template string allowed for Responder.Type (#4882)

pkg/alertmanager/validation/v1alpha1/validation.go, pkg/alertmanager/validation/v1beta1/validation.go
Sending an allegedly mis-configured alertmanagerConfig causes the operator to panic and CrashLoopBackoff.
```release-note
Fix panic when ApiURL is nil in WebexConfig.
```
=> fix: deref nil pointer on WebexConfig

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/prometheus_types.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/testdata/monitorObjectWithDefaultScrapeClassAndTLSConfig.golden, pkg/prometheus/testdata/monitorObjectWithNonDefaultScrapeClassAndTLSConfig.golden
Before this change, the TLS configuration from the scrape class wasn't applied to the generated configuration for PodMonitor, ScrapeConfig and Probe objects.
Closes #6556
```release-note
Fix TLS configuration from scrape classes not being applied to `PodMonitor`, `Probe` and `ScrapeConfig` objects.
```
=> fix: apply TLS scrape class to all objects

cmd/operator/main.go
```release-note
Add `go_sync_mutex_wait_total_seconds_total` metric.
```
=> feat: add `go_sync_mutex_wait_total_seconds_total` metric

Documentation/operator.md, cmd/operator/main.go, pkg/operator/feature_gates.go
As discussed in the last office hours, we want to start to provide a few features behind feature flags. This PR introduces the concept, but still no feature flags are available.
They will be added as need in following PRs.
```release-note
```
=> Add structure for feature flags

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/prometheus_types.go
This PR solves the issue #6550 . Added **default value** in the xxxMonitorNamespaceSelector field description.
- [ `x`] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)
Not required(docs change)
```release-note
- Documentation change foe xxxMonitorNamespaceSelector fields.
```
=> Corrected Documentation for xxxMonitorNamespaceSelector 

pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go
add etc/alertmanager/templates to watched-dir to support config reload when notification template files are modified.
Add etc/alertmanager/templates to watched-dir to support config reload when notification template files are modified
```release-note
Reload alert manager when notification templates are changed
```
=> Reload alert manager when notification templates change

pkg/prometheus/operator.go, pkg/prometheus/promcfg.go, pkg/prometheus/resource_selector.go, pkg/prometheus/server/operator.go, pkg/prometheus/store.go
This PR moves the logic for storing AM endpoints to the store and the subsequent validation to pkg/prometheus/server as per comments on #6467.
- [ x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)
```release-note
```
=> chore: Move AlertmanagerEndpoints validation to pkg/prometheus/server

pkg/prometheus/promcfg.go
It looks like we've got some sort of race conditions when merging https://github.com/prometheus-operator/prometheus-operator/pull/6492 and https://github.com/prometheus-operator/prometheus-operator/pull/6480.
We didn't have merge conflicts, and tests passed for both PRs, but [it failed to compile when they got to the `main` branch](https://github.com/prometheus-operator/prometheus-operator/actions/runs/9213422579/job/25347296248)
This PR fixes the `main` branch
```release-note
NONE
```
=> bugfix: Fix bug created from race conditions during merge

cmd/operator/main.go, pkg/prometheus/server/operator.go
After #6491 got merged, I went back to #6198. While I was trying to pass the feature-gate value to the controller, I noticed how we're passing way too many booleans to the function signature. Something that will only grow as we introduce more optionality as feature flags.
Here I'm proposing that we use a functional options pattern to create Prometheus Controller, allowing us to introduce more options without much effort. (The same can be done to other controllers as well)
In #6198, the plan would be to have a `WithGracefulShutdownSupport()` function, that would enable the feature in the controller's level.
Please check the [Prometheus-Operator testing guidelines](../TESTING.md) …
=> Use functional options pattern for Prometheus Controller

.github/workflows/e2e.yaml, test/e2e/scrapeconfig_test.go, test/framework/framework.go, test/framework/node.go
#6624 made testScrapeConfigKubernetesNodeRole() flaky because the test expected only 1 node target.
```release-note
```
=> chore: fix testScrapeConfigKubernetesNodeRole()

pkg/alertmanager/amcfg_test.go, pkg/alertmanager/testdata/skeleton_base_CR_with_subroutes.golden
Add test coverage to ensure that sub-routes don't enforce the continue value.
```release-note
```
=> chore: add test for AlertmanagerConfig with subroutes

test/framework/framework.go
Another PR aiming to simplify https://github.com/prometheus-operator/prometheus-operator/pull/6198, this one extends the e2e-test framework to allow creating prometheus-operators with feature-flags enabled.
```release-note
```
=> e2e/framework: Allow setting feature-gates when creating Prometheus-Operator

pkg/alertmanager/statefulset.go, pkg/operator/config_reloader.go, pkg/operator/config_reloader_test.go, pkg/prometheus/server/statefulset_test.go, pkg/prometheus/statefulset.go
The Kubernetes API starting from v1.30 will return a warning when a pod template contains 2 containers exposing the same port number, even across init and regular containers.
[1] https://github.com/kubernetes/kubernetes/pull/113245
Closes #6284
```release-note
Use port 8081 instead of 8080 to expose the init config-reloader web server.
```
=> fix: use a separate port number for init container

pkg/operator/config_reloader.go, pkg/operator/config_reloader_test.go
Add `NODE_NAME` env in config reloader for DaemonSet deployment of Prometheus Agent. In DaemonSet deployment, Prometheus Agent is deployed per node and only scrapes targets located on the same node. That's why it needs to know its `NODE_NAME` to filter targets. Detailed reasons and how `NODE_NAME` env is used are explained in the proposal #6600.
Unit tests
Add NODE_NAME env in config reloader
=> Add NODE_NAME env in config reloader

Documentation/operator.md, cmd/operator/main.go, pkg/operator/config.go, pkg/operator/feature_gates.go, pkg/operator/feature_gates_test.go
This change also moves the feature gates to the operator config struct. It means that after a feature gate is enabled/disabled, the operator will reconcile the managed Prometheus resources which should be the right thing to do.
```release-note
```
=> feat: add `prometheus_operator_feature_gate_info` metric

pkg/listwatch/listwatch_test.go, pkg/operator/argument_test.go, pkg/operator/config_reloader_test_lib.go, pkg/operator/prober_test.go, pkg/operator/rules_test.go
Currently, there is an excessive usage of [t.Fatal ](https://github.com/search?q=repo%3Aprometheus-operator%2Fprometheus-operator+t.Fatal&type=code&p=3)in this repository. To make the code more readable, and to remove repetitive manual checks, I have replaced t.Fatal with functions of **testify/require package**. Currently, this PR only consists of changes applied in **pkg/operator**. 
Since I made changes only in **pkg/operator**, I ran a test for this package using ```go test ./pkg/operator``` and received the following output -  ```ok      github.com/prometheus-operator/prometheus-operator/pkg/operator 0.065s```
=> [Enhancement] Replacing t.Fatal with testify/require package 

pkg/prometheus/agent/statefulset_test.go, pkg/prometheus/agent/test_utils.go
Refactor common test code between Prometheus Agent's StatefulSet and DaemonSet modes to reduce duplication and make reviewing https://github.com/prometheus-operator/prometheus-operator/pull/6652 easier.
If seeing any pieces can be refactored further into the Server mode then do it too.
If seeing anywhere `testing` package is used when `require` and `assert` is the better option, make the change too.
If seeing any minor code-related improvement chance, do it too. 
CI green
=> WIP: Refactor common test code between Prometheus Agent's StatefulSet and DaemonSet modes

pkg/prometheus/agent/statefulset.go
Only append `agent` to `EnableFeatures` for Prometheus Agent if it doesn't exist yet, as explained in https://github.com/prometheus-operator/prometheus-operator/pull/6686#discussion_r1644463561
CI green
=> Nit: Check if EnableFeatures already contains agent mode's features

pkg/alertmanager/statefulset.go, pkg/operator/image.go, pkg/operator/storageclass.go, pkg/prometheus/agent/statefulset.go, pkg/prometheus/server/statefulset.go
While reviewing a few PRs from @haanhvu, I've noticed we're using a function that does the same thing as `ptr.Deref`. The reason is because that code was written before generics were a thing.
I don't mean to create conflicts with @haanhvu's PRs, so we can merge this one after we get yours merged first :)
```release-note
```
=> chore: Replace StringPtrValOrDefault with ptr.Deref

pkg/prometheus/agent/statefulset_test.go, pkg/prometheus/agent/test_utils.go, pkg/prometheus/server/statefulset_test.go, pkg/prometheus/test_utils.go
Continues #6688. Do some changes that we agreed in Slack:
- Remove Thanos image in test config: https://cloud-native.slack.com/archives/C071STDT4FP/p1718722242845739
- Refactor `TestWALCompression` for both StatefulSet and DaemonSet: https://cloud-native.slack.com/archives/C071STDT4FP/p1718703164200639
- Refactor `TestStartupProbeTimeoutSeconds`: https://github.com/prometheus-operator/prometheus-operator/pull/6686#discussion_r1645711201
- Use some appropriate refactored functions in server mode
CI green
=> Continue #6688: Refactor common test code between Prometheus modes

pkg/kubelet/controller.go, pkg/kubelet/controller_test.go
We have found that the kubelet controller does not make any node condition checks prior to adding their addresses to the kubelet endpoint. Normally, this is not an issue as it ends in the endpoint target being marked as "down" and scraping fails because the node is not ready.
A much larger symptom occurs when there is an IP address that is reused from a down/NotReady node in the cluster (we have seen this exact scenario in GKE). For instance, node1 can be `NotReady` with IP address 1.2.3.4 and the underlying provisioner creates a new node, node2, reusing IP address 1.2.3.4.
During this scenario, because kubelet controller doesn't check for node status it will add two endpoint addresses with the same IP address. An example of subsets might look like this:
```
- ip: 1.2.3.4
targetRef:
kind: …
```
=> Only add node IPs to kubelet endpoint if they have a known Ready condition

pkg/prometheus/agent/daemonset.go, pkg/prometheus/agent/daemonset_test.go, pkg/prometheus/agent/statefulset.go
Support `makeDaemonSet()` and inner function `makeDaemonSetSpec()` for Prometheus Agent's DaemonSet deployment
Unit tests
Support makeDaemonSet() for Prometheus Agent's DaemonSet deployment
=> Support makeDaemonSet() for Prometheus Agent's DaemonSet deployment

scripts/run-external.sh
This change allows to pass feature gates to the script. For instance:
```
FEATURE_GATES="PrometheusAgentDaemonSet=true"  ./run/run-external.sh -c
```
```release-note
```
=> feat: pass feature gates to scripts/run-external.sh

cmd/operator/main.go
Check DaemonSet RBAC permissions for Prometheus Agent's DaemonSet mode, if Prometheus Agent DaemonSet feature gate is enabled, as explained in https://github.com/prometheus-operator/prometheus-operator/pull/6708#pullrequestreview-2144720179
For now we just need CI to be green. To test this behavior we need to implement other things in next PRs, after which we'll have e2e tests.
Check DaemonSet RBAC permissions for Prometheus Agent's DaemonSet mode
=> Check DaemonSet RBAC permissions for Prometheus Agent's DaemonSet mode

internal/log/slog.go, internal/log/slog_test.go
Fixes #6183
Following the @ArthurSens suggestion, first I'm adapting the new slog constructor to follow the same requirements of the `k8s.io/klog/v2` and afterwards I plan to replace all the imports.
```release-note
feature: add new logger for slog library
```
=> Feat: new logger slog

cmd/admission-webhook/main.go, cmd/operator/main.go, cmd/prometheus-config-reloader/main.go, internal/goruntime/cpu.go, internal/goruntime/memory.go
Adapting the places where we are using the `go_kit_log library`, but doing that in baby steps to avoid changing many places simultaneously.
I'm Keeping the oldLogger (go_kit_log) in places where we have more dependencies and adding the new Logger where it's easy to change
This PR follows up on the changes made here https://github.com/prometheus-operator/prometheus-operator/pull/6743
```release-note
replace go-kit-log
```
=> replace go kit log

bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/prometheus_types.go
This adds the listType:=set kubebuilder marker to the secrets field in the Prometheus CRD. This allows the field to be managed by multiple managers.
I have this Prometheus instance:
```
kind: Prometheus
metadata:
creationTimestamp: "2024-07-18T18:10:17Z"
generation: 4
name: sample-monitoring-stack
namespace: operators
resourceVersion: "47399"
uid: e1d2eb3d-ca6c-4e9d-8032-854109bb539a
spec:
evaluationInterval: 30s
portName: web
scrapeInterval: 30s
```
And 2 files:
_add\_secret.yaml_
```
kind: Prometheus
metadata:
name: sample-monitoring-stack
namespace: operators
spec:
secrets:
- prometheus-sample-monitoring-stack
```
_add\_secret2.yaml_
```
kind: Prometheus
metadata:
name: …
```
=> add listType:=set to Prometheus secrets field

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/server/operator.go, pkg/prometheus/store.go, pkg/prometheus/testdata/AlertmanagerConfigEmpty.golden, pkg/prometheus/testdata/AlertmanagerConfigOtherNamespace.golden, pkg/prometheus/testdata/AlertmanagerConfigTLSconfig.golden, pkg/prometheus/testdata/AlertmanagerConfigTLSconfigOtherNamespace.golden, pkg/prometheus/testdata/K8SSDConfigGenerationTLSConfig.golden
Fixes #6670
```release-note
```
=> fix: avoid invalid alerting config with TLS

cmd/admission-webhook/main.go, cmd/operator/main.go, pkg/admission/admission.go, pkg/admission/admission_test.go
Adapting the places where we are using the `go_kit_log library` into the admission package
```release-note
replace kit log with slog in package admission
```
=> replace go kit log admission pkg

internal/log/slog.go, internal/log/slog_test.go
Using the right level integer to disable logs
```release-note
disable logs for unknow and none levels
```
=> disable logs for unknow and none levels

cmd/operator/main.go, pkg/alertmanager/operator.go, pkg/listwatch/listwatch.go, pkg/operator/config.go, pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go, pkg/thanos/operator.go
This change introduces functional options for all 4 controllers (previously only Prometheus used them).
It also reduces code duplication regarding API version checks.
```release-note
```
=> chore: simplify controller constructors

Documentation/design.md
Wrong link in `design.md` was failing generate and format script. Consequence of #6779.
- [] `BUGFIX` (non-breaking change which fixes an issue)
```release-note
```
=> CHORE: fix wrong link to prometheus-agent proposal

pkg/operator/config_reloader.go, pkg/operator/config_reloader_test.go, pkg/prometheus/agent/daemonset.go, pkg/prometheus/agent/daemonset_test.go, pkg/prometheus/agent/operator.go, pkg/prometheus/agent/statefulset.go, pkg/prometheus/common.go, pkg/prometheus/operator.go, pkg/prometheus/server/statefulset.go, test/e2e/controllerid_test.go, test/e2e/main_test.go, test/e2e/prometheusagent_test.go, test/framework/framework.go, test/framework/prometheusagent.go
Allow Prometheus Agent operator to create DaemonSet if DaemonSet mode is chosen.
WIP: Local tests and e2e tests for sure, unit tests maybe
Allow Prometheus Agent operator to create DaemonSet
=> Allow Prometheus Agent operator to create DaemonSet

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml, jsonnet/prometheus-operator/scrapeconfigs-crd.json, pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go, pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go, pkg/client/applyconfiguration/monitoring/v1alpha1/dnssdconfig.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/resource_selector_test.go, pkg/prometheus/testdata/ScrapeConfigSpecConfig_DNSSD_MXRecord.golden, test/e2e/main_test.go, test/e2e/scrapeconfig_test.go
This PR adds missing validations to the DNS Service Discovery configurations.
Closes #6739 
```release-note
```
=> Refactor DNS SD Config

pkg/prometheus/agent/operator.go
There were some unnoticeable conflicts between #6786 and #6708 that completely broke main. This PR fixes it
```release-note
```
=> bugfix: Fix merge conflict with logger

pkg/alertmanager/amcfg.go, pkg/alertmanager/types.go
This change doesn't implement the corresponding fields in the AlertmanagerConfig CRD but only in the configuration generated by the operator.
```release-note
Support all proxy settings in the Alertmanager configuration.
```
=> feat: sync proxy settings in Alertmanager configuration

cmd/operator/main.go, pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go, pkg/operator/resource_reconciler.go, pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go, pkg/thanos/operator.go, pkg/thanos/rules.go
The `ResourceReconciler` structure is used across all operators. I duplicated the logger and replace their names to a meaningful one (`goKitLogger`), like i'm doing the in the past PRs.
But in the end, this PR just aim to change the log library in the following file: `pgk/operator/resource_reconciler.go`
```release-note
```
=> replace gokitlog in the resource reconciler

pkg/alertmanager/operator.go, pkg/operator/accessor.go, pkg/prometheus/agent/operator.go, pkg/prometheus/resource_selector.go, pkg/prometheus/resource_selector_test.go, pkg/prometheus/server/operator.go, pkg/thanos/operator.go, test/framework/framework.go
- replace go kit log in resource_selector.go
- replace go kit log in accessor.go
- remove unused err validation
```release-note
```
=> replace go kit log in resource selector

pkg/alertmanager/operator.go, pkg/k8sutil/secrets.go, pkg/k8sutil/secrets_test.go, pkg/operator/event_handler.go, pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go, pkg/thanos/operator.go
Replace goKitLogger in k8sutil package and EventHandler struct 
```release-note
```
=> chore: replace goKitLogger in k8sutil and event handler

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml, jsonnet/prometheus-operator/scrapeconfigs-crd.json, pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go, pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go, pkg/client/applyconfiguration/monitoring/v1alpha1/dockersdconfig.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/testdata/ScrapeConfigSpecConfig_DockerSD_with_MatchFirstNetwork.golden, pkg/prometheus/testdata/ScrapeConfigSpecConfig_DockerSD_with_MatchFirstNetwork_OldVersion.golden
Closes #6839 
```release-note
Support MatchFirstNetwork field for DockerSD
```
=> feat: add MatchFirstNetwork field for DockerSD

pkg/prometheus/promcfg.go, pkg/prometheus/testdata/ScrapeConfigSpecConfig_ProxySettingsIncompatiblePrometheusVersion.golden
The `proxy_url` field is supported for all 2.x versions. I found the issue while reviewing some code. The issue doesn't impact ServiceMonitor, Probe and PodMonitor which don't call (yet) `addProxyConfigtoYaml()`. It's also not affecting deployments that use a reasonably recent version of Prometheus (e.g. >= 2.43 which is 1 year and half old)
```release-note
Fix proxy URL support for all Prometheus versions.
```
=> fix: allow proxy URL for all Prometheus versions

Documentation/high-availability.md, Documentation/operator.md, Documentation/rbac-crd.md, Documentation/rbac.md, Documentation/thanos.md, Documentation/troubleshooting.md, Documentation/user-guides/alerting.md, Documentation/user-guides/getting-started.md, Documentation/user-guides/prometheus-agent.md, Documentation/user-guides/scrapeconfig.md, Documentation/user-guides/storage.md, Documentation/user-guides/strategic-merge-patch.md, Documentation/user-guides/webhook.md
On the [website](https://prometheus-operator.dev/), the Developer Guide comes before the Platform Guide. The Developer Guide instructs us how to configure scraping, alerting, and recording rules while the Platform Guide instructs us how to deploy a Prometheus, Alertmanager, or Thanos instance. In discussion with @nicolastakashi and @ArthurSens, we concluded moving the Platform Guide before the Developer Guide would be better to make a better user experience. It makes more sense to learn how to deploy Prometheus before moving on to learning configuration for scraping metrics.
This PR will change the order of these Guides. You can view the preview in this [PR](https://github.com/prometheus-operator/website/pull/100).
_What type of changes does your code introduce to the Prometheus operator? …
=> Switching the position of Platform and Developer Guide in Website

pkg/alertmanager/operator.go, pkg/operator/operator.go, pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go, pkg/thanos/operator.go
Replace goKitLogger in the WaitForNamedCacheSync function
```release-note
```
=> replace goKitLogger in WaitForNamedCacheSync

cmd/operator/main.go, pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go, pkg/listwatch/listwatch.go, pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go, pkg/thanos/operator.go
replace goKitLogger in operators
```release-note
```
=> replace goKitLogger in operators

cmd/admission-webhook/main.go, cmd/operator/main.go, pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go, pkg/prometheus/server/rules.go, pkg/server/server.go, pkg/thanos/operator.go
- Remove `goKitLogger` from unused frames
- replace `goKitLogger` in rules and server
```release-note
```
=> replace goKitLogger in rules and server

pkg/alertmanager/operator.go, pkg/k8sutil/k8sutil.go, pkg/operator/resource_reconciler.go, pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go, pkg/thanos/operator.go, test/e2e/main_test.go, test/e2e/prometheusagent_test.go, test/framework/prometheusagent.go
Allow Prometheus Agent update, delete, and handle changes to DaemonSet object
E2e that update/delete Prometheus Agent DaemonSet
Allow updating and deleting Prometheus Agent DaemonSet
=> Allow Prometheus Agent to update, delete, and handle changes to DaemonSet object

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml, jsonnet/prometheus-operator/scrapeconfigs-crd.json, pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go
ref: https://github.com/prometheus/prometheus/pull/14654
```release-note
fix `MatchFirstNetwork` dependency on prometheus version v2.54.1
```
=> Fix: `MatchFirstNetwork` dependency on prometheus version v2.54.1

pkg/prometheus/agent/daemonset_test.go, pkg/prometheus/agent/operator.go, pkg/prometheus/agent/statefulset_test.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/server/operator.go, pkg/prometheus/server/statefulset_test.go
From https://github.com/prometheus-operator/prometheus-operator/pull/6879
```release-note
```
=> chore: refactor NewConfigGenerator() with functional options

test/e2e/prometheus_test.go, test/e2e/prometheusagent_test.go, test/framework/crd.go, test/framework/prometheusagent.go
This change decreases all timeouts greater than 10 minutes.
```release-note
```
=> chore: reduce e2e test timeouts

cmd/prometheus-config-reloader/main.go, go.mod, go.sum
Recently, exporter toolkit switched to slog. [Reference](https://github.com/prometheus-operator/prometheus-operator/pull/6890#issuecomment-2340185908)
- Update exporter toolkit to v0.13.0
```release-note
```
=> Update exporter toolkit to v0.13.0

Documentation/proposals/202409-status-subresource.md
Continuation of https://github.com/prometheus-operator/prometheus-operator/pull/4575 (for some reason, GitHub doesn't let me reopen the PR).
The document reflects the current implementation of status subresource. In particular, it doesn't cover configuration objects (like ``ServiceMonitor`) which would require a new proposal.
For history, the design proposal before actually implementing it can be found at https://github.com/simonpasquier/prometheus-operator/blob/status-subresource-design-v1/Documentation/proposals/202409-status-subresource.md
_Please put a one-line …
=> doc: add design doc about status subresource

pkg/alertmanager/operator.go
```
2024/09/13 14:20:36 INFO sync alertmanager !BADKEY=&{handler:0xc00090c3a0} key=default/example
```
```release-note
```
=> fix: avoid BADKEY error in logs

CHANGELOG.md, pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go, pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go, pkg/alertmanager/validation/v1alpha1/validation.go, pkg/alertmanager/validation/v1beta1/validation.go, pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go, pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
This change rejects AlertmanagerConfig objects with invalid child routes definition to cause problems in the configuration generation.
Closes #6277
```release-note
```
=> fix: validate child routes

pkg/apis/monitoring/v1/prometheus_types.go, pkg/prometheus/agent/operator.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/testdata/PromAgentDaemonSetPodMonitorConfig.golden, test/e2e/main_test.go, test/e2e/prometheusagent_test.go, test/framework/prometheusagent.go, test/framework/resources/basic-app-for-daemonset-test.yaml
Support PodMonitor for Prometheus Agent in DaemonSet mode. The reasons and design of this feature are described in https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/proposals/202405-agent-daemonset.md#63-targets-filtering-for-pods-podmonitor-support
WIP: e2e for sure, unit tests maybe
Support PodMonitor for Prometheus Agent in DaemonSet mode
=> Support PodMonitor for Prometheus Agent in DaemonSet mode

.github/workflows/e2e-prometheus3.yaml, .github/workflows/test-prom-version-upgrade.yaml, Documentation/compatibility.md, cmd/po-docgen/compatibility.go, pkg/operator/defaults.go, pkg/prometheus/agent/daemonset.go, pkg/prometheus/agent/daemonset_test.go, pkg/prometheus/agent/statefulset.go, pkg/prometheus/agent/statefulset_test.go, pkg/prometheus/promcfg.go, test/framework/prometheus.go
Fixes #6939
```release-note
feat: add experimental Prometheus 3 support
Issues in unsupported prometheus versions won't be supported by operator.
This is just to try out new beta versions
```
=> feat: add experimental Prometheus 3 support

Dockerfile, Makefile, cmd/admission-webhook/Dockerfile, cmd/prometheus-config-reloader/Dockerfile
This introduces multi-stage Dockerfiles. The go build step for images now happens in the build step in the container file definition. The prometheus golang builder image is used.
The main benefit is that external build systems can simply build the Dockerfile, no need to know how to build binaries or what dependencies to install.
In the future there could be benefits for building on non-x86 architectures and perhaps testing.
=> build: move build step to Dockerfiles

TESTING.md, test/e2e/scrapeconfig_test.go
Closes #6976
Adds test cases for empty string values in `[]string` types. As per the discussion in #6976, I only added tests in ScrapeConfig and where the annotation is `kubebuilder:validation:items:MinLength=1`
```release-note
add test cases for empty …
```
=> feat: empty string values test cases

.github/workflows/checks.yaml, .github/workflows/e2e-feature-gated.yaml, .github/workflows/e2e.yaml, .github/workflows/unit.yaml
To cancel the workflow running when new
commits are pushed to pull request branch
This could help us save the action time instead of running the test unnecessarily
To cancel the workflow run when new commits are pushed to pull request branches
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency
_Please put a one-line …
=> chore: add concurrency for workflows

Documentation/proposals/202405-scrapeconfig-graduation.md
Proposal for extending the ScrapeConfig API surface to pave the way for graduation to `v1beta1`. 
- [ x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)
```release-note
```
=> ScrapeConfig CRD: Proposal For Extending The CRD Surface 

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml, jsonnet/prometheus-operator/scrapeconfigs-crd.json, pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go, test/e2e/scrapeconfig_test.go
PR adds additional validation and e2e testcases for StaticConfig.
```release-note
```
=> ScrapeConfig: Refactor StaticConfig

CHANGELOG.md, Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, pkg/apis/monitoring/v1/dns_types.go, pkg/apis/monitoring/v1/prometheus_types.go, pkg/k8sutil/k8sutil.go, pkg/k8sutil/k8sutil_test.go, pkg/prometheus/agent/daemonset.go, pkg/prometheus/agent/statefulset.go, pkg/prometheus/server/statefulset.go, pkg/thanos/statefulset.go, pkg/thanos/statefulset_test.go
In #3899, we missed the DaemonSet mode which is behind a feature gate.
```release-note
```
=> chore: implement DNS options for DaemonSet

pkg/kubelet/controller.go, pkg/kubelet/controller_test.go
add `nodeName` to kubelet endpoints 
Close #6794 
```release-note
add `nodeName` to  kubelet endpoints 
```
=> feat: add `nodeName` to  kubelet endpoints 

Dockerfile, Makefile, cmd/admission-webhook/Dockerfile, cmd/prometheus-config-reloader/Dockerfile
Afaiu the spec is unclear whether to quote this or not. In this case here is certainly not requires and works fine without. Additionally, there is some tooling which does not treat quotes values correctly and generates image links like
`quay.io/prometheus/golang-builder:\"1.23\"-base`.
_Please put a one-line changelog entry below. This will be copied to the changelog …
=> Dockerfile: drop double quotes around ARG default values

.github/workflows/changed-files.yaml, .github/workflows/e2e-feature-gated.yaml, .github/workflows/e2e.yaml, .github/workflows/unit.yaml
Ref: https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
This will help to avoid blocking the merge on conditional execution of jobs. 
When there are only `.md` file update currently unit tests and e2e test won't run but they are required tests to merge
we cannot automatically merge as it will report those tests as pending.
See below screenshot
With this change those tests will be skipped hence will report status as success even though it is a required test.
_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box …
=> .github/workflow: make execution of e2e and unit tests conditional

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/prometheus_types.go, scripts/generate/append-operator-version.sh
The description for `prometheus.spec.remoteWrite.sendExemplars` suggests using `spec.enableFeature` instead of the existing `spec.enableFeatures` field.
```
$ oc explain prometheus.spec.remoteWrite.sendExemplars
GROUP:      monitoring.coreos.com
KIND:       Prometheus
VERSION:    v1FIELD: sendExemplars <boolean>DESCRIPTION:
Enables sending of exemplars over remote write. Note that exemplar-storage
itself must be enabled using the `spec.enableFeature` option for exemplars
to be scraped in the first place. 
It requires Prometheus >= v2.27.0.
```
_What type of changes does your code introduce …
=> fix: address OpenAPI text inconsistency for `prometheus.spec.remoteWrite.sendExemplars`

pkg/prometheus/server/operator.go, pkg/prometheus/server/operator_test.go, pkg/prometheus/server/statefulset.go, pkg/prometheus/server/statefulset_test.go, pkg/prometheus/server/thanos_sidecar_config.go
Change thanos sidecar's param `--prometheus.http-client` to `--prometheus.http-client-file` descripted [here](https://thanos.io/tip/components/sidecar.md/#prometheus-http-client)
This change may make the Thanos sidecar more flexible to configure. It will also be useful to set authorization info in secret for more security.
```release-note
```
=> enhance: change thanos sidecar promethes.http-client params to prometheus.http-client-file and save config file in secret

.github/workflows/e2e-feature-gated.yaml, .github/workflows/e2e-prometheus3.yaml, .github/workflows/e2e.yaml, .github/workflows/test-prom-version-upgrade.yaml, test/e2e/alertmanager_test.go, test/e2e/prometheus_test.go, test/framework/context.go, test/framework/pod.go, test/framework/prometheus.go
When the E2E_DIAGNOSTIC_DIRECTORY environment variable is set, the test framework will save all collected information (logs, events, resources, ...) to this directory.
Related to #6973
```release-note
```
=> chore: allow to save e2e diagnostics to disk

.github/workflows/e2e-prometheus3.yaml, .github/workflows/stale.yaml, .github/workflows/test-prom-version-upgrade.yaml
I found that after forking the **prometheus-operator** code, some github runners will be run cronjob in my repository. Should we let it run only in the prometheus-operator repository?
This is the runner that runs in my repository, including `Close stale issues and PRs`, `Test Prometheus upgrades`, `e2e-prometheus3`:
https://github.com/daviderli614/prometheus-operator/actions
```release-note
```
=> ci: Let github runner run only in the prometheus-operator main repository

Documentation/operator.md, cmd/operator/main.go, pkg/prometheus/server/operator.go
Allow toggling custom config deprecation behaviour; helpful in scenarios where a controller disables all service discovery methods.
```release-note
Users can toggle Prometheus controller's custom configuration deprecation behavior using the "--deprecate-custom-configuration" flag.
```
=> enhancement: allow toggling custom config deprecation behaviour

pkg/alertmanager/statefulset.go
We've noticed that sometimes DNS caching can have a race condition with the alertmanager liveness probe, which causes a cyclic behavior because the alertmanager tries to resolve old addresses for communicating with others alertmanagers.
Essentially the liveness probe relies on the readiness probe, and this patch removes that dependency, and instead the IP for discovery is updated immediately by DNS.
Tested by pausing the Alertmanager object that we've seen be affected by this, setting the field manually and that resolved it. Unpausing and letting the field be set to false again causes the same problem again. …
=> alertmanager: Publish non ready endpoints

cmd/admission-webhook/main.go, cmd/operator/main.go, cmd/prometheus-config-reloader/main.go, internal/metrics/metrics.go, internal/util/metrics.go
Ref: https://github.com/golang/go/issues/49881
Optimize go runtime metrics for operator, admission-webhook and prometheus-config-reloader
```release-note
Optimize go runtime metrics for operator, admission-webhook and prometheus-config-reloader
```
=> chore: Optimize go runtime metrics

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/prometheus_types.go
For the Prometheus CRD, the operator default to true for `spec.disableCompaction` when `spec.thanos.objectStorageConfig(|File)` is defined, but this is not documented anywhere but in code (and in kube-prometheus-stack helm chart values, as it turns out).
https://github.com/prometheus-operator/prometheus-operator/blob/35790cdbeec2f302516781365313e7d6fc007ac8/pkg/prometheus/server/statefulset.go#L753-L761
Document the behavior in the API reference directly.
N/A
```release-note
Document default behavior of `spec.disableCompaction` in Prometheus CRD in relation to Thanos sidecar object store configuration.
```
=> Document disableCompaction defaulting when using thanos sidecar

Documentation/user-guides/shards-and-replicas.md, example/shards/prometheus.yaml
The previous labelling was inconsistent: The deployment was labelled with prometheus: prometheus, but the service was selecting on prometheus: shards. Corrected service definition
```release-note
```
=> fix: Fix incorrect label

pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, pkg/prometheus/server/statefulset_test.go
Code that prevented automatically mounting web config to the AM configReloader (regardless of whether Web Config was defined or not) was to be removed after v0.72.0 of the Operator.
- Always mount webconfig secret to the ConfigReloader for AM 
- 
```
Always mount webconfig secret to the ConfigReloader for AM 
```
=> Chore: Remove outdated code from AM Statefulset generation

.gitignore, Makefile
`make test-e2e-images` was dependent on Dockerfile, which meant that code changes did not affect it and no new images were being created and loaded into the local cluster. 
This PR aims to change that behavior.
```release-note
```
=> Fix make test-e2e-images

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, jsonnet/prometheus-operator/alertmanagers-crd.json, pkg/alertmanager/statefulset.go, pkg/alertmanager/statefulset_test.go, pkg/apis/monitoring/v1/alertmanager_types.go, pkg/apis/monitoring/v1/zz_generated.deepcopy.go, pkg/client/applyconfiguration/monitoring/v1/alertmanagerspec.go
Allows configuring Alertmanager Statefulsets persistentVolumeClaimRetentionPolicy which will allow for easier statefulset cleanups on deletion.
Followup https://github.com/prometheus-operator/prometheus-operator/pull/6038
```release-note
feat: Add …
```
=> feat: Add support for configuring Alertmanager STS persistentVolumeClaimRetentionPolicy

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/prometheus_types.go, pkg/apis/monitoring/v1/zz_generated.deepcopy.go, pkg/client/applyconfiguration/monitoring/v1/alertmanagerendpoints.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/server/operator.go, pkg/prometheus/testdata/AlertmanagerConfigProxyconfig.golden
We add support for client http proxy [settings](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#http_config) for alertmanager endpoints specified in the Prometheus config.
Specifically, we utilize the existing ProxyConfig api used elsewhere and embed it in the `AlertmanagerEndpoints` api.
Ran `make test-unit` and `make test-unit-update-golden` targets with success.
```release-note
Add client http proxy settings for …
```
=> feat: add proxy_url to alertmanagerendpoints

pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go, pkg/alertmanager/testdata/CR_with_EmailConfig_Receiver_Conf.golden, pkg/alertmanager/testdata/CR_with_EmailConfig_Receiver_Global_Defaults_Conf.golden, test/e2e/alertmanager_test.go
Related-to #6003
```release-note
fix: validate smtp smarthost and smtp from fields of emailConfig
```
=> fix: validate smtp smarthost and smtp from fields

Documentation/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml, example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml, example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml, example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml, jsonnet/prometheus-operator/podmonitors-crd.json, jsonnet/prometheus-operator/probes-crd.json, jsonnet/prometheus-operator/scrapeconfigs-crd.json, jsonnet/prometheus-operator/servicemonitors-crd.json, pkg/apis/monitoring/v1/podmonitor_types.go, pkg/apis/monitoring/v1/probe_types.go, pkg/apis/monitoring/v1/servicemonitor_types.go, pkg/apis/monitoring/v1/zz_generated.deepcopy.go, pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go, pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go, pkg/client/applyconfiguration/monitoring/v1/podmonitorspec.go, pkg/client/applyconfiguration/monitoring/v1/probespec.go, pkg/client/applyconfiguration/monitoring/v1/servicemonitorspec.go, pkg/client/applyconfiguration/monitoring/v1alpha1/scrapeconfigspec.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, test/e2e/scrapeconfig_test.go
While reviewing #7197 noticed that Prometheus is using `fallback_scrape_protocol` for the field hence updating to match similar naming to avoid confusion among users.
This is a newly introduced field in this release v0.79 so we want to update it in patch release before users use this field. …
=> CHANGE/BugFix: Rename scrapeFallbackProtocol to fallbackScrapeProtocol

CHANGELOG.md, pkg/prometheus/common.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/resource_selector.go, pkg/prometheus/testdata/PodMonitorObjectWithSelectorAndMatchExpressionSelector.golden
Fixing pod and service monitor selector validation. https://github.com/prometheus-operator/prometheus-operator/issues/7214
```release-note
Fixing pod and service monitor selector validation.
```
=> [BUGFIX] Fixing pod and service monitor selector validation

jsonnet/prometheus-operator/scrapeconfigs-crd.json, test/e2e/scrapeconfig_test.go
Refactor LightsailSDConfig API.
```release-note
1. Add the test cases for the LightSailSD resource.
2. Add Kubernetes resource validation.
```
Fix #7205
=> Refactor LightSailSDConfig

.golangci.yml
The `deadline` option is replaced by timeout
ref: https://golangci-lint.run/usage/configuration/#run-configuration
```release-note
None
```
=> Fix: golangci-lint config timeout option

pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go, pkg/alertmanager/validation/validation.go, pkg/alertmanager/validation/validation_test.go
We need to validate the urls passed as secrets in AlertManagerConfig receivers ( Slack and Discord in particular) to ensure we discard the faulty config early and don't create a hang up at the conversion stage.
Closes #6532
Build the image and try passing a malformed url in slack config for which the operator logs show error.
```release-note
Fix one alertmanagerconfig failing to sync blocks all others
```
=> Fix: One Alertmanager Config failing blocks all others.

Documentation/api-reference/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml, jsonnet/prometheus-operator/scrapeconfigs-crd.json, pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go, pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go, pkg/client/applyconfiguration/monitoring/v1alpha1/openstacksdconfig.go, pkg/prometheus/promcfg_test.go, test/e2e/scrapeconfig_test.go
Refactor OpenStackSDConfig
```release-note
1. Add the validation in the type.
2. Add the test cases for type verification.
```
Fixes #7209
=> chore: Refactor OpenStackSDConfig

pkg/k8sutil/metrics.go, test/e2e/alertmanager_test.go, test/e2e/main_test.go, test/e2e/prometheus_operator_test.go, test/e2e/prometheus_test.go, test/framework/alertmanager.go, test/framework/helpers.go
Given that we have to "patch" the registration of client-go metrics, it's quite important that we prevent regressions.
See also #6525.
```release-note
```
=> chore: add e2e tests on operator metrics

pkg/operator/feature_gates.go, test/e2e/denylist_test.go, test/e2e/main_test.go, test/e2e/prometheus_test.go, test/e2e/prometheusagent_test.go, test/e2e/upgradepath_test.go, test/framework/cluster_role.go, test/framework/cluster_role_binding.go, test/framework/context.go, test/framework/framework.go, test/framework/role_binding.go, test/framework/service_account.go
This PR updates the e2e framework to create dedicated cluster roles for each operator, otherwise tests running in parallel might change the cluster role definition concurrently.
```release-note
```
=> fix: unblock feature-gates CI

pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/testdata/NameValidationSchemeLegacyWithPrometheusV3.golden, pkg/prometheus/testdata/NameValidationSchemeUTF8WithPrometheusV3.golden, pkg/prometheus/testdata/OTLPConfig_Config_translation_strategy_with_suffixes_and_name_validation_scheme.golden
This PR adds rendering of the metric_name_validation_scheme config param if it is provided in the Custom Resource.
Built docker image, deployed in dev k8s cluster, manually edited CR to have nameValidationScheme set to Legacy, UTF-8, and omitting it whatsoever. Checked if resulting config is rendered properly.
```release-note
Render metric_name_validation_scheme in config.
```
=> fix: render metric_name_validation_scheme in config

pkg/prometheus/promcfg.go, pkg/prometheus/server/statefulset_test.go
Fixes #7319
Updated the unit TestPrometheusAdditionalArgsNoError unit test that checks for these arguments with both a `v2` and `v3` prometheus config.  
```release-note
Remove `web.console.templates` and `web.console.libraries` symlinks in >= v3 prometheus
```
=> promcfg: Remove web console arguments if prometheus version >= 3

bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml, example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml, example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml, jsonnet/prometheus-operator/alertmanagerconfigs-crd.json, jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet, jsonnet/prometheus-operator/alertmanagers-crd.json, jsonnet/prometheus-operator/podmonitors-crd.json, jsonnet/prometheus-operator/probes-crd.json, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/scrapeconfigs-crd.json, jsonnet/prometheus-operator/servicemonitors-crd.json, jsonnet/prometheus-operator/thanosrulers-crd.json, pkg/apis/monitoring/v1/types.go
This enhances the regex(es) used to validate proxy URLs in various CRDs.
Fixes #7458
This is a (small) fix to the regex URLs that validate `proxyURL`. Before the change, only `http(s)?://.*$` was allowed, which ruled out the usage of socks5 (which prometheus is fine with).
I manually applied the resulting CRDs to see if `http://`, `https://` and `socks5://` URLs are accepted (which is the case).
```release-note
- Fix ProxyURL validation regex
```
=> Allow socks5 proxy URLs

Documentation/platform/troubleshooting.md
Fixes #6219
Adds documentation how to query kubernetes
```release-note
Document the operators ability to publish kubernetes events for rejected resources
```
=> docs: Document the operators ability to publish kubernetes events for rejected resources

pkg/prometheus/server/rules.go, pkg/thanos/rules.go
- chore: predefine slice capacity to avoid extra allocations
```release-note
```
=> chore: predefine slice capacity to avoid extra allocations

pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go, pkg/alertmanager/operator.go
Fixes #7418
I have been working on a new Grafana Alloy [feature](https://github.com/grafana/alloy/pull/3448) which gathers AlertmanagerConfig CRD resources, merges them, and sends them to an Alertmanager embedded into Grafana Mimir. It would be very helpful if there is a way to use the config builder. I suppose this change could be useful for other projects too, at some point. 
In this PR I only exported the functions which are useful for the Alloy feature. I still haven't finished working on it, but I'm pretty sure that at the very least I would need the functionality from this PR. I'm happy to change the PR if you think it makes sense to export the functionality differently 😊 
I'm not sure if there should be a changelog entry? There is no change from the point of view of Operator users. …
=> Use the AlertmanagerConfig builder outside of the operator repo

.mdox.validate.yaml
This commit changes the mdox configuration to skip Ambassador's dead links as well as github.com URLs which are rate limited.
```release-note
```
=> fix: resolve doc CI failures

CHANGELOG.md, pkg/thanos/statefulset.go, test/e2e/prometheus_test.go, test/e2e/thanosruler_test.go, test/framework/prometheus.go, test/framework/thanos_querier.go
Closes #7492
```release-note
```
=> fix: enable remote-write for Ruler only when set

CHANGELOG.md, pkg/prometheus/promcfg.go, pkg/prometheus/testdata/ScrapeConfigSpecConfig_OpenStackSDConfigValid.golden
Fixes #7514
```release-note
```
=> fix: Fix parsing `role`  field in openstackSDConfigs in ScrapeConfig CRD

Documentation/proposals/202409-status-subresource.md
Fixes: #7545 
status-subresource propsal doc to include only workload crds
```
```
=> rfac: status-subresource propsal doc to include only workload crds

pkg/apis/monitoring/v1/types.go, pkg/apis/monitoring/v1/types_test.go
In order to make it easier for users to creation Duration pointers used by other struct fields like `Rule.For`, add a helper function that takes a duration string and returns a Duration pointer.
```release-note
* [ENHANCEMENT] Add a v1.DurationPointer api package helper #7493
```
=> Add Duration type helper

pkg/assets/store.go, pkg/assets/store_test.go
[Opentelemetry operator](https://github.com/open-telemetry/opentelemetry-operator/tree/main) has a dependeny on prometheus-operator's packages to support detection of pod and service monitors. The targetallocator's [promOperator](https://github.com/open-telemetry/opentelemetry-operator/blob/16e6ccb3aa51c149278432e399ce31c8902af0e2/cmd/otel-allocator/internal/watcher/promOperator.go#L279) component responsible for watching pod and service monitors lacks the ability to pick up the latest changes to the secrets when they are updated. In order to do so a new secretinformer can be added which watches for the events and when a change is detected it needs to be able to update/delete objects from the object store so that the CRs can pick up the latest changes.
Currently the …
=> Ability to update asset store from package consumers

pkg/alertmanager/operator.go, pkg/k8sutil/k8sutil.go, pkg/k8sutil/k8sutil_test.go, pkg/operator/resource_reconciler.go, pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go, pkg/thanos/operator.go, test/e2e/main_test.go, test/e2e/status_subresource_test.go
fixes: #7583 
```finalizer added to workload resources if statusFOrConfigRes flag is enabled
```
=> finalizer added to workload resources if statusFOrConfigRes flag is enabled

pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go, pkg/alertmanager/testdata/valid_global_config.golden, pkg/alertmanager/testdata/valid_global_config_smtp_tlsconfig_email_receiver.golden, pkg/alertmanager/testdata/valid_global_config_with_OpsGenie_API_KEY.golden, pkg/alertmanager/testdata/valid_global_config_with_OpsGenie_API_URL.golden, pkg/alertmanager/testdata/valid_global_config_with_Pagerduty_URL.golden, pkg/alertmanager/testdata/valid_global_config_with_Slack_API_URL.golden, pkg/alertmanager/testdata/valid_global_config_with_amVersion21.golden, test/e2e/alertmanager_test.go
Close #7569
Fix When MatchType is empty and AM version >= v0.22,  match to Regex bug
```release-note
When MatchType is empty and AM version >= v0.22,  match to Regex bug
```
=> Fix `MatchType` is empty in AM matchers

pkg/assets/store.go, pkg/assets/store_test.go
[Opentelemetry operator](https://github.com/open-telemetry/opentelemetry-operator/tree/main) has a dependeny on prometheus-operator's packages to support detection of pod and service monitors. The targetallocator's [promOperator](https://github.com/open-telemetry/opentelemetry-operator/blob/16e6ccb3aa51c149278432e399ce31c8902af0e2/cmd/otel-allocator/internal/watcher/promOperator.go#L279) component responsible for watching pod and service monitors lacks the ability to pick up the latest changes to the secrets when they are updated/deleted. In order to do so a new secretinformer can be added which watches for the events and when a change is detected it needs to be able to update/delete objects( need add and get too to check the store before performing the operation) so that the CRs can pick …
=> Ability to add, get and delete objects from asset store from package consumers

pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go
To be consistent with the rest of the logs.
```release-note
```
=> chore: add key attribute to ResourceSelector logs

test/e2e/kind-conf.yaml
With kubelet syncing the mounted configmaps/secrets more frequently, the tests take a bit less time to execute because the configuration changes are propagated faster.
Before
After
```release-note
```
=> ci: decrease kubelet sync frequency

bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, jsonnet/prometheus-operator/prometheusagents-crd.json, pkg/apis/monitoring/v1alpha1/prometheusagent_types.go, test/e2e/prometheusagent_test.go
This PR adds `kubebuilder` validations to PromAgent Daemonset mode for shards and pvcRetentionClaim
```release-note
```
=> feat: added e2e tests for invalid shards and PVCRetentionClaim policy specs in PrometheusAgents DaemonSet deployment model 

Documentation/api-reference/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml, example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml, jsonnet/prometheus-operator/podmonitors-crd.json, pkg/apis/monitoring/v1/podmonitor_types.go, pkg/apis/monitoring/v1/zz_generated.deepcopy.go, pkg/client/applyconfiguration/monitoring/v1/podmetricsendpoint.go, pkg/prometheus/promcfg.go, pkg/prometheus/resource_selector.go, pkg/prometheus/resource_selector_test.go
Related issue: #7640
Previously, PodMonitor only supported the proxyUrl field. This PR enhances the PodMonitor CRD by adding support for all proxy configuration options. Similar to #7647 
```release-note
```
=> Support ProxyConfig fields for PodMonitor

Documentation/api-reference/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, pkg/apis/monitoring/v1/prometheus_types.go, pkg/apis/monitoring/v1/zz_generated.deepcopy.go, pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go, pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go, pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go, pkg/prometheus/promcfg.go, pkg/prometheus/promcfg_test.go, pkg/prometheus/testdata/ScrapeClassicHistogramsFalseProperPromVersion.golden, pkg/prometheus/testdata/ScrapeClassicHistogramsTrueProperPromVersion.golden, pkg/prometheus/testdata/ScrapeClassicHistogramsTrueWrongPromVersion.golden
From issue https://github.com/prometheus-operator/prometheus-operator/issues/7629, add `always_scrape_classic_histograms` that is going to be release in [prometheus 3.5](https://github.com/prometheus/prometheus/releases/tag/v3.5.0-rc.0)
```release-note
```
=> feat: global always_scrape_classic_histograms

pkg/k8sutil/k8sutil.go, pkg/operator/resource_reconciler.go
…er is present
fixes: #7608 
shouldUpdate to check if the resource should updated if the finalizer is present
```release-note
```
=>  shouldUpdate to check if the resource should updated if the finalizer is present

Documentation/api-reference/api.md, bundle.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, jsonnet/prometheus-operator/alertmanagers-crd.json, pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go, pkg/alertmanager/operator.go, pkg/alertmanager/testdata/skeleton_base_diff_namespace_simple_CR_with_namespaceMatcher_disabled_other_namespaces.golden, pkg/alertmanager/testdata/skeleton_base_same_namespace_simple_CR_with_namespaceMatcher_disabled_other_namespaces.golden, pkg/apis/monitoring/v1/alertmanager_types.go
Adds option to disable namespace matcher only for namespace of the alertmanager, to allow admins of multi-tenant clusters to create cluster-scoped alerts without disabling tenant isolation.
Fixes #7603
Added unit test cases demonstrating selective adding of namespace matcher.
_Please put a one-line changelog entry below. This will be copied to the changelog file during …
=> feat:  Add alertmanagerConfigMatcherStrategy "OnNamespaceExceptForAlertmanagerNamespace"

CHANGELOG.md, pkg/prometheus/server/operator.go
When a Prometheus selects no scrape resources, the operator (by default) expects that users provide the configuration secret themselves. More often than not this type of situation is unintentional and users have a hard time figuring out why the generated configuration remains empty.
When the Prometheus configuration is unmanaged, this change sets `reason: ConfigurationUnmanaged` on the `Reconciled` condition to improve the user experience. Eventually we may want to make unmanaged configuration an opt-in feature (e.g.  having
`--disable-unmanaged-prometheus-configuration=true` by default).
Closes #7649
Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for …
=> feat: add ConfigurationUnmanaged reason

pkg/operator/finalizer.go, pkg/prometheus/server/operator.go
fixes: #7607 
go generic support in syncFinalizer function
```release-note
```
=> go generic support in syncFinalizer function

CHANGELOG.md, pkg/prometheus/resource_selector.go
https://github.com/prometheus-operator/prometheus-operator/pull/7718/files#r2237093300
```release-note
```
=> fix: log only valid resources

CHANGELOG.md, Documentation/platform/operator.md, cmd/operator/main.go, pkg/alertmanager/operator.go, pkg/assets/store.go, pkg/assets/tracker.go, pkg/assets/tracker_test.go, pkg/informers/informers.go, pkg/informers/informers_test.go, pkg/informers/kube.go, pkg/operator/config.go, pkg/operator/config_test.go, pkg/operator/event_handler.go, pkg/operator/informers.go, pkg/operator/operator.go, pkg/prometheus/agent/operator.go, pkg/prometheus/server/operator.go, test/e2e/main_test.go, test/e2e/prometheus_test.go
Closes #6018 
```release-note
```
=> fix: reconcile workload configurations when a referenced secret/configmap key is updated

pkg/prometheus/server/operator.go
added getConfigResources function to get the config resources selected by the prometheus
Closes: #7716 
```release-note
```
=> feat: added getConfigResources function

Documentation/platform/operator.md, cmd/operator/main.go, pkg/kubelet/controller.go
Add `--kubelet-sync-period` flag to allow customization of how often the kubelet endpoints controller syncs with the Kubernetes API. Default remains 3 minutes to maintain backward compatibility.
The hardcoded 3-minute sync period can cause timing issues in environments with
regular node scaling - when nodes are scaled down every 3 minutes, the sync timing can align in a way that causes Prometheus targets to remain persistently unhealthy, triggering false alarms.
Related Issue: N/A
```release-note
Add configurable sync period for kubelet endpoints controller
```
=> feat: add configurable sync period for kubelet endpoints controller

pkg/operator/resource_reconciler.go, test/e2e/main_test.go, test/e2e/prometheus_operator_test.go
This commit adds the following metrics on controller's workqueues:
* prometheus_operator_workqueue_depth
* prometheus_operator_workqueue_adds_total
* prometheus_operator_workqueue_latency_seconds_bucket
* prometheus_operator_workqueue_latency_seconds_count
* prometheus_operator_workqueue_latency_seconds_sum
* prometheus_operator_workqueue_work_duration_seconds_bucket
* prometheus_operator_workqueue_work_duration_seconds_count
* prometheus_operator_workqueue_work_duration_seconds_sum
* prometheus_operator_workqueue_unfinished_work_seconds
* prometheus_operator_workqueue_longest_running_processor_seconds
* prometheus_operator_workqueue_retries_total
Please check the …
=> feat: add workqueue metrics

pkg/alertmanager/operator.go, pkg/operator/factory.go, pkg/prometheus/agent/daemonset.go, pkg/prometheus/agent/operator.go, pkg/prometheus/agent/statefulset.go, pkg/prometheus/common.go, pkg/prometheus/common_test.go, pkg/prometheus/server/operator.go, pkg/prometheus/server/statefulset.go, pkg/thanos/operator.go
This change adds label selectors to statefulset informers so each controller only watches the needed resources.
```release-note
```
=> feat: optimize statefulset informers

.gitignore
This tool has been deprecated so the corresponding gitignore entry
can now be removed.
=> chore: remove po-lint from .gitignore

.github/workflows/checks.yaml
The intent was that the CI would post a comment when documentation or generated files were not up-to-date but it only works for PRs from the origin repository (e.g. not with forks).
```release-note
```
=> chore: remove step commenting on failed runs

pkg/prometheus/operator.go, pkg/prometheus/operator_test.go
fixes: #7792  
Update service monitor status binding only if a change is detected
```release-note
```
=> Update service monitor status binding only if a change is detected

test/e2e/scrapeconfig_test.go
Add E2E testing and Nomad SD.
Relate #6452
E2E Test Cases
```release-note
- Add E2E test cases for NomadSD.
```
=> Chore: Update test cases for NomadSD

pkg/prometheus/operator.go, pkg/prometheus/server/operator.go, test/e2e/main_test.go, test/e2e/status_subresource_test.go, test/framework/service_monitor.go, test/framework/status.go
Remove invaldBindings from smon status
Closes: #7834
```release-note
```
=> Remove invaldBindings from smon status

pkg/prometheus/operator.go, pkg/prometheus/operator_test.go, test/e2e/status_subresource_test.go, test/framework/status.go
This commit extends the existing end-to-end test on the ServiceMonitor status to ensure that the operator only updates the status when a change actually happened.
```release-note
```
=> chore: add e2e test for lazy status updates

pkg/prometheus/agent/operator.go, test/e2e/main_test.go, test/e2e/status_subresource_test.go
Config Status Subresource finalizer in prometheusAgent
Closes: #7884
```release-note
```
=> Config Status Subresource finalizer in prometheusAgent

pkg/alertmanager/operator.go, pkg/operator/operator.go, pkg/operator/rules.go, pkg/prometheus/agent/operator.go, pkg/prometheus/resource_selector.go, pkg/prometheus/resource_selector_test.go, pkg/prometheus/server/operator.go, pkg/thanos/operator.go
This Pull Request migrates from the old events API (`k8s.io/client-go/tools/record`) to the new API (`k8s.io/client-go/tools/events`).
```release-note
None
```
=> chore: change the `record` api to the new `events` api

pkg/alertmanager/operator.go, pkg/alertmanager/operator_test.go, pkg/operator/operator.go, pkg/operator/rules.go, pkg/prometheus/agent/operator.go, pkg/prometheus/resource_selector.go, pkg/prometheus/resource_selector_test.go, pkg/prometheus/server/operator.go, pkg/prometheus/server/rules.go, pkg/thanos/operator.go, pkg/thanos/rules.go
This is a follow-up of #7867 which refactors the event handling to always inject the related object.
```release-note
```
=> chore: inject related object into all events

Documentation/api-reference/api.md, example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml, jsonnet/prometheus-operator/alertmanagers-crd.json, pkg/alertmanager/amcfg.go, pkg/alertmanager/amcfg_test.go, pkg/apis/monitoring/v1/alertmanager_types.go, pkg/apis/monitoring/v1/zz_generated.deepcopy.go, pkg/client/applyconfiguration/monitoring/v1/alertmanagerglobalconfig.go
Change PagerdutyURL's type from string to URL to add kube validation for the URL type in Alertmanager Globalconfig
Use unit testing
```release-note
- Change type for PagerdutyURL in Alertmanager Globalconfig from string to URL to inject kube validation
```
=> Feat: Add URL Validation for PagerdutyURL in Alertmanager Globalconfig

pkg/operator/finalizer.go, pkg/prometheus/server/operator.go
fix: \"prometheus\" not found log message, after deletion of prometheus, when status flog is enabled
Closes: #7941
```release-note
```
=> fix: \"prometheus\" not found log message, after deletion of prometheus, when status flog is enabled

pkg/prometheus/server/operator.go, test/e2e/main_test.go, test/e2e/status_subresource_test.go
ScrapeConfig Status Subresource Removal from prometheus
Closes: #7961
```release-note
```
=> ScrapeConfig Status Subresource Removal from prometheus

Documentation/api-reference/api.md, example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml, example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml, example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml, example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml, example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml, example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml, example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml, example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml, jsonnet/prometheus-operator/podmonitors-crd.json, jsonnet/prometheus-operator/probes-crd.json, jsonnet/prometheus-operator/prometheusagents-crd.json, jsonnet/prometheus-operator/prometheuses-crd.json, jsonnet/prometheus-operator/scrapeconfigs-crd.json, jsonnet/prometheus-operator/servicemonitors-crd.json, jsonnet/prometheus-operator/thanosrulers-crd.json, pkg/apis/monitoring/v1/types.go, test/e2e/main_test.go, test/e2e/prometheus_test.go
Follow-up from #7637 to complete the UTF8 support for labels
Related-to: #7362
```release-note
```
=> feat: allow UTF-8 characters in label names
