test/framework/context.go

Removing space to allow generation step to pass.
```release-note:none
```

test/framework: remove unnecessary space

---

Documentation/troubleshooting.md

This PR fix a path to an image in the documentation.
```release-note:none
```

Fix path to the schema

---

Documentation/rbac.md
Documentation/user-guides/exposing-prometheus-and-alertmanager.md
Documentation/user-guides/getting-started.md
Documentation/user-guides/storage.md
example/additional-scrape-configs/prometheus-cluster-role-binding.yaml
example/additional-scrape-configs/prometheus-cluster-role.yaml
example/rbac/prometheus/prometheus-cluster-role-binding.yaml
example/rbac/prometheus/prometheus-cluster-role.yaml
example/storage/storageclass.yaml
pkg/admission/admission_test.go
scripts/kind-rbac.yaml
test/framework/admission-webhooks.go
test/framework/ingress.go
test/framework/resources/prometheus-operator-mutatingwebhook.yaml
test/framework/resources/prometheus-operator-validatingwebhook.yaml
test/framework/resources/prometheus-role-binding.yml

```release-note:change
Remove use of Kubernetes API versions being removed in v1.22
```

Remove deprecated apis

---

.github/PULL_REQUEST_TEMPLATE.md

The current PR template doesn't give any visual clue about what type of change is introduced. This PR changes this by adding checkboxes and explaining which type of change means what. By doing this we should prevent having PRs with release note, but without change type.
cc @prometheus-operator/prometheus-operator-reviewers 
_What type of changes does your code introduce to Appium? Put an `x` in the box that apply._
```release-note
```

.github: improve pull request template

---

Documentation/additional-scrape-config.md

The first time I used Prometheus operator, I think it's clearer to add this command
```release-note:REPLACEME
```

Update additional-scrape-config.md 

---

ADOPTERS.md

added Clyso to adopters 
```release-note
```

added Clyso because Clyso

---

RELEASE.md

RELEASE.md: fix some release dates

---

pkg/alertmanager/amcfg.go
pkg/prometheus/promcfg.go

When skipping fields in the generation of Alertmanager and Prometheus
configuration because they aren't supported by the current version,
ensure that we log the name and namespace of the resource as well as the
minimum required version and the current version.
This change also reduce code duplication in the generation of the
Prometheus configuration when enforcing sample, target and label limit.
```release-note
```

*: make log messages more consistent

---

Documentation/user-guides/storage.md

fix docs: fix the link to K8s 1.6 changelog

---

pkg/prometheus/statefulset.go
pkg/prometheus/statefulset_test.go

When Prometheus is configured to serve HTTPS traffic, the thanos sidecar
and config reloader still try to reach Prometheus on HTTP.
This commit adjusts the Prometheus URL in both sidecards to match the
Prometheus URI scheme.
Fixes https://github.com/prometheus-operator/prometheus-operator/issues/4273
```release-note
Use the appropriate URI scheme in Prometheus sidecars when web tls is enabled for Prometheus.
```

Use appropriate HTTP scheme in Prometheus sidecars

---

scripts/push-docker-image.sh

Adding support for ppc64le architecture
adding support for ppc64le architecture
```release-note
```

Update push-docker-image.sh to support ppc64le architecture

---

MAINTAINERS.md

Just updating my company affiliation. 
I was doing this via GitHub web UI. Sorry for brevity :)
```release-note
```

[docs] Update Pawel Krupa (paulfantom) Company

---

CHANGELOG.md

CHANGELOG.md: fix typo

---

RELEASE.md

RELEASE.md: update instructions for kube-prometheus

---

Documentation/user-guides/shards-and-replicas.md
example/shards/example-app-deployment.yaml
example/shards/example-app-service-monitor.yaml
example/shards/example-app-service.yaml
example/shards/prometheus-cluster-role-binding.yaml
example/shards/prometheus-cluster-role.yaml
example/shards/prometheus-service-account.yaml
example/shards/prometheus-service.yaml
example/shards/prometheus.yaml

Fix #3795 
```release-note:REPLACEME
```

Shards and Replicas document

---

go.mod
go.sum

Bumping thanos and prometheus dependencies. Removals are due to running `go mod vendor`.
I am trying to figure out why dependabot cannot update our deps and fix the issue reported by it:
```
Dependabot encountered the following error:
go: github.com/thanos-io/thanos@v0.23.0 requires
github.com/efficientgo/e2e@v0.11.1-0.20210829161758-f4cc6dbdc6ea requires
github.com/efficientgo/tools/core@v0.0.0-20210129205121-421d0828c9a6: invalid version: unknown revision
```
_Please put a …

*: bump thanos and prometheus dependencies

---

ADOPTERS.md

Just documenting that Rancher uses Prometheus Operator!
```release-note
- Added SUSE Rancher to ADOPTERS.md
```

Add SUSE Rancher to ADOPTERS.md

---

RELEASE.md

Updates the instructions for cutting new releases.
```release-note
```

RELEASE.md: update release instructions

---

RELEASE.md

Signing up for v0.53.
```release-note
```

RELEASE.md: add Simon Pasquier as the v0.53 shepherd

---

pkg/alertmanager/amcfg.go
pkg/alertmanager/amcfg_test.go
pkg/alertmanager/types.go

Solves part 1/2 of the existing (but seemingly stalled) work in #4176 
```release-note
Support mute_time_intervals in raw config for AlertManager
```

alertmanager: Support mute_time_intervals in raw config

---

.github/workflows/e2e.yaml

Same as https://github.com/prometheus-operator/kube-prometheus/pull/1493
```release-note
```

.github/workflows: group all e2e jobs into one job report

---

CHANGELOG.md

Fixes the 0.52.1 release date
```release-note
```

CHANGELOG.md: Fix 0.52.1 release date

---

test/e2e/prometheus_test.go

Fixes #4401 
```release-note
```

test:e2e:Prometheus: Fix flake in check for minReadySeconds

---

pkg/prometheus/operator.go
pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go

This change makes ConfigGenerator aware of the Prometheus version so
that we don't need to pass this information around.
```release-note
```

pkg/prometheus: refactor ConfigGenerator

---

pkg/k8sutil/k8sutil.go
pkg/k8sutil/k8sutil_test.go

A bug was introduced in 0.50.0 where annotations set in the Prometheus
podMetadata spec were not properly propagated to statefulset pods.
This commit fixes the bug and adds additional unit tests to verify the
functionality works as expected.
Fixes https://github.com/prometheus-operator/prometheus-operator/issues/4392
```release-note
Propagate annotations set in spec.podMetadata to the statefulset pods. Fixes #4392.
```

pkg/k8sutil: fix annotation propagation

---

pkg/alertmanager/amcfg.go

Rather than passing a flag to convertRoute() to indicate whether the
route should be enforced or not, the decision is delegated to the caller
(e.g. generateConfig()). It should make it easier to support
AlertmanagerConfig for defining global configuration (#4220).
```release-note
```

pkg/alertmanager: refactor convertRoute()

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
pkg/alertmanager/amcfg.go
pkg/alertmanager/amcfg_test.go
pkg/alertmanager/operator.go
pkg/alertmanager/operator_test.go
pkg/alertmanager/validation.go
pkg/alertmanager/validation_test.go
pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go

The changes here close the gap between the upstream alertmanager validations (code, docs) and our internal representation of those types.
Changes are made with the intention of reducing the chances
of accepting an invalid CR representation.
```release-note
```

alertmanager: Sync validation with upstream alertmanager

---

pkg/alertmanager/amcfg.go

Similar to df426ac, this change extracts the namespace enforcement into another
function.
```release-note
```

pkg/alertmanager: refactor convertInhibitRule()

---

cmd/operator/main.go
cmd/prometheus-config-reloader/main.go
internal/log/log.go

Looking at #4437 was the motivation for this since we will need to, for a third time, redeclare those types and logging bootstrap boilerplate. 
```release-note
```

Consolidate logging setup into a standalone package

---

pkg/alertmanager/amcfg_test.go
pkg/alertmanager/types.go

Follow on from the work carried out by @phin1x in #4374 - thanks for your contribution. I have marked you as a co-author here.
Partially resolves #4236 
alertmanager: Support SNS receiver in raw config
```release-note
alertmanager: Support SNS receiver in raw config
```

alertmanager: Support SNS receiver in raw config

---

ADOPTERS.md

We love the Prometheus Operator and would be honored to be featured on the website. Let us know if there are any other ways we can contribute back.
- [X ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
Add the Robusta.dev open source project to Adopters.md
```release-note
Add the Robusta.dev open source project to Adopters.md
```

Add the Robusta.dev open source project to Adopters.md

---

ADOPTERS.md

ADOPTERS.md: fix ordering

---

RELEASE.md

Add myself as release manager for v.0.54 
```release-note
```

Add fpetkovski as v0.54 release manager

---

RELEASE.md

Adding 2 more release dates and assigning myself as release shepherd for ~0.56~ 0.55.0.
We still need someone to take March release
```release-note
```

add @paulfantom as 0.55 release shepherd

---

cmd/operator/main.go

use `make` when declare a slice.
```release-note
```

use make to alloc memory

---

Documentation/user-guides/getting-started.md

"Modernise" a link that is causing frequent CI failures.
```release-note
```

docs: Update link describing operator concept

---

Documentation/user-guides/shards-and-replicas.md

Documentation: fix CI for shards-and-replicas.md

---

MAINTAINERS.md

Add @PhilipGough to the maintainers list.
After talking with Serg, Lili and Damien, they decided to resign from
their maintainer duties. Thanks for all you've done and we're happy to
get you back anytime you want.
Looking for approval from @lilic @s-urbaniak @dgrisonnet before we can merge it :)
```release-note
```

MAINTAINERS.md: update the list

---

ADOPTERS.md

ADOPTERS.md: fix links

---

Documentation/designs/prometheus-agent.md

This PR contains submits a design document for the PrometheusAgent CRD
```release-note
```

docs: Submit design doc for PrometheusAgent CRD

---

example/shards/prometheus-cluster-role-binding.yaml
example/shards/prometheus-cluster-role.yaml

Fix rbac api version in example
```release-note
```

example/shards: Fix rbac api version

---

pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go

Finished #4565
```release-note
```

Probe add a __tmp_ingress_address label.

---

CHANGELOG.md

Fix 0.54.0 dates in the changelog
Fixes #4615
```release-note
```

Fix 0.54.x release year

---

Documentation/compatibility.md
pkg/operator/defaults.go

operator: Bump default versions for release prep

---

CHANGELOG.md

Merge 0.54.1 to main

---

pkg/k8sutil/merge.go
pkg/prometheus/operator.go

Some minor refactoring/cleanup as I was reading the code. 
```release-note
```

Code cleanup

---

README.md

README: Update end-to-end test section on kind
Update image names and example kubernetes version
```release-note
```

README: Update end-to-end test section on kind

---

pkg/operator/defaults.go

pkg/operator: bump Thanos to v0.25.2

---

pkg/operator/defaults.go

pkg/operator: bump Alertmanager to v0.24.0

---

RELEASE.md

RELEASE.md: add myself as v0.56.0 release shepherd

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
pkg/alertmanager/amcfg.go
pkg/alertmanager/types.go
pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go

Closed #4658 
```release-note
```

Add support to AlertmanagerConfig for entity and actions fields in the OpsGenie receiver

---

Documentation/user-guides/monitoring-kubernetes-ingress.md

Fix minor typo.
```release-note
- Fix typo in monitoring documentation
```

Update monitoring-kubernetes-ingress.md to fix typo

---

ADOPTERS.md

Refresh stats due to Veepee increased usage on Kubernetes and prometheus-operator
```release-note
* refresh stats due to Veepee increased usage on Kubernetes and prometheus-operator
```

update Veepee adopters stats

---

Documentation/rbac.md

complete a sentence
Fixes: #4721
```release-note
```

Documentation: fix rbac.md

---

go.mod
pkg/client/go.mod

Missed in #4737 
```release-note
```

go.mod,pkg/client/go.mod: bump to v0.56.0

---

README.md

Adds required steps to README about running end to end tests on kind using podman.
```Adds required steps to README about running end to end tests on kind using podman.
```

Add development documentation for podman users

---

ADOPTERS.md

[Deckhouse](https://github.com/deckhouse/deckhouse) is a Kubernetes platform that implements ready-to-use monitoring using [Prometheus](https://github.com/deckhouse/deckhouse/tree/main/modules/010-prometheus-crd) and [Prometheus Operator](https://github.com/deckhouse/deckhouse/tree/main/modules/010-operator-prometheus-crd). The entry I suggest to the ADOPTERS file is actually "meta," as it describes how the operator is used in the platform (in general). On the other side, leveraging this platform and module, we currently manage a number Deckhouse clusters having ~140M active series in …

Add Deckhouse to the adopters list

---

pkg/prometheus/operator.go

When reconciling shards and encountering a statefulset for which
deletion is in progress, the operator should continue to the next shard
instead of returning from the sync() method.
```release-note
```

pkg/prometheus: continue instead of return

---

bundle.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
jsonnet/prometheus-operator/prometheuses-crd.json
pkg/apis/monitoring/v1/types.go

The previous markers were wrong and didn't generate the expected spec...
```release-note
```

*: fix markers for status conditions

---

RELEASE.md

Updating schedule for the current and next releases. I've also signed up for v0.60 but happy to leave it to someone else :)
cc @paulfantom 
```release-note
```

RELEASE.md: update release schedule

---

pkg/apis/monitoring/v1/types.go

pkg/apis: Remove comment not needed
```release-note
```

pkg/apis: Remove comment not needed

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
jsonnet/prometheus-operator/podmonitors-crd.json
jsonnet/prometheus-operator/probes-crd.json
jsonnet/prometheus-operator/servicemonitors-crd.json
pkg/apis/monitoring/v1/types.go
pkg/prometheus/promcfg.go

Fixes #4874
```release-note
```

pkg/apis: Add comment on default metrics path

---

CONTRIBUTING.md

I realize that we never properly documented the office hours meeting!
```release-note
```

CONTRIBUTING.md: add information about office hours

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
jsonnet/prometheus-operator/servicemonitors-crd.json
pkg/apis/monitoring/v1/types.go

I think an example better helps to understand the meaning of this field.
- `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- `FEATURE` (non-breaking change which adds functionality)
- `BUGFIX` (non-breaking change which fixes an issue)
- `ENHANCEMENT` (non-breaking change which improves existing functionality)
```release-note
Documentation: `ServiceMonitor`'s `jobLabel` now contains an example.
```

`ServiceMonitorSpec.JobLabel`: example in description

---

pkg/operator/defaults.go

Follow-up of #4887
```release-note
```

pkg/operator: bump Thanos to v0.27.0

---

Makefile

Enables building images also using podman.
```release-note
Enable building images also using podman.
```

Allow podman for building images

---

README.md

Remove note on Makefile modification needed for container builds via podman
```release-note
Remove note on Makefile modification needed for container builds via podman.
```

Update README on podman container build

---

Makefile
jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet

Add "DO NOT EDIT" comment to alertmanagerconfigs-v1beta1-crd.libsonnet

---

MAINTAINERS.md

docs: Add slashpai as triage member

---

pkg/prometheus/statefulset.go
pkg/prometheus/statefulset_test.go

`p.Spec.Query.MaxSamples` and `p.Spec.Query.MaxConcurrency` would
trigger invalid arguments when not nil.
Discovered while reviewing #4941 
```release-note
Fix `spec.query.maxSamples` and `spec.query.maxConcurrency` fields of Prometheus CRD.
```

pkg/prometheus: fix generation of --query arguments

---

pkg/versionutil/cli_test.go

Fixes: #4956
```release-note
```

pkg/versionutil: Fix TestShouldPrintVersion error on Mac M1

---

pkg/prometheus/statefulset.go
pkg/prometheus/statefulset_test.go
test/e2e/alertmanager_test.go
test/e2e/main_test.go
test/e2e/prometheus_test.go
test/framework/alertmanager.go
test/framework/helpers.go

Fixes #4939 
```release-note
Fixed Thanos sidecar connectivity issue when Prometheus TLS is enabled
```

Fix Thanos sidecar connectivity issue when Prometheus TLS is enabled

---

Documentation/user-guides/webhook.md

Fix of a typo in the documentation.

webhook user guide: fix typo in example YAML.

---

pkg/alertmanager/statefulset.go
pkg/alertmanager/statefulset_test.go
pkg/k8sutil/k8sutil.go
pkg/k8sutil/k8sutil_test.go
pkg/prometheus/statefulset.go
pkg/prometheus/statefulset_test.go
pkg/webconfig/config.go
pkg/webconfig/config_test.go
pkg/webconfig/tls_credentials.go

Previously, adding secrets to Prometheus resource longer than 50
characters resulted in generation of statefulset that have
`volume.name` larger than 63 characters. This doesn't conform to
RFC-1123 (<= 63 chars) requirement and resulted in pod not getting
created.
This patch fixes the issue by ensuring that the volume name conform to
the requirement. Additionally it fixes an issue with SanitizeVolumeName
which used to truncate the name at DNS1123LabelMaxLength thus returing
same name for `<63-char>-foo` and `<63-char>-bar` to return unique name
by computing the sha1 and appending to the end.
Bug: https://github.com/prometheus-operator/prometheus-operator/issues/4944
Signed-off-by: Sunil Thaha <sthaha@redhat.com>
_What type of changes …

Fix 4944 invalid vol name

---

.github/env

Use the latest version of Kubernetes.
```release-note
```

.github: bump to Kubernetes v1.25

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
jsonnet/prometheus-operator/prometheuses-crd.json
pkg/apis/monitoring/v1/types.go

Found minor typos in the CRD documentation.
```release-note
```

pkg/apis/monitoring/v1: fix typo in comment

---

.github/workflows/e2e.yaml
test/e2e/alertmanager_instance_namespaces_test.go
test/e2e/alertmanager_test.go
test/e2e/denylist_test.go
test/e2e/main_test.go
test/e2e/prometheus_instance_namespaces_test.go
test/e2e/prometheus_test.go
test/e2e/thanosruler_test.go
test/e2e/upgradepath_test.go
test/framework/admission-webhooks.go
test/framework/cluster_role.go
test/framework/cluster_role_binding.go
test/framework/crd.go
test/framework/deployment.go
test/framework/framework.go
test/framework/helpers.go
test/framework/namespace.go
test/framework/prometheus.go
test/framework/role-binding.go
test/framework/secret.go
test/framework/service.go
test/framework/service_account.go

Fixes #4067
Signed-off-by: heylongdacoder <heylongdacoder@gmail.com>
```release-note
```

test: Add e2e test for Prometheus Operator Upgrade Path

---

.github/workflows/stale.yaml

The label is `kind/bug`, not `bug`.
```release-note
```

.github/workflows/stale.yaml: fix bug label

---

Dockerfile
cmd/admission-webhook/Dockerfile
cmd/prometheus-config-reloader/Dockerfile
example/alertmanger-webhook/Dockerfile

Its a best practice to use the COPY statement instead of ADD. 
See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy for more information
```release-note
Replace ADD with COPY in Dockerfiles
```

Replace ADD with COPY in Dockerfiles

---

.gitignore
example/alertmanager-webhook/Dockerfile
example/alertmanager-webhook/Makefile
example/alertmanager-webhook/README.md
example/alertmanager-webhook/main.go
example/alertmanger-webhook/Dockerfile
example/alertmanger-webhook/Makefile
test/e2e/alertmanager_test.go

Closes #5012
```release-note
```

Use prometheus-alertmanager-test-webhook image from quay.io/prometheus-operator

---

test/framework/resources/basic-auth-app-deployment.yaml
test/instrumented-sample-app/.gitignore
test/instrumented-sample-app/Dockerfile
test/instrumented-sample-app/Makefile
test/instrumented-sample-app/README.md
test/instrumented-sample-app/main.go

Relates to #5012 
```release-note
```

Use instrumented-sample-app image from quay.io/prometheus-operator

---

CONTRIBUTING.md

CONTRIBUTING.md: update office hours schedule

---

.github/env

.github: bump to Kubernetes v1.25.2

---

.github/workflows/release.yaml

The release workflow requires the Go toolchain to generate the stripped-down version of the CRDs.
```release-note
```

.github/workflows: fix release workflow

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusrules.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
jsonnet/prometheus-operator/prometheusrules-crd.json
pkg/apis/monitoring/v1/types.go
pkg/prometheus/rules.go
test/e2e/main_test.go
test/e2e/prometheus_test.go

pkg/apis: Update RuleGroup desc and add CRD validation
```release-note
pkg/apis: Update RuleGroup description and add CRD validation
```

pkg/apis: Update Rule/RuleGroup desc and add CRD validation

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
jsonnet/prometheus-operator/alertmanagers-crd.json
jsonnet/prometheus-operator/podmonitors-crd.json
jsonnet/prometheus-operator/probes-crd.json
jsonnet/prometheus-operator/prometheuses-crd.json
jsonnet/prometheus-operator/servicemonitors-crd.json
jsonnet/prometheus-operator/thanosrulers-crd.json
pkg/apis/monitoring/v1/types.go

Fixes #5036
```release-note
```

Update ProbeTLSConfig and SafeTLSConfig description

---

Documentation/user-guides/getting-started.md

From Here -> #5106
```release-note
add comment about broken image
```

add comment about broken image

---

Documentation/api.md
Documentation/operator.md
scripts/docs/templates/pkg.tpl

Documentation: add CLI documentation to website

---

CONTRIBUTING.md

@mddeff kindly started a "proposal process" in #4577 as it was called out as a blocker for starting the work on #2787.
After some discussion between the maintainers and other contributors on the office hours meeting (2022-10-10), we decided that the process should be more concise for this project and since we are closely aligned here with the Thanos community, it would make sense to adopt the existing [process there](https://thanos.io/tip/contributing/proposal-process.md/).
This ports over that process in brief, giving acknowledgement, to our existing contribution guide.
_What type of …

docs: Add proposal process adopted from Thanos

---

RELEASE.md

Signing myself for v0.62.
```release-note
```

RELEASE.md: add simonpasquier for v0.62

---

Documentation/user-guides/storage.md

Signed-off-by: Ayush P Gupta <ayushpguptaapg@gmail.com>
This PR aims at fixing the incorrect `labels` in PV example in docs.
```release-note
fix: incorrect label reference key
```

fix(docs): incorrect label reference key

---

pkg/alertmanager/amcfg_test.go
pkg/alertmanager/operator_test.go
pkg/alertmanager/validation/v1beta1/validation_test.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/statefulset_test.go
test/e2e/alertmanager_test.go

Less code to maintain ++
```release-note
```

Removes typePtr functions with k8s.io/utils/pointer

---

RELEASE.md

docs: Add myself for releasing v0.63

---

Documentation/user-guides/storage.md

Instruct users to check that the storage class allows volume expansion.
```release-note
```

docs: follow-up on #5306

---

MAINTAINERS.md

Adds JoaoBraveCoding to Triage

---

.github/env
go.mod
scripts/go.mod

Keeping up to date with the latest Go version.
```release-note
```

chore: update to Go 1.20

---

RELEASE.md

chore: update release schedule

---

pkg/alertmanager/operator.go
pkg/alertmanager/statefulset.go
pkg/alertmanager/statefulset_test.go

Use constants instead of hardcoded strings.
```release-note
```

pkg/alertmanager: minor code clean-up

---

Documentation/network-policies.md
Documentation/user-guides/storage.md

Closes https://github.com/prometheus-operator/prometheus-operator/issues/5375
```release-note
```

Fixes some docs links to k8s docs

---

scripts/push-docker-image.sh

Fix issue that prevented the creation of the manifest because of wrong array manipulation in Bash.
```release-note
```

scripts/push-docker-image.sh: fix script

---

scripts/push-docker-image.sh

Follow-up of #5387
```release-note
```

scripts/push-docker-image.sh: fix bad array index

---

cmd/prometheus-config-reloader/main.go
go.mod
go.sum
pkg/versionutil/cli.go
pkg/versionutil/cli_test.go

Upstream changed package name, see:
https://github.com/alecthomas/kingpin#overview
```release-note
Update gopkg.in/alecthomas/kingpin.v2 to github.com/alecthomas/kingpin/v2
```

Update gopkg.in/alecthomas/kingpin.v2 to github.com/alecthomas/kingpin/v2

---

pkg/alertmanager/operator.go
pkg/operator/accessor.go
pkg/prometheus/server/operator.go
pkg/prometheus/server/rules.go
pkg/thanos/operator.go
pkg/thanos/rules.go

Extracted from #5392 
cc @ArthurSens 
```release-note
```

chore: simplify object manipulation

---

Documentation/compatibility.md
go.mod
go.sum
pkg/operator/defaults.go

update to v0.31.0
```release-note
```

chore: bump Thanos version

---

pkg/thanos/operator.go

This is follow up of fix for #5410. The patch updates thanos controllers as well to use metadata-informer for watching configmaps.
Fixes: https://github.com/prometheus-operator/prometheus-operator/issues/5438

pkg/thanos: use metadata-informer for configmaps

---

Documentation/high-availability.md

Adds missing space in the docs.
```release-note
```

Fix typo in high availabilty docs

---

pkg/prometheus/agent/operator.go

Fix #5457 
```release-note
Log missing permissions if PrometheusAgent controller doesn't start due to lack of authorization
```

prometheus/agent/operator: Log when missing permissions

---

README.md

Mention PrometheusAgent in README

---

test/framework/alertmanager.go

It was accidentally removed in 1a38cb5fde48aabe6dfb89b8b8388d45384d4660 (tbh my comment wasn't really clear).
```release-note
```

chore: use Alertmanager's status to check readiness

---

pkg/prometheus/collector.go

Fixes #5508 
Just waiting for confirmation in case the mentioned new label is really needed 🤔 
```release-note
Fix panic when collecting metrics from agent controller
```

Fix panic when collecting metrics from Prometheus Agent controller

---

RELEASE.md

chore: Add myself as release shepherd for v0.65

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
jsonnet/prometheus-operator/podmonitors-crd.json
jsonnet/prometheus-operator/probes-crd.json
jsonnet/prometheus-operator/servicemonitors-crd.json
pkg/apis/monitoring/v1/podmonitor_types.go
pkg/apis/monitoring/v1/probe_types.go
pkg/apis/monitoring/v1/types.go

Related-to #5526
```release-note
pkg/apis: Add http scheme validation in Podmetricsendpoint and Probespec
```

pkg/apis: Add http scheme validation in podmonitor and probe

---

MAINTAINERS.md

I completely forgot to change this when I left Gitpod 😅 
```release-note
```

Update Arthur's affiliation

---

README.md

* Adds `ScrapeConfig` to the README
* Clarify project status as per https://docs.google.com/document/d/1-fjJmzrwRpKmSPHtXN5u6VZnn39M28KqyQGBEJsqUOk/edit#bookmark=kix.qeft5ilv2u2
```release-note
```

docs: Clarify project status and add ScrapeConfig

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
jsonnet/prometheus-operator/prometheusagents-crd.json
jsonnet/prometheus-operator/prometheuses-crd.json
pkg/apis/monitoring/v1/prometheus_types.go
pkg/apis/monitoring/v1/zz_generated.deepcopy.go
pkg/client/applyconfiguration/monitoring/v1/remotewritespec.go
pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go

Fixes #5560
```release-note
Add send_native_histograms for remote-write
```

pkg/apis: Add send_native_histograms for remote-write

---

Makefile
jsonnet/mixin/alerts/alerts.libsonnet

In the previous form, only files with the .jsonnet extension were formatted.
```release-note
```

Makefile: format libsonnet files too

---

CONTRIBUTING.md
README.md

Add links to the official Kubernetes guidelines on designing APIs.
```release-note
```

docs: update contributing guidelines

---

pkg/prometheus/promcfg_test.go

This PR refactors new ScrapeConfig tests so that they are split into test cases instead of each having its individual test. This helps maintainability but it also help addition of new tests and debugging possible issues
```release-note
```

tests: refactors ScrapeConfig tests in promcfg_test

---

pkg/alertmanager/operator.go
pkg/prometheus/agent/operator.go
pkg/prometheus/server/operator.go
pkg/thanos/operator.go

Noticed that these fields weren't used while reviewing #5499 
```release-note
```

chore: remove unused code

---

test/e2e/main_test.go
test/e2e/prometheusagent_test.go

Fixes #5456 
```release-note
```

Test name colision between Prometheus Server and Agent

---

pkg/alertmanager/operator.go
pkg/operator/rules.go
pkg/operator/rules_test.go
pkg/operator/sharded_secret.go
pkg/thanos/operator.go
test/e2e/alertmanager_instance_namespaces_test.go
test/e2e/denylist_test.go
test/e2e/main_test.go
test/e2e/prometheus_instance_namespaces_test.go
test/e2e/prometheus_test.go
test/e2e/upgradepath_test.go
test/framework/framework.go

This change addresses a few TODOs that waited on v0.65.x being available.
```release-note
```

chore: remove obsolete code

---

governance.md

This commit includes only cosmetic changes, there are no modifications to the definition of the governance itself. As such I don't think that we need a super-majority vote but feel free to disagree.
```release-note
```

chore: update governance.md

---

MAINTAINERS.md

Discussed offline with @vsliouniaev who agreed. Thanks for your involvement!
```release-note
```

MAINTAINERS.md: remove @vas

---

ADOPTERS.md

Add CERN as a prometheus adopter!  :tada:

CERN as a kube-prometheus-stack adopter

---

MAINTAINERS.md

Welcome @xiu :tada:
```release-note
```

Add xiu as a maintainer

---

test/e2e/main_test.go
test/e2e/scrapeconfig_test.go
test/framework/framework.go
test/framework/scrapeconfig.go

Fixes #5554 
```release-note
```

test: Add ScrapeConfig end to end tests

---

.github/ISSUE_TEMPLATE/support.md

Seems like I broke one of our issue templates in #5516 😬 
This PR decreses the `about` size to 196 characters
```release-note
```

Fix issue template support.md

---

RELEASE.md

Adding myself as 0.66 release shepherd

---

pkg/alertmanager/amcfg.go
pkg/operator/config_reloader.go
pkg/operator/operator.go
pkg/prometheus/server/operator.go

doc: fix function name in comments

---

CHANGELOG.md

I somehow managed to mess up the year when cutting the 0.65 release and its patches too 😵‍💫 
```release-note
```

Fix incorrect dates in changelog

---

CHANGELOG.md

Fix incorrect dates in changelog (#5655)

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
jsonnet/prometheus-operator/prometheusagents-crd.json
jsonnet/prometheus-operator/prometheuses-crd.json
pkg/apis/monitoring/v1/prometheus_types.go

chore: update Prometheus CRD documentation

---

test/e2e/alertmanager_test.go

Accidentally broken when merging #5649 after #5669.
```release-note
```

chore: fix double import in Alertmanager e2e tests

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
jsonnet/prometheus-operator/alertmanagers-crd.json
jsonnet/prometheus-operator/podmonitors-crd.json
jsonnet/prometheus-operator/probes-crd.json
jsonnet/prometheus-operator/prometheusagents-crd.json
jsonnet/prometheus-operator/prometheuses-crd.json
jsonnet/prometheus-operator/scrapeconfigs-crd.json
jsonnet/prometheus-operator/servicemonitors-crd.json
pkg/apis/monitoring/v1/prometheus_types.go
pkg/client/applyconfiguration/monitoring/v1/apiserverconfig.go

Follow up of #5663 and #5670 
```release-note
```

chore: update Prometheus CRD documentation (3)

---

pkg/alertmanager/operator.go
pkg/alertmanager/statefulset.go
pkg/operator/config.go
pkg/operator/config_test.go
pkg/prometheus/agent/operator.go
pkg/prometheus/agent/statefulset.go
pkg/prometheus/server/operator.go
pkg/prometheus/server/statefulset.go
pkg/prometheus/statefulset.go
pkg/thanos/operator.go
pkg/thanos/statefulset.go

Follow-up of #5536 
```release-note
```

chore: refactor labels/annotations CLI flags

---

.github/env
pkg/k8sutil/k8sutil.go
test/e2e/alertmanager_test.go
test/e2e/kind-conf.yaml
test/e2e/main_test.go
test/e2e/prometheus_test.go
test/e2e/thanosruler_test.go
test/framework/helpers.go

chore: update e2e tests to Kubernetes v1.27.3

---

pkg/prometheus/agent/operator.go
pkg/prometheus/agent/statefulset.go
pkg/prometheus/collector.go
pkg/prometheus/promcfg.go
pkg/prometheus/server/operator.go
pkg/prometheus/server/statefulset.go
pkg/prometheus/statefulset.go

chore: refactor code to use the pointer package

---

pkg/operator/gzip_config.go
pkg/prometheus/agent/operator.go
pkg/prometheus/server/operator.go
pkg/prometheus/statefulset.go
pkg/prometheus/store.go

This PR address the comments raised in my previous PR that refactored the common functionalities
of prometheus server and agent controllers. 
See: https://github.com/prometheus-operator/prometheus-operator/pull/5700

refactor: improve prometheus package function 

---

RELEASE.md

RELEASE.md: add simonpasquier for 0.67

---

jsonnet/prometheus-operator/prometheus-operator.libsonnet

Mentioned in https://github.com/prometheus-operator/prometheus-operator/issues/5446#issuecomment-1645232425
```release-note
Expose resource requests/limits for the config reloader in the jsonnet configuration.
```

jsonnet/prometheus-operator: expose resource settings for the reloader

---

Documentation/operator.md
cmd/operator/main.go
pkg/operator/config.go
pkg/operator/config_reloader.go
pkg/operator/config_reloader_test.go
pkg/operator/config_reloader_test_lib.go

Let the standard flag library validate the requests and limits arguments.
```release-note
```

chore: refactor reloader arguments

---

Documentation/user-guides/scrapeconfig.md

docs: Add a user guide on ScrapeConfig

---

Documentation/troubleshooting.md

Apparently ServiceMonitors will not be added to the Service Discovery page if their selector does not match any Service. This is a bit counter-intuitive, so let's just add this to the troubleshooting docs.
I found one other instance of this being confusing on Slack, which helped me figure my problem out: https://kubernetes.slack.com/archives/CFFDS2Z7F/p1664187585784579?thread_ts=1663922438.028919&cid=CFFDS2Z7F
```release-note
add hint to troubleshooting docs why a ServiceMonitor might not show up on the Service Discovery page
```

doc: add hint why ServiceMonitor might not be in Service Discovery

---

pkg/admission/admission_test.go
pkg/admission/testdata/Test_happy_path_v1alpha1.golden
pkg/admission/testdata/Test_happy_path_v1beta1.golden
pkg/admission/testdata/Test_reject_on_duplicate_receiver_v1alpha1.golden
pkg/admission/testdata/Test_reject_on_duplicate_receiver_v1beta1.golden
pkg/admission/testdata/Test_reject_on_invalid_mute_time_intervals_v1alpha1.golden
pkg/admission/testdata/Test_reject_on_invalid_receiver_v1alpha1.golden
pkg/admission/testdata/Test_reject_on_invalid_receiver_v1beta1.golden
pkg/admission/testdata/Test_reject_on_invalid_time_intervals_v1beta1.golden
pkg/admission/testdata/badRulesNoAnnotations.golden
pkg/admission/testdata/badRulesWithBooleanInAnnotations.golden
pkg/admission/testdata/goodRulesWithAnnotations.golden
pkg/admission/testdata/goodRulesWithExternalLabelsInAnnotations.golden
pkg/admission/testdata/happy_path_v1alpha1_v1beta1.golden
pkg/admission/testdata/happy_path_v1beta1_v1alpha1.golden
pkg/admission/testdata/nonStringsInLabelsAnnotations.golden

I'm adding golden file supports on `admission` package, solves #5738
```release-note
adding golden file supports on `admission` package
```

chore: adding golden files support on admission tests

---

pkg/alertmanager/operator.go
pkg/apis/monitoring/v1/servicemonitor_types_test.go
pkg/apis/monitoring/v1/types.go
pkg/apis/monitoring/v1/zz_generated.deepcopy.go
pkg/assets/store.go
pkg/assets/store_test.go
pkg/prometheus/promcfg.go
pkg/prometheus/resource_selector.go
test/e2e/prometheus_test.go
test/framework/prometheus.go

Fixes issue https://github.com/prometheus-operator/prometheus-operator/issues/5713
```release-note
```

fix minor issue with endpoint bearertoken

---

pkg/alertmanager/types.go
pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go
test/e2e/alertmanager_test.go

Closes #5421
```release-note
fix: support text-only email configs
```

fix: support text-only email configs

---

test/e2e/alertmanager_test.go
test/framework/alertmanager.go

Fix Alertmanager e2e tests for v0.26.0

---

Documentation/compatibility.md
pkg/operator/defaults.go

chore: bump Alertmanager and Thanos versions

---

RELEASE.md

Add myself as 0.68 shepherd

---

.github/workflows/automerge-dependabot.yaml

Another attempt for #5849 😅 
```release-note
```

Add git config to dependabot workflow

---

ADOPTERS.md

Add Deezer as an adopter !
```release-note
- Added Deezer to ADOPTERS.md
```

Add Deezer to ADOPTERS.md

---

pkg/alertmanager/operator.go
pkg/listwatch/listwatch.go
pkg/prometheus/agent/operator.go
pkg/prometheus/server/operator.go
pkg/thanos/operator.go

chore: simplify NewUnprivilegedNamespaceListWatchFromClient()

---

pkg/prometheus/promcfg_test.go
pkg/prometheus/testdata/ConsulScrapeConfig.golden
pkg/prometheus/testdata/ConsulScrapeConfigAuthorization.golden
pkg/prometheus/testdata/ConsulScrapeConfigBasicAuth.golden
pkg/prometheus/testdata/ConsulScrapeConfigOAuth.golden
pkg/prometheus/testdata/ConsulScrapeConfigTLSConfig.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_Authorization.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_BasicAuth.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_DNSSD_ARecord.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_DNSSD_SRVRecord.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_Empty.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_EmptyRelabelConfig.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_FileSD.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_HTTPSD.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_HonorLabels.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_HonorTimeStamp.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_K8SSD.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_Limits.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_MetricPath.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_NonEmptyMetricRelabelConfig.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_NonEmptyRelabelConfig.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_Params.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_Scheme.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_ScrapeInterval.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_ScrapeTimeout.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_Static.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_TLSConfig.golden

Related-to #5724
```release-note
```

test: update ScrapeConfig tests to use golden files

---

pkg/alertmanager/operator.go

Remove typo duplicate line

---

cmd/operator/main.go
pkg/k8sutil/k8sutil.go
pkg/prometheus/agent/operator.go
pkg/prometheus/server/operator.go

This change is a pre-requisite for #5898.
```release-note
```

chore: refactor CRD and RBAC checks

---

README.md

While I was exploring Kubernetes and Prometheus, I came across this very simple typo. 😅
```release-note
```

docs: fix very simple typo

---

cmd/operator/main.go

chore: use leveled log instead of fmt.Fprint()

---

.github/workflows/test-prom-version-upgrade.yaml
test/e2e/main_test.go
test/e2e/prometheus_test.go

Fixing the test that I broke with #5732 😬 
```release-note
```

Fix prom upgrade test

---

.github/workflows/stale.yaml

chore: don't close doc issues

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
pkg/apis/monitoring/v1beta1/alertmanager_config_types.go

Improve alertmanagerConfig description

docs: improve alertmanagerConfig description

---

.golangci.yml
pkg/assets/store.go
pkg/informers/informers.go

Enable depguard in more packages

---

MAINTAINERS.md

Welcome @nicolastakashi 🥳 
```release-note
```

Add @nicolastakashi to Triage members list

---

MAINTAINERS.md
RELEASE.md

Long overdue PR regarding my company affiliation.
I am also offering myself as release shepherd for 0.70 release. Sadly I won't be able to do a 0.69 release so we are still looking for a release shepherd there.
Please merge this as soon as it is approved.
```release-note
```

*: changing @paulfantom company affiliation and adding as 0.70 release shepherd

---

MAINTAINERS.md

docs: Update xiu's affiliation

---

RELEASE.md

chore: add Simon as 0.69 shepherd

---

.golangci.yml
pkg/prometheus/agent/operator.go
pkg/prometheus/agent/statefulset.go
pkg/prometheus/operator.go
pkg/prometheus/promcfg.go
pkg/prometheus/resource_selector.go
pkg/prometheus/server/operator.go
pkg/prometheus/server/rules.go
pkg/prometheus/server/statefulset.go
pkg/prometheus/statefulset.go
pkg/prometheus/store.go

Related to #4682 
```release-note
```

Enable depguard in prometheus pkg

---

pkg/prometheus/agent/operator.go

The Prometheus agent controller didn't use the metadata informer for secrets and configmaps as implemented in #5424 and #5448 for the other controllers.
```release-note
Reduce memory usage in the Prometheus agent controller.
```

fix: use metadata informer for agent controller

---

pkg/operator/config.go
test/e2e/config_reloader_test.go
test/e2e/main_test.go
test/framework/framework.go
test/framework/role_binding.go

Closes #5970
```release-note
```

fix: update reloader requests and limits when updated

---

.golangci.yml
test/framework/admission_webhooks.go
test/framework/alertmanager.go
test/framework/crd.go
test/framework/framework.go

Related to #4682 
```release-note
```

Enable depguard in more test files

---

Documentation/design.md

fix spelling mistake
```release-note
```

docs: fix spelling mistake

---

.github/workflows/e2e.yaml
.github/workflows/unit.yaml

**Skip unit test and e2e test for \*.md update**
Ref:
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
```release-note
```

.github/workflows: skip unit and e2e tests for *.md file updates

---

CONTRIBUTING.md

We changed it a few weeks ago :)
```release-note
```

Update Office Hours Meetings

---

pkg/prometheus/promcfg.go

Noticed while playing around ConsulSD config `Scheme` should be converted to lowercase to fix error ` unsupported protocol scheme \"HTTPS\""` from Prometheus
```release-note
fix: convert consul scheme to lowercase while setting prometheus config
```

fix: convert consul scheme to lowercase while setting prometheus config

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
jsonnet/prometheus-operator/podmonitors-crd.json
jsonnet/prometheus-operator/servicemonitors-crd.json
pkg/apis/monitoring/v1/podmonitor_types.go
pkg/apis/monitoring/v1/servicemonitor_types.go
pkg/apis/monitoring/v1/types.go
pkg/prometheus/promcfg.go
pkg/prometheus/resource_selector.go

Similar to #6095 but for PodMonitor.
```release-note
```

chore: update PodMonitor documentation

---

cmd/po-rule-migration/main.go
test/framework/config_map.go
test/framework/deployment.go
test/framework/helpers.go
test/framework/ingress.go
test/framework/namespace.go
test/framework/pod.go
test/framework/prometheus.go
test/framework/prometheusagent.go
test/framework/service.go
test/framework/status.go
test/framework/thanosruler.go

Fixes #4682 
```release-note
```

Fully enable depguard

---

.golangci.yml

Forgot to commit this file in #6103 🤦 
```release-note
```

Remove depguard file filters

---

pkg/alertmanager/amcfg.go
pkg/alertmanager/amcfg_test.go
pkg/alertmanager/testdata/CR_with_MSTeams_Receiver_Partial_Conf.golden

Fixes #6082.
```release-note
fix: Check for nil in MS Teams config
```

fix: Check for nil in MS Teams config

---

.mdox.validate.yaml

Discussed in office hours, adding an exception for our twitter profile
```release-note
```

Add exception for PromOperator's twitter profile

---

pkg/alertmanager/operator.go
pkg/alertmanager/statefulset.go
pkg/alertmanager/statefulset_test.go
pkg/operator/factory.go
pkg/operator/factory_test.go
pkg/prometheus/agent/operator.go
pkg/prometheus/agent/statefulset.go
pkg/prometheus/operator.go
pkg/prometheus/server/operator.go
pkg/prometheus/server/rules.go
pkg/prometheus/server/statefulset.go
pkg/prometheus/server/statefulset_test.go
pkg/prometheus/statefulset.go
pkg/thanos/rules.go
pkg/thanos/statefulset.go
pkg/thanos/statefulset_test.go

Follow-up of #6170 
```release-note
```

chore: generalize usage of UpdateObject()

---

RELEASE.md

chore: add simonpasquier for v0.71

---

pkg/alertmanager/statefulset.go
pkg/operator/config_reloader.go
pkg/prometheus/agent/statefulset.go
pkg/prometheus/server/statefulset.go
pkg/thanos/statefulset.go

chore: use ptr.To()

---

Documentation/proposals/202310-shard-autoscaling.md

Add proposal for automated sharding
```release-note
```

Add proposal for Shard Autoscaling

---

pkg/alertmanager/operator.go
pkg/alertmanager/operator_test.go
pkg/assets/types.go
pkg/operator/factory.go
pkg/operator/sharded_secret.go
pkg/operator/sharded_secret_test.go
pkg/prometheus/agent/operator.go
pkg/prometheus/operator.go
pkg/prometheus/server/operator.go
pkg/prometheus/server/operator_test.go

This commit reorganizes the code makinguse of `SharedSecret` to reduce duplication.
```release-note
```

chore: refactor ShardedSecret

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
Makefile
README.md
TESTING.md

I see a lot of people struggling, especially first-time contributors, with our testing suite. I thought we could write some guidelines to help them out.
```release-note
```

Add testing guidelines

---

cmd/operator/main.go
pkg/alertmanager/operator.go
pkg/operator/operator.go
pkg/prometheus/agent/operator.go
pkg/prometheus/server/operator.go
pkg/thanos/operator.go

chore: refactor logger and eventrecorder creations

---

.golangci.yml
test/e2e/prometheus_test.go
test/framework/config_map.go
test/framework/deployment.go
test/framework/helpers.go
test/framework/prometheus.go

Enable revive

---

.github/workflows/checks.yaml

Setting `golangci-lint` targeted go version to be consistent with dependency version.
ref: https://github.com/golangci/golangci-lint/discussions/2314
```release-note
```

chore: setting `golangci-lint` targeted go version

---

pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/testdata/ScrapeConfigSpecConfig_Already_Sharded.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_Sharded.golden

Fixes #5637.
```release-note
feat(scrapeConfigs): Add sharding to scrapeConfigs
```

feat(scrapeConfigs): Add sharding to scrapeConfigs

---

Makefile

Fixing a silly mistake I made when introducing the new Markefile steps focused on specific e2e tests 😬 
```release-note
```

chore: fix makefile targets

---

ADOPTERS.md

This PR adds authzed to the adaptors file!
We'd be honored to be able to publicly acknowledge our usage of the Prometheus Operator as it hearken back to our teams' shared origins at CoreOS. 
Rendered markdown LGTM!
```release-note
- Add authzed to ADOPTERS
```

ADOPTERS: add authzed

---

pkg/alertmanager/operator.go
pkg/alertmanager/statefulset.go
pkg/alertmanager/statefulset_test.go
pkg/operator/sharded_secret.go
pkg/operator/sharded_secret_test.go
pkg/prometheus/agent/operator.go
pkg/prometheus/agent/statefulset.go
pkg/prometheus/agent/statefulset_test.go
pkg/prometheus/server/operator.go
pkg/prometheus/server/statefulset.go
pkg/prometheus/server/statefulset_test.go
pkg/prometheus/statefulset.go

Follow up of #6200 
```release-note
```

chore: refactor creation of the TLS assets volume

---

MAINTAINERS.md

add slashpai to maintainers

---

.github/env

This commit also bumps the Kubernetes version to v1.29.1.
```release-note
```

chore: update Kind version to v0.21.0

---

test/e2e/prometheus_test.go
test/e2e/scrapeconfig_test.go
test/framework/prometheus.go
test/framework/thanosruler.go

In prevision of #6252. 
```release-note
```

chore: update remote-write tests

---

ADOPTERS.md

Adds WarpBuild as an adopter!
```release-note
- Adds WarpBuild to Adopters.md
```

Adds WarpBuild to Adopters.md

---

Documentation/user-guides/getting-started.md
Documentation/user-guides/shards-and-replicas.md
example/shards/example-app-deployment.yaml
example/user-guides/getting-started/example-app-deployment.yaml

Switching to https://github.com/brancz/prometheus-example-app
```release-note
```

chore: switch example app image

---

.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md
MAINTAINERS.md
README.md
contrib/kube-prometheus/README.md

fix: update kubernetes slack link

---

MAINTAINERS.md

Just realized when got emails for GSoc I have wrong slack id on doc :|
```release-note
```

docs: correct slashpai slack id

---

pkg/prometheus/resource_selector.go
pkg/prometheus/resource_selector_test.go

Fixing the regression added on the #6199 
```release-note
```

[FIX] scrape class regression

---

Documentation/user-guides/scrapeconfig.md

Documentation updated to help users check api reference to see currently supported scrape configs

Documentation: adding link for other supported service discoveries #6382

---

RELEASE.md

chore: add slashpai as v0.73 release shepherd

---

CHANGELOG.md
Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
jsonnet/prometheus-operator/prometheusagents-crd.json
jsonnet/prometheus-operator/prometheuses-crd.json
pkg/apis/monitoring/v1/prometheus_types.go
scripts/run-external.sh

chore: remove repetitive words

---

pkg/alertmanager/operator.go
pkg/operator/event_handler.go
pkg/prometheus/agent/operator.go
pkg/prometheus/server/operator.go
pkg/thanos/operator.go

Fixes #6415
```release-note
```

Refactor operators event handler

---

Documentation/user-guides/prometheus-agent.md

PR to fix the issue #6428 .
Fixed the link to getting started page in Prometheus Agent page.

Fixed the link in Prometheus Agent page

---

TESTING.md

TESTING.md now includes the command to make and load images before running e2e tests. New users were having trouble running tests without this.
- [ x] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)
```release-note
```

Docs: update TESTING.md

---

pkg/alertmanager/amcfg.go

chore: clean up code in Alertmanager config generation

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
jsonnet/prometheus-operator/prometheusagents-crd.json
jsonnet/prometheus-operator/prometheuses-crd.json
pkg/apis/monitoring/v1/prometheus_types.go

chore: fix small omission in CRD documentation

---

RELEASE.md

Improved release docs
```release-note
```

chore: update RELEASE.md with instructions

---

RELEASE.md

chore: update RELEASE.md instructions

---

bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
jsonnet/prometheus-operator/scrapeconfigs-crd.json

Follow-up fix after https://github.com/prometheus-operator/prometheus-operator/pull/6485
```release-note
```

fix generate checks

---

pkg/alertmanager/operator.go
pkg/assets/interface.go
pkg/assets/store.go
pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/resource_selector.go
pkg/prometheus/store.go

This is the follow-up of #6537 for OAuth2 credentials.
```release-note
```

chore: refactor OAuth2 in the assets package

---

CONTRIBUTING.md

chore: add link to public calendar

---

Documentation/compatibility.md
pkg/operator/defaults.go

```release-note
chore: update default thanos version
```

chore: update default thanos version

---

.github/env

chore: update kind version to v0.23.0

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
jsonnet/prometheus-operator/scrapeconfigs-crd.json
pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
pkg/prometheus/resource_selector.go
pkg/prometheus/resource_selector_test.go

feat: support SDK auth in AzureSD
Related-to #6584
```release-note
feat: support SDK auth in AzureSD
```

feat: support SDK auth in AzureSD

---

cmd/admission-webhook/main.go
cmd/operator/main.go
cmd/prometheus-config-reloader/main.go
internal/goruntime/cpu.go

Follow-up of #6576 
```release-note
```

feat: add automatic GOMAXPROCS to admission webhook

---

Documentation/operator.md
cmd/operator/main.go
pkg/operator/feature_gates.go

Add feature gate for the upcoming Prometheus Agent's DaemonSet deployment (proposal in #6600).
Add feature gate for Prometheus Agent's DaemonSet deployment

Add feature gate for Prometheus Agent's DaemonSet deployment

---

pkg/alertmanager/operator.go
pkg/apis/monitoring/v1/prometheus_types.go
pkg/assets/store.go
pkg/assets/store_test.go
pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/resource_selector.go
pkg/prometheus/resource_selector_test.go
pkg/prometheus/server/operator.go
pkg/prometheus/store.go
pkg/prometheus/testdata/ConsulScrapeConfigAuthorization.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_DigitalOceanSD.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_DigitalOceanSD_with_TLSConfig.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_DockerSDConfig.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_EurekaSD.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_EurekaSD_with_TLSConfig.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_HetznerSD_with_Authorization.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_K8SSD_with_Authorization.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_KumaSD.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_KumaSD_with_TLSConfig.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_NomadSD.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_NomadSD_with_TLSConfig.golden

This is a follow-up of #6537 and #6557.
```release-note
```

chore: refactor tokens management in the assets package

---

pkg/alertmanager/operator.go
pkg/assets/store.go
pkg/assets/store_test.go
pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/server/operator.go
pkg/prometheus/store.go

This is a follow-up of #6537 and #6557 and #6641.
```release-note
```

chore: refactor sigv4 management in the assets package

---

Makefile
TESTING.md

This change also simplifies the end-to-end testing instructions.
```release-note
```

chore: add test-e2e-image target to Makefile

---

pkg/assets/store.go
pkg/assets/store_test.go
pkg/assets/types.go
pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/store.go

This is a follow-up of #6537 and #6557, #6641 and #6644.
```release-note
```

chore: refactor AzureAD management in the assets package

---

pkg/alertmanager/amcfg_test.go
pkg/alertmanager/operator_test.go
pkg/alertmanager/statefulset_test.go
pkg/alertmanager/validation/validation_test.go

Continuation to #6659 and #6680. Alertmanager package was edited in this PR.

Replaced t.Fatal with require in Alertmanager Package

---

pkg/admission/admission_test.go
pkg/assets/store_test.go
pkg/k8sutil/k8sutil_test.go
pkg/k8sutil/merge_test.go
pkg/listwatch/listwatch_test.go

Continuation to #6659 . In this PR, I have made changes to admission, assets, k8sutil and listwatch packages.

Replacing t.fatal with require Package 

---

pkg/operator/config_reloader.go

When the prometheus operator is started with `--enable-config-reloader-probes` it will now create `exec` probes that run curl/wget in the `config-reloader` container against localhost to check the /healthz endpoint if `listenLocal` is set to `true`.
Otherwise, it creates `httpGet` probes as before.
This change resolves https://github.com/prometheus-operator/prometheus-operator/issues/6682
I ran unit tests and they all passed.
I also created a local [kind](https://kind.sigs.k8s.io/) cluster and modified the `scripts/run-external.sh` script to add the `--enable-config-reloader-probes` option for the operator here:
https://github.com/prometheus-operator/prometheus-operator/blob/886997 …

Create correct readiness/liveness probes for config-reloader when `listenLocal` is set to `true`

---

RELEASE.md

adding Nicolas as release volunteer
```release-note
```

[CHORE] adding Nicolas as release volunteer

---

Documentation/proposals/202405-agent-daemonset.md

Proposal for DaemonSet deployment of Prometheus Agent

Proposal for DaemonSet deployment of Prometheus Agent

---

pkg/operator/config_reloader.go
pkg/operator/prober.go
pkg/operator/prober_test.go
pkg/prometheus/statefulset.go

This is a quick follow-up of #6698.
```release-note
```

chore: factorize prober code

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
jsonnet/prometheus-operator/scrapeconfigs-crd.json
pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
pkg/prometheus/agent/operator.go
pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/server/operator.go

optimize get secret key from store
```release-note
optimize get secret key from store
```

chore: optimize get secret key from store

---

pkg/alertmanager/operator.go
pkg/alertmanager/statefulset.go
pkg/operator/factory.go
pkg/prometheus/agent/operator.go
pkg/prometheus/agent/statefulset.go
pkg/prometheus/common.go
pkg/prometheus/server/operator.go
pkg/prometheus/server/statefulset.go
pkg/thanos/operator.go
pkg/thanos/statefulset.go

Follow-up of #6694
```release-note
```

chore: refactor annotation propagation

---

pkg/prometheus/agent/operator_test.go
pkg/prometheus/agent/statefulset_test.go
pkg/prometheus/operator_test.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/resource_selector_test.go
pkg/prometheus/server/operator_test.go
pkg/prometheus/server/rules_test.go
pkg/prometheus/server/statefulset_test.go

Continuation to #6659, #6680 and #6683.

Replace t.Fatal with require in Prometheus package

---

Documentation/api.md
scripts/docs/templates/pkg.tpl

Fixed navigation for API Reference page

---

pkg/assets/store_test.go
pkg/thanos/operator_test.go
pkg/thanos/statefulset_test.go

Continuation to #6659 , #6680, #6683 and #6690.

Replace t.Fatal with require in pkg/thanos

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
jsonnet/prometheus-operator/podmonitors-crd.json
jsonnet/prometheus-operator/prometheusagents-crd.json
jsonnet/prometheus-operator/prometheuses-crd.json
jsonnet/prometheus-operator/servicemonitors-crd.json
pkg/apis/monitoring/v1/podmonitor_types.go
pkg/apis/monitoring/v1/prometheus_types.go
pkg/apis/monitoring/v1/types.go
pkg/prometheus/promcfg.go

follow-up of #6756
cc @nicolastakashi @hamishforbes 
```release-note
```

chore: update attachMetada documentation

---

Documentation/rbac.md
Documentation/user-guides/getting-started.md
example/rbac/prometheus/prometheus-cluster-role.yaml
pkg/prometheus/promcfg.go
test/e2e/prometheus_test.go

This change also adds e2e tests for the new EndpointSlice discovery role.
```release-note
```

chore: add RBAC for endpointslices to Prometheus SA

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagers.yaml
example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
jsonnet/prometheus-operator/alertmanagers-crd.json
pkg/alertmanager/amcfg.go
pkg/apis/monitoring/v1/alertmanager_types.go
pkg/apis/monitoring/v1/zz_generated.deepcopy.go
pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
pkg/client/applyconfiguration/monitoring/v1/alertmanagerconfigmatcherstrategy.go
pkg/client/applyconfiguration/monitoring/v1/alertmanagerspec.go

Triggered by #6622.
```release-note
```

chore: refactor Alertmanager route processing

---

.github/workflows/checks.yaml

chore: disable the `generate` job on MacOS

---

Makefile
TESTING.md

chore: add test-e2e-feature-gates target

---

cmd/operator/main.go
pkg/prometheus/agent/operator.go

Replacing the gokit-log in the prometheusagent package
```release-note
replace gokit-log prometheusagent package
```

replace gokit-log prometheusagent package

---

pkg/prometheus/agent/operator.go
pkg/prometheus/promcfg.go
pkg/prometheus/resource_selector.go
pkg/prometheus/resource_selector_test.go
pkg/prometheus/server/operator.go

chore: avoid version parsing duplication

---

Documentation/compatibility.md
pkg/operator/defaults.go

Upgrading Operand version
```release-note
```

[NONE] upgrading operands

---

test/e2e/alertmanager_test.go
test/e2e/controllerid_test.go
test/e2e/main_test.go
test/e2e/prometheusagent_test.go
test/e2e/scrapeconfig_test.go
test/e2e/upgradepath_test.go

Continuation to #6749, #6690, #6683, #6680 
```release-note
```

Replace t.Fatal with require package in tests-e2e

---

.github/workflows/checks.yaml
.mdox.validate.yaml
Makefile

Revert of 5732d79d
```release-note
```

chore: re-enable the `generate` job on MacOS

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
jsonnet/prometheus-operator/prometheusagents-crd.json
jsonnet/prometheus-operator/prometheuses-crd.json
pkg/apis/monitoring/v1/prometheus_types.go
pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/testdata/AlertmanagerConfigEndpointSlice.golden
pkg/prometheus/testdata/AlertmanagerConfigOtherNamespace.golden
pkg/prometheus/testdata/AlertmanagerConfigTLSconfig.golden
test/e2e/prometheus_test.go

Follow-up of #6672 
```release-note
```

feat: use service endpoint role for alerting

---

pkg/alertmanager/operator.go
pkg/alertmanager/operator_test.go

- replace go kit logger in alertmanager package
```release-note
```

replace go kit log in alertmanager package

---

MAINTAINERS.md

chore: Update Arthur's affiliation

---

ADOPTERS.md

Add [DACHS IT](https://dachs-it.de) to Prometheus Operator Adopters.
n/a
```release-note
- Add [DACHS IT](https://dachs-it.de) to adopters list.
```

ADOPTERS: Add DACHS IT

---

CHANGELOG.md

Fix format in CHANGELOG
```release-note
Fix format in CHANGELOG
```

fix: fix CHANGELOG format

---

pkg/alertmanager/amcfg.go
pkg/alertmanager/amcfg_test.go

This is a follow-up of #6818.
```release-note
```

chore: sanitize proxy configuration for Alertmanager

---

.github/env
go.mod
scripts/go.mod

upgrade golang version to 1.23
```release-note
Upgrade golang version to 1.23
```

chore: Upgrade golang version to 1.23

---

pkg/admission/admission_test.go
pkg/alertmanager/operator.go
pkg/alertmanager/statefulset.go
pkg/alertmanager/statefulset_test.go

replace goKitLogger in alertmanager
```release-note
```

replace goKitLogger in alertmanager

---

bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
jsonnet/prometheus-operator/scrapeconfigs-crd.json
pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
test/e2e/scrapeconfig_test.go

Add tests and api validations for FileSD.
```release-note
```

ScrapeConfig: Refactor FileSD

---

cmd/operator/main.go
pkg/kubelet/controller.go

chore: simplify kubelet controller constructor

---

pkg/alertmanager/amcfg.go
pkg/alertmanager/amcfg_test.go
pkg/alertmanager/operator.go

replacing goKitLogger in amcfg
```release-note
```

replace goKitLogger in amcfg

---

pkg/prometheus/agent/operator.go
pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/server/operator.go
pkg/prometheus/test_utils.go

replace goKitLogger in config generator
```release-note
```

replace goKitLogger in config generator

---

cmd/operator/main.go
pkg/kubelet/controller.go
pkg/listwatch/namespace_denylist.go
pkg/listwatch/namespace_denylist_test.go

- Replace goKitLogger in controller and namespace denylist
```release-note
```

replace goKitLogger in controller and namespace denylist

---

ADOPTERS.md

add iflytek adopter
```release-note
add iflytek adopter
```

chore: Add [iflytek](https://iflytek.com/)

---

.mdox.validate.yaml
Documentation/troubleshooting.md

doc: add instructions for port forwarding

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
jsonnet/prometheus-operator/thanosrulers-crd.json
pkg/apis/monitoring/v1/thanos_types.go

chore: fix typo in ThanosRuler CRD doc

---

RELEASE.md

Add slashpai as release shepherd for v0.77

---

CONTRIBUTING.md
Documentation/proposals/template.md

chore: update CONTRIBUTING.md

---

scripts/run-external.sh

chore: add LOG_LEVEL variable to scripts/run-external.sh

---

CHANGELOG.md
pkg/operator/resource_reconciler.go
pkg/thanos/operator.go
pkg/thanos/statefulset.go

fix: ensure reconciliation on Thanos sts updates

---

CHANGELOG.md
pkg/alertmanager/statefulset.go
pkg/prometheus/promcfg.go

fix: fix error message for unsupported versions

---

.github/workflows/e2e-prometheus3.yaml
test/framework/prometheus.go

.github/workflow: Fix prometheus 3 tests

---

pkg/prometheus/agent/daemonset.go
pkg/prometheus/agent/operator.go
pkg/prometheus/agent/statefulset.go
pkg/prometheus/agent/test_utils.go
pkg/prometheus/common.go
pkg/prometheus/promcfg.go
pkg/prometheus/server/operator.go
pkg/prometheus/server/statefulset.go
pkg/prometheus/server/statefulset_test.go

continuation of #6953 
```release-note
```

chore: simplify Prometheus server and agent code

---

test/framework/namespace.go

To help in cleaning up for manual running as well as debug it helps if there is label.
```release-note
```

chore: add e2e test label for namespaces

---

Documentation/api.md
pkg/apis/monitoring/v1alpha1/scrapeconfig_test.go
pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
pkg/client/applyconfiguration/monitoring/v1alpha1/staticconfig.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/resource_selector.go
pkg/prometheus/resource_selector_test.go
test/e2e/scrapeconfig_test.go

Following @simonpasquier 's [suggestion](https://github.com/prometheus-operator/prometheus-operator/pull/6867#discussion_r1735808482).
Closes #6889 
- [] `BUGFIX` (non-breaking change which fixes an issue)
```release-note
Fix LabelName validation issue 
```

FIX: LabelName validation issue 

---

test/e2e/scrapeconfig_test.go

ref: https://github.com/prometheus-operator/prometheus-operator/actions/runs/11301850465/job/31436840934?pr=7003
```release-note
NONE
```

Fix: fix e2e case

---

Documentation/compatibility.md
pkg/operator/defaults.go

chore: add v3.0.0-beta.1 to experimental versions

---

RELEASE.md

chore: add simonpasquier as v0.78 shepherd

---

Makefile

Close #6949 
Note:
https://tip.golang.org/doc/go1.23#gotypespkggotypes
```
W1015 16:21:58.244775   18153 parse.go:769] Making unsupported type entry "any" for: &types.Alias{obj:(*types.TypeName)(0x140001beb90), orig:(*types.Alias)(0x140001900c0), tparams:(*types.TypeParamList)(nil), targs:(*types.TypeList)(nil), fromRHS:(*types.Interface)(0x140001beaf0), actual:(*types.Interface)(0x140001beaf0)}
W1015 16:21:58.245160   18153 parse.go:769] Making unsupported type entry "reflect.uncommonType" for: &types.Alias{obj:(*types.TypeName)(0x14009946cd0), orig:(*types.Alias)(0x14004608780), …
```

Fix: fix warning message with make clean generate command

---

Documentation/troubleshooting.md

Closes #5660
```release-note
```

doc: document deduplication config for Mimir/Grafana Cloud

---

Documentation/installation.md
README.md

This change documents how to install the operator in another namespace than `default`.
Closes #6905
```release-note
```

doc: update install instructions

---

CHANGELOG.md
pkg/kubelet/controller.go

Closes #7023
```release-note
```

fix: correct HTTP port name for Kubelet

---

.github/workflows/unit.yaml
CONTRIBUTING.md

chore: markdown lint fixes in CONTRIBUTING.md

---

Documentation/proposals/202407-remote-write.md

This PR adds a proposal document for RemoteWrite CRD.
ref. https://github.com/prometheus-operator/prometheus-operator/issues/6508
cc @simonpasquier

Proposal for RemoteWrite CRD

---

Documentation/compatibility.md
pkg/operator/defaults.go

chore: add prometheus v2.55.0

---

code-of-conduct.md

chore: update CoC links

---

Dockerfile
cmd/admission-webhook/Dockerfile
cmd/prometheus-config-reloader/Dockerfile

fix: pass GOARCH variable to the build stage

---

go.mod
pkg/client/go.mod

chore: update version in go.mod files

---

Documentation/compatibility.md
pkg/operator/defaults.go

chore: add v3.0.0-rc.0 to experimental versions

---

.github/workflows/checks.yaml
.github/workflows/e2e-prometheus3.yaml

Noticed e2e prom3 tests were failing https://github.com/prometheus-operator/prometheus-operator/actions/runs/11666384990/job/32481209214, we were calling wrong make target for operator upgrade.
Also fixed typo for comment action
```release-note
```

chore: fix actions for operator upgrade and typo fix

---

.github/workflows/test-prom-version-upgrade.yaml
Documentation/compatibility.md
pkg/operator/defaults.go
test/e2e/prometheus_test.go

Related to #7039
```release-note
```

chore: fix TestPrometheusVersionUpgrade

---

Dockerfile
cmd/admission-webhook/Dockerfile
cmd/prometheus-config-reloader/Dockerfile

This change speeds up the building of the images by caching the Go build and module directories.
```release-note
```

chore: optimize build layers

---

Documentation/compatibility.md
pkg/operator/defaults.go

```release-note
update prometheus version
```

chore: update prometheus version

---

.github/workflows/e2e-prometheus3.yaml
.github/workflows/stale.yaml
.github/workflows/test-prom-version-upgrade.yaml

Follow-up of #7082
```release-note
```

fix: fix if conditions in GitHub workflows

---

pkg/prometheus/testdata/ScrapeConfigSpecConfig_EnableHTTP2_False.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_EnableHTTP2_True.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_EnableHTTP2_Unsupported.golden

chore: fix unit tests

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
jsonnet/prometheus-operator/scrapeconfigs-crd.json
pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
pkg/client/applyconfiguration/monitoring/v1alpha1/digitaloceansdconfig.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/resource_selector.go
pkg/prometheus/resource_selector_test.go
pkg/prometheus/testdata/ScrapeConfigSpecConfig_DigitalOceanSD.golden
test/e2e/scrapeconfig_test.go

Refactor Digital Ocean Service Discovery

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
jsonnet/prometheus-operator/prometheuses-crd.json
pkg/apis/monitoring/v1/prometheus_types.go
pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/testdata/AlertmanagerAPIVersionV1.golden
pkg/prometheus/testdata/AlertmanagerAPIVersionV1PrometheusV3.golden

Fixes issue https://github.com/prometheus-operator/prometheus-operator/issues/7089
```release-note
```

[feat] - AM API Version Compatibility

---

RELEASE.md

chore: add slashpai as release shepherd for v0.79

---

pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/testdata/ConsulScrapeConfigNamespace.golden
pkg/prometheus/testdata/ConsulScrapeConfigNamespace_unsupported_version.golden
pkg/prometheus/testdata/ConsulScrapeConfigPathPrefix.golden
pkg/prometheus/testdata/ConsulScrapeConfigPathPrefix_unsupported_version.golden
pkg/prometheus/testdata/NativeHistogramConfigAlwaysScrapeClassicHistograms.golden

Fix https://github.com/prometheus-operator/prometheus-operator/issues/7088
```release-note
```

FEAT - Rename scrape_classic_histograms

---

Documentation/compatibility.md
pkg/operator/defaults.go

Prepping as v3 GA is expected to release soon 🚀 
https://github.com/prometheus/prometheus/pull/15393
```release-note
```

chore: add v3.0.0 to experimental versions

---

example/thanos/prometheus.yaml
example/thanos/query-deployment.yaml
example/thanos/thanos-ruler-secret.yaml
example/thanos/thanos-ruler.yaml
jsonnet/thanos/config.libsonnet
scripts/generate/thanos.jsonnet

chore: update Thanos Ruler example

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
jsonnet/prometheus-operator/prometheusagents-crd.json
jsonnet/prometheus-operator/prometheuses-crd.json
pkg/apis/monitoring/v1/prometheus_types.go
pkg/apis/monitoring/v1/zz_generated.deepcopy.go
pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/testdata/NameValidationSchemeLegacyWithPrometheusLowerThanV3.golden
pkg/prometheus/testdata/NameValidationSchemeLegacyWithPrometheusV3.golden
pkg/prometheus/testdata/NameValidationSchemeUTF8WithPrometheusV3.golden
pkg/prometheus/testdata/OTLPConfig_Config_translation_strategy_with_suffixes_and_name_validation_scheme.golden

Fix https://github.com/prometheus-operator/prometheus-operator/issues/7091
```release-note
```

[FEAT] - Add metric_name_validation_scheme

---

CHANGELOG.md
Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
pkg/alertmanager/amcfg.go
pkg/alertmanager/amcfg_test.go
pkg/apis/monitoring/v1/alertmanager_types.go
pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
pkg/apis/monitoring/v1beta1/alertmanager_config_types.go
pkg/apis/monitoring/v1beta1/conversion_from.go
pkg/apis/monitoring/v1beta1/conversion_to.go
pkg/apis/monitoring/v1beta1/zz_generated.deepcopy.go
pkg/client/applyconfiguration/monitoring/v1alpha1/httpconfig.go
pkg/client/applyconfiguration/monitoring/v1beta1/httpconfig.go

Closes #7114 
```release-note
```

fix: revert removal of the `proxyURL` field

---

pkg/prometheus/testdata/SettingScrapeFallbackProtocolInPodMonitor_NewVersion.golden
pkg/prometheus/testdata/SettingScrapeFallbackProtocolInPodMonitor_OldVersion.golden
pkg/prometheus/testdata/SettingScrapeFallbackProtocolInServiceMonitor_NewVersion.golden
pkg/prometheus/testdata/SettingScrapeFallbackProtocolInServiceMonitor_OldVersion.golden

PR #7126 and PR #7131 were merged in sequence but the former changed the format of the Prometheus configuration significantly which breaks the new tests added in #7131.
```release-note
```

chore: fix tests

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
jsonnet/prometheus-operator/scrapeconfigs-crd.json
pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
pkg/client/applyconfiguration/monitoring/v1alpha1/consulsdconfig.go
pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/resource_selector.go
pkg/prometheus/resource_selector_test.go
pkg/prometheus/testdata/ConsulScrapeConfigWithFilter.golden

Support add consul filter
ref: https://github.com/prometheus/prometheus/pull/11224/files
```release-note
Support add consul filter
```

feat: Support add consul filter

---

Documentation/compatibility.md
pkg/operator/defaults.go

Bump to prometheus v3.0.1

---

Makefile

chore: fix test-e2e-images makefile target

---

.github/workflows/e2e-prometheus2.yaml
Documentation/compatibility.md
cmd/po-docgen/compatibility.go
pkg/operator/defaults.go
test/framework/prometheus.go

```release-note
feat: make prometheus v3.0.1 as default version
```

feat: make prometheus v3.0.1 as default version

---

pkg/prometheus/agent/operator.go
pkg/prometheus/agent/statefulset.go
pkg/prometheus/common.go
pkg/prometheus/server/operator.go
pkg/prometheus/server/statefulset.go

Pre-requisite for #6687
```release-note
```

chore: refactor service creation in Prometheus controllers

---

pkg/operator/rules.go

chore: use ptr.Deref

---

CHANGELOG.md
Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
jsonnet/prometheus-operator/servicemonitors-crd.json
pkg/apis/monitoring/v1/servicemonitor_types.go
pkg/apis/monitoring/v1/types.go
pkg/apis/monitoring/v1/zz_generated.deepcopy.go
pkg/client/applyconfiguration/monitoring/v1/servicemonitorspec.go
pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/resource_selector.go
pkg/prometheus/testdata/ServiceMonitorObjectWithEndpointSliceSelectorAndMatchLabelSelector.golden
pkg/prometheus/testdata/ServiceMonitorObjectWithMatchExpressionSelector.golden
pkg/prometheus/testdata/ServiceMonitorObjectWithMatchLabelSelector.golden
pkg/prometheus/testdata/ServiceMonitorObjectWithSelectorAndMatchExpressionSelector.golden

If it fixes a bug or resolves a feature request, be sure to link to that issue. https://github.com/prometheus-operator/prometheus-operator/issues/5345
Be able to define selectors in kubernetes_sd_config
Overtaking https://github.com/prometheus-operator/prometheus-operator/pull/6580 to solve https://github.com/prometheus-operator/prometheus-operator/issues/5345
_Please …

[FEATURE] adding RoleSelector field in ServiceMonitor

---

.github/env

chore: update Kind version to v0.26.0

---

.golangci.yml

chore: update .golangci.yaml config

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
jsonnet/prometheus-operator/prometheusagents-crd.json
pkg/apis/monitoring/v1alpha1/prometheusagent_types.go
pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
pkg/prometheus/agent/operator.go
pkg/prometheus/server/operator.go
test/e2e/prometheusagent_test.go
test/framework/prometheusagent.go

chore: reduce code duplication in agent controller

---

Documentation/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_podmonitors.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_probes.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
jsonnet/prometheus-operator/podmonitors-crd.json
jsonnet/prometheus-operator/probes-crd.json
jsonnet/prometheus-operator/prometheusagents-crd.json
jsonnet/prometheus-operator/prometheuses-crd.json
jsonnet/prometheus-operator/scrapeconfigs-crd.json
jsonnet/prometheus-operator/servicemonitors-crd.json
pkg/apis/monitoring/v1/podmonitor_types.go
pkg/apis/monitoring/v1/probe_types.go
pkg/apis/monitoring/v1/prometheus_types.go
pkg/apis/monitoring/v1/types.go
pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go

From issue https://github.com/prometheus-operator/prometheus-operator/issues/7254
```release-note
```

[fix] - Scrape Timeout Doc

---

Documentation/proposals/202411-zone-aware-sharding.md
README.md

After rebase https://github.com/prometheus-operator/prometheus-operator/pull/7220 noticed that some docs links are broken and causing issues with the pipeline, pr to fix.
```release-note
```

[fix] - Docs pipeline

---

RELEASE.md

chore: add slashpai as release shepherd for v0.80

---

Documentation/getting-started/compatibility.md
pkg/operator/defaults.go

```release-note
Update alertmanager to v0.28.0
```

chore: Update alertmanager to v0.28.0

---

Documentation/api-reference/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
jsonnet/prometheus-operator/prometheusagents-crd.json
jsonnet/prometheus-operator/prometheuses-crd.json
o.txt
pkg/apis/monitoring/v1/prometheus_types.go
pkg/apis/monitoring/v1/zz_generated.deepcopy.go
pkg/client/applyconfiguration/monitoring/v1/scrapeclass.go
pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/testdata/monitorObjectWithDefaultScrapeClassAndFallbackScrapeProtocol.golden
pkg/prometheus/testdata/podMonitorObjectWithDefaultScrapeClassWithFallbackScrapeProtocol.golden
pkg/prometheus/testdata/podMonitorObjectWithNonDefaultScrapeClassWithFallbackScrapeProtocol.golden
pkg/prometheus/testdata/probeObjectWithDefaultScrapeClassWithFallbackScrapeProtocol.golden
pkg/prometheus/testdata/probeObjectWithNonDefaultScrapeClassWithFallbackScrapeProtocol.golden
pkg/prometheus/testdata/scrapeConfigObjectWithDefaultScrapeClassWithFallbackScrapeProtocol.golden
pkg/prometheus/testdata/scrapeConfigObjectWithNonDefaultScrapeClassWithFallbackScrapeProtocol.golden
pkg/prometheus/testdata/serviceMonitorObjectWithDefaultScrapeClassWithFallbackScrapeProtocol.golden
pkg/prometheus/testdata/serviceMonitorObjectWithNonDefaultScrapeClassWithFallbackScrapeProtocol.golden

```release-note
Add fallbackScrapeProtocol to ScrapeClass
```

feat: add fallbackScrapeProtocol to ScrapeClass

---

pkg/alertmanager/amcfg.go
pkg/alertmanager/amcfg_test.go
pkg/alertmanager/testdata/msteamsv2_config_for_supported_versions.golden
pkg/alertmanager/types.go

```release-note
Add MSTeamsV2Config to alertmanager
```

feat: santize msteamsv2config

---

Documentation/api-reference/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
jsonnet/prometheus-operator/scrapeconfigs-crd.json
pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
pkg/client/applyconfiguration/monitoring/v1alpha1/gcesdconfig.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/testdata/ScrapeConfigSpecConfig_GCESDConfigValidRequiredFields.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_GCESDConfigValid_all_options.golden
test/e2e/scrapeconfig_test.go

From issue https://github.com/prometheus-operator/prometheus-operator/issues/7204
```release-note
ENHANCEMENT: Refactor GCESDConfig
```

[feat] - Refactor GCESDConfig

---

Documentation/api-reference/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
jsonnet/prometheus-operator/scrapeconfigs-crd.json
pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
pkg/client/applyconfiguration/monitoring/v1alpha1/azuresdconfig.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/resource_selector.go
pkg/prometheus/resource_selector_test.go
pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigValidWithSubscriptionID.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigValid_ManagedIdentityAuth.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigValid_SDKAuth.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigValid_basic_auth_and_TLS.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigValid_http_config.golden
pkg/prometheus/testdata/ScrapeConfigSpecConfig_AzureSDConfigValid_with_oauth2.golden
test/e2e/scrapeconfig_test.go

From issue https://github.com/prometheus-operator/prometheus-operator/issues/7202
```release-note
ENHANCEMENT: Refactor AzureSD
```

[feat] - Refactor AzureSD

---

Documentation/api-reference/api.md

Fix make generate after merging https://github.com/prometheus-operator/prometheus-operator/pull/7215 as https://github.com/prometheus-operator/prometheus-operator/pull/7293 merged before that.
```release-note
```

chore: Fix generate check

---

.github/workflows/e2e-prometheus-v2.yaml

chore: rename prometheus 2 actions file

---

pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go

After merging https://github.com/prometheus-operator/prometheus-operator/pull/7038 seeing  `make generate` failure
```release-note
```

fix: chore generate failure

---

pkg/prometheus/promcfg.go

Address follow-up comment from #7038 
```release-note
```

chore: handle nil case first for scrapeFailureLogFile

---

CHANGELOG.md
pkg/alertmanager/amcfg.go
pkg/alertmanager/amcfg_test.go
pkg/alertmanager/testdata/test_avatar_url_field_added_in_discord_config_for_supported_versions.golden
pkg/alertmanager/testdata/test_avatar_url_field_dropped_in_discord_config_for_unsupported_versions.golden
pkg/alertmanager/testdata/test_content_field_added_in_discord_config_for_supported_versions.golden
pkg/alertmanager/testdata/test_content_field_dropped_in_discord_config_for_unsupported_versions.golden
pkg/alertmanager/testdata/test_username_field_added_in_discord_config_for_supported_versions.golden
pkg/alertmanager/testdata/test_username_field_dropped_in_discord_config_for_unsupported_versions.golden
pkg/alertmanager/types.go

feat: add 'content', 'username' and 'avatarUrl' fields in discordConfig

---

CHANGELOG.md
pkg/alertmanager/amcfg.go
pkg/alertmanager/amcfg_test.go
pkg/alertmanager/testdata/jira_configs_for_supported_versions.golden
pkg/alertmanager/testdata/rocketchat_configs_for_supported_versions.golden
pkg/alertmanager/types.go

```release-note
Support `JiraConfig` and `RocketChat` receivers in Alertmanager configuration secret.
```

feat: Support Jira and RocketChat receivers in Alertmanager config secret

---

CHANGELOG.md

chore: update changelog for v0.80.0 updates

---

Documentation/developer/scrapeconfig.md

This is just a document change which was mentioned in the website repository as issue-127: https://github.com/prometheus-operator/website/issues/127
```release-note
```

issue-127 of website repo(docs change)

---

pkg/alertmanager/amcfg_test.go
pkg/alertmanager/testdata/msteamsv2_config_with_webhook_config_file_set.golden
pkg/alertmanager/types.go

From issue https://github.com/prometheus-operator/prometheus-operator/issues/7346
```release-note
```

fix - MSTeamsV2 config

---

Documentation/api-reference/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
jsonnet/prometheus-operator/scrapeconfigs-crd.json
pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
pkg/client/applyconfiguration/monitoring/v1alpha1/openstacksdconfig.go
pkg/prometheus/promcfg.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/resource_selector.go
pkg/prometheus/resource_selector_test.go
pkg/prometheus/testdata/ScrapeConfigSpecConfig_OpenStackSDConfigValid.golden
test/e2e/scrapeconfig_test.go

Add support the `loadbalancer` role in OpenStackSDConfig
```release-note
Add support the `loadbalancer` role in OpenStackSDConfig
```

feat: Add support the `loadbalancer` role in OpenStackSDConfig

---

bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
jsonnet/prometheus-operator/scrapeconfigs-crd.json
pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/resource_selector_test.go
test/e2e/scrapeconfig_test.go

Remove the lower-case Role(`hypervisor` and `instance`) in OpenStackSD
Follow PR: https://github.com/prometheus-operator/prometheus-operator/pull/7356#discussion_r1965842310
```release-note
Remove the lower-case Role(`hypervisor` and `instance`) in …
```

CHANGE: Remove the lower-case Role(`hypervisor` and `instance`) in OpenStackSD

---

RELEASE.md

Add myself for v0.83 release

---

MAINTAINERS.md

Add myself to the list of maintainers 

---

MAINTAINERS.md

Add myself to triage team

---

pkg/alertmanager/clustertlsconfig/config.go
pkg/alertmanager/clustertlsconfig/config_test.go
pkg/alertmanager/operator.go
pkg/alertmanager/statefulset.go

cc @mviswanathsai 
```release-note
```

chore: refactor following #7149

---

Documentation/getting-started/compatibility.md
pkg/operator/defaults.go

chore: update Alertmanager to v0.28.1

---

pkg/alertmanager/amcfg_test.go

Noticed duplicated `apiextensionsv1` import, for clarity adjusted all to use `apiextensionsv1` instead of `v1`
```release-note
```

fix - AM tests

---

Documentation/getting-started/compatibility.md
example/thanos/prometheus.yaml
example/thanos/query-deployment.yaml
example/thanos/thanos-ruler.yaml
jsonnet/thanos/config.libsonnet
pkg/operator/defaults.go
test/e2e/prometheus_test.go

chore: update Thanos to v0.38.0

---

pkg/prometheus/promcfg.go

chore: fix topology sharding flag in ConfigGenerator

---

RELEASE.md

- [ x `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)
```release-note
```

chore: add slashpai as release shepherd 0.82

---

test/e2e/main_test.go
test/e2e/prometheus_test.go
test/e2e/thanosruler_test.go
test/framework/prometheus.go

Fix test regression introduced in #4451 
```release-note
```

test: fix testThanosRulerStateless

---

Documentation/platform/troubleshooting.md

fixes #6411
No tests needed as it is a documentation change.
```release-note
Add documentation on how to use the controller-id flag
```

docs: Add documentation on how to use the controller-id flag to prevent shared ownership of objects

---

.golangci.yml
pkg/k8sutil/k8sutil.go

optimize redefines-builtin-id lint
```release-note
NONE
```

chore: optimize redefines-builtin-id lint

---

Documentation/user-guides/monitoring-kubernetes-ingress.md

Fix dead link 
```
2 errors:
Documentation/user-guides/monitoring-kubernetes-ingress.md:22: "https://getambassador.io/user-guide/getting-started#3-creating-your-first-service" not accessible; status code 404: Not Found
Documentation/user-guides/monitoring-kubernetes-ingress.md:70: "https://getambassador.io/reference/configuration/" not accessible; status code 404: Not Found
```
ref: 
https://github.com/prometheus-operator/prometheus-operator/actions/runs/14746868922/job/41395774548?pr=7487
https://github.com/prometheus-operator/prometheus-operator/actions/runs/14740126855/job/41375820222?pr= …

doc: Fix dead link

---

scripts/go.mod
scripts/go.sum

chore: update jsonnet

---

go.mod
pkg/client/go.mod

*: update go.mod files

---

CHANGELOG.md

chore: update changelog to correct date

---

.github/env

chore: update CI k8s version to v1.33.0

---

RELEASE.md

Add myself as volunteer for the next release

---

.mdox.validate.yaml

```
I think that I prefer an immediate error (as it is now). For istio.com, I'm +1 putting it in the exclude list since it's flaky.
```  
ref: https://github.com/prometheus-operator/prometheus-operator/pull/7511#issuecomment-2883791992
cc @simonpasquier  …

chore: Ignore `istio.io`

---

pkg/admission/admission_test.go
pkg/alertmanager/amcfg_test.go
pkg/alertmanager/statefulset_test.go
pkg/k8sutil/secrets_test.go
pkg/listwatch/listwatch.go
pkg/listwatch/namespace_denylist_test.go
pkg/prometheus/promcfg.go
pkg/server/server.go

Ref https://pkg.go.dev/log/slog#hdr-Writing_a_handler
```release-note
```

chore: update logger with slog's discard handler

---

Documentation/platform/operator.md
pkg/operator/config.go
pkg/operator/feature_gates.go
pkg/prometheus/server/operator.go

fixes: #7549 
added feature gate for status subresource for config obj
```
added feature gate for status subresource for config obj
```

 added feature gate for status subresource for config obj

---

Documentation/api-reference/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
jsonnet/prometheus-operator/prometheusagents-crd.json
jsonnet/prometheus-operator/prometheuses-crd.json
pkg/apis/monitoring/v1/prometheus_types.go

chore: fix NameEscapingSchemeOptions documentation

---

CONTRIBUTING.md
Documentation/proposals/template.md

This change moves the `Audience` section before `Goals`.
```release-note
```

chore: update proposal template

---

Documentation/platform/storage.md

fixes: #7009 
updated storage docs to include hostPath volumes
```release-note
```

updated storage docs to include hostPath volumes

---

pkg/prometheus/resource_selector.go

This commit refactors the ResourceSelector struct to reduce code duplication leveraging Go generics. The behavior remains unchanged.
```release-note
```

chore: refactor ResourceSelector

---

Documentation/materials.md

https://kubernetes.slack.com/archives/C01B03QCSMN/p1751725016308729
According to the Slack discussion above, it would be better to replace the link for the slide causing the CI test to fail.
```release-note
```

Fix link for Materials Page

---

.github/PULL_REQUEST_TEMPLATE.md

This PR adds a `fixes` option to the PR template. 
_Fixes: #7692 
Does not apply.
Add a fixes option to the PR template
```release-note
```

Chore: Update PR template to include fixes

---

pkg/prometheus/resource_selector.go

Fix `unnecessary type arguments infertypeargs` 
```release-note
```

fix: unnecessary type object

---

CHANGELOG.md
pkg/prometheus/server/statefulset.go
pkg/prometheus/server/statefulset_test.go

Continuation of https://github.com/prometheus-operator/prometheus-operator/pull/7731 (rebased on release-0.84 branch + test updated).
```release-note
```

Fix overlapping compaction argument

---

Documentation/platform/troubleshooting.md

From issue https://github.com/prometheus-operator/prometheus-operator/issues/7530
```release-note
```

feat: high cpu troubleshooting

---

Documentation/api-reference/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
jsonnet/prometheus-operator/thanosrulers-crd.json
pkg/apis/monitoring/v1/thanos_types.go
pkg/apis/monitoring/v1/zz_generated.deepcopy.go
pkg/client/applyconfiguration/monitoring/v1/thanosrulerspec.go
pkg/thanos/statefulset.go
pkg/thanos/statefulset_test.go

ref: https://github.com/thanos-io/thanos/pull/5230
```release-note
add `ruleGracePeriod` options for thanos CRD
```

feat: add `ruleGracePeriod` options for thanos CRD

---

pkg/prometheus/resource_selector.go

change ResourcesSelection from slice to map 
TC of lookup from map is o(1) while for slice is o(n)
Closes: #7713
```release-note
```

 change ResourcesSelection from slice to map 

---

test/framework/resources/prometheus-operator-validatingwebhook.yaml

https://github.com/prometheus-operator/prometheus-operator/issues/7757
```release-note
```

fix: validatingwebhook

---

pkg/alertmanager/operator.go
pkg/operator/event_handler.go
pkg/operator/informers.go
pkg/prometheus/agent/operator.go
pkg/prometheus/server/operator.go
pkg/thanos/operator.go

feat: optimize event handler

---

pkg/prometheus/agent/operator.go

This change is a follow-up of #7763.
```release-note
```

feat: optimize daemonset informers

---

Documentation/api-reference/api.md
bundle.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
jsonnet/prometheus-operator/scrapeconfigs-crd.json
pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
pkg/client/applyconfiguration/monitoring/v1alpha1/dockersdconfig.go
pkg/prometheus/promcfg_test.go
test/e2e/scrapeconfig_test.go

Add validations for fields and create E2E testing for Docker SD.
Relate #6452
E2E Testing
```release-note
- Add validation for fields and create E2E test cases for DockerSD.
```

Chore: Refactor DockerSD

---

example/prometheus-operator-crd-full/monitoring.coreos.com_servicemonitors.yaml
example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
jsonnet/prometheus-operator/servicemonitors-crd.json
pkg/apis/monitoring/v1/types.go
pkg/prometheus/applyconfiguration.go
pkg/prometheus/operator.go

Use map list type for status bindings
Closes: #7790
```release-note
```

Use map list type for status bindings

---

test/e2e/scrapeconfig_test.go

Add E2E testing and Linode SD.
Relate #6452
E2E Test Cases
```release-note
- Add E2E test cases for LinodeSD.
```

Chore: Update test cases for LinodeSD

---

test/e2e/scrapeconfig_test.go

Add E2E testing and Linode SD.
Relate #6452
E2E Test Cases
```release-note
- Add E2E test cases for PuppetDB SD
```

Chore: Update test cases for PuppetDBSD

---

example/prometheus-operator-crd-full/monitoring.coreos.com_scrapeconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
jsonnet/prometheus-operator/scrapeconfigs-crd.json
pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
test/e2e/scrapeconfig_test.go

Add E2E testing and Server field validation for Eureka SD.
Relate #6452
E2E Test Cases
```release-note
- Add E2E test cases and the Server field validation for Eureka SD
```

Chore: Update test cases and validation for Euraka SD

---

.custom-gcl.yaml

chore: Update golangci-linter to v2.4.0

---

pkg/prometheus/operator.go
pkg/prometheus/server/operator.go

This commit changes the Prometheus controller to update the status of
the configuration resources with JSON patch [1] operations instead of
Apply operations.
The advantages are:
* The generated patches should be compatible across all configuration resources.
* The update scope is narrower since we don't need to pass the full list of bindings.
[1] https://datatracker.ietf.org/doc/html/rfc6902
```release-note
```

chore: use JSON patches for status updates

---

test/framework/context.go

test: collect all custom resources on failed test

---

pkg/apis/monitoring/v1/podmonitor_types.go
pkg/apis/monitoring/v1/servicemonitor_types.go
pkg/prometheus/config_resource.go
pkg/prometheus/resource_selector.go
pkg/prometheus/server/operator.go

chore: simplify ConfigResourceSyncer methods

---

test/framework/context.go

chore: collect Kubernetes resources on failed test

---

RELEASE.md

chore: add myself for v0.87 release

---

Documentation/api-reference/api.md
example/prometheus-operator-crd-full/monitoring.coreos.com_alertmanagerconfigs.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd-full/monitoring.coreos.com_thanosrulers.yaml
example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
jsonnet/prometheus-operator/alertmanagerconfigs-crd.json
jsonnet/prometheus-operator/alertmanagerconfigs-v1beta1-crd.libsonnet
jsonnet/prometheus-operator/prometheusagents-crd.json
jsonnet/prometheus-operator/prometheuses-crd.json
jsonnet/prometheus-operator/thanosrulers-crd.json
pkg/apis/monitoring/v1/prometheus_types.go

Addresses the comment here: https://github.com/prometheus-operator/prometheus-operator/pull/7987#discussion_r2410503164.
Followup to #7987.
N/A.
```release-note
Update FIPS STS endpoint description.
```

chore: Update FIPS STS endpoint description
